/* V16 baseline regression tests (carried forward) + V16.3–V16.5 behaviour, against the real sources. */
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const path = require('node:path');
const mem = new Map(); globalThis.localStorage = { getItem: (k) => (mem.has(k) ? mem.get(k) : null), setItem: (k, v) => mem.set(k, String(v)), removeItem: (k) => mem.delete(k), clear: () => mem.clear() };
const B = process.env.V17_BUILD; const root = path.join(__dirname, '..');
const { buildSelectSQL } = require(`${B}/engines/sqlEngine`); const { buildCrSQL } = require(`${B}/engines/crEngine`); const { rectify } = require(`${B}/engines/errorRectifierEngine`);
const { CORE_SCHEMA, DEFAULT_SCHEMAS } = require(`${B}/data/defaultSchemas`); const { filterToKnownTables } = require(`${B}/engines/nlpEngine`);
const { isCopilotConfigured } = require(`${B}/services/copilotNlpService`); const { validateSchemaIntegrity, validateIncomingRegistryFile } = require(`${B}/engines/schemaIntegrityEngine`);
const { shouldApplyRemoteActiveSchema } = require(`${B}/engines/schemaVersionEngine`); const { parseCrRequirement } = require(`${B}/engines/crNlpEngine`);
const base = (o = {}) => ({ dialect: 'Generic', naturalLanguageText: '', selectedTables: [], selectedColumns: [], joins: [], filters: [], sorts: [], advanced: { distinct: false, groupByColumns: [], havingClause: '', limit: null, recursive: false, saveAsView: null, caseExpressions: [], decodeExpressions: [], ctes: [] }, generatedSql: '', lastGeneratedAt: null, joinPathChoices: {}, ...o });
test('sqlEngine: basic SELECT with join and filter', () => { const sql = buildSelectSQL(base({ selectedTables: ['INVOICE_HEADER', 'VENDOR'], selectedColumns: [{ id: 'c', table: 'VENDOR', column: 'VENDOR_NAME', alias: '', useDecode: false, aggregate: null }], filters: [{ id: 'f', table: 'INVOICE_HEADER', column: 'STATUS', operator: '=', value: 'P', combinator: 'AND' }] }), CORE_SCHEMA); assert.match(sql, /INNER JOIN VENDOR/); assert.match(sql, /WHERE INVOICE_HEADER.STATUS = 'P'/); });
test('sqlEngine: dialect limits (Oracle FETCH FIRST, SQL Server TOP, others LIMIT) and schema DECODE', () => {
  const s = (d) => base({ dialect: d, selectedTables: ['VENDOR'], selectedColumns: [{ id: 'c', table: 'VENDOR', column: 'STATUS', alias: '', useDecode: true, aggregate: null, displayMode: 'schema-decode' }], advanced: { ...base().advanced, limit: 5 } });
  assert.match(buildSelectSQL(s('Oracle'), CORE_SCHEMA), /DECODE\(VENDOR.STATUS, 'A', 'Active'.*FETCH FIRST 5 ROWS ONLY/s); assert.match(buildSelectSQL(s('SQL Server'), CORE_SCHEMA), /SELECT TOP 5 CASE WHEN/); assert.match(buildSelectSQL(s('MySQL'), CORE_SCHEMA), /LIMIT 5/);
});
test('crEngine: UPDATE/DELETE without WHERE is blocked; confirmed no-WHERE is allowed with warning', () => { const st = { dialect: 'Generic', naturalLanguageText: '', queryType: 'UPDATE', table: 'INVOICE_HEADER', values: [{ id: 'v', column: 'STATUS', value: 'A' }], filters: [], confirmNoWhere: false, generatedSql: '', lastGeneratedAt: null }; assert.equal(buildCrSQL(st).blocked, true); assert.match(buildCrSQL({ ...st, confirmNoWhere: true }).sql, /ALL rows/); assert.match(buildCrSQL({ ...st, queryType: 'INSERT' }).sql, /INSERT INTO INVOICE_HEADER \(STATUS\)/); });
test('crNlpEngine: "Update invoice 1234 status to Approved"', () => { const r = parseCrRequirement('Update invoice 1234 status to Approved', CORE_SCHEMA); assert.equal(r.queryType, 'UPDATE'); assert.equal(r.matchedTable, 'INVOICE_HEADER'); assert.equal(r.values[0].value, 'A'); assert.equal(r.filters[0].value, '1234'); });
test('errorRectifier: ORA-00904 produces a review comment', () => { const r = rectify('ORA-00904: "INVOICE_AMMOUNT": invalid identifier', 'SELECT INVOICE_AMMOUNT FROM INVOICE_HEADER'); assert.equal(r.detectedDialect, 'Oracle'); assert.match(r.correctedSql, /Review/); });
test('schema-authoritative filtering discards fabricated tables', () => { assert.deepEqual(filterToKnownTables(['INVOICE_HEADER', 'X'], CORE_SCHEMA).unknown, ['X']); });
test('isCopilotConfigured requires every field', () => { assert.equal(isCopilotConfigured(null), false); assert.equal(isCopilotConfigured({ enabled: true, tenantId: 't', clientId: 'c', agentEndpoint: 'https://x', scope: 's' }), true); });
test('V16.1: real-world data types valid in schema and registry validation', () => { assert.equal(validateSchemaIntegrity([{ name: 'T', module: 'M', description: '', columns: [{ name: 'ID', label: 'ID', type: 'INTEGER', nullable: false, isPrimaryKey: true, description: '' }, { name: 'N', label: 'N', type: 'VARCHAR2', nullable: true, description: '' }] }]).valid, true); assert.equal(validateIncomingRegistryFile({ schemas: [{ id: 'x', name: 'X', tables: [{ name: 'E', module: 'E', description: '', columns: [{ name: 'ID', label: 'ID', type: 'NUMBER(10)', nullable: false, isPrimaryKey: true, description: '' }] }], relationships: [] }] }).valid, true); });
test('default schemas are internally valid', () => { DEFAULT_SCHEMAS.forEach((s) => assert.equal(validateSchemaIntegrity(s.tables).valid, true, s.name)); });
test('V16.2: error containers render empty (no hidden-attribute pattern)', () => {
  const sp = fs.readFileSync(path.join(root, 'src/pages/settingsPage.ts'), 'utf8'); assert.match(sp, /<div id="settingsPwError"><\/div>/);
  assert.doesNotMatch(fs.readFileSync(path.join(root, 'src/pages/schemaEditorSection.ts'), 'utf8'), /id="c3Error"[^>]*hidden/); assert.doesNotMatch(fs.readFileSync(path.join(root, 'src/components/schemaNameModal.ts'), 'utf8'), /id="schemaNameError"[^>]*hidden/);
});
test('V16.4/16.5: Active Schema pointer last-write-wins', () => { assert.equal(shouldApplyRemoteActiveSchema(null, '2026-01-01T00:00:00Z', 'b', 'a'), true); assert.equal(shouldApplyRemoteActiveSchema('2026-01-02T00:00:00Z', '2026-01-01T00:00:00Z', 'b', 'a'), false); assert.equal(shouldApplyRemoteActiveSchema('2026-01-01T00:00:00Z', '2026-01-02T00:00:00Z', 'b', 'a'), true); assert.equal(shouldApplyRemoteActiveSchema(null, '2026-01-02T00:00:00Z', 'a', 'a'), false); });
test('V16.5: discoverPublicRegistry merges content before syncing the Active Schema pointer', () => { const src = fs.readFileSync(path.join(root, 'src/services/syncService.ts'), 'utf8'); const body = src.slice(src.indexOf('async discoverPublicRegistry'), src.indexOf('async pullRegistryFromGitHub')); assert.ok(body.indexOf('applyMerge') > 0 && body.indexOf('syncActiveSchemaPointer') > body.indexOf('applyMerge')); });
test('V16.5: GitHub calls have a timeout', () => { assert.match(fs.readFileSync(path.join(root, 'src/services/githubApiService.ts'), 'utf8'), /AbortController/); });
test('V17: Secret Vault no longer auto-pushes to the repository', () => { assert.doesNotMatch(fs.readFileSync(path.join(root, 'src/services/secretVaultService.ts'), 'utf8'), /pushToRepository\(\)/); });
