/* V16 baseline regression tests + V16.3–V16.5 behaviour, against the real sources. */
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const path = require('node:path');
const { B } = require('./helpers.cjs'); const root = path.join(__dirname, '..'); const R = (p) => require(`${B}/${p}`);
const { buildCrSQL } = R('engines/crEngine'); const { rectify } = R('engines/errorRectifierEngine'); const { CORE_SCHEMA, DEFAULT_SCHEMAS } = R('data/defaultSchemas');
const { isCopilotConfigured } = R('services/copilotNlpService'); const { validateSchemaIntegrity, validateIncomingRegistryFile } = R('engines/schemaIntegrityEngine');
const { shouldApplyRemoteActiveSchema } = R('engines/schemaVersionEngine'); const { parseCrRequirement } = R('engines/crNlpEngine');
test('crEngine: UPDATE/DELETE without WHERE blocked; confirmed allowed; INSERT', () => { const st = { dialect: 'Generic', naturalLanguageText: '', queryType: 'UPDATE', table: 'INVOICE_HEADER', values: [{ id: 'v', column: 'STATUS', value: 'A' }], filters: [], confirmNoWhere: false, generatedSql: '', lastGeneratedAt: null }; assert.equal(buildCrSQL(st).blocked, true); assert.match(buildCrSQL({ ...st, confirmNoWhere: true }).sql, /ALL rows/); assert.match(buildCrSQL({ ...st, queryType: 'INSERT' }).sql, /INSERT INTO INVOICE_HEADER/); });
test('crNlpEngine: "Update invoice 1234 status to Approved"', () => { const r = parseCrRequirement('Update invoice 1234 status to Approved', CORE_SCHEMA); assert.equal(r.matchedTable, 'INVOICE_HEADER'); assert.equal(r.values[0].value, 'A'); assert.equal(r.filters[0].value, '1234'); });
test('errorRectifier: ORA-00904', () => assert.match(rectify('ORA-00904: "X": invalid identifier', 'SELECT X FROM T').correctedSql, /Review/));
test('isCopilotConfigured requires every field', () => { assert.equal(isCopilotConfigured(null), false); assert.equal(isCopilotConfigured({ enabled: true, tenantId: 't', clientId: 'c', agentEndpoint: 'https://x', scope: 's' }), true); });
test('V16.1: real-world data types valid', () => { assert.equal(validateSchemaIntegrity([{ name: 'T', module: 'M', description: '', columns: [{ name: 'ID', label: 'ID', type: 'INTEGER', nullable: false, isPrimaryKey: true, description: '' }, { name: 'N', label: 'N', type: 'VARCHAR2(100 CHAR)', nullable: true, description: '' }] }]).valid, true); assert.equal(validateIncomingRegistryFile({ schemas: [{ id: 'x', name: 'X', tables: [{ name: 'E', module: 'E', description: '', columns: [{ name: 'ID', label: 'ID', type: 'NUMBER(10)', nullable: false, isPrimaryKey: true, description: '' }] }], relationships: [] }] }).valid, true); });
test('default schemas valid with the shared validator (incl. relationships)', () => { DEFAULT_SCHEMAS.forEach((s) => assert.equal(validateSchemaIntegrity(s.tables, s.relationships).valid, true, s.name)); });
test('V16.2: error containers render empty', () => { assert.match(fs.readFileSync(path.join(root, 'src/pages/settingsPage.ts'), 'utf8'), /<div id="settingsPwError"><\/div>/); assert.doesNotMatch(fs.readFileSync(path.join(root, 'src/pages/schemaEditorSection.ts'), 'utf8'), /id="c3Error"[^>]*hidden/); assert.doesNotMatch(fs.readFileSync(path.join(root, 'src/components/schemaNameModal.ts'), 'utf8'), /id="schemaNameError"[^>]*hidden/); });
test('V16.4/16.5: Active Schema pointer last-write-wins (and invalid timestamps ignored)', () => { assert.equal(shouldApplyRemoteActiveSchema(null, '2026-01-01T00:00:00Z', 'b', 'a'), true); assert.equal(shouldApplyRemoteActiveSchema('2026-01-02T00:00:00Z', '2026-01-01T00:00:00Z', 'b', 'a'), false); assert.equal(shouldApplyRemoteActiveSchema('2026-01-01T00:00:00Z', 'garbage', 'b', 'a'), false); });
test('V16.5: GitHub calls time out; V17: vault never auto-pushes', () => { assert.match(fs.readFileSync(path.join(root, 'src/services/githubApiService.ts'), 'utf8'), /AbortController/); assert.doesNotMatch(fs.readFileSync(path.join(root, 'src/services/secretVaultService.ts'), 'utf8'), /pushToRepository\(\)/); });
