/* V17.0 feature suite (carried forward unchanged in intent) — offline NLU, Advanced Options, learning, schema records, vault sync, AI/LLM. */
const test = require('node:test'); const assert = require('node:assert/strict');
const { B, emptyState: empty } = require('./helpers.cjs');
const R = (p) => require(`${B}/${p}`);
const { CORE_SCHEMA } = R('data/defaultSchemas'); const { buildSelectSQL } = R('engines/sqlEngine'); const { validateReadOnlySql } = R('engines/validationEngine');
const { validateSchemaIntegrity } = R('engines/schemaIntegrityEngine'); const { parseRequirement, filterToKnownTables } = R('engines/nlpEngine');
const { runOfflineNlu } = R('v17/engines/nluEngine'); const { getSchemaContext, schemaFingerprint } = R('v17/engines/schemaContext');
const { isSafeDateExpression } = R('v17/engines/dateExpressions'); const { renderFilterClause } = R('engines/filterEngine');
const { applyV17ToState, validateAdvancedConsistency } = R('v17/engines/advancedOptionsResolver');
const { upsertSchemaRecord, deleteSchemaRecord, dataTypeOptionValues } = R('v17/engines/schemaRecordEngine');
const { LearningStore, statusOf, pushLearning, pullLearning } = R('v17/services/learningStore');
const vault = R('v17/services/vaultSyncService'); const llm = R('v17/services/llmService');
const { describeWhatYouNeed, isResultStale, validateLlmSql } = R('v17/services/v17Orchestrator');
const { redactSecrets, renderErrorListHtml, escapeHtmlV17 } = R('v17/errors/appErrors');
const clone = (v) => JSON.parse(JSON.stringify(v));
const gen = async (text, o = {}) => describeWhatYouNeed(text, o.schema || CORE_SCHEMA, o.state || empty(o.dialect || 'Generic'), o.deps || {});
const memStorage = () => { const m = new Map(); return { get: (k) => m.get(k) ?? null, set: (k, v) => m.set(k, v) }; };
const norm = (s) => s.replace(/\s+/g, ' ').trim();
test('baseline: buildSelectSQL join + filter', () => { const sql = buildSelectSQL({ ...empty(), selectedTables: ['INVOICE_HEADER', 'VENDOR'], selectedColumns: [{ id: 'c', table: 'INVOICE_HEADER', column: 'INVOICE_ID', alias: '', useDecode: false, aggregate: null }], filters: [{ id: 'f', table: 'INVOICE_HEADER', column: 'STATUS', operator: '=', value: 'P', combinator: 'AND' }] }, CORE_SCHEMA); assert.match(sql, /INNER JOIN VENDOR/); assert.match(sql, /WHERE INVOICE_HEADER.STATUS = 'P'/); });
test('baseline: destructive SQL rejected', () => assert.equal(validateReadOnlySql('DELETE FROM VENDOR').valid, false));
test('baseline: fabricated table discarded', () => assert.deepEqual(filterToKnownTables(['INVOICE_HEADER', 'X'], CORE_SCHEMA).unknown, ['X']));
test('baseline: V16 parser still runs', () => assert.ok(parseRequirement('approved invoices', CORE_SCHEMA).matchedTables.includes('INVOICE_HEADER')));
test('filter quoting: user text quoted; only generated date expressions pass', () => { assert.equal(renderFilterClause('T', 'C', '=', "x' OR 1=1 --"), "T.C = 'x'' OR 1=1 --'"); assert.equal(renderFilterClause('T', 'D', '>=', 'TRUNC(SYSDATE) - 30'), 'T.D >= TRUNC(SYSDATE) - 30'); assert.equal(isSafeDateExpression('TRUNC(SYSDATE) - 30; DROP TABLE X'), false); });
test('NLU: simple SELECT', async () => assert.equal(norm((await gen('show all vendors')).sql), 'SELECT * FROM VENDOR;'));
test('NLU: JOIN (direct + bridge + FK-derived)', async () => { assert.match((await gen('show invoices with vendor name')).sql, /INNER JOIN VENDOR ON INVOICE_HEADER.VENDOR_ID = VENDOR.VENDOR_ID/); assert.match((await gen('invoices with organization name')).sql, /INNER JOIN ORGANIZATION ON VENDOR.ORG_ID = ORGANIZATION.ORG_ID/); assert.match((await gen('invoice lines with gl account name for po 1234')).sql, /INNER JOIN GL_ACCOUNT ON INVOICE_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.ACCOUNT_ID/); });
test('NLU: WHERE, multiple conditions, negation, IN', async () => { const r = (await gen('approved invoices with invoice amount over 5000 and currency is EUR')).sql; assert.match(r, /STATUS = 'A'/); assert.match(r, /INVOICE_AMOUNT > 5000/); assert.match(r, /CURRENCY = 'EUR'/); assert.match((await gen('unpaid invoices')).sql, /STATUS <> 'D'/); assert.match((await gen('approved or rejected invoices')).sql, /STATUS IN \('A', 'R'\)/); });
test('NLU: string conditions', async () => { assert.match((await gen('vendor name containing acme')).sql, /LIKE '%acme%'/); assert.match((await gen('vendors where payment terms is empty')).sql, /PAYMENT_TERMS IS NULL/); });
test('NLU: date filtering across dialects', async () => { assert.match((await gen('invoices in 2025')).sql, /DATE '2025-01-01'/); assert.match((await gen('invoices from the last 30 days', { dialect: 'Oracle' })).sql, /TRUNC\(SYSDATE\) - 30/); assert.match((await gen('invoices from the last 30 days', { dialect: 'SQL Server' })).sql, /DATEADD\(DAY, -30/); assert.match((await gen('invoices with due date between 2025-01-01 and 2025-03-31')).sql, /DUE_DATE BETWEEN DATE '2025-01-01' AND DATE '2025-03-31'/); });
test('NLU: ORDER BY, GROUP BY, aggregation, DISTINCT, complex', async () => {
  assert.match((await gen('vendors sorted by vendor name descending')).sql, /ORDER BY VENDOR.VENDOR_NAME DESC/);
  const a = await gen('total invoice amount by vendor'); assert.match(a.sql, /SUM\(INVOICE_HEADER.INVOICE_AMOUNT\)/); assert.match(a.sql, /GROUP BY VENDOR.VENDOR_NAME/);
  assert.match((await gen('count of invoices per vendor having more than 5')).sql, /HAVING COUNT\(INVOICE_HEADER.INVOICE_ID\) > 5/);
  assert.equal(norm((await gen('unique countries of vendors')).sql), 'SELECT DISTINCT VENDOR.COUNTRY FROM VENDOR;');
  const c = await gen('top 5 vendors by total invoice amount for approved invoices in 2025', { dialect: 'Oracle' });
  for (const re of [/SUM\(INVOICE_HEADER.INVOICE_AMOUNT\)/, /STATUS = 'A'/, /GROUP BY VENDOR.VENDOR_NAME/, /ORDER BY SUM\(INVOICE_HEADER.INVOICE_AMOUNT\) DESC/, /FETCH FIRST 5 ROWS ONLY/]) assert.match(c.sql, re);
  assert.equal(c.errors.length, 0);
});
test('NLU: unknown identifiers reported, never added; no substring false positives', async () => { const r = await gen('show invoices with VENDOR_CODE'); assert.ok(r.errors.some((e) => e.code === 'COLUMN_NOT_FOUND')); assert.doesNotMatch(r.sql, /VENDOR_CODE/); assert.doesNotMatch((await gen('invoices by posting date')).sql, /PO_HEADER/); });
test('errors: empty schema / unknown text / no error box when no error', async () => { assert.equal((await gen('x', { schema: { ...clone(CORE_SCHEMA), tables: [], relationships: [] } })).errors[0].code, 'ACTIVE_SCHEMA_UNAVAILABLE'); assert.ok((await gen('weather forecast for tomorrow')).errors.some((e) => e.code === 'OFFLINE_MODEL_UNABLE')); assert.equal(renderErrorListHtml([], escapeHtmlV17), ''); });
test('Advanced Options: manual wins; all options still render', () => {
  const st = empty(); st.advanced.limit = 50; const req = runOfflineNlu('top 5 vendors by total invoice amount', CORE_SCHEMA, { dialect: 'Generic' });
  assert.equal(applyV17ToState(st, req, { isManual: (k) => k === 'limit' }).state.advanced.limit, 50);
  const s = { ...empty('PostgreSQL'), selectedTables: ['VENDOR'], selectedColumns: [{ id: 'a', table: 'VENDOR', column: 'COUNTRY', alias: '', useDecode: false, aggregate: null }, { id: 'b', table: 'VENDOR', column: 'VENDOR_ID', alias: 'N', useDecode: false, aggregate: 'COUNT' }] };
  s.advanced = { ...s.advanced, distinct: true, groupByColumns: ['VENDOR.COUNTRY'], havingClause: 'COUNT(VENDOR.VENDOR_ID) > 1', limit: 3, recursive: true, ctes: [{ id: 'c', name: 'c1', body: 'SELECT 1' }] };
  const sql = buildSelectSQL(s, CORE_SCHEMA); for (const re of [/^WITH RECURSIVE c1 AS/, /SELECT DISTINCT/, /GROUP BY VENDOR.COUNTRY/, /HAVING COUNT/, /LIMIT 3/]) assert.match(sql, re);
  assert.ok(validateAdvancedConsistency({ ...s, advanced: { ...s.advanced, groupByColumns: [] } }).some((i) => i.severity === 'error'));
});
test('learning: one-off not used; repeated used; accepted confirmed; schema untouched; survives restart', async () => {
  const storage = memStorage(); const ls = new LearningStore(storage, () => 'devA'); const before = JSON.stringify(CORE_SCHEMA);
  const r1 = await gen('open purchase orders with vendor name', { deps: { learning: ls } }); assert.equal(statusOf(ls.get(r1.learningId)), 'observed'); assert.equal(ls.findHints('open purchase orders with vendor name', CORE_SCHEMA).length, 0);
  await gen('open purchase orders with vendor name', { deps: { learning: ls } }); assert.equal(statusOf(ls.get(r1.learningId)), 'repeated');
  assert.equal(ls.recordAcceptance(r1.learningId, 'DELETE FROM PO_HEADER', CORE_SCHEMA).ok, false);
  assert.equal(ls.recordAcceptance(r1.learningId, r1.sql, CORE_SCHEMA).status, 'confirmed');
  assert.equal(JSON.stringify(CORE_SCHEMA), before); assert.equal(new LearningStore(storage, () => 'devA').stats().confirmed, 1);
});
test('learning: hint influences later request; sync masks literals and merges idempotently', async () => {
  const ls = new LearningStore(memStorage(), () => 'devA'); const r = await gen('vendor payment terms report', { deps: { learning: ls } });
  ls.recordAcceptance(r.learningId, 'SELECT VENDOR.VENDOR_NAME, VENDOR.PAYMENT_TERMS FROM VENDOR ORDER BY VENDOR.VENDOR_NAME ASC;', CORE_SCHEMA, { sorts: [{ table: 'VENDOR', column: 'VENDOR_NAME', direction: 'ASC' }] });
  assert.match((await gen('vendor payment terms report please', { deps: { learning: ls } })).sql, /ORDER BY VENDOR.VENDOR_NAME ASC/);
  const a = new LearningStore(memStorage(), () => 'devA'); const b = new LearningStore(memStorage(), () => 'devB'); const ra = await gen("vendors named 'Acme Ltd'", { deps: { learning: a } }); a.recordAcceptance(ra.learningId, "SELECT * FROM VENDOR WHERE VENDOR.VENDOR_NAME = 'Acme Ltd';", CORE_SCHEMA);
  const files = new Map(); const api = { getFile: async (r_, br, p) => files.get(p) || null, putFile: async (r_, br, p, t, c) => { files.set(p, { content: c, sha: 'x' }); return { sha: 'x' }; } };
  await pushLearning(a, api, 'o/r', 'main', 'tok_123456', true); assert.doesNotMatch([...files.values()][0].content, /Acme Ltd/);
  await pullLearning(b, api, 'o/r', 'main', ''); await pullLearning(b, api, 'o/r', 'main', ''); assert.equal(b.all()[0].counters.devA.accepted, 1);
});
const rowOf = (schema, t, c) => { const tb = schema.tables.find((x) => x.name === t); const col = tb.columns.find((x) => x.name === c); return { rowId: `${t}::${c}`, module: tb.module, tableName: t, tableDescription: tb.description, columnName: col.name, columnDescription: col.description, dataType: col.type, length: col.length ?? null, precision: col.precision ?? null, nullable: col.nullable, alias: col.alias ?? '', decodeText: (col.decode || []).map((d) => `${d.rawValue}=${d.label}`).join('\n'), isPrimaryKey: !!col.isPrimaryKey, isForeignKey: !!col.isForeignKey, fkTable: col.references?.table ?? '', fkColumn: col.references?.column ?? '' }; };
test('schema records: edit one row only; rename updates refs; invalid rejected; delete blocked/cascade', () => {
  const r = upsertSchemaRecord(CORE_SCHEMA, { ...rowOf(CORE_SCHEMA, 'VENDOR', 'COUNTRY'), columnDescription: 'X' }, 'VENDOR::COUNTRY'); assert.equal(r.ok, true);
  r.schema.tables.forEach((t) => { if (t.name !== 'VENDOR') assert.deepEqual(t, CORE_SCHEMA.tables.find((x) => x.name === t.name)); });
  const rn = upsertSchemaRecord(CORE_SCHEMA, { ...rowOf(CORE_SCHEMA, 'VENDOR', 'VENDOR_ID'), columnName: 'SUPPLIER_ID' }, 'VENDOR::VENDOR_ID'); assert.ok(rn.schema.relationships.filter((x) => x.toTable === 'VENDOR').every((x) => x.toColumn === 'SUPPLIER_ID'));
  assert.equal(upsertSchemaRecord(CORE_SCHEMA, { ...rowOf(CORE_SCHEMA, 'VENDOR', 'COUNTRY'), columnName: 'BAD NAME' }, 'VENDOR::COUNTRY').ok, false);
  assert.equal(deleteSchemaRecord(CORE_SCHEMA, 'VENDOR::VENDOR_ID').errors[0].code, 'SCHEMA_DEPENDENCY_BLOCKED');
  const c = deleteSchemaRecord(CORE_SCHEMA, 'VENDOR::VENDOR_ID', { cascade: true }); assert.equal(c.ok, true); assert.equal(validateSchemaIntegrity(c.schema.tables, c.schema.relationships).valid, true);
  assert.deepEqual(dataTypeOptionValues('VARCHAR2', ['VARCHAR']), ['VARCHAR2', 'VARCHAR']);
});
test('schema change refreshes NLU context; stale results detected', async () => { const renamed = upsertSchemaRecord(CORE_SCHEMA, { ...rowOf(CORE_SCHEMA, 'INVOICE_HEADER', 'INVOICE_AMOUNT'), columnName: 'GROSS_AMOUNT' }, 'INVOICE_HEADER::INVOICE_AMOUNT').schema; const r = await gen('total gross amount by vendor', { schema: renamed }); assert.match(r.sql, /SUM\(INVOICE_HEADER.GROSS_AMOUNT\)/); assert.notEqual(getSchemaContext(CORE_SCHEMA).fingerprint, getSchemaContext(renamed).fingerprint); assert.equal(isResultStale(r, CORE_SCHEMA), true); assert.notEqual(schemaFingerprint(CORE_SCHEMA), schemaFingerprint(renamed)); });
const TOKEN = 'ghp_' + 'A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8'; const payload = { githubToken: TOKEN, githubRepo: 'o/r', githubBranch: 'main', githubSchemaPath: 'p', llmApiKey: 'sk-test-0123456789abcdefghij' }; const PASS = 'Correct-Horse-42-Battery';
test('vault: encrypted, never plaintext; push/pull; wrong passphrase / tamper / downgrade / garbage handled', async () => {
  const files = new Map(); const api = { getFile: async (r_, b, p) => files.get(p) || null, putFile: async (r_, b, p, t, c) => { files.set(p, { content: c, sha: 's' }); return { sha: 's' }; } };
  assert.equal((await vault.pushVaultSync({ payload, passphrase: PASS, deviceTag: 'd', api, iterations: 100000 })).ok, true);
  const stored = files.get(vault.VAULT_SYNC_PATH).content; assert.doesNotMatch(stored, /ghp_|sk-test|Correct-Horse/); assert.equal(stored.includes(Buffer.from(TOKEN).toString('base64')), false);
  assert.equal((await vault.pullVaultSync({ repo: 'o/r', branch: 'main', readToken: '', passphrase: PASS, api })).payload.githubToken, TOKEN);
  assert.equal((await vault.pullVaultSync({ repo: 'o/r', branch: 'main', readToken: '', passphrase: 'Wrong-Horse-42-Battery', api })).error.code, 'DECRYPTION_FAILED');
  const env = JSON.parse(stored); env.ciphertext = env.ciphertext.slice(0, -4) + 'AAAA'; files.set(vault.VAULT_SYNC_PATH, { content: JSON.stringify(env), sha: 's' }); assert.equal((await vault.pullVaultSync({ repo: 'o/r', branch: 'main', readToken: '', passphrase: PASS, api })).error.code, 'DECRYPTION_FAILED');
  const down = JSON.parse(stored); down.kdf.iterations = 1000; assert.equal(vault.parseEnvelope(JSON.stringify(down)).error.code, 'DECRYPTION_FAILED');
  assert.equal(vault.parseEnvelope('not json').error.code, 'DECRYPTION_FAILED'); const bad = JSON.parse(stored); bad.ciphertext = '%%%'; assert.equal((await vault.decryptEnvelope(bad, PASS)).error.code, 'DECRYPTION_FAILED');
  assert.ok(vault.validatePassphrase('admin').length > 0); assert.doesNotMatch(redactSecrets(`Bearer ${TOKEN}`), /ghp_A1/);
});
const llmCfg = (o = {}) => ({ ...llm.defaultLlmConfig(), enabled: true, provider: 'openai-compatible', endpoint: 'https://llm.example.com/v1', model: 'm', ...o });
const okFetch = (content) => async () => ({ ok: true, status: 200, json: async () => ({ choices: [{ message: { content } }] }) });
test('AI/LLM: optional; validated; invalid config and failures fall back to offline; key never leaked', async () => {
  assert.equal((await gen('approved invoices')).engineUsed, 'offline');
  const good = await gen('total invoice amount by vendor', { deps: { llm: { config: llmCfg(), apiKey: 'sk-test-0123456789abcdefghij', vaultLocked: false, fetchImpl: okFetch(JSON.stringify({ sql: 'SELECT VENDOR.VENDOR_NAME, SUM(INVOICE_HEADER.INVOICE_AMOUNT) AS T FROM INVOICE_HEADER INNER JOIN VENDOR ON INVOICE_HEADER.VENDOR_ID = VENDOR.VENDOR_ID GROUP BY VENDOR.VENDOR_NAME' })) } } }); assert.equal(good.engineUsed, 'offline+llm');
  const bad = await gen('approved invoices', { deps: { llm: { config: llmCfg(), apiKey: 'sk-x-0123456789abcdef', vaultLocked: false, fetchImpl: okFetch('{"sql":"DELETE FROM INVOICE_HEADER"}') } } }); assert.ok(bad.errors.some((e) => e.code === 'AI_LLM_RESPONSE_REJECTED')); assert.match(bad.sql, /STATUS = 'A'/);
  assert.ok(validateLlmSql('SELECT FAKE.X FROM FAKE', CORE_SCHEMA).length > 0);
  const inv = await gen('approved invoices', { deps: { llm: { config: llmCfg({ endpoint: 'http://remote.example.com', model: '' }), apiKey: 'k-0123456789', vaultLocked: false } } }); assert.ok(inv.errors.some((e) => e.code === 'AI_LLM_CONFIG_INVALID'));
  const un = await gen('approved invoices', { deps: { llm: { config: llmCfg(), apiKey: 'sk-secret-0123456789abcdef', vaultLocked: false, fetchImpl: async () => ({ ok: false, status: 401, json: async () => ({ error: { message: 'Incorrect API key provided: sk-secret-0123456789abcdef' } }) }) } } });
  assert.doesNotMatch(un.errors.map((e) => e.message).join(' '), /sk-secret-0123456789abcdef/); assert.match(un.sql, /STATUS = 'A'/);
  const net = await gen('approved invoices', { deps: { llm: { config: llmCfg(), apiKey: 'sk-secret-0123456789abcdef', vaultLocked: false, fetchImpl: async () => { throw new TypeError('Failed to fetch'); } } } }); assert.ok(net.errors.some((e) => e.code === 'AI_LLM_REQUEST_FAILED'));
  const m = new Map(); const kv = { getItem: (k) => m.get(k) ?? null, setItem: (k, v) => m.set(k, v) }; assert.equal(llm.migrateFromV16Endpoint(kv, 'https://nlp.example.com').config.provider, 'custom-endpoint');
});
