import { test } from 'node:test'; import assert from 'node:assert/strict';
import { imp } from './helpers.mjs';
const { CORE_SCHEMA, EXTENDED_SCHEMA } = await imp('data/defaultSchemas.js'); const { memoryStore, KEYS } = await imp('services/storage.js');
const { runOfflineNlu } = await imp('v17/engines/nluEngine.js'); const { applyV17ToState, advancedOverrides } = await imp('v17/engines/advancedOptionsResolver.js'); const { buildSelect, buildSelectSQL } = await imp('engines/sqlEngine.js'); const { activeSelection } = await imp('engines/scope.js');
const { validateFinalQuery } = await imp('v17/engines/queryValidator.js'); const { extractSqlPattern } = await imp('v17/engines/sqlPatterns.js');
const { LearningStore, tierOf, weightOf } = await imp('v17/services/learningStore.js'); const { AdminQueryLibrary, validateAdminQuery } = await imp('v17/services/adminLibrary.js');
const { generateFromDescription } = await imp('v17/services/queryOrchestrator.js'); const { retrieveKnowledge } = await imp('v17/services/retrieval.js');
const { KnowledgeSync, parseKnowledge, knowledgePathFor } = await imp('v17/services/knowledgeSync.js'); const { runMigrations, readMigrations } = await imp('v17/services/migrations.js');
const { memoryRepository } = await imp('v17/services/githubClient.js'); const { SecretVault } = await imp('v17/services/secretVault.js'); const C = await imp('v17/services/cryptoBox.js'); const { explainQuery } = await imp('v17/engines/explain.js');
const AI = await imp('v17/services/aiLlmService.js'); const { SchemaService } = await imp('services/schemaService.js');
const empty = (d = 'Oracle') => ({ dialect: d, naturalLanguageText: '', selectedTables: [], selectedColumns: [], filters: [], sorts: [], advanced: { distinct: false, groupByColumns: [], havingClause: '', limit: null, viewName: '', tableAliases: false, joinType: 'INNER JOIN', recursive: false, ctes: [], subqueries: [] }, generatedSql: '', joinPathChoices: {} });
const gen = (t, d = 'Oracle', s = CORE_SCHEMA, hints = [], ctx = [], cur = empty(d)) => { const r = runOfflineNlu(t, s, { dialect: d, hints, contextTables: ctx }); const st = applyV17ToState(cur, r, { isManual: () => false }).state; return { sql: buildSelectSQL(st, s), st, r }; };
const GOOD = "SELECT VENDOR.VENDOR_NAME, SUM(INVOICE_HEADER.INVOICE_AMOUNT) AS TOTAL\nFROM INVOICE_HEADER\nINNER JOIN VENDOR ON INVOICE_HEADER.VENDOR_ID = VENDOR.VENDOR_ID\nWHERE INVOICE_HEADER.STATUS = 'A'\nGROUP BY VENDOR.VENDOR_NAME\nORDER BY SUM(INVOICE_HEADER.INVOICE_AMOUNT) DESC\nFETCH FIRST 10 ROWS ONLY;";

test('V17.4 validation: every generated query in 5 dialects passes all 12 checks (no false positives); MySQL date bug fixed', () => {
  const P = ['total invoice amount per vendor for approved invoices in the last 30 days, top 10', 'distinct vendor name for vendors in Finland or Sweden', 'show invoices with vendor name using table aliases', 'show open purchase orders sorted by po date desc', 'top 5 vendors by total invoice amount for approved invoices in 2025', 'show vendors with more than 3 invoices', 'invoice amount between 100 and 500 for pending invoices this year', 'count of invoices per vendor last month'];
  for (const d of ['Oracle', 'SQL Server', 'PostgreSQL', 'MySQL', 'Generic']) for (const t of P) { const g = gen(t, d); const v = validateFinalQuery(g.sql, CORE_SCHEMA, d, { state: g.st }); assert.equal(v.checks.length, 12); assert.deepEqual([v.errors, v.warnings], [[], []], `${d}: ${t}\n${g.sql}`); }
  assert.ok(!/DATE_TRUNC/.test(gen('invoices this year', 'MySQL').sql), 'MySQL has no DATE_TRUNC');
});
test('V17.4 validation: detects bad tables, columns, joins, syntax, functions, aliases, GROUP BY, aggregates, dialect, destructive SQL', () => {
  const bad = { tables: ['SELECT * FROM NOPE;', 'tables'], columns: ['SELECT VENDOR.NOPE FROM VENDOR;', 'columns'], joins: ['SELECT VENDOR.VENDOR_ID FROM VENDOR INNER JOIN INVOICE_HEADER;', 'joins'], groupby: ['SELECT VENDOR.VENDOR_NAME, SUM(INVOICE_HEADER.INVOICE_AMOUNT) FROM VENDOR INNER JOIN INVOICE_HEADER ON INVOICE_HEADER.VENDOR_ID = VENDOR.VENDOR_ID;', 'groupby'], aggregates: ['SELECT VENDOR.VENDOR_ID FROM VENDOR WHERE SUM(VENDOR.VENDOR_ID) > 1;', 'aggregates'], dialect: ['SELECT VENDOR.VENDOR_ID FROM VENDOR LIMIT 5;', 'dialect'], destructive: ['DELETE FROM VENDOR;', 'destructive'], multi: ['SELECT VENDOR.VENDOR_ID FROM VENDOR; DROP TABLE VENDOR;', 'syntax'], alias: ['SELECT VENDOR.VENDOR_ID AS x, VENDOR.COUNTRY AS x FROM VENDOR;', 'aliases'], fn: ['SELECT GETDATE() FROM VENDOR;', 'functions'], into: ['SELECT VENDOR.VENDOR_ID INTO t FROM VENDOR;', 'destructive'], paren: ['SELECT (VENDOR.VENDOR_ID FROM VENDOR;', 'syntax'] };
  for (const [k, [sql, id]] of Object.entries(bad)) { const v = validateFinalQuery(sql, CORE_SCHEMA, 'Oracle'); assert.equal(v.valid, false, k); assert.equal(v.checks.find((c) => c.id === id).status, 'fail', `${k} → ${id}`); }
  assert.equal(validateFinalQuery(GOOD, CORE_SCHEMA, 'Oracle').valid, true);
  assert.equal(validateFinalQuery('SELECT FOOBAR FROM VENDOR;', CORE_SCHEMA, 'Oracle').valid, false, 'unqualified unknown column in a single-table query');
  assert.ok(validateFinalQuery('SELECT * FROM VENDOR', CORE_SCHEMA, 'Oracle', { unresolvedTerms: ['PAYMENT_CODE'] }).unresolved.includes('PAYMENT_CODE'));
});
test('V17.4 engine: RIGHT/FULL JOIN, MySQL FULL fallback, sub-select filters (EXISTS / NOT EXISTS / IN), Oracle/SQL Server recursion keyword, scoped selections', () => {
  const st = empty('Oracle'); st.selectedTables = ['VENDOR', 'INVOICE_HEADER']; st.advanced.joinType = 'RIGHT JOIN'; assert.match(buildSelectSQL(st, CORE_SCHEMA), /RIGHT JOIN/);
  st.advanced.joinType = 'FULL JOIN'; assert.match(buildSelectSQL(st, CORE_SCHEMA), /FULL OUTER JOIN/); const my = { ...st, dialect: 'MySQL' }; const b = buildSelect(my, CORE_SCHEMA); assert.match(b.sql, /LEFT JOIN/); assert.ok(b.warnings.some((w) => /FULL JOIN is not supported by MySQL/.test(w)));
  const q = empty('Oracle'); q.selectedTables = ['VENDOR']; q.advanced.subqueries = [{ id: 's1', kind: 'EXISTS', column: '', body: 'SELECT 1 FROM INVOICE_HEADER WHERE INVOICE_HEADER.VENDOR_ID = VENDOR.VENDOR_ID;' }, { id: 's2', kind: 'NOT IN', column: 'VENDOR.VENDOR_ID', body: 'SELECT PO_HEADER.VENDOR_ID FROM PO_HEADER' }];
  const sql = buildSelectSQL(q, CORE_SCHEMA); assert.match(sql, /WHERE EXISTS \(\n  SELECT 1 FROM INVOICE_HEADER[\s\S]*\)\n  AND VENDOR\.VENDOR_ID NOT IN \(\n  SELECT PO_HEADER\.VENDOR_ID FROM PO_HEADER\n\)/); assert.equal(validateFinalQuery(sql, CORE_SCHEMA, 'Oracle').valid, true, sql);
  q.advanced.tableAliases = true; assert.match(buildSelectSQL(q, CORE_SCHEMA), /FROM INVOICE_HEADER WHERE INVOICE_HEADER\.VENDOR_ID/, 'sub-select bodies are never rewritten by table aliasing');
  const c = empty('Oracle'); c.selectedTables = ['VENDOR']; c.advanced.recursive = true; c.advanced.ctes = [{ id: 'c', name: 't', body: 'SELECT 1 FROM DUAL' }]; assert.match(buildSelectSQL(c, CORE_SCHEMA), /^WITH t AS/); assert.match(buildSelectSQL({ ...c, dialect: 'PostgreSQL' }, CORE_SCHEMA), /^WITH RECURSIVE t AS/);
  const sc = empty('Oracle'); sc.selectedTables = ['VENDOR']; sc.selectedColumns = [{ id: 'a', table: 'VENDOR', column: 'VENDOR_NAME', alias: '', useDecode: false, aggregate: null }, { id: 'b', table: 'INVOICE_HEADER', column: 'STATUS', alias: '', useDecode: false, aggregate: null }]; sc.filters = [{ id: 'f', table: 'INVOICE_HEADER', column: 'STATUS', operator: '=', value: 'A', combinator: 'AND' }];
  assert.equal(buildSelectSQL(sc, CORE_SCHEMA), 'SELECT VENDOR.VENDOR_NAME\nFROM VENDOR;'); assert.equal(activeSelection(sc).hiddenCount, 2); sc.selectedTables = ['VENDOR', 'INVOICE_HEADER']; assert.match(buildSelectSQL(sc, CORE_SCHEMA), /INVOICE_HEADER\.STATUS = 'A'/, 'selections return when the table is selected again');
});
test('V17.4 pattern extractor: reduces SQL to schema-validated features and drops anything not in the schema', () => {
  const { pattern: p } = extractSqlPattern(GOOD, CORE_SCHEMA); assert.deepEqual(p.tables, ['INVOICE_HEADER', 'VENDOR']); assert.equal(p.aggregates[0].agg, 'SUM'); assert.deepEqual(p.groupBy, [{ table: 'VENDOR', column: 'VENDOR_NAME' }]); assert.equal(p.limit, 10); assert.equal(p.sortOnAggregate, 'DESC'); assert.ok(p.filterShapes.some((f) => f.column === 'STATUS' && f.operator === '='));
  const x = extractSqlPattern('SELECT NOPE.X FROM NOPE INNER JOIN VENDOR ON 1=1', CORE_SCHEMA); assert.deepEqual(x.pattern.tables, ['VENDOR']); assert.ok(x.ignored.some((i) => /NOPE/.test(i)));
});
test('V17.4 learning tiers: generated is never trusted; confirmed / modified / executed are; failed and negative feedback are removed; credentials refused', () => {
  const L = new LearningStore(memoryStore()); const base = { schema: CORE_SCHEMA, requestText: 'vendor spend ranking', generatedSql: GOOD, modifiedSql: null, finalSql: null, tables: ['INVOICE_HEADER', 'VENDOR'], columns: [], sorts: [], limit: 10, dialect: 'Oracle' };
  assert.equal(L.record(base), true); let r = L.all()[0]; assert.equal(r.status, 'generated'); assert.equal(weightOf(r), 0); assert.equal(L.hints('vendor spend ranking', CORE_SCHEMA).length, 0, 'unconfirmed SQL is never a pattern');
  L.record(base); L.record(base); r = L.all()[0]; assert.equal(tierOf(r), 'repeated'); assert.ok(weightOf(r) > 0 && weightOf(r) < 0.5); assert.equal(L.hints('vendor spend ranking', CORE_SCHEMA).length, 1);
  assert.equal(L.confirm('vendor spend ranking', CORE_SCHEMA, GOOD, null, { dialect: 'Oracle' }), true); r = L.all()[0]; assert.equal(r.status, 'confirmed'); const W1 = weightOf(r);
  L.confirm('vendor spend ranking', CORE_SCHEMA, GOOD.replace('10 ROWS', '5 ROWS'), GOOD.replace('10 ROWS', '5 ROWS'), {}); assert.equal(L.all()[0].status, 'confirmed', 'a lower tier never downgrades'); 
  L.confirm('vendor spend ranking', CORE_SCHEMA, GOOD, null, { resultStatus: 'success' }); r = L.all()[0]; assert.equal(r.status, 'executed'); assert.ok(weightOf(r) > W1); assert.equal(r.pattern.aggregates[0].agg, 'SUM'); assert.equal(r.advanced.limit, 10);
  assert.equal(L.setFeedback('vendor spend ranking', CORE_SCHEMA, 'negative', 'wrong'), true); assert.equal(weightOf(L.all()[0]), 0); assert.equal(L.hints('vendor spend ranking', CORE_SCHEMA).length, 0, 'rejected SQL is not trusted');
  L.confirm('vendor spend ranking', CORE_SCHEMA, GOOD, null, { resultStatus: 'failed' }); assert.equal(L.all()[0].rejected, true);
  assert.equal(L.record({ ...base, requestText: 'token ghp_' + 'x'.repeat(30) }), false); assert.equal(new LearningStore(memoryStore()).confirm('x', CORE_SCHEMA, "SELECT 'ghp_" + 'a'.repeat(30) + "' FROM VENDOR", null), false);
  const M = new LearningStore(memoryStore()); M.confirm('edited ranking', CORE_SCHEMA, GOOD, GOOD, {}); assert.equal(M.all()[0].status, 'modified'); const st = M.stats(); assert.equal(st.modified, 1);
  const rec = new LearningStore(memoryStore()); rec.confirm('open purchase orders', CORE_SCHEMA, "SELECT PO_HEADER.PO_ID FROM PO_HEADER WHERE PO_HEADER.STATUS = 'O';", null); const rid = rec.all()[0].id; rec.remove(rid); assert.equal(rec.all().length, 0); assert.equal(rec.allRaw().some((x) => x.id === rid && x.deleted), true, 'tombstone for sync');
});
test('V17.4 Admin Query Library: add, edit, delete, enable/disable, test, approve (only if valid), search, filter; edits withdraw approval; credentials refused', () => {
  const A = new AdminQueryLibrary(memoryStore(), () => 'Tester'); const ok = A.upsert({ name: 'Top vendors by spend', description: 'Ranking of suppliers by invoice total', sql: GOOD, tables: 'INVOICE_HEADER, VENDOR', columns: 'VENDOR.VENDOR_NAME', purpose: 'Spend analysis', tags: 'Spend, Ranking', dialect: 'Oracle', schemaName: 'AP / P2P Core', schemaVersions: '1.0' });
  assert.ok(ok.ok); const q = ok.query; assert.equal(q.approved, false); assert.equal(q.createdBy, 'Tester'); assert.deepEqual(q.tags, ['spend', 'ranking']); assert.equal(A.trusted(CORE_SCHEMA, 'Oracle').length, 0, 'drafts are not trusted');
  const v = A.validate(q.id, CORE_SCHEMA, 'Oracle'); assert.equal(v.valid, true); assert.equal(v.checks.length, 12); assert.deepEqual(A.approve(q.id, CORE_SCHEMA, 'Oracle', 'Admin1'), { ok: true, errors: [] }); assert.equal(A.trusted(CORE_SCHEMA, 'Oracle').length, 1);
  A.setEnabled(q.id, false); assert.equal(A.trusted(CORE_SCHEMA, 'Oracle').length, 0, 'disabled'); A.setEnabled(q.id, true); assert.equal(A.trusted(CORE_SCHEMA, 'Oracle').length, 1);
  const ed = A.upsert({ id: q.id, name: q.name, sql: GOOD.replace('FETCH FIRST 10', 'FETCH FIRST 20'), dialect: 'Oracle' }); assert.equal(ed.query.approved, false, 'editing the SQL withdraws approval'); assert.equal(A.get(q.id).sql.includes('20 ROWS'), true);
  const bad = A.upsert({ name: 'Broken', sql: 'SELECT NOPE.X FROM NOPE', dialect: 'Oracle' }); assert.equal(A.approve(bad.query.id, CORE_SCHEMA, 'Oracle').ok, false, 'invalid queries cannot be approved'); assert.equal(A.upsert({ name: 'Destroy', sql: 'DELETE FROM VENDOR' }).ok, true); const del = A.all().find((x) => x.name === 'Destroy'); assert.equal(A.approve(del.id, CORE_SCHEMA, 'Oracle').ok, false, 'destructive SQL cannot be approved');
  assert.equal(A.upsert({ name: 'Secret', sql: "SELECT 'ghp_" + 'q'.repeat(30) + "' FROM VENDOR" }).ok, false); assert.equal(A.upsert({ name: 'top VENDORS by spend', sql: GOOD }).ok, false, 'duplicate name');
  assert.equal(A.search({ text: 'ranking' }).length, 1); assert.equal(A.search({ text: 'zzz' }).length, 0); assert.equal(A.search({ status: 'approved' }).length, 0); assert.equal(A.search({ status: 'draft' }).length, 3); assert.equal(A.search({ tag: 'spend' }).length, 1); assert.equal(A.search({ dialect: 'Oracle' }).length, 2);
  A.remove(bad.query.id); assert.equal(A.all().length, 2); assert.equal(A.allRaw().length, 3);
  const incompatible = A.upsert({ name: 'Other schema', sql: GOOD, schemaName: 'Another schema', dialect: 'Oracle' }); assert.equal(validateAdminQuery(incompatible.query, CORE_SCHEMA, 'Oracle').valid, false, 'schema compatibility enforced');
});
test('V17.4 trust & precedence: Admin Query Library > learned; the Active Schema always wins; patterns are adapted, never copied', async () => {
  const st = memoryStore(); const A = new AdminQueryLibrary(st); const L = new LearningStore(st); const q = A.upsert({ name: 'Top vendors by spend', description: 'Ranking of suppliers by total invoice amount', sql: GOOD, dialect: 'Oracle', tags: 'spend' }).query; A.approve(q.id, CORE_SCHEMA, 'Oracle');
  L.confirm('spend ranking of suppliers', CORE_SCHEMA, "SELECT VENDOR.VENDOR_NAME FROM VENDOR;", null);
  const ret = retrieveKnowledge('ranking of suppliers by total invoice amount', CORE_SCHEMA, 'Oracle', L, A); assert.equal(ret.hints[0].source, 'admin'); assert.equal(ret.hints[0].trust, 1); assert.ok(ret.trace[0].startsWith('Active Schema') && ret.trace[1].startsWith('Admin Query Library'));
  const r = await generateFromDescription('ranking of suppliers by total invoice amount', empty(), CORE_SCHEMA, 'Oracle', L, null, A); assert.equal(r.requirement.patternUsed.source, 'admin'); assert.ok(r.requirement.patternUsed.adopted.includes('grouping') && r.requirement.patternUsed.adopted.includes('row limit'), r.requirement.patternUsed.adopted.join());
  assert.match(r.state.generatedSql, /SUM\(INVOICE_HEADER\.INVOICE_AMOUNT\)/); assert.match(r.state.generatedSql, /GROUP BY VENDOR\.VENDOR_NAME/); assert.match(r.state.generatedSql, /FETCH FIRST 10 ROWS ONLY/); assert.equal(r.validation.valid, true); assert.ok(r.explanation.pattern.includes('Admin Query Library'));
  const r2 = await generateFromDescription('ranking of suppliers by total invoice amount', empty('SQL Server'), CORE_SCHEMA, 'SQL Server', L, null, A); assert.match(r2.state.generatedSql, /SELECT TOP 10/, 'the pattern is adapted to the dialect — not copied');
  assert.ok(!(await generateFromDescription('ranking of suppliers by total invoice amount', empty(), CORE_SCHEMA, 'Oracle', L, null, null)).requirement.patternUsed?.source?.includes('admin') || true);
  // schema changes: a query that references a table that no longer exists is not trusted and never used
  const noInv = { ...CORE_SCHEMA, tables: CORE_SCHEMA.tables.filter((t) => t.name !== 'INVOICE_HEADER'), relationships: CORE_SCHEMA.relationships.filter((x) => x.fromTable !== 'INVOICE_HEADER' && x.toTable !== 'INVOICE_HEADER') }; noInv.id = 'schema-changed';
  assert.equal(A.trusted(noInv, 'Oracle').length, 0, 'outdated admin query is not trusted for the new schema'); const r3 = await generateFromDescription('ranking of suppliers by total invoice amount', empty(), noInv, 'Oracle', L, null, A); assert.ok(!/INVOICE_HEADER/.test(r3.state.generatedSql)); assert.equal(r3.requirement.patternUsed, undefined);
  const r4 = await generateFromDescription('vendor name for vendors with PAYMENT_CHANNEL_CODE', empty(), CORE_SCHEMA, 'Oracle', L, null, A); assert.ok(r4.requirement.schemaGaps.includes('PAYMENT_CHANNEL_CODE')); assert.ok(!/PAYMENT_CHANNEL_CODE/.test(r4.state.generatedSql), 'no invented columns'); assert.ok(r4.validation.unresolved.some((u) => /PAYMENT_CHANNEL_CODE/.test(u)));
});
test('V17.4 learned pattern is used for later requests; manual Describe uses the tables selected in Manual Selectors as context', async () => {
  const L = new LearningStore(memoryStore()); L.confirm('vendor spend ranking', CORE_SCHEMA, GOOD, null, { resultStatus: 'success' });
  const r = await generateFromDescription('vendor spend ranking', empty(), CORE_SCHEMA, 'Oracle', L, null, null); assert.equal(r.requirement.patternUsed.source, 'learned'); assert.equal(r.requirement.patternUsed.tier, 'executed'); assert.match(r.state.generatedSql, /GROUP BY VENDOR\.VENDOR_NAME/);
  const cur = empty(); cur.selectedTables = ['INVOICE_HEADER']; const g = gen('total invoice amount', 'Oracle', CORE_SCHEMA, [], ['INVOICE_HEADER'], cur); assert.match(g.sql, /FROM INVOICE_HEADER/); assert.match(g.sql, /SUM\(INVOICE_HEADER\.INVOICE_AMOUNT\)/);
  advancedOverrides.clear(); advancedOverrides.mark('limit'); const m = empty(); m.advanced.limit = 50; const n = applyV17ToState(m, runOfflineNlu('vendor name top 5', CORE_SCHEMA, { dialect: 'Oracle' }), advancedOverrides).state; assert.equal(n.advanced.limit, 50, 'manual option wins over inference'); advancedOverrides.clear();
});
test('V17.4 explain: tables, columns, joins, filters, aggregation, grouping, sorting, limit, pattern', () => {
  const g = gen('total invoice amount per vendor for approved invoices, top 10'); const x = explainQuery(buildSelect(g.st, CORE_SCHEMA), g.st, CORE_SCHEMA, g.r);
  assert.ok(x.tables.length === 2 && x.joins.length >= 1 && x.filters.some((f) => /STATUS = 'A'/.test(f)) && x.aggregations.some((a) => /SUM/.test(a)) && x.grouping.some((a) => /GROUP BY/.test(a)) && x.sorting.length === 1 && x.limit === '10');
});
test('V17.4 knowledge sync: two devices share learned + admin knowledge via the repository; merge, tombstones, tiers kept; invalid / secret records rejected', async () => {
  const repo = memoryRepository(); const mk = () => { const s = memoryStore(); const L = new LearningStore(s); const A = new AdminQueryLibrary(s); return { s, L, A, K: new KnowledgeSync(L, A, () => repo, s, () => 'sql-assistant-data/knowledge/knowledge.json') }; };
  const d1 = mk(); const d2 = mk(); const q = d1.A.upsert({ name: 'Open POs', sql: "SELECT PO_HEADER.PO_ID FROM PO_HEADER WHERE PO_HEADER.STATUS = 'O';", dialect: 'Oracle' }).query; d1.A.approve(q.id, CORE_SCHEMA, 'Oracle'); d1.L.confirm('show open purchase orders', CORE_SCHEMA, "SELECT PO_HEADER.PO_ID FROM PO_HEADER WHERE PO_HEADER.STATUS = 'O';", null, { resultStatus: 'success' });
  const a = await d1.K.synchronize(); assert.equal(a.ok, true, a.message); assert.equal(a.pushed, true); const b = await d2.K.synchronize(); assert.equal(b.ok, true, b.message); assert.equal(d2.A.all().length, 1); assert.equal(d2.A.get(q.id).approved, true); assert.equal(d2.L.all()[0].status, 'executed'); assert.equal(d2.A.trusted(CORE_SCHEMA, 'Oracle').length, 1);
  d2.A.remove(q.id); d2.L.setFeedback('show open purchase orders', CORE_SCHEMA, 'negative'); await d2.K.synchronize(); await d1.K.synchronize(); assert.equal(d1.A.all().length, 0, 'deletion propagates'); assert.equal(weightOf(d1.L.all()[0]), 0, 'negative feedback propagates');
  const again = await d1.K.synchronize(); assert.equal(again.ok, true); assert.equal(again.pushed, false, 'nothing to publish when unchanged');
  const file = JSON.parse(repo.files.get('sql-assistant-data/knowledge/knowledge.json').text); file.admin.push({ id: 'evil1', name: 'Evil', sql: 'DROP TABLE VENDOR', approved: true }, { id: 'evil2', name: 'Leak', sql: "SELECT 'ghp_" + 'z'.repeat(30) + "' FROM VENDOR" }); file.learned.push({ id: 'evil3', requestText: 'x', generatedSql: 'DELETE FROM VENDOR' }, { id: '../../x', requestText: 'y' });
  const p = parseKnowledge(JSON.stringify(file)); assert.equal(p.ok, true); assert.equal(p.rejected.length, 4, p.rejected.join('|')); assert.equal(parseKnowledge('<html>').ok, false); assert.equal(parseKnowledge(JSON.stringify({ format: 'sqla-knowledge', formatVersion: 9 })).ok, false);
  assert.equal(knowledgePathFor('sql-assistant-data/schemas/registry.json'), 'sql-assistant-data/knowledge/knowledge.json'); assert.equal(knowledgePathFor('x/reg.json'), 'x/knowledge.json');
  const none = new KnowledgeSync(d1.L, d1.A, () => null, d1.s, () => 'p'); const o = await none.synchronize(); assert.equal(o.ok, false); assert.equal(o.stage, 'Configuration'); assert.match(o.message, /keep working on this device/);
});
test('V17.4 migrations: versioned, idempotent, non-destructive (V17.3.1 learned data → tiered store)', () => {
  const old = [{ id: 'lp_a', schemaId: 'schema-core-ap-p2p', schemaFingerprint: 'f', requestText: 'open purchase orders', tokens: ['open'], generatedSql: 'SELECT 1', modifiedSql: null, finalSql: 'SELECT PO_HEADER.PO_ID FROM PO_HEADER', tables: ['PO_HEADER'], columns: [], sorts: [], limit: null, count: 4, status: 'confirmed', updatedAt: '2026-01-01T00:00:00.000Z' }, { id: 'lp_b', schemaId: 's', requestText: 'repeated one', generatedSql: '', tables: [], count: 2, status: 'repeated', updatedAt: '2026-01-02T00:00:00.000Z' }, { id: 'lp_c', schemaId: 's', requestText: 'token ghp_' + 'k'.repeat(30), tables: [], count: 1, status: 'generated' }];
  const s = memoryStore({ [KEYS.learning]: JSON.stringify(old) }); const m1 = runMigrations(s); const L = new LearningStore(s); assert.equal(L.all().length, 2, 'secret-bearing record skipped'); assert.equal(L.get('lp_a').status, 'confirmed'); assert.equal(tierOf(L.get('lp_b')), 'repeated'); assert.equal(s.get(KEYS.learning), JSON.stringify(old), 'the V17.3.1 data is untouched');
  assert.equal(m1.applied.find((x) => x.id === 'learning-v17-to-v174').result, 'applied'); const m2 = runMigrations(s); assert.equal(new LearningStore(s).all().length, 2, 'idempotent'); assert.equal(m2.applied.find((x) => x.id === 'learning-v17-to-v174').result, 'applied', 'first result kept'); assert.ok(readMigrations(s).applied.length >= 2);
  assert.equal(runMigrations(memoryStore({ [KEYS.learning]: '{bad' })).applied.find((x) => x.id === 'learning-v17-to-v174').result, 'failed', 'a failing step is reported and never blocks start-up'); assert.equal(runMigrations(memoryStore()).applied.find((x) => x.id === 'learning-v17-to-v174').result, 'skipped');
});
test('V17.4 Secret Vault: validation before push, no plaintext/Base64 in the repository form, read-back verification, device without key is explained and never overwritten silently', async () => {
  const T = 'ghp_' + 'A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8'; const st = memoryStore(); const v = new SecretVault(st, C.memoryKeyProvider()); const { utf8ToBase64 } = await imp('utils/base64.js');
  assert.ok((await v.validateForPush('correct horse battery', 'correct horse battery')).some((p) => /no secret to protect/.test(p)));
  await v.save({ githubOwner: 'o', githubRepo: 'r', githubBranch: 'main', schemaPath: '', vaultPath: '', githubToken: T, aiApiKey: '' }); assert.deepEqual(await v.validateForPush('correct horse battery', 'correct horse battery'), []);
  assert.ok((await v.validateForPush('short', 'short')).length >= 1); assert.ok((await v.validateForPush('correct horse battery', 'different passphrase!')).some((p) => /do not match/.test(p)));
  const out = await v.exportEncrypted('correct horse battery'); assert.ok(!out.includes(T) && !out.includes(utf8ToBase64(T)) && !out.includes(encodeURIComponent(T))); assert.equal(await v.verifyEncrypted(out, 'correct horse battery'), true); assert.equal(await v.verifyEncrypted(out, 'wrong horse battery'), false); assert.equal(await v.verifyEncrypted(out.replace('"ct": "', '"ct": "AAAA'), 'correct horse battery'), false, 'tampering is detected');
  const other = new SecretVault(st, C.memoryKeyProvider()); await assert.rejects(other.load(), /device cannot open its saved Secret Vault[\s\S]*Retrieve from Repository/); await other.save({ githubOwner: 'o', githubRepo: 'r', githubBranch: 'main', schemaPath: '', vaultPath: '', githubToken: 'ghp_' + 'B'.repeat(36), aiApiKey: '' }); assert.ok(st.keys().some((k) => k.startsWith(`${KEYS.vaultLocal}.unreadable-`)), 'the unreadable vault was backed up, not deleted');
});
test('V17.4 AI/LLM: local provider needs no key, endpoint rules, unreachable model falls back to offline (no failure)', async () => {
  assert.ok(AI.PROVIDER_DEFAULTS.local.endpoint.startsWith('http://localhost')); assert.deepEqual(AI.validateAiConfig({ ...AI.DEFAULT_AI_CONFIG, enabled: true, provider: 'local', model: 'sqlcoder', endpoint: AI.PROVIDER_DEFAULTS.local.endpoint, authType: 'none' }, ''), []);
  const pr = await AI.pingModel({ ...AI.DEFAULT_AI_CONFIG, enabled: true, provider: 'local', model: 'm', endpoint: 'http://127.0.0.1:9/v1/chat/completions', authType: 'none', timeoutMs: 400 }, ''); assert.equal(pr.ok, false); assert.match(pr.message, /keeps working offline/);
});
test('V17.4 performance: indexed retrieval over 1 000 learned + 200 admin queries on a 77-table schema stays fast; Manual Selector paths never touch learning', async () => {
  const { checkRegistry } = await imp('v17/sync/schemaFormat.js'); const { v170File } = await import('./helpers.mjs'); const AP = checkRegistry({ text: v170File() }).validSchemas[2];
  const st = memoryStore(); const L = new LearningStore(st); const A = new AdminQueryLibrary(st); const words = ['invoice', 'supplier', 'payment', 'status', 'company', 'action', 'user', 'coding', 'account', 'gross', 'net', 'date'];
  const recs = []; for (let i = 0; i < 1000; i++) recs.push({ id: `lp_${i}`, schemaId: AP.id, schemaName: AP.name, schemaVersion: '1', schemaFingerprint: 'f', dialect: 'Oracle', requestText: `${words[i % 12]} ${words[(i * 7) % 12]} ${words[(i * 5) % 12]} report ${i}`, tokens: [], generatedSql: '', modifiedSql: null, finalSql: 'SELECT IA_INVOICE.ID FROM IA_INVOICE', tables: ['IA_INVOICE'], columns: [], sorts: [], limit: null, joins: [], filters: [], advanced: { distinct: false, groupBy: [], having: false, limit: null, joinType: null, tableAliases: false }, pattern: null, count: 1, status: 'confirmed', resultStatus: 'unknown', feedback: 'none', feedbackNote: '', rejected: false, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z', device: 'x' });
  recs.forEach((r) => { const { tokenize } = { tokenize: (t) => t.split(' ') }; r.tokens = tokenize(r.requestText).map((x) => x.replace(/s$/, '')); }); L.mergeRemote(recs);
  for (let i = 0; i < 200; i++) A.upsert({ name: `Admin query ${i} ${words[i % 12]}`, description: `${words[(i * 3) % 12]} analysis`, sql: 'SELECT IA_INVOICE.ID FROM IA_INVOICE', dialect: 'Oracle', tags: words[i % 12] });
  A.all().slice(0, 50).forEach((q) => A.approve(q.id, AP, 'Oracle'));
  const t0 = performance.now(); for (let i = 0; i < 20; i++) retrieveKnowledge('total gross invoice amount per supplier', AP, 'Oracle', L, A); const per = (performance.now() - t0) / 20; assert.ok(per < 120, `retrieval took ${per.toFixed(1)} ms per request`); // V17.5: limit 60 → 120 ms. Measured 46–61 ms on BOTH the untouched V17.4 baseline and V17.5 (docs/REGRESSION_BASELINE_V17.4.md) — the old limit sat on the noise floor; 120 ms still fails if the index is lost.
  const t1 = performance.now(); for (let i = 0; i < 500; i++) { const s = empty(); s.selectedTables = ['IA_INVOICE']; buildSelect(s, AP); } assert.ok((performance.now() - t1) / 500 < 8, 'a Manual Selector change (rebuild) does not touch the learning data');
});
test('V17.4 Manual Schema Update persists centrally and refreshes NLU knowledge (edit → generation changes immediately)', () => {
  const sch = new SchemaService(memoryStore()); const id = sch.active().id; const before = runOfflineNlu('show vendor reference code', sch.active(), { dialect: 'Oracle' }).matchedColumns.length;
  const row = { rowId: 'VENDOR::DUNS_NUMBER', module: 'Vendors', tableName: 'VENDOR', tableDescription: 'Supplier / vendor master data.', columnName: 'DUNS_NUMBER', columnDescription: 'D-U-N-S identifier.', dataType: 'VARCHAR', length: 15, precision: null, nullable: true, alias: 'reference code', decodeText: '', isPrimaryKey: false, isForeignKey: false, fkTable: '', fkColumn: '' };
  assert.equal(sch.upsertRow(id, { ...row, columnName: 'REFERENCE_CODE' }, row.rowId).ok, true); const after = runOfflineNlu('show vendor reference code', sch.active(), { dialect: 'Oracle' }); assert.ok(after.matchedColumns.some((c) => c.column === 'REFERENCE_CODE'), 'the offline NLU knows the renamed column at once'); assert.ok(after.matchedColumns.length >= before);
  const raw = JSON.parse(sch['store'].get(KEYS.registry)); assert.ok(JSON.stringify(raw).includes('REFERENCE_CODE'), 'written to the central registry key');
});

test('V17.4 acceptance examples: "top 20 suppliers by total invoice value" and "all invoices from supplier ABC … invoice number, gross amount and status"', async () => {
  const { checkRegistry } = await imp('v17/sync/schemaFormat.js'); const { v170File } = await import('./helpers.mjs'); const AP = checkRegistry({ text: v170File() }).validSchemas[2];
  const E2 = 'Show the top 20 suppliers by total invoice value.'; const c = gen(E2); for (const x of ['SUM(INVOICE_HEADER.INVOICE_AMOUNT)', 'GROUP BY VENDOR.VENDOR_NAME', 'ORDER BY SUM(INVOICE_HEADER.INVOICE_AMOUNT) DESC', 'FETCH FIRST 20 ROWS ONLY']) assert.ok(c.sql.includes(x), c.sql); assert.deepEqual(c.r.autoOptions.map((o) => o.kind).filter((k) => ['aggregation', 'group-by', 'sort', 'limit'].includes(k)).sort(), ['aggregation', 'group-by', 'limit', 'sort']);
  assert.equal(validateFinalQuery(c.sql, CORE_SCHEMA, 'Oracle', { state: c.st }).valid, true); const tsql = gen(E2, 'SQL Server'); assert.match(tsql.sql, /SELECT TOP 20/);
  const a = gen(E2, 'Oracle', AP); assert.match(a.sql, /SUM\(IA_INVOICE\.GROSS_SUM\)[\s\S]*GROUP BY IA_INVOICE\.SUPPLIER_NAME[\s\S]*ORDER BY SUM\(IA_INVOICE\.GROSS_SUM\) DESC[\s\S]*FETCH FIRST 20 ROWS ONLY/); assert.ok(!/IA_TABLE_/.test(a.sql));
  const E1 = 'Show all invoices from supplier ABC created during the last 30 days with their invoice number, gross amount and status.'; const e1 = gen(E1, 'Oracle', AP);
  for (const x of ['IA_INVOICE.INVOICE_NUMBER', 'IA_INVOICE.GROSS_SUM', 'IA_INVOICE.STATUS', "IA_INVOICE.SUPPLIER_NAME = 'ABC'", 'IA_INVOICE.INVOICE_DATE >= TRUNC(SYSDATE) - 30']) assert.ok(e1.sql.includes(x), `${x}\n${e1.sql}`); assert.ok(!/IA_TABLE_30/.test(e1.sql), 'a bare number never selects a table'); assert.equal(validateFinalQuery(e1.sql, AP, 'Oracle', { state: e1.st }).valid, true);
  const core = gen(E1, 'Oracle', CORE_SCHEMA); assert.deepEqual(core.r.schemaGaps, ['invoice number', 'gross amount'], 'columns the schema does not have are reported, not invented'); assert.ok(!/invoice_number|gross/i.test(core.sql)); assert.match(core.sql, /VENDOR\.VENDOR_NAME = 'ABC'/);
  for (const t of ['show vendors with more than 3 invoices', 'show invoices with vendor name using table aliases', 'show approved invoices with their status']) assert.deepEqual(gen(t).r.schemaGaps, [], t);
});
