import { test } from 'node:test'; import assert from 'node:assert/strict';
import { imp, tiny, AP77, v170File } from './helpers.mjs';
const { CORE_SCHEMA } = await imp('data/defaultSchemas.js'); const { memoryStore, KEYS } = await imp('services/storage.js'); const { SchemaService } = await imp('services/schemaService.js');
const SY = await imp('v17/sync/syncService.js'); const { memoryRepository } = await imp('v17/services/githubClient.js'); const V = await imp('v17/services/secretVault.js'); const C = await imp('v17/services/cryptoBox.js');
const SC = await imp('v17/services/schemaCrypto.js'); const { SchemaPassphraseStore } = await imp('v17/services/schemaPassphrase.js'); const F = await imp('v17/sync/schemaFormat.js');
const { runOfflineNlu } = await imp('v17/engines/nluEngine.js'); const { applyV17ToState } = await imp('v17/engines/advancedOptionsResolver.js'); const { buildSelect, buildSelectSQL, schemaDecodeSql } = await imp('engines/sqlEngine.js');
const { validateFinalQuery } = await imp('v17/engines/queryValidator.js'); const { extractSqlPattern } = await imp('v17/engines/sqlPatterns.js'); const { LearningStore } = await imp('v17/services/learningStore.js'); const { AdminQueryLibrary } = await imp('v17/services/adminLibrary.js');
const { generateFromDescription } = await imp('v17/services/queryOrchestrator.js'); const { explainQuery } = await imp('v17/engines/explain.js');
const PATH = V.CANONICAL_SCHEMA_PATH; const ENC = SC.encryptedPathFor(PATH); const PASS = 'correct horse battery staple';
const empty = (d = 'Oracle') => ({ dialect: d, naturalLanguageText: '', selectedTables: [], selectedColumns: [], filters: [], sorts: [], advanced: { distinct: false, groupByColumns: [], havingClause: '', limit: null, viewName: '', tableAliases: false, joinType: 'INNER JOIN', recursive: false, ctes: [], subqueries: [] }, generatedSql: '', joinPathChoices: {} });
const col = (t, c, x = {}) => ({ id: `c_${t}_${c}`, table: t, column: c, alias: '', useDecode: false, aggregate: null, ...x });
/** A device: its own storage, schema service and sync service. `pass.value` null = classic plain sync (V17.4 behaviour). */
const dev = (repo, pass = { value: null }, store = memoryStore()) => { const schemas = new SchemaService(store); const sync = new SY.SyncService(schemas, () => repo, store, () => PATH, () => (pass.value ? [pass.value] : []), { passphrase: async () => pass.value, path: () => ENC }); return { store, schemas, sync, pass }; };
const coreSnap = (d) => JSON.stringify([d.schemas.registry(), d.store.get(KEYS.syncMeta), d.store.get(KEYS.syncBase)]); // schemas + sync state (a failure may add a log line — that is fine)
const snapshot = (d) => JSON.stringify([d.schemas.registry(), d.store.get(KEYS.syncMeta), d.store.get(KEYS.syncLog), d.store.get(KEYS.syncBase)]);
const withSchema = (d, s) => { const r = d.schemas.registry(); assert.equal(d.schemas.replaceRegistry({ ...r, schemas: [...r.schemas.filter((x) => x.name !== s.name), s], activeSchemaId: s.id }).ok, true); };
const published = async () => { const repo = memoryRepository(); const A = dev(repo, { value: PASS }); const s = tiny('Core A'); s.version = '2.1'; s.updatedAt = '2026-03-01T10:00:00.000Z'; s.tables[0].columns[1].decode = [{ rawValue: '1', label: 'Open' }, { rawValue: '2', label: 'Approved' }, { rawValue: '3', label: 'Rejected' }]; s.relationships = []; withSchema(A, s); const r = await A.sync.push(); assert.equal(r.ok, true, r.problems.join('|')); return { repo, A, s }; };

test('V17.5 crypto: real AES-256-GCM — nothing readable in the file, random per write, wrong passphrase / damage / tampering / plain file / weak passphrase are told apart', async () => {
  const text = F.serializeRegistry({ schemas: [tiny('Secret Schema Name')], activeSchemaId: 's-secret-schema-name' }, 'dev-x').text; const f1 = await SC.encryptSchemaRegistry(text, PASS, { device: 'dev-x', schemaCount: 1 }); const f2 = await SC.encryptSchemaRegistry(text, PASS, { device: 'dev-x', schemaCount: 1 });
  const { utf8ToBase64 } = await imp('utils/base64.js'); for (const bad of ['Secret Schema Name', 'STATUS', PASS, utf8ToBase64('Secret Schema Name'), utf8ToBase64(PASS)]) assert.ok(!f1.includes(bad), bad); assert.notEqual(JSON.parse(f1).cipher.ct, JSON.parse(f2).cipher.ct); assert.notEqual(JSON.parse(f1).cipher.salt, JSON.parse(f2).cipher.salt);
  const h = SC.readHeader(f1); assert.deepEqual([h.format, h.formatVersion, h.appVersion, h.writtenBy, h.schemaFormatVersion, h.schemaCount], ['sqla-schema-sync', 1, F.APP_VERSION, F.WRITER_LABEL, F.SCHEMA_FORMAT_VERSION, 1]); assert.ok(!f1.includes('tables') && !f1.includes('columns'), 'header holds no schema structure');
  assert.equal((await SC.decryptSchemaRegistry(f1, PASS)).text, text);
  await assert.rejects(SC.decryptSchemaRegistry(f1, 'a completely different passphrase'), (e) => e.code === 'incorrect-passphrase');
  const j = JSON.parse(f1); const flip = (s) => `${s.slice(0, 10)}${s[10] === 'A' ? 'B' : 'A'}${s.slice(11)}`;
  await assert.rejects(SC.decryptSchemaRegistry(JSON.stringify({ ...j, cipher: { ...j.cipher, ct: flip(j.cipher.ct) } }), PASS), (e) => e.code === 'corrupted', 'damaged data');
  await assert.rejects(SC.decryptSchemaRegistry(JSON.stringify({ ...j, schemaCount: 9 }), PASS), (e) => e.code === 'corrupted', 'header tampering is detected');
  await assert.rejects(SC.decryptSchemaRegistry(text, PASS), (e) => e.code === 'not-encrypted'); await assert.rejects(SC.decryptSchemaRegistry('<html>', PASS), (e) => e.code === 'corrupted'); await assert.rejects(SC.decryptSchemaRegistry(JSON.stringify({ ...j, formatVersion: 9 }), PASS), (e) => e.code === 'unsupported');
  await assert.rejects(SC.decryptSchemaRegistry(f1, 'short'), (e) => e.code === 'weak-passphrase'); await assert.rejects(SC.encryptSchemaRegistry(text, 'short', { device: 'd', schemaCount: 1 }), (e) => e.code === 'weak-passphrase');
  await assert.rejects(SC.decryptSchemaRegistry(JSON.stringify({ ...j, cipher: { ...j.cipher, iter: 10 } }), PASS), (e) => e.code === 'corrupted', 'a downgraded key-derivation cost is refused');
  assert.equal(SC.encryptedPathFor('sql-assistant-data/schemas/registry.json'), 'sql-assistant-data/schemas/registry.enc.json');
});
test('V17.5 saved passphrase: only ciphertext at rest (never plaintext / Base64), unreadable-not-deleted when the device key is lost, never returned by known() before use', async () => {
  const st = memoryStore(); const keys = C.memoryKeyProvider(); const P = new SchemaPassphraseStore(st, keys); assert.equal(await P.get(), null); await assert.rejects(P.set('short'), /at least 10/); await P.set(PASS);
  const raw = st.get(KEYS.schemaPassphrase); const { utf8ToBase64 } = await imp('utils/base64.js'); assert.ok(raw && !raw.includes(PASS) && !raw.includes(utf8ToBase64(PASS)) && JSON.parse(raw).alg === 'AES-256-GCM'); assert.equal(await new SchemaPassphraseStore(st, keys).get(), PASS);
  const lost = new SchemaPassphraseStore(st, C.memoryKeyProvider()); assert.equal(await lost.get(), null); assert.equal(lost.isUnreadable(), true); assert.ok(st.get(KEYS.schemaPassphrase), 'kept, not silently deleted'); P.clear(); assert.equal(P.hasSaved(), false);
});
test('V17.5 schema metadata: the registry carries id / version / updatedAt per schema and the writer, app and format version for the whole file', async () => {
  const { repo } = await published(); const enc = repo.files.get(ENC).text; assert.ok(!repo.files.has(PATH), 'no plain schema file is written while a passphrase protects the schema'); const hdr = SC.readHeader(enc); assert.equal(hdr.appVersion, F.APP_VERSION); assert.equal(hdr.schemaFormatVersion, F.SCHEMA_FORMAT_VERSION); assert.match(hdr.writtenBy, /^SQL Assistant 17\.5/); assert.ok(hdr.writtenAt && hdr.writtenByDevice);
  const reg = JSON.parse((await SC.decryptSchemaRegistry(enc, PASS)).text); assert.equal(reg.appVersion, F.APP_VERSION); assert.equal(reg.formatVersion, F.SCHEMA_FORMAT_VERSION); assert.match(reg.writtenBy, /17\.5/); const s = reg.schemas.find((x) => x.name === 'Core A'); assert.deepEqual([s.id, s.version, s.updatedAt], ['s-core-a', '2.1', '2026-03-01T10:00:00.000Z']);
  assert.equal(F.detectWriter(reg).appVersion, F.APP_VERSION);
});
test('V17.5 cross-device: Device A publishes, Device B previews (nothing written), applies, and receives structure, tables, columns, types, relationships, CASE/DECODE, metadata, ids and the active schema', async () => {
  const { repo, s } = await published(); const B = dev(repo, { value: null }); const before = snapshot(B); const pv = await B.sync.previewEncryptedPull(PASS);
  assert.equal(pv.ok, true); assert.deepEqual(pv.rows.map((r) => [r.name, r.kind, r.remoteVersion, r.decodeEntries]), [['Core A', 'add', '2.1', 3]]); assert.equal(pv.remoteActive, 'Core A'); assert.equal(pv.willChange, true); assert.equal(snapshot(B), before, 'previewing wrote nothing: no schema, no sync metadata, no log');
  const out = await B.sync.applyPreview(pv); assert.equal(out.ok, true); assert.deepEqual(out.added, ['Core A']); assert.equal(out.activeChanged, true); const got = B.schemas.byId('s-core-a'); assert.ok(got);
  assert.deepEqual(got.tables.map((t) => [t.name, t.module, t.columns.map((c) => [c.name, c.type, c.nullable, !!c.isPrimaryKey, c.decode || null])]), s.tables.map((t) => [t.name, t.module, t.columns.map((c) => [c.name, c.type, c.nullable, !!c.isPrimaryKey, c.decode || null])])); assert.deepEqual([got.version, got.updatedAt, got.id], ['2.1', '2026-03-01T10:00:00.000Z', 's-core-a']); assert.equal(B.schemas.active().name, 'Core A');
  assert.equal(SY.contentHash(got), SY.contentHash(s), 'content identical'); assert.ok(B.sync.meta().sha, 'sync metadata recorded only after a successful apply');
  const nlu = runOfflineNlu('show id and status description', B.schemas.active(), { dialect: 'Oracle' }); assert.ok(nlu.matchedColumns.some((c) => c.column === 'STATUS' && c.useDecode), 'the offline NLU already uses the pulled schema and its CASE/DECODE');
  const again = await B.sync.previewEncryptedPull(PASS); assert.equal(again.rows[0].kind, 'unchanged'); assert.equal(again.willChange, false);
});
test('V17.5 failure scenarios: wrong passphrase, missing file, corrupted file, invalid schema, decryption failure, repository failure, weak passphrase — local schema intact in every case, passphrase never echoed', async () => {
  const { repo } = await published(); const B = dev(repo); withSchema(B, Object.assign(tiny('Local Work'), { updatedAt: '2026-04-01T00:00:00.000Z' })); const before = snapshot(B); const secretLeak = (pv) => JSON.stringify(pv.problem).includes(PASS);
  let pv = await B.sync.previewEncryptedPull('this is the wrong passphrase'); assert.deepEqual([pv.ok, pv.problem.kind], [false, 'incorrect-passphrase']); assert.ok(!secretLeak(pv));
  pv = await B.sync.previewEncryptedPull('short'); assert.deepEqual([pv.ok, pv.problem.kind], [false, 'passphrase']); assert.equal((await B.sync.previewEncryptedPull('')).problem.kind, 'passphrase');
  pv = await dev(memoryRepository()).sync.previewEncryptedPull(PASS); assert.equal(pv.problem.kind, 'missing'); assert.match(pv.problem.detail, /registry\.enc\.json/);
  const text = repo.files.get(ENC).text; const j = JSON.parse(text); const bad = (mut) => { const r = memoryRepository({ [ENC]: JSON.stringify(mut) }); return dev(r).sync.previewEncryptedPull(PASS); };
  pv = await bad({ ...j, cipher: { ...j.cipher, ct: j.cipher.ct.slice(0, 20) + (j.cipher.ct[20] === 'A' ? 'B' : 'A') + j.cipher.ct.slice(21) } }); assert.equal(pv.problem.kind, 'decryption'); pv = await bad({ ...j, schemaCount: 7 }); assert.equal(pv.problem.kind, 'decryption'); pv = await dev(memoryRepository({ [ENC]: '{broken' })).sync.previewEncryptedPull(PASS); assert.equal(pv.problem.kind, 'decryption');
  pv = await dev(memoryRepository({ [ENC]: F.serializeRegistry({ schemas: [tiny('X')], activeSchemaId: 's-x' }, 'd').text })).sync.previewEncryptedPull(PASS); assert.equal(pv.problem.kind, 'not-encrypted');
  const invalid = tiny('Broken'); invalid.tables[0].columns[1].decode = [{ rawValue: '', label: 'oops' }]; const mk = (obj) => SC.encryptSchemaRegistry(JSON.stringify(obj), PASS, { device: 'd', schemaCount: obj.schemas.length });
  pv = await dev(memoryRepository({ [ENC]: await mk({ formatVersion: 2, writtenBy: 'SQL Assistant 17.5.0', schemas: [tiny('Fine'), invalid], activeSchemaId: 's-fine' }) })).sync.previewEncryptedPull(PASS); assert.deepEqual([pv.ok, pv.problem.kind], [false, 'validation']); assert.ok(pv.problem.items.some((x) => /empty raw value/.test(x)), 'the first problem is located'); assert.equal(pv.rows.length, 0, 'one invalid schema fails the whole pull — all or nothing');
  const noMeta = tiny('NoMeta'); delete noMeta.version; pv = await dev(memoryRepository({ [ENC]: await mk({ formatVersion: 2, writtenBy: 'SQL Assistant 17.5.0', schemas: [noMeta], activeSchemaId: noMeta.id }) })).sync.previewEncryptedPull(PASS); assert.equal(pv.problem.kind, 'metadata'); assert.match(pv.problem.items[0], /"version"/);
  pv = await dev(memoryRepository({ [ENC]: await mk({ formatVersion: 2, writtenBy: 'SQL Assistant 17.5.0', schemas: [], activeSchemaId: null }) })).sync.previewEncryptedPull(PASS); assert.equal(pv.problem.kind, 'validation');
  const flaky = { ...repo, async read() { throw new Error('Could not reach GitHub (network down).'); } }; pv = await dev(flaky).sync.previewEncryptedPull(PASS); assert.equal(pv.problem.kind, 'unavailable'); pv = await new SY.SyncService(B.schemas, () => null, B.store, () => PATH, () => [], { passphrase: async () => null, path: () => ENC }).previewEncryptedPull(PASS); assert.equal(pv.problem.kind, 'configuration');
  assert.equal(snapshot(B), before, 'the existing local schema, sync metadata and log are unchanged after every failure'); assert.equal(B.schemas.active().name, 'Local Work');
});
test('V17.5 apply is transactional: a failing write rolls back, the working schema stays', async () => {
  const { repo } = await published(); const B = dev(repo); const pv = await B.sync.previewEncryptedPull(PASS); const before = coreSnap(B); const store = B.store; const real = store.set; store.set = (k, v) => (k === KEYS.registry ? false : real(k, v));
  const out = await B.sync.applyPreview(pv); store.set = real; assert.equal(out.ok, false); assert.equal(out.stage, 'Persistence'); assert.match(out.fileProblem, /kept unchanged/); assert.equal(coreSnap(B), before); assert.ok(!B.schemas.byId('s-core-a'));
});
test('V17.5 versioning: an older repository schema never replaces a newer local one; a newer repository schema updates; both-changed is a conflict, not an overwrite', async () => {
  const { repo, A } = await published(); const B = dev(repo); let pv = await B.sync.previewEncryptedPull(PASS); await B.sync.applyPreview(pv);
  const newer = { ...B.schemas.byId('s-core-a'), description: 'x', updatedAt: '2026-06-01T00:00:00.000Z' }; newer.tables = JSON.parse(JSON.stringify(newer.tables)); newer.tables[0].columns[0].description = 'edited on B'; assert.equal(B.schemas.saveSchema(newer).ok, true);
  pv = await B.sync.previewEncryptedPull(PASS); assert.deepEqual(pv.rows.map((r) => r.kind), ['local-newer']); assert.equal(pv.willChange, false); const keep = JSON.stringify(B.schemas.byId('s-core-a')); const out = await B.sync.applyPreview(pv); assert.equal(out.ok, true); assert.deepEqual(out.localAhead, ['Core A']); assert.equal(JSON.stringify(B.schemas.byId('s-core-a')), keep, 'the newer local schema was not replaced');
  const C2 = dev(repo); const mine = tiny('Core A'); mine.updatedAt = '2027-01-01T00:00:00.000Z'; mine.tables[0].columns[0].description = 'mine'; withSchema(C2, mine); pv = await C2.sync.previewEncryptedPull(PASS); assert.equal(pv.rows[0].kind, 'local-newer', 'no sync history + newer local timestamp → never overwritten');
  const D = dev(repo); const old = tiny('Core A'); old.updatedAt = '2025-01-01T00:00:00.000Z'; old.tables[0].columns[0].description = 'old'; withSchema(D, old); pv = await D.sync.previewEncryptedPull(PASS); assert.equal(pv.rows[0].kind, 'update'); assert.equal(pv.willChange, true);
  const s2 = JSON.parse(JSON.stringify(A.schemas.byId('s-core-a'))); s2.version = '2.2'; s2.updatedAt = '2026-09-01T00:00:00.000Z'; s2.tables[0].columns[0].description = 'admin change'; assert.equal(A.schemas.saveSchema(s2).ok, true); assert.equal((await A.sync.push()).ok, true);
  const E2 = dev(repo); await E2.sync.applyPreview(await E2.sync.previewEncryptedPull(PASS)); E2.schemas.byId('s-core-a'); const rows2 = (await B.sync.previewEncryptedPull(PASS)).rows; assert.ok(['conflict', 'update', 'local-newer'].includes(rows2[0].kind)); assert.notEqual(rows2[0].kind, 'unchanged');
});
test('V17.5 passphrase change: the administrator re-publishes, devices with the old passphrase are told, the new passphrase opens it; a plain device is unaffected', async () => {
  const { repo, A } = await published(); const NEW = 'a brand new passphrase!'; A.pass.value = NEW; let r = await A.sync.push(); assert.equal(r.ok, false); assert.equal(r.stage, 'Passphrase'); assert.match(r.problems[0], /different passphrase/); assert.ok(!r.problems.join().includes(NEW));
  r = await A.sync.push({ allowReplacingInvalidRemote: true, replaceUndecryptable: true }); assert.equal(r.ok, true, r.problems.join()); const B = dev(repo); assert.equal((await B.sync.previewEncryptedPull(PASS)).problem.kind, 'incorrect-passphrase'); assert.equal((await B.sync.previewEncryptedPull(NEW)).ok, true);
  const plainRepo = memoryRepository({ [PATH]: v170File() }); const P = dev(plainRepo); const x = await P.sync.synchronize(); assert.equal(x.pull.ok, true); assert.ok(!x.pull.encrypted); assert.ok(plainRepo.files.get(PATH), 'classic plain synchronization is unchanged'); assert.ok(!plainRepo.files.has(ENC));
});
test('V17.5 encrypted mode for ordinary sync: with a saved passphrase "Sync now" pulls and publishes the encrypted file; a wrong saved passphrase is reported without touching the local schema', async () => {
  const { repo } = await published(); const B = dev(repo, { value: PASS }); const r = await B.sync.synchronize(); assert.equal(r.pull.ok, true); assert.equal(r.pull.encrypted, true); assert.ok(B.schemas.byId('s-core-a')); assert.equal(repo.files.size, 1, 'one encrypted file, no plain file');
  const W = dev(repo, { value: 'not the right passphrase' }); const before = coreSnap(W); const w = await W.sync.pull(); assert.equal(w.ok, false); assert.equal(w.stage, 'Passphrase'); assert.match(w.fileProblem, /passphrase is incorrect[\s\S]*has not been changed/); assert.equal(coreSnap(W), before);
  const v = await B.sync.validateRemote(); assert.equal(v.ok, true);
});
test('V17.5 CASE/DECODE engine: schema CASE, schema DECODE (Oracle), CASE fallback elsewhere, definition read from the active schema, never invented, NULL-safe quoting', () => {
  const st = empty('Oracle'); st.selectedTables = ['INVOICE_HEADER']; st.selectedColumns = [col('INVOICE_HEADER', 'INVOICE_ID'), col('INVOICE_HEADER', 'STATUS', { useDecode: true, displayMode: 'schema-decode', decodeStyle: 'case' })];
  assert.match(buildSelectSQL(st, CORE_SCHEMA), /CASE WHEN INVOICE_HEADER\.STATUS = 'P' THEN 'Pending' WHEN INVOICE_HEADER\.STATUS = 'A' THEN 'Approved'[\s\S]*ELSE CAST\(INVOICE_HEADER\.STATUS AS VARCHAR\(255\)\) END AS STATUS_DESC/);
  st.selectedColumns[1].decodeStyle = 'decode'; assert.match(buildSelectSQL(st, CORE_SCHEMA), /DECODE\(INVOICE_HEADER\.STATUS, 'P', 'Pending', 'A', 'Approved', 'R', 'Rejected', 'D', 'Paid', TO_CHAR\(INVOICE_HEADER\.STATUS\)\) AS STATUS_DESC/);
  for (const d of ['SQL Server', 'PostgreSQL', 'MySQL']) { const b = buildSelect({ ...st, dialect: d }, CORE_SCHEMA); assert.ok(!/DECODE\(/.test(b.sql) && /CASE WHEN/.test(b.sql), `${d} always gets CASE`); assert.ok(b.applied.some((a) => /DECODE is Oracle-only/.test(a))); }
  st.selectedColumns[1].alias = 'STATE_TEXT'; assert.match(buildSelectSQL(st, CORE_SCHEMA), /AS STATE_TEXT/);
  const noDef = empty(); noDef.selectedTables = ['INVOICE_HEADER']; noDef.selectedColumns = [col('INVOICE_HEADER', 'INVOICE_DATE', { useDecode: true, displayMode: 'schema-decode' })]; const b = buildSelect(noDef, CORE_SCHEMA); assert.equal(b.sql, 'SELECT INVOICE_HEADER.INVOICE_DATE\nFROM INVOICE_HEADER;'); assert.ok(b.warnings.some((w) => /No CASE\/DECODE definition is available for INVOICE_HEADER\.INVOICE_DATE in the active schema/.test(w)));
  const quote = schemaDecodeSql('T.C', [{ rawValue: "O'N", label: "It's" }], 'Generic', 'case', 'X'); assert.match(quote.sql, /'O''N' THEN 'It''s'/);
  // the definition follows the schema: change it and the SQL changes with it (this is what a pull does)
  const changed = JSON.parse(JSON.stringify(CORE_SCHEMA)); changed.tables.find((t) => t.name === 'INVOICE_HEADER').columns.find((c) => c.name === 'STATUS').decode = [{ rawValue: 'P', label: 'In progress' }]; st.selectedColumns[1].decodeStyle = 'case'; assert.match(buildSelectSQL(st, changed), /THEN 'In progress'/); assert.ok(!/Pending/.test(buildSelectSQL(st, changed)));
  const ex = explainQuery(buildSelect(st, CORE_SCHEMA), st, CORE_SCHEMA, null); assert.ok(ex.options.some((o) => /CASE\/DECODE INVOICE_HEADER\.STATUS/.test(o)));
});
test('V17.5 CASE/DECODE validation: the generated SQL passes all 12 checks in every dialect, also next to an aggregate (decode of the grouped column); a bad / fabricated decode is caught', () => {
  for (const d of ['Oracle', 'SQL Server', 'PostgreSQL', 'MySQL', 'Generic']) for (const style of ['case', 'decode']) { const st = empty(d); st.selectedTables = ['INVOICE_HEADER']; st.selectedColumns = [col('INVOICE_HEADER', 'INVOICE_ID'), col('INVOICE_HEADER', 'STATUS', { useDecode: true, displayMode: 'schema-decode', decodeStyle: style })]; const v = validateFinalQuery(buildSelectSQL(st, CORE_SCHEMA), CORE_SCHEMA, d, { state: st }); assert.deepEqual([v.errors, v.warnings], [[], []], `${d}/${style}`); }
  const ag = empty('Oracle'); ag.selectedTables = ['INVOICE_HEADER']; ag.selectedColumns = [col('INVOICE_HEADER', 'STATUS', { useDecode: true, displayMode: 'schema-decode' }), col('INVOICE_HEADER', 'INVOICE_AMOUNT', { aggregate: 'SUM' })]; ag.advanced.groupByColumns = ['INVOICE_HEADER.STATUS']; assert.equal(validateFinalQuery(buildSelectSQL(ag, CORE_SCHEMA), CORE_SCHEMA, 'Oracle', { state: ag }).valid, true);
  ag.advanced.groupByColumns = []; assert.equal(validateFinalQuery(buildSelectSQL(ag, CORE_SCHEMA), CORE_SCHEMA, 'Oracle', { state: ag }).valid, false, 'a non-grouped decode next to an aggregate is still an error');
  assert.equal(validateFinalQuery("SELECT DECODE(INVOICE_HEADER.NOPE, 'A', 'x') AS X FROM INVOICE_HEADER;", CORE_SCHEMA, 'Oracle').valid, false); assert.equal(validateFinalQuery("SELECT DECODE(INVOICE_HEADER.STATUS, 'A', 'x') AS X FROM INVOICE_HEADER;", CORE_SCHEMA, 'PostgreSQL').valid, false, 'DECODE is not offered outside Oracle');
});
test('V17.5 CASE/DECODE in Describe What You Need / offline NLU: label intent, "using decode / case", no definition → reported, existing selections never overwritten', async () => {
  const gen = (t, d = 'Oracle', cur = empty(d)) => { const r = runOfflineNlu(t, CORE_SCHEMA, { dialect: d }); const st = applyV17ToState(cur, r, { isManual: () => false }).state; return { r, st, sql: buildSelectSQL(st, CORE_SCHEMA) }; };
  let g = gen('show invoice id and status description for invoices'); assert.match(g.sql, /CASE WHEN INVOICE_HEADER\.STATUS = 'P'[\s\S]*END AS STATUS_DESC/); assert.equal(validateFinalQuery(g.sql, CORE_SCHEMA, 'Oracle', { state: g.st }).valid, true);
  g = gen('show invoices with decoded status'); assert.match(g.sql, /DECODE\(INVOICE_HEADER\.STATUS, 'P', 'Pending'/); g = gen('show invoice id and status using decode', 'SQL Server'); assert.match(g.sql, /CASE WHEN/); assert.ok(!/DECODE\(/.test(g.sql));
  g = gen('show invoice id and invoice date description'); assert.ok(g.r.notes.some((n) => /No CASE\/DECODE definition is available for INVOICE_HEADER\.INVOICE_DATE in the active schema/.test(n))); assert.ok(!/CASE WHEN|DECODE\(/.test(g.sql), 'nothing fabricated'); assert.deepEqual(g.r.schemaGaps, []);
  assert.ok(!/CASE WHEN|DECODE\(/.test(gen('show approved invoices with their status').sql), 'a plain mention of "status" is not a decode request');
  const cur = empty(); cur.selectedTables = ['INVOICE_HEADER']; cur.selectedColumns = [col('INVOICE_HEADER', 'STATUS', { useDecode: true, displayMode: 'schema-decode', decodeStyle: 'decode', alias: 'MY_STATE' })]; g = gen('show invoice id and status', 'Oracle', cur); assert.equal(g.st.selectedColumns.filter((c) => c.column === 'STATUS').length, 1); assert.deepEqual([g.st.selectedColumns.find((c) => c.column === 'STATUS').decodeStyle, g.st.selectedColumns.find((c) => c.column === 'STATUS').alias], ['decode', 'MY_STATE']); assert.match(g.sql, /DECODE\([\s\S]*AS MY_STATE/);
  const man = empty(); man.selectedTables = ['INVOICE_HEADER']; man.selectedColumns = [col('INVOICE_HEADER', 'STATUS', { displayMode: 'manual-decode', manualExpr: "DECODE(INVOICE_HEADER.STATUS, 'A', 'OK', 'bad') AS MAN" , alias: 'MAN' })]; g = gen('show invoice id and status', 'Oracle', man); assert.equal(g.st.selectedColumns.filter((c) => c.column === 'STATUS').length, 1, 'no duplicate plain column next to a manual decode'); assert.match(g.sql, /AS MAN/);
  const o = await generateFromDescription('show invoice id and status description', cur, CORE_SCHEMA, 'Oracle', null, null, null); assert.equal(o.state.selectedColumns.find((c) => c.column === 'STATUS').alias, 'MY_STATE', 'the orchestrator keeps the user configuration'); assert.equal(o.validation.valid, true);
});
test('V17.5 CASE/DECODE with learned queries and the Admin Query Library: the pattern remembers THAT a column was decoded, the definition is re-read from the schema (adapted, never copied)', async () => {
  const SQL = "SELECT INVOICE_HEADER.INVOICE_ID,\n  DECODE(INVOICE_HEADER.STATUS, 'P', 'Pending', 'A', 'Approved', 'R', 'Rejected', 'D', 'Paid', TO_CHAR(INVOICE_HEADER.STATUS)) AS STATUS_DESC\nFROM INVOICE_HEADER;";
  const p = extractSqlPattern(SQL, CORE_SCHEMA).pattern; assert.deepEqual(p.decodes, [{ table: 'INVOICE_HEADER', column: 'STATUS', style: 'decode' }]); assert.ok(p.columns.some((c) => c.column === 'STATUS'));
  assert.deepEqual(extractSqlPattern("SELECT CASE WHEN INVOICE_HEADER.STATUS = 'ZZ' THEN 'x' ELSE 'y' END AS X FROM INVOICE_HEADER;", CORE_SCHEMA).pattern.decodes, [], 'a free-form manual CASE is not a schema decode');
  assert.deepEqual(extractSqlPattern("SELECT CASE WHEN INVOICE_HEADER.STATUS = 'P' THEN 'Pending' ELSE CAST(INVOICE_HEADER.STATUS AS VARCHAR(255)) END AS X FROM INVOICE_HEADER;", CORE_SCHEMA).pattern.decodes.map((d) => d.style), ['case']);
  const st = memoryStore(); const L = new LearningStore(st); L.confirm('invoice number and state labels', CORE_SCHEMA, SQL, null, { resultStatus: 'success', dialect: 'Oracle' });
  let r = await generateFromDescription('invoice number and state labels', empty(), CORE_SCHEMA, 'Oracle', L, null, null); assert.equal(r.requirement.patternUsed?.source, 'learned', r.requirement.notes.join()); assert.ok(r.requirement.patternUsed.adopted.includes('CASE/DECODE')); assert.match(r.state.generatedSql, /DECODE\(INVOICE_HEADER\.STATUS, 'P', 'Pending'/); assert.equal(r.validation.valid, true);
  const changed = JSON.parse(JSON.stringify(CORE_SCHEMA)); changed.id = CORE_SCHEMA.id; changed.tables.find((t) => t.name === 'INVOICE_HEADER').columns.find((c) => c.name === 'STATUS').decode = [{ rawValue: 'P', label: 'Waiting' }, { rawValue: 'A', label: 'Approved' }]; r = await generateFromDescription('invoice number and state labels', empty(), changed, 'Oracle', L, null, null); assert.match(r.state.generatedSql, /'Waiting'/); assert.ok(!/Pending/.test(r.state.generatedSql), 'the CURRENT schema definition is used, not the stored SQL');
  const noDef = JSON.parse(JSON.stringify(CORE_SCHEMA)); delete noDef.tables.find((t) => t.name === 'INVOICE_HEADER').columns.find((c) => c.name === 'STATUS').decode; r = await generateFromDescription('invoice number and state labels', empty(), noDef, 'Oracle', L, null, null); assert.ok(!/DECODE\(|CASE WHEN/.test(r.state.generatedSql)); assert.ok(r.requirement.notes.some((n) => /INVOICE_HEADER\.STATUS through a CASE\/DECODE, but the Active Schema has no definition for it/.test(n)), r.requirement.notes.join());
  const A = new AdminQueryLibrary(memoryStore()); const q = A.upsert({ name: 'Invoice state labels', description: 'Invoice number with the readable state of the invoice', sql: SQL, dialect: 'Oracle' }).query; assert.deepEqual(A.approve(q.id, CORE_SCHEMA, 'Oracle'), { ok: true, errors: [] }); assert.equal(validateFinalQuery(SQL, CORE_SCHEMA, 'Oracle').valid, true);
  r = await generateFromDescription('invoice number with the readable state of the invoice', empty(), CORE_SCHEMA, 'Oracle', null, null, A); assert.equal(r.requirement.patternUsed?.source, 'admin', r.requirement.notes.join()); assert.match(r.state.generatedSql, /DECODE\(INVOICE_HEADER\.STATUS/);
});
test('V17.5 AP schema 77 (numeric codes): CASE/DECODE works with the migrated legacy schema', () => {
  const AP = F.checkRegistry({ text: v170File() }).validSchemas[2]; const st = empty('Oracle'); st.selectedTables = ['IA_INVOICE']; st.selectedColumns = [col('IA_INVOICE', 'INVOICE_NUMBER'), col('IA_INVOICE', 'STATUS', { useDecode: true, displayMode: 'schema-decode', decodeStyle: 'decode' })];
  const sql = buildSelectSQL(st, AP); assert.match(sql, /DECODE\(IA_INVOICE\.STATUS, '0', 'New', '1', 'In approval', '2', 'Approved'/); assert.equal(validateFinalQuery(sql, AP, 'Oracle', { state: st }).valid, true);
});
