import type { Dialect, RectifyResult } from '../types';
interface Rule { test: RegExp; dialect: Dialect | null; explain: string; fix: (sql: string, m: RegExpMatchArray) => { sql: string; changes: string[] }; }
const RULES: Rule[] = [
  { test: /ORA-00904:\s*"?([A-Z0-9_."]+)"?\s*:?\s*invalid identifier/i, dialect: 'Oracle', explain: 'ORA-00904 means the column or alias referenced does not exist (or is misspelled) in the table(s) in the FROM clause.', fix: (sql, m) => { const bad = (m[1] || '').replace(/"/g, ''); return { sql: `-- Review: "${bad}" was not found on any table in scope.\n${sql}`, changes: [`Checked for a typo in column reference "${bad}".`, 'Verify the column exists on the referenced table/alias, or add the missing table to the FROM/JOIN list.'] }; } },
  { test: /ORA-00942:\s*table or view does not exist/i, dialect: 'Oracle', explain: 'ORA-00942 means the table or view name is misspelled, does not exist, or you lack privileges on it.', fix: (sql) => ({ sql: `-- Review: confirm the table/view name and schema prefix (e.g. SCHEMA.TABLE), and that SELECT privilege is granted.\n${sql}`, changes: ['Flagged the FROM/JOIN target(s) for a name or privilege check.'] }) },
  { test: /ORA-00918:\s*column ambiguously defined/i, dialect: 'Oracle', explain: 'ORA-00918 means a column name exists in more than one joined table and needs to be qualified with a table alias.', fix: (sql) => ({ sql, changes: ['Qualify ambiguous column references with their table alias (e.g. a.COLUMN instead of COLUMN).'] }) },
  { test: /ORA-00937:\s*not a single-group group function/i, dialect: 'Oracle', explain: 'ORA-00937 means the SELECT list mixes aggregate and non-aggregate columns without a matching GROUP BY.', fix: (sql) => ({ sql: `${sql}\n-- Add a GROUP BY listing every non-aggregated column in the SELECT list.`, changes: ['Added a reminder to GROUP BY all non-aggregated SELECT columns.'] }) },
  { test: /(?:ORA-00933|SQL command not properly ended)/i, dialect: 'Oracle', explain: 'ORA-00933 usually means there is unexpected text after a complete SQL statement — often a stray semicolon, keyword, or trailing comma.', fix: (sql) => { const f = sql.replace(/,\s*(FROM|WHERE|GROUP BY|ORDER BY|HAVING)/gi, ' $1'); return { sql: f, changes: f !== sql ? ['Removed a trailing comma before a clause keyword.'] : ['Checked for stray tokens after the statement — none were auto-fixable; review manually.'] }; } },
  { test: /(?:Msg 102|Incorrect syntax near)/i, dialect: 'SQL Server', explain: 'This SQL Server syntax error usually points to a misplaced keyword, missing comma, or unbalanced parenthesis right before the reported token.', fix: (sql) => ({ sql, changes: ['Flagged the token before the reported position for a syntax review (commas, parentheses, keywords).'] }) },
  { test: /column\s+"?([A-Za-z0-9_.]+)"?\s+does not exist/i, dialect: 'PostgreSQL', explain: 'PostgreSQL reports this when a column name is misspelled, missing a table alias, or the wrong case was used with double-quoted identifiers.', fix: (sql, m) => ({ sql: `-- Review: "${m[1]}" was not found — check spelling, alias qualification, and case sensitivity.\n${sql}`, changes: [`Flagged column "${m[1]}" for a name/case check.`] }) },
  { test: /Unknown column\s+'([^']+)'/i, dialect: 'MySQL', explain: 'MySQL could not find this column in any table currently in scope for the query (missing JOIN, typo, or wrong alias).', fix: (sql, m) => ({ sql: `-- Review: unknown column '${m[1]}' — confirm it exists and the owning table is joined.\n${sql}`, changes: [`Flagged unknown column '${m[1]}'.`] }) },
  { test: /You have an error in your SQL syntax/i, dialect: 'MySQL', explain: 'A general MySQL syntax error — check the area right around the reported line/position for missing commas, quotes, or parentheses.', fix: (sql) => ({ sql, changes: ['Flagged the statement for a manual syntax pass near the reported position.'] }) }
];
function parens(sql: string): string[] { let d = 0; for (const ch of sql) { if (ch === '(') d++; if (ch === ')') d--; } if (d > 0) return [`Detected ${d} unclosed opening parenthesis "(" — add matching closing parenthesis/parentheses.`]; if (d < 0) return [`Detected ${-d} extra closing parenthesis ")" with no matching open — remove the extra parenthesis/parentheses.`]; return []; }
function quotes(sql: string): string[] { return (sql.match(/'/g) || []).length % 2 ? ['Detected an odd number of single quotes — a string literal is likely unterminated.'] : []; }
export function rectify(errorText: string, sql: string): RectifyResult {
  const structural = [...parens(sql), ...quotes(sql)];
  for (const r of RULES) { const m = errorText.match(r.test); if (m) { const f = r.fix(sql, m); return { correctedSql: f.sql, explanation: r.explain, whatChanged: [...f.changes, ...structural], detectedDialect: r.dialect }; } }
  return { correctedSql: sql, explanation: 'This error message did not match a known pattern in the rule library. General checklist: verify object names and privileges, confirm every non-aggregated SELECT column is in GROUP BY, qualify ambiguous columns with table aliases, and check for unbalanced quotes/parentheses.', whatChanged: structural.length ? structural : ['No known error pattern matched. Re-check table/column names, join conditions, and clause order (SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY).'], detectedDialect: null };
}
