/** V17.2 crypto for the Admin Password marker and the V17.2 local Secret Vault (PBKDF2-SHA-256 150 000 → AES-256-GCM). Unchanged format. */
const PBKDF2_ITERATIONS = 150000;
function toBase64(bytes: Uint8Array): string { let b = ''; bytes.forEach((x) => { b += String.fromCharCode(x); }); return btoa(b); }
function fromBase64(b64: string): Uint8Array { const s = atob(b64); const u = new Uint8Array(s.length); for (let i = 0; i < s.length; i++) u[i] = s.charCodeAt(i); return u; }
async function deriveKey(secret: string, salt: Uint8Array): Promise<CryptoKey> { const km = await crypto.subtle.importKey('raw', new TextEncoder().encode(secret) as BufferSource, 'PBKDF2', false, ['deriveKey']); return crypto.subtle.deriveKey({ name: 'PBKDF2', salt: salt as BufferSource, iterations: PBKDF2_ITERATIONS, hash: 'SHA-256' }, km, { name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']); }
export interface EncryptedBlob { salt: string; iv: string; ciphertext: string; }
export async function encryptWithSecret(secret: string, plaintext: string): Promise<EncryptedBlob> { const salt = crypto.getRandomValues(new Uint8Array(16)); const iv = crypto.getRandomValues(new Uint8Array(12)); const key = await deriveKey(secret, salt); const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv: iv as BufferSource }, key, new TextEncoder().encode(plaintext) as BufferSource); return { salt: toBase64(salt), iv: toBase64(iv), ciphertext: toBase64(new Uint8Array(ct)) }; }
/** Returns null for a wrong secret or corrupted data (never throws). */
export async function decryptWithSecret(secret: string, blob: EncryptedBlob): Promise<string | null> { try { if (!blob || typeof blob.salt !== 'string' || typeof blob.iv !== 'string' || typeof blob.ciphertext !== 'string') return null; const key = await deriveKey(secret, fromBase64(blob.salt)); const pt = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: fromBase64(blob.iv) as BufferSource }, key, fromBase64(blob.ciphertext) as BufferSource); return new TextDecoder().decode(pt); } catch { return null; } }
