import type { Dialect } from '../../types';
export type DateUnit = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR';
export function agoExpr(n: number, u: DateUnit, d: Dialect): string { const a = Math.max(0, Math.floor(n)); if (d === 'Oracle') return u === 'DAY' ? `TRUNC(SYSDATE) - ${a}` : u === 'WEEK' ? `TRUNC(SYSDATE) - ${a * 7}` : `ADD_MONTHS(TRUNC(SYSDATE), -${u === 'YEAR' ? a * 12 : a})`; if (d === 'SQL Server') return `DATEADD(${u}, -${a}, CAST(GETDATE() AS DATE))`; if (d === 'MySQL') return `DATE_SUB(CURDATE(), INTERVAL ${a} ${u})`; return `CURRENT_DATE - INTERVAL '${a} ${u}'`; }
export function startOfExpr(u: 'WEEK' | 'MONTH' | 'YEAR', back: number, d: Dialect): string {
  if (d === 'Oracle') { const b = `TRUNC(SYSDATE, '${u === 'WEEK' ? 'IW' : u === 'MONTH' ? 'MM' : 'YYYY'}')`; return !back ? b : u === 'WEEK' ? `${b} - ${7 * back}` : `ADD_MONTHS(${b}, -${u === 'YEAR' ? 12 * back : back})`; }
  if (d === 'SQL Server') { const b = u === 'WEEK' ? 'DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0)' : u === 'MONTH' ? 'DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)' : 'DATEFROMPARTS(YEAR(GETDATE()), 1, 1)'; return back ? `DATEADD(${u}, -${back}, ${b})` : b; }
  if (d === 'MySQL') { const b = u === 'WEEK' ? 'DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY)' : u === 'MONTH' ? 'DATE_SUB(CURDATE(), INTERVAL DAYOFMONTH(CURDATE()) - 1 DAY)' : 'MAKEDATE(YEAR(CURDATE()), 1)'; return back ? `DATE_SUB(${b}, INTERVAL ${back} ${u})` : b; }
  const b = `DATE_TRUNC('${u}', CURRENT_DATE)`; return back ? `${b} - INTERVAL '${back} ${u}'` : b;
}
export const todayExpr = (d: Dialect) => (d === 'Oracle' ? 'TRUNC(SYSDATE)' : d === 'SQL Server' ? 'CAST(GETDATE() AS DATE)' : d === 'MySQL' ? 'CURDATE()' : 'CURRENT_DATE');
export const dateLiteral = (iso: string, d: Dialect) => (d === 'SQL Server' ? `CAST('${iso}' AS DATE)` : `DATE '${iso}'`);
const SAFE = [/^CURRENT_DATE( - INTERVAL '\d{1,5} (DAY|WEEK|MONTH|YEAR)')?$/, /^TRUNC\(SYSDATE(, '(IW|MM|YYYY)')?\)( - \d{1,5})?$/, /^ADD_MONTHS\(TRUNC\(SYSDATE(, '(IW|MM|YYYY)')?\), -\d{1,5}\)$/, /^CAST\(GETDATE\(\) AS DATE\)$/, /^DATEADD\((DAY|WEEK|MONTH|YEAR), -?\d{1,5}, [A-Z(), 0-9]+\)$/, /^DATEFROMPARTS\([A-Z(), 0-9]+\)$/, /^DATEADD\(WEEK, DATEDIFF\(WEEK, 0, GETDATE\(\)\), 0\)$/, /^CURDATE\(\)$/, /^DATE_SUB\(CURDATE\(\), INTERVAL \d{1,5} (DAY|WEEK|MONTH|YEAR)\)$/, /^DATE_SUB\(CURDATE\(\), INTERVAL WEEKDAY\(CURDATE\(\)\) DAY\)$/, /^DATE_SUB\(CURDATE\(\), INTERVAL DAYOFMONTH\(CURDATE\(\)\) - 1 DAY\)$/, /^MAKEDATE\(YEAR\(CURDATE\(\)\), 1\)$/, /^DATE_SUB\((?:DATE_SUB\(CURDATE\(\), INTERVAL WEEKDAY\(CURDATE\(\)\) DAY\)|DATE_SUB\(CURDATE\(\), INTERVAL DAYOFMONTH\(CURDATE\(\)\) - 1 DAY\)|MAKEDATE\(YEAR\(CURDATE\(\)\), 1\)), INTERVAL \d{1,5} (WEEK|MONTH|YEAR)\)$/, /^DATE_TRUNC\('(WEEK|MONTH|YEAR)', CURRENT_DATE\)( - INTERVAL '\d{1,5} (WEEK|MONTH|YEAR)')?$/, /^DATE '\d{4}-\d{2}-\d{2}'$/, /^CAST\('\d{4}-\d{2}-\d{2}' AS DATE\)$/];
export const isSafeDateExpression = (v: string) => SAFE.some((r) => r.test(v.trim()));
