import type { SchemaModel, SelectedColumnSpec, ColumnDef, Dialect } from '../../types'; import { icon } from './icons'; import { makeId } from '../../utils/id'; import { e } from '../dom'; import { selectorUi } from '../selectorState';
const RESERVED = new Set(['select', 'from', 'where', 'group', 'order', 'having', 'join', 'on', 'and', 'or', 'not', 'null', 'as', 'distinct', 'case', 'when', 'then', 'else', 'end', 'with', 'union', 'insert', 'update', 'delete', 'table', 'view']);
export function validateAlias(a: string): { valid: boolean; message?: string } { const t = a.trim(); if (!t) return { valid: true }; if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(t)) return { valid: false, message: 'Alias must start with a letter or underscore, and contain only letters, digits, and underscores (no spaces or symbols).' }; if (RESERVED.has(t.toLowerCase())) return { valid: false, message: `"${t}" is a reserved SQL keyword and cannot be used as an alias.` }; return { valid: true }; }
export interface ColumnPickerCallbacks { onChange: (next: SelectedColumnSpec[]) => void; onRequestManualDecodeForColumn: (table: string, column: ColumnDef, existingSpecId: string) => void; /** V17.5: the dialect decides whether DECODE (Oracle) is offered next to CASE. */ getDialect?: () => Dialect; }
export interface ColumnPickerCtl { update(selectedTables: string[], selectedColumns: SelectedColumnSpec[]): void; }
/** V17.4: mounted once; search text + scroll are centralized in selectorUi; `update()` follows table/column changes without rebuilding the section. */
export function renderColumnPicker(container: HTMLElement, schema: SchemaModel, initialTables: string[], selectedColumns: SelectedColumnSpec[], cb: ColumnPickerCallbacks): ColumnPickerCtl {
  const ui = selectorUi; let selectedTables = [...initialTables]; let current = [...selectedColumns];
  const scope = () => selectedTables.flatMap((tn) => { const t = schema.tables.find((x) => x.name === tn); return t ? t.columns.map((c) => ({ table: tn, column: c })) : []; });
  // V17.5: a column that carries its own manual CASE/DECODE (manual-decode) is still a SELECTED column of this table — it is shown ticked with its
  // CASE / DECODE settings, instead of disappearing from the picker as before.
  const own = (x: SelectedColumnSpec, t: string, c: string) => x.table === t && x.column === c && (!x.manualExpr || x.displayMode === 'manual-decode');
  const spec = (t: string, c: string) => current.find((x) => own(x, t, c));
  const change = (t: string, c: string, fn: (x: SelectedColumnSpec) => SelectedColumnSpec) => { current = current.map((x) => (own(x, t, c) ? fn(x) : x)); cb.onChange([...current]); renderList(); };
  // moving between Column / From Schema / Manual never loses a manual expression: it is parked in manualDraft and restored on return
  const park = (x: SelectedColumnSpec): SelectedColumnSpec => { const { manualExpr, ...rest } = x; return { ...rest, manualDraft: manualExpr ? { expr: manualExpr, alias: x.alias } : x.manualDraft, alias: manualExpr ? '' : x.alias }; };
  const toRaw = (x: SelectedColumnSpec): SelectedColumnSpec => ({ ...park(x), displayMode: 'raw', useDecode: false });
  const toSchema = (x: SelectedColumnSpec): SelectedColumnSpec => ({ ...park(x), displayMode: 'schema-decode', useDecode: true, decodeStyle: x.decodeStyle || 'case' });
  const toManual = (x: SelectedColumnSpec): SelectedColumnSpec => { const p = park(x); return { ...p, displayMode: 'manual-decode', useDecode: false, ...(p.manualDraft ? { manualExpr: p.manualDraft.expr, alias: p.manualDraft.alias } : {}) }; };
  function definitionHtml(tn: string, c: ColumnDef, s: SelectedColumnSpec): string {
    const d = c.decode || []; const note = s.aggregate ? '<div class="hint">An aggregate is selected — CASE / DECODE is not applied while the column is aggregated.</div>' : '';
    if (!d.length) return `<div class="column-cd-detail" data-cd="schema"><div class="issue-box warn mini column-cd-none">${icon('alert-triangle', 14)} No CASE/DECODE definition is available for this column in the active schema.</div>${note}</div>`;
    const shown = d.slice(0, 12).map((x) => `${e(x.rawValue)} = ${e(x.label)}`).join(' · '); const more = d.length > 12 ? ` · +${d.length - 12} more` : '';
    return `<div class="column-cd-detail" data-cd="schema"><div class="hint"><strong>Schema definition</strong> for ${e(c.name)} (active schema ${e(schema.name)}):</div><label class="inline-check column-cd-def"><input type="radio" class="column-cd-def-input" name="cd_${e(tn)}_${e(c.name)}" checked> <span>${shown}${more}</span></label>${note}</div>`;
  }
  function manualHtml(s: SelectedColumnSpec): string {
    return `<div class="column-cd-detail" data-cd="manual">${s.manualExpr ? `<div class="hint">Manual expression: <code>${e(s.manualExpr)}</code></div>` : '<div class="hint">No manual CASE/DECODE has been defined for this column yet.</div>'}<div class="row-actions" style="margin-top:.3rem"><button type="button" class="btn btn-outline btn-sm column-cd-edit">${icon('edit', 13)} ${s.manualExpr ? 'Edit manual CASE/DECODE…' : 'Define manual CASE/DECODE…'}</button></div></div>`;
  }
  function row(tn: string, c: ColumnDef): string {
    const s = spec(tn, c.name); const mode = s?.displayMode ?? (s?.useDecode ? 'schema-decode' : 'raw'); const cd = mode !== 'raw'; const source = mode === 'manual-decode' ? 'manual' : 'schema'; const oracle = (cb.getDialect?.() ?? 'Oracle') === 'Oracle';
    const controls = s ? `<div class="column-row-controls">${source === 'manual' && cd ? '' : `<label class="column-inline-label">Alias<input type="text" class="column-alias-input" value="${e(s.alias || '')}" placeholder="${cd ? e(`${c.name}_DESC`) : 'optional'}"></label>`}<label class="column-inline-label" title="Show the stored value, or turn it into readable text with CASE / DECODE.">Display as<select class="column-mode-select"><option value="raw" ${!cd ? 'selected' : ''}>Column</option><option value="casedecode" ${cd ? 'selected' : ''}>CASE / DECODE</option></select></label>${cd ? `<label class="column-inline-label" title="Manual = you write the mapping. From Schema = use the definition stored in the active schema.">CASE / DECODE<select class="column-cd-source"><option value="manual" ${source === 'manual' ? 'selected' : ''}>Manual</option><option value="schema" ${source === 'schema' ? 'selected' : ''}>From Schema</option></select></label>` : ''}${cd && source === 'schema' && oracle && c.decode?.length ? `<label class="column-inline-label" title="DECODE is Oracle-specific; CASE works everywhere.">Style<select class="column-cd-style"><option value="case" ${(s.decodeStyle || 'case') === 'case' ? 'selected' : ''}>CASE</option><option value="decode" ${s.decodeStyle === 'decode' ? 'selected' : ''}>DECODE</option></select></label>` : ''}<label class="column-inline-label" title="Combine the values of many rows into one number (count, total, average, smallest, largest).">Aggregate<select class="column-agg-select">${['', 'COUNT', 'SUM', 'AVG', 'MIN', 'MAX'].map((a) => `<option value="${a}" ${(s.aggregate || '') === a ? 'selected' : ''}>${a || 'None'}</option>`).join('')}</select></label></div>${cd ? (source === 'manual' ? manualHtml(s) : definitionHtml(tn, c, s)) : ''}<div class="column-alias-error"></div>` : '';
    return `<div class="column-row ${s ? 'is-selected' : ''}" data-table="${e(tn)}" data-column="${e(c.name)}"><label class="column-row-checkbox-label"><input type="checkbox" class="column-checkbox" ${s ? 'checked' : ''}><span class="picker-row-main"><strong>${e(c.name)}</strong><span class="hint">${e(c.type)}${c.length ? `(${c.length})` : ''}${c.isPrimaryKey ? ' · PK' : ''}${c.isForeignKey ? ' · FK' : ''}${c.description ? ` — ${e(c.description)}` : ''}</span></span></label>${controls}</div>`;
  }
  function renderList(): void {
    const list = container.querySelector<HTMLElement>('.picker-list'); const count = container.querySelector('.picker-count'); const all = container.querySelector<HTMLInputElement>('.select-all-checkbox'); if (!list) return; const keepScroll = list.scrollTop || ui.columnScroll;
    if (!selectedTables.length) { list.innerHTML = '<p class="hint">Select one or more tables first.</p>'; if (count) count.textContent = ''; if (all) { all.checked = false; all.disabled = true; } return; }
    const sc = scope(); if (all) { all.disabled = false; all.checked = sc.length > 0 && sc.every((r) => !!spec(r.table, r.column.name)); }
    const term = ui.columnSearch.toLowerCase();
    list.innerHTML = selectedTables.map((tn) => { const t = schema.tables.find((x) => x.name === tn); if (!t) return ''; const cols = t.columns.filter((c) => !term || c.name.toLowerCase().includes(term) || (c.label || '').toLowerCase().includes(term) || (c.description || '').toLowerCase().includes(term)); return cols.length ? `<div class="picker-group-label">${e(tn)}</div>${cols.map((c) => row(tn, c)).join('')}` : ''; }).join('') || '<p class="hint">No columns match your search.</p>';
    if (count) count.textContent = `${current.filter((c) => (!c.manualExpr || c.displayMode === 'manual-decode') && selectedTables.includes(c.table)).length} selected`; list.scrollTop = keepScroll;
    list.querySelectorAll<HTMLElement>('.column-row').forEach((r) => { const t = r.dataset.table!; const cn = r.dataset.column!; const def = schema.tables.find((x) => x.name === t)?.columns.find((x) => x.name === cn); if (!def) return;
      r.querySelector('.column-checkbox')?.addEventListener('click', (ev) => { ev.stopPropagation(); current = spec(t, cn) ? current.filter((x) => !(x.table === t && x.column === cn && !x.manualExpr)) : [...current, { id: makeId('col'), table: t, column: cn, alias: '', useDecode: false, aggregate: null, displayMode: 'raw' }]; cb.onChange([...current]); renderList(); });
      r.querySelector('.column-alias-input')?.addEventListener('change', (ev) => { const v = (ev.target as HTMLInputElement).value; const s = spec(t, cn); if (!s) return; const ok = validateAlias(v); const box = r.querySelector('.column-alias-error'); if (box) box.innerHTML = ok.valid ? '' : `<span class="hint" style="color:#d64550">${e(ok.message || '')}</span>`; if (ok.valid) { s.alias = v.trim(); cb.onChange([...current]); } });
      r.querySelector('.column-mode-select')?.addEventListener('change', (ev) => { const v = (ev.target as HTMLSelectElement).value; const s0 = spec(t, cn); if (!s0) return; change(t, cn, (x) => (v === 'raw' ? toRaw(x) : def.decode?.length ? toSchema(x) : toManual(x))); }); // a column WITH a schema definition starts on "From Schema"; one without starts on "Manual"
      r.querySelector('.column-cd-source')?.addEventListener('change', (ev) => { const v = (ev.target as HTMLSelectElement).value; change(t, cn, (x) => (v === 'schema' ? toSchema(x) : toManual(x))); });
      r.querySelector('.column-cd-style')?.addEventListener('change', (ev) => { const v = (ev.target as HTMLSelectElement).value as 'case' | 'decode'; change(t, cn, (x) => ({ ...x, decodeStyle: v })); });
      r.querySelector('.column-cd-edit')?.addEventListener('click', () => { const s0 = spec(t, cn); if (s0) cb.onRequestManualDecodeForColumn(t, def, s0.id); });
      r.querySelector('.column-agg-select')?.addEventListener('change', (ev) => { const s = spec(t, cn); if (!s) return; s.aggregate = ((ev.target as HTMLSelectElement).value || null) as SelectedColumnSpec['aggregate']; cb.onChange([...current]); }); });
  }
  container.innerHTML = `<div class="picker"><div class="picker-search">${icon('search', 14)}<input type="text" class="picker-search-input" placeholder="Search columns…" aria-label="Search columns"></div><label class="select-all-row"><input type="checkbox" class="select-all-checkbox"> ${icon('checkbox-checked', 14)} Select All (all columns for the selected table(s) — search only filters what's shown)</label><div class="picker-actions"><button type="button" class="btn-link" data-action="clear">Clear</button><span class="picker-count"></span></div><div class="picker-list"></div></div>`;
  const search = container.querySelector<HTMLInputElement>('.picker-search-input')!; search.value = ui.columnSearch; search.addEventListener('input', () => { ui.columnSearch = search.value; renderList(); });
  container.querySelector('.picker-list')!.addEventListener('scroll', (ev) => { ui.columnScroll = (ev.target as HTMLElement).scrollTop; });
  container.querySelector('.select-all-checkbox')!.addEventListener('change', (ev) => { if ((ev.target as HTMLInputElement).checked) scope().forEach((r) => { if (!spec(r.table, r.column.name)) current.push({ id: makeId('col'), table: r.table, column: r.column.name, alias: '', useDecode: false, aggregate: null, displayMode: 'raw' }); }); else { const s = new Set(selectedTables); current = current.filter((c) => !s.has(c.table)); } cb.onChange([...current]); renderList(); });
  container.querySelector('[data-action="clear"]')!.addEventListener('click', () => { const s = new Set(selectedTables); current = current.filter((c) => !s.has(c.table)); cb.onChange([...current]); renderList(); });
  renderList();
  return { update(tables, cols) { selectedTables = [...tables]; current = [...cols]; renderList(); } };
}
