/** Manual CASE / DECODE expression builders (V17.2). */
import { icon } from './icons'; import { openModal } from './modal'; import { e } from '../dom'; import { validateAlias } from './columnPicker'; import { makeId } from '../../utils/id';
import type { Dialect, SelectedColumnSpec } from '../../types';
const lit = (v: string) => `'${v.replace(/'/g, "''")}'`;
const issuesHtml = (l: string[]) => `<div class="issue-box mini">${icon('alert-triangle', 14)}<ul>${l.map((i) => `<li>${e(i)}</li>`).join('')}</ul></div>`;
export function openManualCaseBuilder(onAdd: (s: SelectedColumnSpec) => void): void {
  const m = openModal(`${icon('code', 18)} Manual CASE Expression`, `<p class="hint">Build a CASE expression manually — useful when the column you need doesn't already have a schema-defined decode.</p><div id="whenRows" class="filter-rows"></div><button type="button" id="addWhenBtn" class="btn btn-outline btn-sm">${icon('plus', 14)} Add WHEN</button><div class="form-row-2"><label class="block-label">ELSE value<input type="text" id="caseElse"></label><label class="block-label">Alias *<input type="text" id="caseAlias"></label></div><div id="caseIssues"></div><div class="modal-actions"><button type="button" class="btn btn-ghost" id="caseCancel">Cancel</button><button type="button" class="btn btn-primary" id="caseSave">${icon('save', 14)} Add Column</button></div>`, { wide: true });
  const rows = m.element.querySelector<HTMLElement>('#whenRows')!; const whens = [{ w: '', t: '' }];
  const render = () => { rows.innerHTML = whens.map((x, i) => `<div class="mini-row" data-idx="${i}"><span>WHEN</span><input type="text" class="when-expr" value="${e(x.w)}" placeholder="TABLE.COLUMN = 'X'"><span>THEN</span><input type="text" class="when-then" value="${e(x.t)}" placeholder="Label"><button type="button" class="icon-btn remove-when" aria-label="Remove">${icon('trash', 14)}</button></div>`).join(''); rows.querySelectorAll<HTMLElement>('.mini-row').forEach((r) => { const i = +r.dataset.idx!; r.querySelector('.when-expr')!.addEventListener('input', (ev) => { whens[i].w = (ev.target as HTMLInputElement).value; }); r.querySelector('.when-then')!.addEventListener('input', (ev) => { whens[i].t = (ev.target as HTMLInputElement).value; }); r.querySelector('.remove-when')!.addEventListener('click', () => { whens.splice(i, 1); render(); }); }); };
  render(); m.element.querySelector('#addWhenBtn')!.addEventListener('click', () => { whens.push({ w: '', t: '' }); render(); }); m.element.querySelector('#caseCancel')!.addEventListener('click', () => m.close());
  m.element.querySelector('#caseSave')!.addEventListener('click', () => { const alias = (m.element.querySelector('#caseAlias') as HTMLInputElement).value.trim(); const els = (m.element.querySelector('#caseElse') as HTMLInputElement).value; const issues: string[] = []; if (!alias) issues.push('Alias is required.'); else { const v = validateAlias(alias); if (!v.valid) issues.push(v.message!); } const ok = whens.filter((x) => x.w.trim() && x.t.trim()); if (!ok.length) issues.push('Add at least one complete WHEN / THEN pair.'); if (issues.length) { m.element.querySelector('#caseIssues')!.innerHTML = issuesHtml(issues); return; }
    onAdd({ id: makeId('col'), table: '', column: alias, alias, useDecode: false, aggregate: null, manualExpr: `CASE ${ok.map((x) => `WHEN ${x.w} THEN ${lit(x.t)}`).join(' ')}${els.trim() ? ` ELSE ${lit(els)}` : ''} END AS ${alias}` }); m.close(); });
}
export function openManualDecodeBuilder(dialect: Dialect, onAdd: (s: SelectedColumnSpec) => void, prefill?: { table: string; column: string }, replaceSpecId?: string): void {
  const m = openModal(`${icon('sparkles', 18)} Manual DECODE Expression${prefill ? ` — ${e(prefill.table)}.${e(prefill.column)}` : ''}`, `<p class="hint">Build a DECODE (Oracle) / CASE (other dialects) expression manually.</p><label class="block-label">Source column/expression *<input type="text" id="decodeSource" value="${prefill ? e(`${prefill.table}.${prefill.column}`) : ''}"></label><div id="pairRows" class="filter-rows mt"></div><button type="button" id="addPairBtn" class="btn btn-outline btn-sm">${icon('plus', 14)} Add raw=label pair</button><div class="form-row-2"><label class="block-label">ELSE value<input type="text" id="decodeElse"></label><label class="block-label">Alias *<input type="text" id="decodeAlias" value="${prefill ? e(`${prefill.column}_DESC`) : ''}"></label></div><div id="decodeIssues"></div><div class="modal-actions"><button type="button" class="btn btn-ghost" id="decodeCancel">Cancel</button><button type="button" class="btn btn-primary" id="decodeSave">${icon('save', 14)} ${replaceSpecId ? 'Apply' : 'Add Column'}</button></div>`, { wide: true });
  const rows = m.element.querySelector<HTMLElement>('#pairRows')!; const pairs = [{ r: '', l: '' }];
  const render = () => { rows.innerHTML = pairs.map((p, i) => `<div class="mini-row" data-idx="${i}"><input type="text" class="pair-raw" value="${e(p.r)}" placeholder="raw"><span>=</span><input type="text" class="pair-label" value="${e(p.l)}" placeholder="label"><button type="button" class="icon-btn remove-pair" aria-label="Remove">${icon('trash', 14)}</button></div>`).join(''); rows.querySelectorAll<HTMLElement>('.mini-row').forEach((r) => { const i = +r.dataset.idx!; r.querySelector('.pair-raw')!.addEventListener('input', (ev) => { pairs[i].r = (ev.target as HTMLInputElement).value; }); r.querySelector('.pair-label')!.addEventListener('input', (ev) => { pairs[i].l = (ev.target as HTMLInputElement).value; }); r.querySelector('.remove-pair')!.addEventListener('click', () => { pairs.splice(i, 1); render(); }); }); };
  render(); m.element.querySelector('#addPairBtn')!.addEventListener('click', () => { pairs.push({ r: '', l: '' }); render(); }); m.element.querySelector('#decodeCancel')!.addEventListener('click', () => m.close());
  m.element.querySelector('#decodeSave')!.addEventListener('click', () => { const src = (m.element.querySelector('#decodeSource') as HTMLInputElement).value.trim(); const alias = (m.element.querySelector('#decodeAlias') as HTMLInputElement).value.trim(); const els = (m.element.querySelector('#decodeElse') as HTMLInputElement).value; const issues: string[] = []; if (!src) issues.push('Source column/expression is required.'); if (!alias) issues.push('Alias is required.'); else { const v = validateAlias(alias); if (!v.valid) issues.push(v.message!); } const ok = pairs.filter((p) => p.r.trim() && p.l.trim()); if (!ok.length) issues.push('Add at least one complete raw=label pair.'); if (issues.length) { m.element.querySelector('#decodeIssues')!.innerHTML = issuesHtml(issues); return; }
    const expr = dialect === 'Oracle' ? `DECODE(${src}, ${ok.map((p) => `${lit(p.r)}, ${lit(p.l)}`).join(', ')}${els.trim() ? `, ${lit(els)}` : ''}) AS ${alias}` : `CASE ${ok.map((p) => `WHEN ${src} = ${lit(p.r)} THEN ${lit(p.l)}`).join(' ')}${els.trim() ? ` ELSE ${lit(els)}` : ''} END AS ${alias}`;
    onAdd({ id: replaceSpecId || makeId('col'), table: replaceSpecId ? (prefill?.table || '') : '', column: replaceSpecId ? (prefill?.column || alias) : alias, alias, useDecode: false, aggregate: null, manualExpr: expr, displayMode: 'manual-decode' }); m.close(); });
}
