/** V17.2 navbar + hamburger navigation panel. */
import { icon, type IconName } from './icons'; import { logoMarkSvg } from './logoMark'; import { store, type Route, type Theme } from '../state'; import { e } from '../dom';
import { services, APP } from '../context'; import type { AdminMessage } from '../../v17/services/adminMessage'; import { SRC, TIME, getSyncPrefs, setSyncSource, setSyncTime, subscribeSyncPrefs, type SyncSource, type SyncTimeOption } from '../syncPrefs';
interface NavLeaf { id: Route; label: string; icon: IconName; tour?: string; } interface NavGroup { id: string; label: string; icon: IconName; children: NavLeaf[]; tour?: string; }
const NAV: (NavLeaf | NavGroup)[] = [{ id: 'quickstart', label: 'Quick Start', icon: 'compass' }, { id: 'query-builder-group', label: 'Query Builder', icon: 'code', tour: 'nav-query-builder', children: [{ id: 'readonly', label: 'Read Only Query Builder', icon: 'table', tour: 'nav-readonly' }, { id: 'cr', label: 'Query Builder for CR', icon: 'edit', tour: 'nav-cr' }] }, { id: 'schema-used', label: 'Schema', icon: 'database', tour: 'nav-schema' }, { id: 'error-rectifier', label: 'Error Rectifier', icon: 'bug', tour: 'nav-error' }, { id: 'settings', label: 'Settings', icon: 'settings', tour: 'nav-settings' }, { id: 'about', label: 'About', icon: 'info' }];
const isGroup = (x: NavLeaf | NavGroup): x is NavGroup => 'children' in x;
export function renderNavbar(container: HTMLElement, onNavigate: (r: Route) => void, onStartTour: () => void, signatureName: string): void {
  let menuOpen = false; let expanded: string | null = null; let srcOpen = false; let timeOpen = false; let themeOpen = false;
  function draw(): void {
    let activeName = '…'; let conflicts = 0; let adminMsg: AdminMessage | null = null; try { activeName = services().schemas.active().name; conflicts = services().sync.conflicts().length; adminMsg = services().adminMessage.current(); } catch { /* services not ready yet */ }
    // V17.5.1: the administrator message is a slim row INSIDE the navbar (below the controls). It needs no horizontal room, so no existing control is squeezed,
    // and the full text (up to 140 characters) stays readable on every screen width. Plain text only (escaped); dismissible per device.
    const msgHtml = adminMsg ? `<div class="admin-msg-bar is-${adminMsg.level}" id="adminMsgBar" role="status" aria-live="polite">${icon(adminMsg.level === 'warning' ? 'alert-triangle' : 'info', 15)}<span class="admin-msg-bar-label">${adminMsg.level === 'warning' ? 'Warning from the administrator' : 'Message from the administrator'}</span><span class="admin-msg-bar-text">${e(adminMsg.text)}</span><button type="button" class="admin-msg-dismiss" id="adminMsgDismiss" aria-label="Hide this message on this device" title="Hide this message on this device (a new message will appear again)">${icon('x', 14)}</button></div>` : '';
    const cfg = getSyncPrefs(); const lockIcon: IconName = store.settingsUnlocked ? 'unlock' : 'lock'; const online = typeof navigator === 'undefined' || navigator.onLine !== false; const themeIcon: IconName = store.theme === 'light' ? 'sun' : store.theme === 'dark' ? 'moon' : 'monitor';
    container.innerHTML = `<nav class="navbar" id="mainNavbar"><div class="navbar-inner"><div class="navbar-left-cluster"><button type="button" class="navbar-toggler" id="navToggle" aria-label="Open navigation" data-tour="hamburger-btn">${icon('menu', 22)}</button><button type="button" class="hero-brand-row" id="logoHomeBtn" data-tour="brand" aria-label="SQL Assistant — Quick Start"><span class="app-logo-badge">${logoMarkSvg(40)}</span><span class="brand-text"><span class="builder-heading" id="appName">SQL Assistant</span><span class="small">V${e(APP.version.split('.').slice(0, 2).join('.'))}</span></span></button></div>
      <div class="navbar-sync-cluster" data-tour="navbar-sync"><div class="sync-dropdown-wrap"><button type="button" class="sync-dropdown-btn" id="syncSourceBtn" aria-haspopup="true">${icon('folder-sync', 15)} ${SRC[cfg.source]} ${icon('chevron-down', 13)}</button>${srcOpen ? `<div class="sync-dropdown-menu">${(Object.keys(SRC) as SyncSource[]).map((s) => `<button type="button" data-source="${s}" class="${cfg.source === s ? 'active' : ''}">${icon(s === 'github' ? 'github' : 'folder', 14)} ${SRC[s]}</button>`).join('')}</div>` : ''}</div>
        <div class="sync-dropdown-wrap"><button type="button" class="sync-dropdown-btn" id="syncTimeBtn" aria-haspopup="true">${icon('clock', 15)} ${TIME[cfg.time]} ${icon('chevron-down', 13)}</button>${timeOpen ? `<div class="sync-dropdown-menu">${(Object.keys(TIME) as SyncTimeOption[]).map((t) => `<button type="button" data-time="${t}" class="${cfg.time === t ? 'active' : ''}">${TIME[t]}</button>`).join('')}</div>` : ''}</div>
        ${conflicts ? `<button type="button" class="conflict-nav-badge" id="conflictNavBadge" title="Unresolved synchronization conflicts">${icon('shield-alert', 13)} ${conflicts}</button>` : ''}</div>
      <div class="navbar-right-cluster"><span class="schema-badge" id="activeSchemaBadge" title="Active Schema">${icon('database', 14)} ${e(activeName)}</span><span class="net-status-badge" title="${online ? 'Online' : 'Offline — the offline NLU keeps working'}">${icon(online ? 'wifi' : 'wifi-off', 14)}</span><button type="button" class="settings-lock-badge ${store.settingsUnlocked ? 'is-unlocked' : ''}" id="settingsLockBadge" title="${store.settingsUnlocked ? 'Settings unlocked — select to lock' : 'Settings locked'}">${icon(lockIcon, 14)}</button>
        <div class="theme-toggle-wrap"><button type="button" class="theme-btn" id="themeBtn" aria-label="Theme">${icon(themeIcon, 18)}</button>${themeOpen ? `<div class="theme-menu">${([['system', 'monitor', 'System Default'], ['light', 'sun', 'Light'], ['dark', 'moon', 'Dark']] as [Theme, IconName, string][]).map(([t, ic, l]) => `<button type="button" data-theme-choice="${t}" class="${store.theme === t ? 'active' : ''}">${icon(ic, 15)} ${l}</button>`).join('')}</div>` : ''}</div>
        <button type="button" class="btn btn-outline btn-sm navbar-tour-btn" id="tourBtnNav">${icon('play', 15)}<span class="tour-btn-label">Guided Walkthrough</span></button><span class="navbar-signature">${icon('user', 14)} <span>${e(signatureName)}</span></span></div></div>${msgHtml}</nav>
      ${menuOpen ? `<div class="hamburger-overlay" id="hamburgerOverlay"><aside class="hamburger-panel" aria-label="Navigation"><div class="hamburger-panel-header"><span class="hamburger-panel-title">${icon('menu', 18)} Navigation</span><button type="button" class="icon-btn" id="hamburgerCloseBtn" aria-label="Close navigation">${icon('x', 18)}</button></div><div class="hamburger-panel-body">
        ${NAV.map((n) => { if (isGroup(n)) { const inG = n.children.some((c) => c.id === store.route); const ex = expanded === n.id || inG; return `<button type="button" class="hb-group-toggle ${inG ? 'active' : ''}" data-group="${n.id}" ${n.tour ? `data-tour="${n.tour}"` : ''}><span class="hb-group-toggle-main">${icon(n.icon, 18)}${n.label}</span><span class="hb-group-chevron">${icon('chevron-down', 15, ex ? 'rotated' : '')}</span></button>${ex ? `<div class="hb-group-children">${n.children.map((c) => `<a href="#${c.id}" class="hb-link hb-link-child ${store.route === c.id ? 'active' : ''}" data-route="${c.id}" ${c.tour ? `data-tour="${c.tour}"` : ''}>${icon(c.icon, 16)}${c.label}</a>`).join('')}</div>` : ''}`; } return `<a href="#${n.id}" class="hb-link ${store.route === n.id ? 'active' : ''}" data-route="${n.id}" ${n.tour ? `data-tour="${n.tour}"` : ''}>${icon(n.icon, 18)}${n.label}${n.id === 'settings' ? icon(lockIcon, 14, 'hb-lock-icon') : ''}</a>`; }).join('')}
        <div class="hb-divider"></div><label class="hb-mobile-sync-label">${icon('folder-sync', 14)} Sync Source</label><select class="hb-mobile-sync-select" id="hbSyncSourceSelect">${(Object.keys(SRC) as SyncSource[]).map((s) => `<option value="${s}" ${cfg.source === s ? 'selected' : ''}>${SRC[s]}</option>`).join('')}</select><label class="hb-mobile-sync-label">${icon('clock', 14)} Sync Time</label><select class="hb-mobile-sync-select" id="hbSyncTimeSelect">${(Object.keys(TIME) as SyncTimeOption[]).map((t) => `<option value="${t}" ${cfg.time === t ? 'selected' : ''}>${TIME[t]}</option>`).join('')}</select>
        <div class="hb-divider"></div><button type="button" class="hb-link hb-tour-btn" id="tourBtnHb">${icon('play', 18)}Guided Walkthrough</button><div class="hb-signature">${icon('user', 14)} ${e(signatureName)}</div></div></aside></div>` : ''}`;
    wire();
  }
  const closeAll = () => { srcOpen = false; timeOpen = false; themeOpen = false; };
  function wire(): void {
    const q = (s: string) => container.querySelector<HTMLElement>(s);
    q('#adminMsgDismiss')?.addEventListener('click', (ev) => { ev.stopPropagation(); try { services().adminMessage.dismiss(); } catch { /* services not ready */ } });
    q('#navToggle')?.addEventListener('click', (ev) => { ev.stopPropagation(); menuOpen = !menuOpen; closeAll(); draw(); });
    q('#hamburgerCloseBtn')?.addEventListener('click', () => { menuOpen = false; draw(); });
    q('#hamburgerOverlay')?.addEventListener('click', (ev) => { if (ev.target === q('#hamburgerOverlay')) { menuOpen = false; draw(); } });
    q('#logoHomeBtn')?.addEventListener('click', () => onNavigate('quickstart'));
    q('#settingsLockBadge')?.addEventListener('click', () => { if (store.settingsUnlocked) { store.lockSettings(); store.pushToast('info', 'Settings locked.'); } else onNavigate('settings'); });
    q('#conflictNavBadge')?.addEventListener('click', () => { store.settingsTab = 'synchronization'; onNavigate('settings'); });
    container.querySelectorAll<HTMLElement>('.hb-group-toggle').forEach((b) => b.addEventListener('click', (ev) => { ev.stopPropagation(); expanded = expanded === b.dataset.group ? null : b.dataset.group!; draw(); }));
    container.querySelectorAll<HTMLElement>('[data-route]').forEach((a) => a.addEventListener('click', (ev) => { ev.preventDefault(); menuOpen = false; onNavigate(a.dataset.route as Route); draw(); }));
    q('#tourBtnHb')?.addEventListener('click', () => { menuOpen = false; draw(); onStartTour(); }); q('#tourBtnNav')?.addEventListener('click', () => onStartTour());
    q('#themeBtn')?.addEventListener('click', (ev) => { ev.stopPropagation(); const o = !themeOpen; closeAll(); themeOpen = o; draw(); });
    container.querySelectorAll<HTMLElement>('[data-theme-choice]').forEach((b) => b.addEventListener('click', (ev) => { ev.stopPropagation(); themeOpen = false; store.setTheme(b.dataset.themeChoice as Theme); }));
    q('#syncSourceBtn')?.addEventListener('click', (ev) => { ev.stopPropagation(); const o = !srcOpen; closeAll(); srcOpen = o; draw(); });
    container.querySelectorAll<HTMLElement>('[data-source]').forEach((b) => b.addEventListener('click', (ev) => { ev.stopPropagation(); srcOpen = false; setSyncSource(b.dataset.source as SyncSource); store.pushToast('info', `Sync source set to ${SRC[b.dataset.source as SyncSource]}.`); }));
    q('#syncTimeBtn')?.addEventListener('click', (ev) => { ev.stopPropagation(); const o = !timeOpen; closeAll(); timeOpen = o; draw(); });
    container.querySelectorAll<HTMLElement>('[data-time]').forEach((b) => b.addEventListener('click', (ev) => { ev.stopPropagation(); timeOpen = false; setSyncTime(b.dataset.time as SyncTimeOption); store.pushToast('info', `Sync time set to ${TIME[b.dataset.time as SyncTimeOption]}.`); }));
    q('#hbSyncSourceSelect')?.addEventListener('change', (ev) => setSyncSource((ev.target as HTMLSelectElement).value as SyncSource));
    q('#hbSyncTimeSelect')?.addEventListener('change', (ev) => setSyncTime((ev.target as HTMLSelectElement).value as SyncTimeOption));
  }
  document.addEventListener('click', () => { if (srcOpen || timeOpen || themeOpen) { closeAll(); draw(); } });
  document.addEventListener('keydown', (ev) => { if (ev.key === 'Escape' && menuOpen) { menuOpen = false; draw(); } });
  store.subscribe(draw); subscribeSyncPrefs(draw); window.addEventListener('online', draw); window.addEventListener('offline', draw);
  draw();
  (container as unknown as { redraw: () => void }).redraw = draw;
}
