/** Settings → Schema Management · Manual Schema Update · Secret Vault · AI/LLM Model */
import type { SchemaEditorRow, SchemaModel } from '../../types';
import { services, secrets, reloadSecrets, repository, aiConfig, setAiConfig, vaultProblem } from '../context';
import { $, esc, val, checked, on, toast, options, multiline, modal } from '../dom';
import { legacyLeftovers, checkRegistry, describeIssue } from '../../v17/sync/schemaFormat';
import { rejectionMessage, migrationMessage, type PullOutcome } from '../../v17/sync/syncService';
import { analyzeDependencies, rowsOf, diffRows } from '../../v17/engines/schemaRecordEngine';
import { maskSecret, CANONICAL_SCHEMA_PATH, type VaultSecrets } from '../../v17/services/secretVault';
import { validateAiConfig, saveAiConfig, PROVIDER_DEFAULTS, type AiProvider, type AiAuth } from '../../v17/services/aiLlmService';
import { redactSecrets } from '../../v17/errors/appErrors';
import { downloadBlob } from '../../utils/dom';
export const SETTINGS_TABS = ['schema-management', 'manual-update', 'vault', 'ai'] as const;
export type SettingsTab = typeof SETTINGS_TABS[number];
let lastPull: PullOutcome | null = null; let lastAction = ''; let edId: string | null = null; let selRow: string | null = null; let filt = ''; let changes: string[] = [];
const chip = (cls: string, l: string) => `<span class="badge ${cls}">${esc(l)}</span>`;
export function renderSettings(tab: SettingsTab): void {
  document.querySelectorAll<HTMLElement>('#settingsTabs [data-settings-tab]').forEach((a) => a.classList.toggle('active', a.dataset.settingsTab === tab));
  const body = $('settingsBody'); const warn = vaultProblem ? `<div class="alert alert-danger py-2 small">The Secret Vault on this device could not be opened (${esc(vaultProblem)}). Re-enter the configuration in Secret Vault.</div>` : '';
  try { ({ 'schema-management': mgmt, 'manual-update': manual, vault: vaultTab, ai: aiTab } as Record<SettingsTab, (b: HTMLElement) => void>)[tab](body); if (warn) body.insertAdjacentHTML('afterbegin', warn); }
  catch (e) { body.innerHTML = `<div class="alert alert-danger">This settings page could not be displayed: ${esc((e as Error).message)}</div>`; }
}
/** Re-render after the current event: a 'change' fires during blur, and replacing the focused element then throws. */
const rerender = (t: SettingsTab) => () => { setTimeout(() => renderSettings(t), 0); };
// ───────── Schema Management ─────────
function mgmt(body: HTMLElement): void {
  const { schemas, sync } = services(); const reg = schemas.registry(); const d = schemas.loadDiagnostics; const m = sync.meta();
  body.innerHTML = `<div class="card mb-3"><div class="card-body"><h2 class="h6"><span class="icon-badge icon-badge-sm badge-purple"><i class="bi bi-hdd-stack-fill"></i></span> Schemas on this device</h2>
    <div class="table-responsive"><table class="table table-sm align-middle small mb-2" id="schemaList"><thead><tr><th>Name</th><th>Format</th><th>Tables</th><th>Legacy leftovers</th><th>Last synced</th><th></th></tr></thead><tbody>
    ${reg.schemas.map((s) => { const l = legacyLeftovers(s); return `<tr data-schema-row="${esc(s.name)}"><td><strong>${esc(s.name)}</strong> ${s.id === reg.activeSchemaId ? chip('text-bg-primary', 'Active') : ''}</td><td>${s.migration ? `${chip('text-bg-info-subtle text-info-emphasis', 'Migrated schema')}<div class="text-body-secondary">from ${esc(s.migration.fromFormat)}</div>` : chip('text-bg-success-subtle text-success-emphasis', 'Current schema')}</td><td>${s.tables.length}</td><td>${l.unmappedLabels ? `${l.unmappedLabels} decode label(s) without code<br>` : ''}${l.unresolvedRefs ? `${l.unresolvedRefs} reference(s) outside schema` : ''}${!l.unmappedLabels && !l.unresolvedRefs ? '—' : ''}</td><td>${esc(s.lastSyncedAt ? s.lastSyncedAt.replace('T', ' ').slice(0, 16) : 'never')}</td>
      <td class="text-end text-nowrap">${s.id !== reg.activeSchemaId ? `<button class="btn btn-outline-primary btn-sm" data-activate="${esc(s.id)}" type="button">Set active</button> ` : ''}${l.unmappedLabels ? `<button class="btn btn-outline-secondary btn-sm" data-recover="${esc(s.id)}" type="button">Recover decode codes</button> ` : ''}<button class="btn btn-outline-danger btn-sm" data-del="${esc(s.id)}" type="button" aria-label="Delete schema"><i class="bi bi-trash-fill"></i></button></td></tr>`; }).join('')}</tbody></table></div><input type="file" id="recoverFile" accept=".json" class="d-none">
    ${d.recoveredFrom.length ? '<div class="alert alert-success py-2 small mb-2">Schemas saved by SQL Assistant V17.2.1 / V17.2.2 / V17.3 on this device were recovered into the standard storage.</div>' : ''}
    ${d.unreadable ? `<div class="alert alert-danger py-2 small mb-0">The schemas stored on this device could not be read (${esc(d.unreadable)}). Default schemas were loaded; the original data was kept as <code>${esc(d.backupKey || '')}</code>. Use <strong>Restore from repository</strong> below.</div>` : ''}</div></div>
  <div class="card mb-3" id="syncDiagnostics"><div class="card-body"><div class="d-flex flex-wrap align-items-center gap-2 mb-2"><h2 class="h6 mb-0 me-auto"><span class="icon-badge icon-badge-sm badge-cyan"><i class="bi bi-arrow-repeat"></i></span> Repository synchronization</h2>
      <button class="btn btn-primary btn-sm" id="syncNowBtn" type="button"><i class="bi bi-arrow-repeat me-1"></i>Synchronize now</button><button class="btn btn-outline-secondary btn-sm" id="pullOnlyBtn" type="button"><i class="bi bi-cloud-download me-1"></i>Restore from repository</button></div>
    <p class="small text-body-secondary mb-2">Repository: <strong>${esc(secrets.githubOwner && secrets.githubRepo ? `${secrets.githubOwner}/${secrets.githubRepo}` : '(not configured)')}</strong> · branch ${esc(secrets.githubBranch)} · file <code id="syncPath">${esc(secrets.schemaPath)}</code> · last download ${esc(m.lastPullAt?.replace('T', ' ').slice(0, 16) || 'never')} · last publish ${esc(m.lastPushAt?.replace('T', ' ').slice(0, 16) || 'never')}</p>
    <p class="small text-body-secondary mb-2">Download → detect format → migrate legacy schemas → validate → save → refresh Active Schema → publish in the current format. Invalid repository data never replaces a valid local schema.</p>
    <div id="pullReportWrap">${lastPull ? pullHtml(lastPull) : '<p class="small text-body-secondary mb-0">No synchronization in this session yet.</p>'}</div>
    ${lastAction ? `<div class="alert ${/^Published|^Repository file is valid|^OK/.test(lastAction) ? 'alert-success' : 'alert-warning'} py-2 small mt-2 mb-0 pre-line" id="actionResult">${esc(lastAction)}</div>` : ''}
    ${sync.conflicts().map((c) => `<div class="alert alert-warning py-2 small mt-2 mb-0">Schema <strong>${esc(c.schemaName)}</strong> changed on this device and in the repository. <button class="btn btn-sm btn-outline-secondary" data-cf="${esc(c.id)}" data-ch="keep-local" type="button">Keep this device's version</button> <button class="btn btn-sm btn-outline-secondary" data-cf="${esc(c.id)}" data-ch="take-remote" type="button">Use repository version</button></div>`).join('')}
  </div></div>
  <div class="card mb-3"><div class="card-body"><h2 class="h6"><span class="icon-badge icon-badge-sm badge-orange"><i class="bi bi-life-preserver"></i></span> Recovery options</h2>
    <div class="d-flex flex-wrap gap-2"><button class="btn btn-outline-secondary btn-sm" id="validateRemoteBtn" type="button"><i class="bi bi-clipboard-check me-1"></i>Validate repository file</button><button class="btn btn-outline-secondary btn-sm" id="downloadRemoteBtn" type="button"><i class="bi bi-download me-1"></i>Download repository file</button><button class="btn btn-outline-warning btn-sm" id="publishLocalBtn" type="button"><i class="bi bi-cloud-upload me-1"></i>Publish my local copies</button><button class="btn btn-outline-secondary btn-sm" id="exportAllBtn" type="button"><i class="bi bi-box-arrow-down me-1"></i>Export all schemas</button></div>
    <p class="small text-body-secondary mt-2 mb-0">Publish my local copies validates every local schema first (publish gate) and writes them with the current writer stamp — use it to replace a repository file that older app copies keep breaking.</p></div></div>
  <details class="small"><summary>Synchronization log</summary><table class="table table-sm small mt-2">${sync.log().slice(0, 25).map((l) => `<tr><td class="text-nowrap">${esc(l.timestamp.replace('T', ' ').slice(0, 19))}</td><td>${esc(l.kind)}</td><td>${esc(l.message)}</td></tr>`).join('') || '<tr><td>No entries.</td></tr>'}</table></details>`;
  const re = rerender('schema-management');
  body.querySelectorAll<HTMLElement>('[data-activate]').forEach((b) => b.addEventListener('click', () => { schemas.setActive(b.dataset.activate!); toast('success', `Active Schema: ${schemas.active().name}`); }));
  body.querySelectorAll<HTMLElement>('[data-del]').forEach((b) => b.addEventListener('click', () => { const s = schemas.byId(b.dataset.del!)!; if (!confirm(`Delete schema "${s.name}" from this device?`)) return; const r = schemas.deleteSchema(s.id); if (!r.ok) toast('error', r.errors.map((e) => e.message).join(' ')); re(); }));
  let rt = ''; body.querySelectorAll<HTMLElement>('[data-recover]').forEach((b) => b.addEventListener('click', () => { rt = b.dataset.recover!; $<HTMLInputElement>('recoverFile').click(); }));
  on('recoverFile', 'change', async (e) => { const f = (e.target as HTMLInputElement).files?.[0]; if (!f) return; const r = schemas.recoverFromSource(rt, await f.text()); toast(r.ok ? 'success' : 'error', r.ok ? `${r.restored} decode code(s) restored from the source file; ${r.stillUnmapped} label(s) still without a code.` : r.errors.map((x) => x.message).join(' ')); re(); });
  const run = async (fn: () => Promise<void>) => { body.querySelectorAll('button').forEach((b) => b.setAttribute('disabled', '')); try { await fn(); } catch (e) { lastAction = `Unexpected error: ${redactSecrets((e as Error).message, services().vault.knownSecrets())}`; } re(); };
  on('syncNowBtn', 'click', () => run(async () => { const r = await sync.synchronize(); lastPull = r.pull; lastAction = r.push ? [...r.push.messages, ...r.push.problems].join('\n') : ''; if (r.pull.fileProblem) toast('error', `${r.pull.stage}: ${r.pull.fileProblem}`); else if (r.pull.migrated.length) toast('success', 'Legacy schema migrated and synchronized.'); else toast('success', 'Synchronization finished.'); }));
  on('pullOnlyBtn', 'click', () => run(async () => { lastPull = await sync.pull(); lastAction = ''; }));
  on('validateRemoteBtn', 'click', () => run(async () => { const v = await sync.validateRemote(); lastAction = `${v.ok ? 'Repository file is valid. ' : `${v.stage}: `}${v.message}${v.report ? `\n${v.report.invalidSchemas.map((s) => `✗ ${s.name}: ${s.errors.slice(0, 3).map(describeIssue).join('; ')}${s.errors.length > 3 ? ` …and ${s.errors.length - 3} more` : ''}`).join('\n')}` : ''}`; }));
  on('downloadRemoteBtn', 'click', () => run(async () => { const t = await sync.downloadRemoteText(); if (t === null) { lastAction = 'No repository file to download (not configured or not found).'; return; } downloadBlob('repository-registry.json', t, 'application/json'); lastAction = 'OK — repository file downloaded.'; }));
  on('publishLocalBtn', 'click', () => run(async () => { if (!confirm('Replace the repository schema file with the schemas on this device? Every schema is validated first.')) return; const r = await sync.push({ allowReplacingInvalidRemote: true }); lastAction = [...r.messages, ...r.problems.map((p) => `${r.stage ? `${r.stage}: ` : ''}${p}`)].join('\n'); }));
  on('exportAllBtn', 'click', () => downloadBlob('sql-assistant-schemas.json', schemas.exportRegistryJson(), 'application/json'));
  body.querySelectorAll<HTMLElement>('[data-cf]').forEach((b) => b.addEventListener('click', () => { sync.resolveConflict(b.dataset.cf!, b.dataset.ch as 'keep-local'); re(); }));
  void checkRegistry;
}
function pullHtml(p: PullOutcome): string {
  if (p.fileProblem) return `<div class="alert alert-danger py-2 small mb-0" id="pullReport"><strong>Synchronization failed at stage: ${esc(p.stage || 'unknown')}</strong><br>${multiline(p.fileProblem)}<br><span class="text-body-secondary">Your local schemas and the Active Schema were not changed. Fix the cause and press Synchronize now to retry.</span></div>`;
  const rows = [...p.migrated.map((m) => `<tr><td>${esc(m.name)}</td><td>${chip('text-bg-info-subtle text-info-emphasis', 'Migration successful')}</td><td class="pre-line">${esc(migrationMessage(m))}</td></tr>`),
    ...p.rejected.map((r) => `<tr><td>${esc(r.name)}</td><td>${chip('text-bg-danger-subtle', r.legacy ? 'Migration failed' : 'Invalid schema')}</td><td><div class="pre-line">${esc(rejectionMessage(r))}</div><details><summary>All ${r.total} problem(s)</summary><ul>${r.errors.map((e) => `<li>${esc(e)}</li>`).join('')}${r.total > r.errors.length ? `<li>…and ${r.total - r.errors.length} more</li>` : ''}</ul></details></td></tr>`),
    ...[...p.added, ...p.updated, ...p.unchanged].filter((n) => !p.migrated.some((m) => m.name === n)).map((n) => `<tr><td>${esc(n)}</td><td>${chip(p.remoteLegacy ? 'text-bg-warning-subtle text-warning-emphasis' : 'text-bg-success-subtle text-success-emphasis', p.remoteLegacy ? 'Legacy schema' : 'Current schema')}</td><td>${p.added.includes(n) ? 'Added' : p.updated.includes(n) ? 'Updated from repository' : 'Up to date'}</td></tr>`),
    ...p.localAhead.map((n) => `<tr><td>${esc(n)}</td><td>${chip('text-bg-secondary', 'Newer on this device')}</td><td>Published with this synchronization.</td></tr>`)];
  return `<div class="small mb-1">Repository file written by: <strong>${esc(p.remoteWriter || '—')}</strong>${p.remoteLegacy ? ` ${chip('text-bg-warning-subtle text-warning-emphasis', 'Legacy schema')} ${chip('text-bg-warning-subtle text-warning-emphasis', 'Migration required')}` : ''}${p.activeChanged ? ` ${chip('text-bg-primary', 'Active Schema refreshed')}` : ''}</div>
    <table class="table table-sm sync-report mb-0" id="pullReport"><tbody>${rows.join('') || '<tr><td>The repository has no schema file yet — publishing creates it.</td></tr>'}</tbody></table>
    ${p.rejected.length ? `<div class="alert alert-danger py-2 small mt-2 mb-0">${p.rejected.length} schema(s) in the repository failed validation and were not loaded — your local copies were kept unchanged.</div>` : ''}`;
}
// ───────── Manual Schema Update (row-wise) ─────────
function manual(body: HTMLElement): void {
  const { schemas } = services(); const reg = schemas.registry(); if (!edId || !schemas.byId(edId)) edId = reg.activeSchemaId; const s = schemas.byId(edId)!; const all = rowsOf(s);
  const vis = all.filter((r) => !filt || r.rowId.toLowerCase().includes(filt.toLowerCase()) || r.columnDescription.toLowerCase().includes(filt.toLowerCase())).slice(0, 500); const sel = all.find((r) => r.rowId === selRow) || null;
  body.innerHTML = `<div class="card"><div class="card-body"><div class="d-flex flex-wrap gap-2 align-items-center mb-2 mu-table-bar"><select class="form-select form-select-sm w-auto" id="muSchema">${options(reg.schemas.map((x) => x.id), s.id, Object.fromEntries(reg.schemas.map((x) => [x.id, x.name])))}</select><input class="form-control form-control-sm w-auto" id="muFilter" placeholder="Filter rows" value="${esc(filt)}">
      <span class="small me-auto" id="muSelected">${sel ? `Selected row: <strong>${esc(sel.tableName)}.${esc(sel.columnName)}</strong>` : '<span class="text-body-secondary">Select one row to edit or delete it.</span>'}</span>
      <button class="btn btn-primary btn-sm" id="muEditBtn" type="button"${sel ? '' : ' disabled'}><i class="bi bi-pencil-square me-1"></i>Edit selected row</button><button class="btn btn-outline-danger btn-sm" id="muDeleteBtn" type="button"${sel ? '' : ' disabled'}><i class="bi bi-trash-fill me-1"></i>Delete selected row</button></div>
    <div class="table-responsive" style="max-height:480px;overflow:auto"><table class="table table-sm table-hover small mb-0" id="muGrid"><thead><tr><th>Module</th><th>Table</th><th>Column</th><th>Type</th><th>Null</th><th>Key</th><th>Decode</th><th>Description</th></tr></thead><tbody>
    ${vis.map((r) => `<tr class="mu-row${r.rowId === selRow ? ' table-active' : ''}" data-row="${esc(r.rowId)}"><td>${esc(r.module)}</td><td>${esc(r.tableName)}</td><td><strong>${esc(r.columnName)}</strong></td><td>${esc(r.dataType)}</td><td>${r.nullable ? 'Y' : 'N'}</td><td>${r.isPrimaryKey ? 'PK ' : ''}${r.isForeignKey ? `FK→${esc(r.fkTable)}` : ''}</td><td>${esc(r.decodeText.split('\n').slice(0, 2).join('; '))}${r.decodeText.split('\n').length > 2 ? '…' : ''}</td><td>${esc(r.columnDescription)}</td></tr>`).join('')}</tbody></table></div>
    ${all.length > vis.length ? `<div class="small text-body-secondary mt-1">${all.length - vis.length} more rows — use the filter.</div>` : ''}
    ${changes.length ? `<div class="alert alert-success py-2 small mt-2 mb-0" id="muChanges">Saved to the centralized schema and the Active Schema was refreshed:<ul class="mb-0">${changes.map((c) => `<li>${esc(c)}</li>`).join('')}</ul></div>` : ''}</div></div>`;
  const re = rerender('manual-update');
  on('muSchema', 'change', () => { edId = val('muSchema'); selRow = null; changes = []; re(); }); on('muFilter', 'change', () => { filt = val('muFilter'); re(); });
  body.querySelectorAll<HTMLElement>('[data-row]').forEach((tr) => { tr.addEventListener('click', () => { selRow = tr.dataset.row!; changes = []; re(); }); tr.addEventListener('dblclick', () => { selRow = tr.dataset.row!; openEditor(s, all.find((r) => r.rowId === selRow)!); }); });
  on('muEditBtn', 'click', () => { if (sel) openEditor(s, sel); });
  on('muDeleteBtn', 'click', () => { if (!sel) return; const deps = analyzeDependencies(s, sel.tableName, sel.columnName); if (!confirm(deps.length ? `Delete ${sel.tableName}.${sel.columnName}?\nThese dependent records will also be removed/unlinked:\n• ${deps.map((d) => d.description).join('\n• ')}` : `Delete ${sel.tableName}.${sel.columnName}?`)) return;
    const r = schemas.deleteRow(s.id, sel.rowId, deps.length > 0); if (!r.ok) { toast('error', r.errors.map((e) => `${e.message} ${(e.details || []).join(' ')}`).join(' ')); return; } changes = r.changes; selRow = null; toast('success', 'Row deleted.'); re(); });
}
function openEditor(s: SchemaModel, row: SchemaEditorRow): void {
  const types = Array.from(new Set([row.dataType, 'VARCHAR2', 'NVARCHAR2', 'VARCHAR', 'CHAR', 'NUMBER', 'INTEGER', 'DATE', 'TIMESTAMP', 'CLOB', 'BLOB', 'FLAG']));
  $('muEditTitle').textContent = `Edit row: ${row.tableName}.${row.columnName}`;
  const f = (id: string, label: string, v: string, extra = '') => `<div class="col-md-6"><label class="form-label small mb-1" for="${id}">${label}</label><input class="form-control form-control-sm mu-field" id="${id}" value="${esc(v)}" ${extra}></div>`;
  $('muEditBody').innerHTML = `<div class="row g-2">${f('muColumn', 'Column Name', row.columnName)}<div class="col-md-6"><label class="form-label small mb-1" for="muType">Data Type</label><select class="form-select form-select-sm mu-field" id="muType">${options(types, row.dataType)}</select></div>
    ${f('muLength', 'Length', row.length === null ? '' : String(row.length), 'inputmode="numeric"')}${f('muPrecision', 'Precision', row.precision === null ? '' : String(row.precision), 'inputmode="numeric"')}${f('muAlias', 'Alias', row.alias)}
    <div class="col-md-6 d-flex align-items-end gap-3"><div class="form-check"><input class="form-check-input mu-field" type="checkbox" id="muNullable"${row.nullable ? ' checked' : ''}><label class="form-check-label small" for="muNullable">Nullable</label></div><div class="form-check"><input class="form-check-input mu-field" type="checkbox" id="muPk"${row.isPrimaryKey ? ' checked' : ''}><label class="form-check-label small" for="muPk">Primary Key</label></div><div class="form-check"><input class="form-check-input mu-field" type="checkbox" id="muFk"${row.isForeignKey ? ' checked' : ''}><label class="form-check-label small" for="muFk">Foreign Key</label></div></div>
    ${f('muFkTable', 'References Table', row.fkTable)}${f('muFkColumn', 'References Column', row.fkColumn)}
    <div class="col-12"><label class="form-label small mb-1" for="muDesc">Column Description</label><textarea class="form-control form-control-sm mu-field" id="muDesc" rows="2">${esc(row.columnDescription)}</textarea></div>
    <div class="col-12"><label class="form-label small mb-1" for="muDecode">Decode (one per line: CODE=Label)</label><textarea class="form-control form-control-sm font-monospace mu-field" id="muDecode" rows="4">${esc(row.decodeText)}</textarea></div>
    ${f('muModule', 'Module <span class="badge text-bg-warning-subtle text-warning-emphasis">applies to all columns of the table</span>', row.module)}${f('muTableDesc', 'Table Description <span class="badge text-bg-warning-subtle text-warning-emphasis">applies to all columns of the table</span>', row.tableDescription)}
    <div class="col-12"><div class="small fw-semibold mt-1">Current → modified</div><div id="muDiff" class="small text-body-secondary">No changes.</div><div id="muError"></div></div></div>`;
  const read = (): SchemaEditorRow => { const n = (id: string) => { const v = val(id).trim(); return v === '' ? null : Number(v); }; return { ...row, columnName: val('muColumn'), dataType: val('muType'), length: n('muLength'), precision: n('muPrecision'), alias: val('muAlias'), nullable: checked('muNullable'), isPrimaryKey: checked('muPk'), isForeignKey: checked('muFk'), fkTable: val('muFkTable'), fkColumn: val('muFkColumn'), columnDescription: val('muDesc'), decodeText: val('muDecode'), module: val('muModule'), tableDescription: val('muTableDesc') }; };
  const refresh = () => { const d = diffRows(row, read()); $('muDiff').innerHTML = d.length ? `<ul class="mb-0">${d.map((x) => `<li>${esc(x.field)}${x.tableLevel ? ' (table-level)' : ''}: <span class="diff-from">${esc(x.from)}</span> → <span class="diff-to">${esc(x.to)}</span></li>`).join('')}</ul>` : 'No changes.'; ($('muSaveBtn') as HTMLButtonElement).disabled = !d.length; $('muEditHint').textContent = d.length ? `${d.length} field(s) changed` : 'Save is enabled once something changes.'; };
  $('muEditBody').querySelectorAll('.mu-field').forEach((el) => { el.addEventListener('input', refresh); el.addEventListener('change', refresh); }); refresh();
  const m = modal('muEditModal');
  $('muResetBtn').onclick = () => openEditor(s, row);
  $('muSaveBtn').onclick = () => { const r = services().schemas.upsertRow(s.id, read(), row.rowId); if (!r.ok) { $('muError').innerHTML = `<div class="alert alert-danger py-2 small mt-2 mb-0">${r.errors.map((e) => `${esc(e.message)}${e.details?.length ? `<ul class="mb-0">${e.details.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>` : ''}`).join('')}</div>`; return; }
    changes = r.changes; selRow = `${row.tableName}::${read().columnName.trim()}`; m.hide(); toast('success', 'Row saved, validated, and the Active Schema was refreshed.'); renderSettings('manual-update'); };
  m.show();
}
// ───────── Secret Vault ─────────
function vaultTab(body: HTMLElement): void {
  const s = secrets; const { vault } = services();
  body.innerHTML = `<div class="card mb-3"><div class="card-body"><h2 class="h6"><span class="icon-badge icon-badge-sm badge-dark"><i class="bi bi-github"></i></span> GitHub repository (schema sync)</h2>
    <div class="alert alert-secondary py-2 small"><i class="bi bi-shield-lock-fill me-1"></i>Stored on this device encrypted with AES-256-GCM (non-extractable device key). The token is sent only to <code>api.github.com</code> over HTTPS. Use a fine-grained token scoped to this one repository with <strong>Contents: Read and write</strong>.</div>
    <div class="row g-2"><div class="col-md-4"><label class="form-label small mb-1" for="vOwner">Repository Owner</label><input class="form-control form-control-sm" id="vOwner" value="${esc(s.githubOwner)}" placeholder="e.g. acme-corp"></div><div class="col-md-4"><label class="form-label small mb-1" for="vRepo">Repository Name</label><input class="form-control form-control-sm" id="vRepo" value="${esc(s.githubRepo)}" placeholder="e.g. sql-assistant-data"></div><div class="col-md-4"><label class="form-label small mb-1" for="vBranch">Branch</label><input class="form-control form-control-sm" id="vBranch" value="${esc(s.githubBranch)}"></div>
      <div class="col-md-6"><label class="form-label small mb-1" for="vSchemaPath">Schema file path <span class="text-body-secondary">(default ${esc(CANONICAL_SCHEMA_PATH)})</span></label><input class="form-control form-control-sm" id="vSchemaPath" value="${esc(s.schemaPath)}"></div><div class="col-md-6"><label class="form-label small mb-1" for="vVaultPath">Vault file path</label><input class="form-control form-control-sm" id="vVaultPath" value="${esc(s.vaultPath)}"></div>
      <div class="col-12"><label class="form-label small mb-1" for="vToken">Personal Access Token</label><input class="form-control form-control-sm" type="password" id="vToken" autocomplete="off" placeholder="${esc(maskSecret(s.githubToken))} — leave empty to keep"></div></div>
    <button class="btn btn-primary btn-sm mt-2" id="vSaveBtn" type="button"><i class="bi bi-save me-1"></i>Save configuration</button></div></div>
  <div class="card"><div class="card-body"><h2 class="h6"><span class="icon-badge icon-badge-sm badge-green"><i class="bi bi-cloud-upload"></i></span> Push Secret Vault to Repository</h2>
    <p class="small text-body-secondary">Shares this configuration with your other devices. The vault is encrypted with AES-256-GCM using a key derived (PBKDF2-SHA-256, 310 000 iterations) from your <strong>Vault Sync Passphrase</strong>. The passphrase and key are never stored or uploaded — without them the repository file cannot be read.</p>
    <label class="form-label small mb-1" for="vPass">Vault Sync Passphrase (min. 10 characters)</label><input class="form-control form-control-sm" type="password" id="vPass" autocomplete="new-password" style="max-width:340px">
    <div class="d-flex flex-wrap gap-2 mt-2"><button class="btn btn-outline-primary btn-sm" id="vPushBtn" type="button"><i class="bi bi-cloud-upload me-1"></i>Push Secret Vault to Repository</button><button class="btn btn-outline-secondary btn-sm" id="vPullBtn" type="button"><i class="bi bi-cloud-download me-1"></i>Retrieve Secret Vault from Repository</button></div><div id="vResult" class="mt-2"></div></div></div>`;
  const out = (ok: boolean, m: string) => { $('vResult').innerHTML = `<div class="alert ${ok ? 'alert-success' : 'alert-danger'} py-2 small mb-0">${esc(redactSecrets(m, vault.knownSecrets()))}</div>`; };
  on('vSaveBtn', 'click', async () => { const n: VaultSecrets = { ...s, githubOwner: val('vOwner').trim(), githubRepo: val('vRepo').trim(), githubBranch: val('vBranch').trim() || 'main', schemaPath: val('vSchemaPath').trim(), vaultPath: val('vVaultPath').trim(), githubToken: val('vToken').trim() || s.githubToken };
    if ((n.githubOwner && !/^[\w.-]+$/.test(n.githubOwner)) || (n.githubRepo && !/^[\w.-]+(\/[\w.-]+)?$/.test(n.githubRepo))) { toast('error', 'Owner and repository may only contain letters, digits, ".", "-" and "_".'); return; }
    try { await vault.save(n); await reloadSecrets(); toast('success', 'Secret Vault saved (encrypted).'); renderSettings('vault'); } catch (e) { toast('error', `Encryption failed: ${(e as Error).message}`); } });
  on('vPushBtn', 'click', async () => { const r = repository(); if (!r) { out(false, 'Configure the repository and token first.'); return; } try { const t = await vault.exportEncrypted(val('vPass')); const c = await r.read(secrets.vaultPath); await r.write(secrets.vaultPath, t, c?.sha ?? null, 'SQL Assistant: update encrypted Secret Vault'); out(true, 'Encrypted Secret Vault pushed to the repository.'); } catch (e) { out(false, `Push failed: ${(e as Error).message}`); } });
  on('vPullBtn', 'click', async () => { const r = repository(); if (!r) { out(false, 'Configure the repository and token first (the token is needed to read the repository).'); return; } try { const f = await r.read(secrets.vaultPath); if (!f) { out(false, 'No vault file in the repository yet.'); return; } await vault.importEncrypted(f.text, val('vPass')); await reloadSecrets(); out(true, 'Secret Vault retrieved, decrypted and validated.'); } catch (e) { out(false, `Retrieve failed: ${(e as Error).message}`); } });
}
// ───────── AI/LLM Model ─────────
function aiTab(body: HTMLElement): void {
  const c = aiConfig; const { vault, store } = services();
  body.innerHTML = `<div class="card"><div class="card-body"><h2 class="h6"><span class="icon-badge icon-badge-sm badge-indigo"><i class="bi bi-cpu-fill"></i></span> AI/LLM Model <span class="badge text-bg-secondary">optional</span></h2>
    <div class="alert alert-info py-2 small">The <strong>offline NLU model is the primary/default engine</strong>. The AI/LLM Model is consulted only when it is enabled and the offline result is uncertain; its SQL is validated against the Active Schema. If it is unavailable (offline browser, locked vault, missing key, provider error) the offline result is used.</div>
    <div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" id="aiEnabled"${c.enabled ? ' checked' : ''}><label class="form-check-label" for="aiEnabled">Enable AI/LLM Model</label></div>
    <div class="row g-2"><div class="col-md-4"><label class="form-label small mb-1" for="aiProvider">Provider</label><select class="form-select form-select-sm" id="aiProvider">${options(Object.keys(PROVIDER_DEFAULTS), c.provider, Object.fromEntries(Object.entries(PROVIDER_DEFAULTS).map(([k, v]) => [k, v.label])))}</select></div>
      <div class="col-md-4"><label class="form-label small mb-1" for="aiModel">Model</label><input class="form-control form-control-sm" id="aiModel" value="${esc(c.model)}" placeholder="e.g. gpt-4o-mini"></div><div class="col-md-4"><label class="form-label small mb-1" for="aiAuth">Authentication</label><select class="form-select form-select-sm" id="aiAuth">${options(['bearer', 'api-key-header', 'none'], c.authType, { bearer: 'Bearer token', 'api-key-header': 'API key header', none: 'None (local model)' })}</select></div>
      <div class="col-12"><label class="form-label small mb-1" for="aiEndpoint">Endpoint</label><input class="form-control form-control-sm" id="aiEndpoint" value="${esc(c.endpoint || PROVIDER_DEFAULTS[c.provider].endpoint)}"></div>
      <div class="col-md-6"><label class="form-label small mb-1" for="aiKey">API key (stored encrypted in the Secret Vault)</label><input class="form-control form-control-sm" type="password" id="aiKey" autocomplete="off" placeholder="${esc(maskSecret(secrets.aiApiKey))} — leave empty to keep"></div>
      <div class="col-md-3"><label class="form-label small mb-1" for="aiApiVersion">API version</label><input class="form-control form-control-sm" id="aiApiVersion" value="${esc(c.apiVersion)}"></div><div class="col-md-3"><label class="form-label small mb-1" for="aiTimeout">Timeout (ms)</label><input class="form-control form-control-sm" id="aiTimeout" value="${c.timeoutMs}" inputmode="numeric"></div>
      <div class="col-12"><label class="form-label small mb-1" for="aiExtra">Model-specific configuration (JSON)</label><textarea class="form-control form-control-sm font-monospace" id="aiExtra" rows="2">${esc(c.extraJson)}</textarea></div></div>
    <button class="btn btn-primary btn-sm mt-2" id="aiSaveBtn" type="button"><i class="bi bi-save me-1"></i>Save</button><div id="aiResult" class="mt-2"></div></div></div>`;
  on('aiProvider', 'change', () => { const p = val('aiProvider') as AiProvider; $<HTMLInputElement>('aiEndpoint').value = PROVIDER_DEFAULTS[p].endpoint; $<HTMLSelectElement>('aiAuth').value = PROVIDER_DEFAULTS[p].authType; });
  on('aiSaveBtn', 'click', async () => { const cfg = { ...c, enabled: checked('aiEnabled'), provider: val('aiProvider') as AiProvider, model: val('aiModel').trim(), endpoint: val('aiEndpoint').trim(), authType: val('aiAuth') as AiAuth, apiVersion: val('aiApiVersion').trim(), timeoutMs: Number(val('aiTimeout')) || 20000, extraJson: val('aiExtra') }; const key = val('aiKey').trim() || secrets.aiApiKey; const p = validateAiConfig(cfg, key);
    if (p.length) { $('aiResult').innerHTML = `<div class="alert alert-danger py-2 small mb-0">AI/LLM configuration invalid:<ul class="mb-0">${p.map((x) => `<li>${esc(x)}</li>`).join('')}</ul></div>`; return; }
    try { if (key !== secrets.aiApiKey) { await vault.save({ ...secrets, aiApiKey: key }); await reloadSecrets(); } saveAiConfig(cfg, store); setAiConfig(cfg); toast('success', 'AI/LLM Model configuration saved.'); renderSettings('ai'); } catch (e) { toast('error', (e as Error).message); } });
}
