/** Settings → Admin Query Library (V17.4). Trusted, administrator-approved SQL examples that the offline NLU uses as PATTERNS (never copied). */
import { icon } from '../components/icons'; import { openModal } from '../components/modal'; import { store } from '../state'; import { services, secrets } from '../context'; import { e } from '../dom'; import { downloadBlob } from '../../utils/dom';
import { verifyPassword } from '../../services/passwordService'; import { validateAdminQuery, schemaCompatible, type AdminQuery, type AdminInput, type AdminValidation, type AdminDialect } from '../../v17/services/adminLibrary';
import { extractSqlPattern } from '../../v17/engines/sqlPatterns'; import { parseKnowledge, sanitizeAdmin, KNOWLEDGE_FORMAT } from '../../v17/services/knowledgeSync'; import { TIER_LABEL, tierOf, weightOf } from '../../v17/services/learningStore'; import { redactSecrets } from '../../v17/errors/appErrors';
import type { Dialect } from '../../types';
const box = (kind: 'ok' | 'warn' | 'err', html: string) => `<div class="issue-box ${kind === 'ok' ? 'ok' : kind === 'warn' ? 'warn' : ''} mini">${icon(kind === 'ok' ? 'check' : 'alert-triangle', 14)}<div>${html}</div></div>`;
const DIALECT_OPTS: AdminDialect[] = ['Any', 'SQL Server', 'Oracle', 'PostgreSQL', 'MySQL', 'Generic'];
let fText = ''; let fStatus = 'all'; let fEnabled = 'all'; let fDialect = 'all'; let fTag = ''; let result = '';
const fallbackDialect = (q: Pick<AdminQuery, 'dialect'>): Dialect => (q.dialect === 'Any' ? 'Generic' : q.dialect);
const checksHtml = (v: AdminValidation) => `<ul class="check-list">${v.checks.map((c) => `<li><span class="ck ck-${c.status}">${c.status === 'pass' ? '✔' : c.status === 'warn' ? '!' : '✖'}</span><span>${e(c.label)}${c.details.map((d) => `<span class="why">${e(d)}</span>`).join('')}</span></li>`).join('')}</ul>${v.errors.filter((x) => /Not compatible|Only SELECT/.test(x)).map((x) => `<div class="hint" style="color:#d64550">${e(x)}</div>`).join('')}`;
async function confirmPassword(title: string, message: string, then: () => void): Promise<void> {
  const m = openModal(`${icon('trash', 18)} ${title}`, `<p>${message}</p><label class="block-label">Admin Password<input type="password" id="aqPw" autocomplete="off"></label><div id="aqPwErr"></div><div class="modal-actions"><button type="button" class="btn btn-ghost" id="aqPwCancel">Cancel</button><button type="button" class="btn btn-primary" id="aqPwOk">Confirm</button></div>`, { closeOnBackdrop: false });
  m.element.querySelector('#aqPwCancel')!.addEventListener('click', () => m.close());
  m.element.querySelector('#aqPwOk')!.addEventListener('click', async () => { if (!(await verifyPassword((m.element.querySelector('#aqPw') as HTMLInputElement).value))) { m.element.querySelector('#aqPwErr')!.innerHTML = box('err', 'Incorrect Admin Password — nothing was changed.'); return; } m.close(); then(); });
}
export function adminLibraryTab(p: HTMLElement): void {
  const { admin, learning, knowledge, store: kv } = services(); const s = services().schemas.active(); const c = admin.counts(); const re = () => adminLibraryTab(p);
  const list = admin.search({ text: fText, status: fStatus as 'all', enabled: fEnabled as 'all', dialect: fDialect, tag: fTag });
  const lv = (q: AdminQuery) => { const v = q.lastValidation; if (!v) return '<span class="chip chip-inactive">Not tested</span>'; const stale = v.fingerprint !== undefined && v.schemaId !== s.id; return v.valid ? `<span class="chip chip-active">Valid${stale ? ` · for ${e(v.schemaName)}` : ''}</span>` : `<span class="chip chip-invalid" title="${e(v.errors.join(' '))}">Invalid</span>`; };
  const learned = learning.all().filter((r) => weightOf(r) >= 0.65 && (r.finalSql || r.generatedSql) && !admin.all().some((q) => q.sql.trim() === (r.finalSql || r.generatedSql).trim())).slice(0, 8);
  const ls = learning.stats();
  p.innerHTML = `<div class="builder-panel"><h2>${icon('shield', 16)} Admin Query Library</h2><p class="hint">Previously created, successfully executed SQL that administrators trust. The offline NLU searches this library <strong>before</strong> the centrally learned queries (higher trust) and uses a matching query as a <em>pattern</em> — it is adapted to the Active Schema <strong>${e(s.name)}</strong> and to your request, never copied. Only <strong>approved + enabled</strong> queries that still validate against the Active Schema are trusted.</p>
    <div class="admin-stats"><span class="chip">${c.total} quer${c.total === 1 ? 'y' : 'ies'}</span><span class="chip chip-active">${c.approved} approved</span><span class="chip">${c.enabled} enabled</span><span class="chip chip-migrated">${c.trusted} trusted for use</span><span class="chip chip-inactive">Learned: ${ls.executed} executed · ${ls.confirmed + ls.modified} confirmed · ${ls.repeated} repeated · ${ls.generated} unconfirmed${ls.rejected ? ` · ${ls.rejected} rejected` : ''}</span></div>
    <div class="admin-toolbar"><input type="text" id="aqSearch" placeholder="Search name, description, tags, tables, SQL…" aria-label="Search queries" value="${e(fText)}"><select id="aqStatus" aria-label="Approval status"><option value="all">All statuses</option><option value="approved" ${fStatus === 'approved' ? 'selected' : ''}>Approved</option><option value="draft" ${fStatus === 'draft' ? 'selected' : ''}>Draft (not approved)</option></select><select id="aqEnabled" aria-label="Enabled"><option value="all">Enabled + disabled</option><option value="enabled" ${fEnabled === 'enabled' ? 'selected' : ''}>Enabled</option><option value="disabled" ${fEnabled === 'disabled' ? 'selected' : ''}>Disabled</option></select><select id="aqDialect" aria-label="Dialect"><option value="all">All dialects</option>${DIALECT_OPTS.map((d) => `<option ${fDialect === d ? 'selected' : ''}>${d}</option>`).join('')}</select><select id="aqTag" aria-label="Tag"><option value="">All tags</option>${admin.tags().map((t) => `<option ${fTag === t ? 'selected' : ''}>${e(t)}</option>`).join('')}</select></div>
    <div class="row-actions"><button type="button" class="btn btn-primary" id="aqAdd">${icon('plus', 14)} Add query</button><button type="button" class="btn btn-outline" id="aqExport">${icon('download', 14)} Export JSON</button><label class="btn btn-outline file-input-label">${icon('upload', 14)} Import JSON<input type="file" id="aqImport" accept=".json" hidden></label><button type="button" class="btn btn-outline" id="aqSync">${icon('folder-sync', 14)} Sync knowledge now</button></div><div id="aqResult">${result}</div>
    <div class="data-table-scroll-wrap mt"><table class="data-table" style="min-width:760px"><thead><tr><th>Name</th><th>Status</th><th>Dialect</th><th>Tables</th><th>Updated</th><th>Actions</th></tr></thead><tbody>${list.map((q) => `<tr data-id="${e(q.id)}" style="cursor:default"><td style="white-space:normal;max-width:300px"><strong>${e(q.name)}</strong><br><span class="hint">${e(q.description || q.purpose)}</span>${q.tags.length ? `<br>${q.tags.map((t) => `<span class="chip chip-inactive tier-chip">${e(t)}</span>`).join(' ')}` : ''}</td><td>${q.approved ? '<span class="chip chip-active">Approved</span>' : '<span class="chip chip-legacy">Draft</span>'} ${q.enabled ? '' : '<span class="chip chip-inactive">Disabled</span>'} ${lv(q)}</td><td>${e(q.dialect)}</td><td style="white-space:normal;max-width:180px">${e(q.tables.join(', '))}</td><td>${e(q.updatedAt.slice(0, 10))}<br><span class="hint">${e(q.createdBy)}</span></td><td style="white-space:normal"><div class="row-actions" style="margin:0"><button type="button" class="btn btn-outline btn-sm" data-act="edit">${icon('edit', 13)} Edit</button><button type="button" class="btn btn-outline btn-sm" data-act="test">${icon('clipboard-check', 13)} Test</button>${q.approved ? `<button type="button" class="btn btn-outline btn-sm" data-act="unapprove">Withdraw approval</button>` : `<button type="button" class="btn btn-primary btn-sm" data-act="approve">${icon('check', 13)} Approve</button>`}<button type="button" class="btn btn-outline btn-sm" data-act="toggle">${q.enabled ? 'Disable' : 'Enable'}</button><button type="button" class="icon-btn" data-act="delete" aria-label="Delete query">${icon('trash', 14)}</button></div></td></tr>`).join('') || `<tr><td colspan="6" class="data-table-empty">${c.total ? 'No query matches the search or filters.' : 'The library is empty. Add a previously created, successfully executed SELECT query to make it a trusted example.'}</td></tr>`}</tbody></table></div></div>
    <div class="builder-panel mt"><h2>${icon('sparkles', 16)} Learned queries ready for review</h2><p class="hint">Confirmed or successfully executed queries learned on the connected devices. Promote one to the library to review, edit and approve it as a trusted example. Unconfirmed or rejected queries never appear here.</p>${learned.length ? `<ul class="plan-list">${learned.map((r) => `<li><strong>${e(r.requestText)}</strong> <span class="chip chip-inactive tier-chip">${e(TIER_LABEL[tierOf(r)])}</span> <button type="button" class="btn-link" data-promote="${e(r.id)}">Add to library as draft</button></li>`).join('')}</ul>` : '<p class="hint">Nothing waiting for review.</p>'}</div>`;
  const on = (sel: string, ev: string, fn: (e: Event) => void) => p.querySelector(sel)!.addEventListener(ev, fn);
  on('#aqSearch', 'input', (ev) => { fText = (ev.target as HTMLInputElement).value; const pos = fText.length; re(); const i = p.querySelector<HTMLInputElement>('#aqSearch')!; i.focus(); i.setSelectionRange(pos, pos); });
  on('#aqStatus', 'change', (ev) => { fStatus = (ev.target as HTMLSelectElement).value; re(); }); on('#aqEnabled', 'change', (ev) => { fEnabled = (ev.target as HTMLSelectElement).value; re(); }); on('#aqDialect', 'change', (ev) => { fDialect = (ev.target as HTMLSelectElement).value; re(); }); on('#aqTag', 'change', (ev) => { fTag = (ev.target as HTMLSelectElement).value; re(); });
  on('#aqAdd', 'click', () => editor(null, re)); on('#aqExport', 'click', () => downloadBlob('sql-assistant-admin-queries.json', admin.exportJson(), 'application/json'));
  on('#aqImport', 'change', async (ev) => { const f = (ev.target as HTMLInputElement).files?.[0]; if (!f) return; try { const j = JSON.parse(await f.text()); const arr = Array.isArray(j.queries) ? j.queries : []; let n = 0; const bad: string[] = []; arr.forEach((o: unknown, i: number) => { const r = sanitizeAdmin({ ...(o as object), id: undefined === (o as { id?: string }).id ? `aq_imp${Date.now().toString(36)}${i}` : (o as { id: string }).id }); if (typeof r === 'string') { bad.push(`#${i + 1}: ${r}`); return; } const x = admin.upsert({ ...r, id: undefined } as AdminInput); if (x.ok) n++; else bad.push(`#${i + 1} ${r.name}: ${x.errors[0]}`); }); result = box(bad.length ? 'warn' : 'ok', `${n} quer${n === 1 ? 'y' : 'ies'} imported as drafts — test and approve them before use.${bad.length ? `<br>Not imported: ${e(bad.join(' · '))}` : ''}`); } catch (err) { result = box('err', `Import failed: ${e((err as Error).message)} — the file must be a SQL Assistant Admin Query Library export.`); } re(); });
  on('#aqSync', 'click', async () => { result = box('warn', 'Synchronizing knowledge…'); (p.querySelector('#aqResult') as HTMLElement).innerHTML = result; const r = await knowledge.synchronize(); result = box(r.ok ? 'ok' : 'err', e(r.ok ? r.message : `Failed at stage ${r.stage}: ${r.message}`) + (r.rejected.length ? `<br>${e(r.rejected.slice(0, 3).join(' · '))}` : '')); re(); });
  p.querySelectorAll<HTMLElement>('[data-act]').forEach((b) => b.addEventListener('click', () => { const id = (b.closest('tr') as HTMLElement).dataset.id!; const q = admin.get(id); if (!q) return; const act = b.dataset.act!;
    if (act === 'edit') editor(q, re);
    else if (act === 'test') { const v = admin.validate(id, s, fallbackDialect(q)); result = v ? box(v.valid ? 'ok' : 'err', `<strong>${e(q.name)}</strong> — ${v.valid ? 'valid against the Active Schema' : 'not valid'}${checksHtml(v)}${v.warnings.length ? `<div class="hint">${e(v.warnings.join(' '))}</div>` : ''}`) : ''; re(); }
    else if (act === 'approve') { const r = admin.approve(id, s, fallbackDialect(q)); result = r.ok ? box('ok', `<strong>${e(q.name)}</strong> approved — it is now a trusted example for SQL generation.`) : box('err', `<strong>${e(q.name)}</strong> was not approved because it is not valid against the Active Schema:<ul>${r.errors.slice(0, 5).map((x) => `<li>${e(x)}</li>`).join('')}</ul>Edit the query or choose the Active Schema it was written for, then test it again.`); re(); }
    else if (act === 'unapprove') { admin.unapprove(id); result = box('ok', `Approval withdrawn for ${e(q.name)} — it is no longer used as a trusted example.`); re(); }
    else if (act === 'toggle') { admin.setEnabled(id, !q.enabled); result = box('ok', `${e(q.name)} ${q.enabled ? 'disabled' : 'enabled'}.`); re(); }
    else if (act === 'delete') void confirmPassword('Delete query', `Delete <strong>${e(q.name)}</strong> from the Admin Query Library? The deletion is synchronized to your other devices.`, () => { admin.remove(id); result = box('ok', `${e(q.name)} deleted.`); store.pushToast('success', 'Query deleted.'); re(); }); }));
  p.querySelectorAll<HTMLElement>('[data-promote]').forEach((b) => b.addEventListener('click', () => { const r = learning.get(b.dataset.promote!); if (!r) return; const sql = r.finalSql || r.generatedSql; const pt = extractSqlPattern(sql, s).pattern; editor(null, re, { name: r.requestText.slice(0, 80), description: `Promoted from a ${TIER_LABEL[tierOf(r)].toLowerCase()} query: ${r.requestText}`, sql, tables: pt.tables, columns: pt.columns.map((x) => `${x.table}.${x.column}`), purpose: '', tags: [], dialect: (r.dialect || 'Any') as AdminDialect, schemaName: r.schemaName || s.name, schemaVersions: '*' }); }));
  void secrets; void kv;
}
function editor(q: AdminQuery | null, done: () => void, seed: Partial<AdminInput> = {}): void {
  const { admin, store: kv } = services(); const s = services().schemas.active(); const v = q || ({ name: '', description: '', sql: '', tables: [], columns: [], purpose: '', tags: [], dialect: 'Any', schemaName: s.name, schemaVersions: '*', createdBy: kv.get('sqla.adminname.v174') || 'Administrator', enabled: true, ...seed } as Partial<AdminQuery> & AdminInput);
  const f = (id: string, label: string, val: string, extra = '') => `<label class="block-label">${label}<input type="text" id="aq_${id}" value="${e(val)}" ${extra}></label>`;
  const m = openModal(`${icon('shield', 18)} ${q ? 'Edit query' : 'Add query'}`, `<div class="form-row-2">${f('name', 'Query name *', v.name, 'maxlength="120"')}${f('purpose', 'Business purpose', v.purpose || '', 'maxlength="300"')}</div>${f('description', 'Description', v.description || '', 'maxlength="600"')}
    <label class="block-label">SQL query * <span class="hint">(a read-only SELECT / WITH that has been run successfully)</span><textarea id="aq_sql" rows="9" spellcheck="false" style="font-family:'Cascadia Code',Consolas,monospace;font-size:12.5px">${e(v.sql)}</textarea></label>
    <div class="form-row-2">${f('tables', 'Relevant tables (comma separated)', (v.tables || []).join(', '))}${f('columns', 'Relevant columns (TABLE.COLUMN, comma separated)', (v.columns || []).join(', '))}</div><div class="row-actions" style="margin-top:0"><button type="button" class="btn-link" id="aqDetect">Detect tables &amp; columns from the SQL</button></div>
    <div class="form-row-3">${f('tags', 'Tags / categories', (v.tags || []).join(', '))}<label class="block-label">SQL dialect<select id="aq_dialect">${DIALECT_OPTS.map((d) => `<option ${v.dialect === d ? 'selected' : ''}>${d}</option>`).join('')}</select></label>${f('createdBy', 'Created by', v.createdBy || '', q ? 'readonly' : '')}</div>
    <div class="form-row-3">${f('schemaName', 'Schema compatibility (name; empty = any)', v.schemaName || '')}${f('schemaVersions', 'Schema versions (e.g. 1.0, 2.* or *)', v.schemaVersions || '*')}<label class="block-label">Created / approved<input type="text" readonly value="${e(q ? `${q.createdAt.slice(0, 10)} · ${q.approved ? `approved ${q.approvedAt?.slice(0, 10) || ''} by ${q.approvedBy}` : 'not approved'}` : 'set when saved')}"></label></div>
    <label class="inline-check"><input type="checkbox" id="aq_enabled" ${v.enabled !== false ? 'checked' : ''}> Enabled (used during SQL generation once approved)</label><p class="hint">${q ? 'Changing the SQL withdraws the approval — test and approve it again.' : 'New queries start as drafts. Test the query, then approve it from the list.'} Dialect <em>Any</em> means portable SQL; choose a dialect if the query uses dialect-specific functions.</p><div id="aqIssues"></div><div class="modal-actions"><button type="button" class="btn btn-ghost" id="aqCancel">Cancel</button><button type="button" class="btn btn-outline" id="aqTestBtn">${icon('clipboard-check', 14)} Test / validate</button><button type="button" class="btn btn-primary" id="aqSave">${icon('save', 14)} Save</button></div>`, { wide: true, closeOnBackdrop: false });
  const g = (id: string) => (m.element.querySelector(`#aq_${id}`) as HTMLInputElement).value; const read = (): AdminInput => ({ id: q?.id, name: g('name'), description: g('description'), purpose: g('purpose'), sql: g('sql'), tables: g('tables') as unknown as string[], columns: g('columns') as unknown as string[], tags: g('tags') as unknown as string[], dialect: g('dialect') as AdminDialect, schemaName: g('schemaName'), schemaVersions: g('schemaVersions'), createdBy: g('createdBy'), enabled: (m.element.querySelector('#aq_enabled') as HTMLInputElement).checked });
  const issues = m.element.querySelector('#aqIssues') as HTMLElement;
  m.element.querySelector('#aqCancel')!.addEventListener('click', () => m.close());
  m.element.querySelector('#aqDetect')!.addEventListener('click', () => { const { pattern, ignored } = extractSqlPattern(g('sql'), s); (m.element.querySelector('#aq_tables') as HTMLInputElement).value = pattern.tables.join(', '); (m.element.querySelector('#aq_columns') as HTMLInputElement).value = [...pattern.columns, ...pattern.aggregates].map((x) => `${x.table}.${x.column}`).join(', '); issues.innerHTML = ignored.length ? box('warn', `Not found in the Active Schema: ${e(ignored.join(', '))}`) : box('ok', 'Tables and columns detected from the SQL.'); });
  const test = (): AdminValidation => { const i = read(); const val = validateAdminQuery({ ...i, tables: String(g('tables')).split(',').map((x) => x.trim()).filter(Boolean), columns: String(g('columns')).split(',').map((x) => x.trim()).filter(Boolean), schemaName: i.schemaName || '', schemaVersions: i.schemaVersions || '' } as AdminInput, s, (i.dialect === 'Any' ? 'Generic' : i.dialect) as Dialect); issues.innerHTML = box(val.valid ? 'ok' : 'err', `${val.valid ? 'Valid against the Active Schema' : 'Not valid'} (${e(s.name)})${checksHtml(val)}${val.warnings.length ? `<div class="hint">${e(val.warnings.join(' '))}</div>` : ''}`); return val; };
  m.element.querySelector('#aqTestBtn')!.addEventListener('click', test);
  m.element.querySelector('#aqSave')!.addEventListener('click', () => { const r = admin.upsert(read()); if (!r.ok) { issues.innerHTML = box('err', `<strong>Not saved.</strong><ul>${r.errors.map((x) => `<li>${e(redactSecrets(x))}</li>`).join('')}</ul>`); return; } kv.set('sqla.adminname.v174', r.query!.createdBy); admin.validate(r.query!.id, s, (r.query!.dialect === 'Any' ? 'Generic' : r.query!.dialect) as Dialect); m.close(); store.pushToast('success', q ? 'Query saved.' : 'Query added as a draft — test and approve it to make it a trusted example.'); done(); });
  void schemaCompatible; void parseKnowledge; void KNOWLEDGE_FORMAT;
}
