/** Quick Start, Query Builder for CR, Schema (Stored Schemas + Tables & Views), Error Rectifier, About — V17.2 layouts. */
import { icon, type IconName } from '../components/icons'; import { logoMarkSvg } from '../components/logoMark'; import { renderSqlCodeBlock } from '../components/sqlCodeBlock'; import { renderTabs } from '../components/tabs'; import { renderFilterBuilder } from '../components/filterBuilder';
import { store, type Route } from '../state'; import { services, APP } from '../context'; import { e, copyText } from '../dom';
import { buildCrSQL, parseCrDescription } from '../../engines/crEngine'; import { validateCrState } from '../../engines/validationEngine'; import { rectify } from '../../engines/errorRectifierEngine';
import { legacyLeftovers } from '../../v17/sync/schemaFormat'; import { makeId } from '../../utils/id'; import { downloadBlob } from '../../utils/dom'; import { NLU_ENGINE_VERSION } from '../../v17/engines/nluEngine'; import { renderSchemaPullTab } from './schemaPull';
import type { CrQueryState, CrQueryType, Dialect, SchemaModel } from '../../types';
const active = (): SchemaModel => services().schemas.active();
export function renderQuickstartPage(c: HTMLElement, nav: (r: Route) => void): void {
  const s = active(); const modules = Array.from(new Set(s.tables.map((t) => t.module)));
  const card = (r: Route, ic: IconName, title: string, text: string) => `<div class="feature-card" role="button" tabindex="0" data-nav="${r}"><div class="feature-icon">${icon(ic, 22)}</div><h3>${title}</h3><p>${text}</p><span class="card-link">Open ${icon('arrow-right', 16)}</span></div>`;
  c.innerHTML = `<div class="page"><div class="hero-card"><h1>Welcome — what does this tool do?</h1><p class="lead">SQL Assistant helps you describe what you need in plain language — or make manual selections, or combine both. Every request uses your currently saved Active Schema as the single source of truth. The offline NLU engine generates the SQL locally, learns from queries you accept, and can optionally consult an AI/LLM Model configured by your administrator.</p></div>
    <h2 class="section-title">${icon('database')} Active schema: ${e(s.name)}</h2><div class="chip-row">${modules.map((m) => `<span class="chip">${e(m)}</span>`).join('')}</div>
    <h2 class="section-title">${icon('play')} Try an example</h2><div class="card-grid">${card('readonly', 'table', 'Read Only Query Builder', 'Try "Top 5 vendors by total invoice amount for approved invoices this year" — joins, grouping and sorting are generated for you.')}${card('cr', 'code', 'Query Builder for CR', 'Build INSERT / UPDATE / DELETE SQL, with mandatory-WHERE safeguards.')}${card('settings', 'settings', `Settings ${icon('lock', 15)}`, 'Password-protected: Security, Manual Schema Update, Schema Management, Secret Vault, Synchronization, Admin Query Library, AI/LLM Model, Danger Zone.')}${card('error-rectifier', 'bug', 'Error Rectifier', 'Paste a database error and the SQL that caused it to get a corrected query.')}</div>
    <div class="note-box">${icon('shield', 16)}<span>No execution, ever. SQL Assistant only ever produces SQL text for you to review and copy.</span></div></div>`;
  c.querySelectorAll<HTMLElement>('[data-nav]').forEach((x) => { const go = () => nav(x.dataset.nav as Route); x.addEventListener('click', go); x.addEventListener('keydown', (ev) => { if ((ev as KeyboardEvent).key === 'Enter') go(); }); });
}
// ── Query Builder for CR ──
let cr: CrQueryState = { dialect: 'Oracle', naturalLanguageText: '', queryType: 'UPDATE', table: null, values: [], filters: [], confirmNoWhere: false, generatedSql: '-- Choose a table for this Change Request.' }; let crNotes = ''; let crTab = 'details';
export function renderCrPage(c: HTMLElement): void {
  const s = active(); if (cr.table && !s.tables.some((t) => t.name === cr.table)) { cr.table = null; cr.values = []; cr.filters = []; }
  const regen = () => { cr.generatedSql = buildCrSQL(cr); };
  const issuesHtml = () => { const i = validateCrState(cr); return i.length ? `<div class="issue-box">${icon('alert-triangle', 15)}<ul>${i.map((x) => `<li>${e(x.message)}</li>`).join('')}</ul></div>` : ''; };
  const refresh = () => { regen(); renderSql(); const m = c.querySelector('#crIssues'); if (m) m.innerHTML = issuesHtml(); };
  function draw(): void {
    regen(); c.innerHTML = `<div class="page"><h1 class="page-title">${icon('edit')} Query Builder for CR</h1><p class="page-subtitle">Generates INSERT / UPDATE / DELETE SQL text for change requests — never executed. A WHERE condition is mandatory for UPDATE and DELETE.</p>
    <div class="builder-grid-top"><div class="builder-panel"><h2>${icon('sparkles', 16)} Describe the Change (optional)</h2><textarea id="crNlDesc" rows="5" placeholder="e.g. Update invoice 1234 status to Approved">${e(cr.naturalLanguageText)}</textarea><label class="inline-label">SQL dialect<select id="crDialectSelect">${(['SQL Server', 'Oracle', 'PostgreSQL', 'MySQL', 'Generic'] as Dialect[]).map((d) => `<option ${d === cr.dialect ? 'selected' : ''}>${d}</option>`).join('')}</select></label><div class="row-actions"><button type="button" id="crNlBuildBtn" class="btn btn-primary">${icon('zap', 15)} Build from Description</button></div><div id="crNotes">${crNotes}</div></div>
    <div class="builder-panel"><h2>${icon('code', 16)} Generated SQL</h2><div id="crSqlMount"></div></div></div>
    <div class="builder-panel manual-selectors-panel"><h2>${icon('sliders', 16)} Manual Selectors</h2><div id="crTabsMount"></div></div><div id="crIssues">${issuesHtml()}</div></div>`;
    c.querySelector('#crNlDesc')!.addEventListener('input', (ev) => { cr.naturalLanguageText = (ev.target as HTMLTextAreaElement).value; });
    c.querySelector('#crDialectSelect')!.addEventListener('change', (ev) => { cr.dialect = (ev.target as HTMLSelectElement).value as Dialect; refresh(); });
    c.querySelector('#crNlBuildBtn')!.addEventListener('click', () => { const r = parseCrDescription(cr.naturalLanguageText, s); if (r.queryType) cr.queryType = r.queryType; if (r.table) { cr.table = r.table; cr.values = r.values; cr.filters = r.filters; }
      crNotes = `<div class="notes-box"><div style="width:100%"><span class="engine-badge engine-offline">${icon('wifi-off', 13)} Offline/local engine</span><div class="schema-audit-line">${icon('database', 12)} Active Schema used: ${e(s.name)}</div><ul>${r.notes.map((n) => `<li>${e(n)}</li>`).join('')}${r.values.length ? `<li>SET: ${e(r.values.map((v) => `${v.column} = ${v.value}`).join(', '))}</li>` : ''}${r.filters.length ? `<li>WHERE: ${e(r.filters.map((f) => `${f.column} ${f.operator} ${f.value}`).join(' AND '))}</li>` : '<li>No WHERE condition detected — add one in Filters before the statement can be used.</li>'}</ul></div></div>`; draw(); });
    renderSql(); renderTabsSection();
  }
  function renderSql(): void { const m = c.querySelector<HTMLElement>('#crSqlMount'); if (!m) return; renderSqlCodeBlock(m, cr.generatedSql, { onCopy: () => { void copyText(cr.generatedSql); store.pushToast('success', 'SQL copied to clipboard.'); }, onClear: () => { cr = { ...cr, naturalLanguageText: '', table: null, values: [], filters: [], confirmNoWhere: false }; crNotes = ''; store.pushToast('info', 'CR query cleared.'); draw(); }, onRegenerate: () => refresh() }); }
  function renderTabsSection(): void { const m = c.querySelector<HTMLElement>('#crTabsMount'); if (!m) return; renderTabs(m, [{ id: 'details', label: 'Query Details', render: details }, { id: 'summary', label: 'Selected / Described Requirements', render: summary }], crTab, { details: 'cr-tab-details' }, (id) => { crTab = id; }); }
  function details(p: HTMLElement): void {
    const cols = cr.table ? (s.tables.find((t) => t.name === cr.table)?.columns || []) : []; const modules = Array.from(new Set(s.tables.map((t) => t.module)));
    p.innerHTML = `<div class="advanced-grid"><div><h5>Query Type</h5><div class="segmented" data-tour="cr-query-type">${(['INSERT', 'UPDATE', 'DELETE'] as CrQueryType[]).map((q) => `<button type="button" class="seg-btn ${cr.queryType === q ? 'active' : ''}" data-qt="${q}">${q}</button>`).join('')}</div><h5>Pick Table</h5><select id="crTableSelect"><option value="">— choose a table —</option>${modules.map((m) => `<optgroup label="${e(m)}">${s.tables.filter((t) => t.module === m && t.objectType !== 'VIEW').map((t) => `<option ${t.name === cr.table ? 'selected' : ''}>${e(t.name)}</option>`).join('')}</optgroup>`).join('')}</select>
      <h5 class="mt">${cr.queryType === 'UPDATE' ? 'Columns to Set' : cr.queryType === 'INSERT' ? 'Columns & Values' : 'Values'}</h5>${cr.queryType === 'DELETE' ? '<p class="hint">DELETE only needs a WHERE condition — no column values required.</p>' : `<div id="crValuesList" class="filter-rows"></div><button type="button" id="addCrValueBtn" class="btn btn-outline btn-sm" ${cols.length ? '' : 'disabled'}>${icon('plus', 14)} Add column</button>`}</div>
      <div><h5>Filters (WHERE Conditions)</h5><div id="crFilterMount"></div>${cr.queryType !== 'INSERT' ? `<div class="issue-box warn mini">⚠️ A WHERE condition is required to identify which records should be updated or deleted.</div><label class="inline-check"><input type="checkbox" id="confirmNoWhere" ${cr.confirmNoWhere ? 'checked' : ''}/> I explicitly confirm this query should have no WHERE condition</label>` : ''}</div></div>`;
    p.querySelectorAll<HTMLElement>('.seg-btn').forEach((b) => b.addEventListener('click', () => { cr.queryType = b.dataset.qt as CrQueryType; details(p); refresh(); }));
    p.querySelector('#crTableSelect')!.addEventListener('change', (ev) => { cr.table = (ev.target as HTMLSelectElement).value || null; cr.values = []; cr.filters = []; details(p); refresh(); });
    p.querySelector('#addCrValueBtn')?.addEventListener('click', () => { cr.values.push({ id: makeId('crv'), column: cols[0].name, value: '' }); renderValues(); refresh(); });
    p.querySelector('#confirmNoWhere')?.addEventListener('change', (ev) => { cr.confirmNoWhere = (ev.target as HTMLInputElement).checked; refresh(); });
    const renderValues = () => { const l = p.querySelector<HTMLElement>('#crValuesList'); if (!l) return; l.innerHTML = cr.values.map((v, i) => { const col = cols.find((x) => x.name === v.column); return `<div class="mini-row" data-idx="${i}"><select class="crv-col-select" aria-label="Column">${cols.map((x) => `<option ${x.name === v.column ? 'selected' : ''}>${e(x.name)}</option>`).join('')}</select><span>=</span>${col?.decode?.length ? `<select class="crv-val-input" aria-label="Value"><option value=""></option>${col.decode.map((d) => `<option value="${e(d.rawValue)}" ${d.rawValue === v.value ? 'selected' : ''}>${e(d.label)} (${e(d.rawValue)})</option>`).join('')}</select>` : `<input type="text" class="crv-val-input" value="${e(v.value)}" aria-label="Value">`}<button type="button" class="icon-btn remove-btn" aria-label="Remove">${icon('trash', 14)}</button></div>`; }).join('');
      l.querySelectorAll<HTMLElement>('.mini-row').forEach((r) => { const i = +r.dataset.idx!; r.querySelector('.crv-col-select')!.addEventListener('change', (ev) => { cr.values[i].column = (ev.target as HTMLSelectElement).value; renderValues(); refresh(); }); r.querySelector('.crv-val-input')!.addEventListener('change', (ev) => { cr.values[i].value = (ev.target as HTMLInputElement).value; refresh(); }); r.querySelector('.remove-btn')!.addEventListener('click', () => { cr.values.splice(i, 1); renderValues(); refresh(); }); }); };
    renderValues(); const fm = p.querySelector<HTMLElement>('#crFilterMount')!; if (!cr.table) fm.innerHTML = '<p class="hint">Select a table first.</p>'; else renderFilterBuilder(fm, s, [cr.table], cr.filters, (next) => { cr.filters = next; refresh(); });
  }
  function summary(p: HTMLElement): void { p.innerHTML = `<div class="summary-grid"><div><h3>Natural-language requirement</h3><p>${e(cr.naturalLanguageText || '(none provided)')}</p><h3>Query type</h3><p>${cr.queryType}</p><h3>Table</h3><p>${e(cr.table || '(none)')}</p></div><div><h3>Values</h3><p>${cr.values.length ? cr.values.map((v) => e(`${v.column} = ${v.value}`)).join('<br/>') : '(none)'}</p><h3>Filters</h3><p>${cr.filters.length ? cr.filters.map((f, i) => e(`${i ? f.combinator + ' ' : ''}${f.table}.${f.column} ${f.operator} ${f.value}`)).join('<br/>') : '(none)'}</p></div></div>`; }
  draw();
}
// ── Schema (Stored Schemas + Tables & Views) ──
let schTab = 'tables'; let schModule = ''; let schSearch = '';
export function renderSchemaPage(c: HTMLElement): void {
  const { schemas } = services(); const s = active(); if (location.hash.replace(/^#!?\/?/, '').split(/[?/]/)[1] === 'pull') schTab = 'pull'; // deep link: #schema-used/pull
  c.innerHTML = `<div class="page"><h1 class="page-title">${icon('database')} Schema</h1><p class="page-subtitle">Browse the Active Schema and the schemas stored on this device. Changing schemas happens in Settings (password protected).</p><div id="schemaTabs"></div></div>`;
  renderTabs(c.querySelector<HTMLElement>('#schemaTabs')!, [{ id: 'tables', label: 'Tables & Views in Active Schema', render: tables }, { id: 'stored', label: 'Stored Schemas', render: stored }, { id: 'pull', label: 'Pull Schema', render: renderSchemaPullTab }], schTab, {}, (id) => { schTab = id; });
  function tables(p: HTMLElement): void { const modules = Array.from(new Set(s.tables.map((t) => t.module))).sort(); const l = legacyLeftovers(s);
    p.innerHTML = `<div class="form-row-2" data-tour="schema-module-selector"><select id="schemaModuleSelect" aria-label="Module"><option value="">All Modules</option>${modules.map((m) => `<option ${m === schModule ? 'selected' : ''}>${e(m)}</option>`).join('')}</select><div class="picker-search">${icon('search', 14)}<input type="text" class="picker-search-input" id="schemaSearchInput" value="${e(schSearch)}" placeholder="Search tables, columns, descriptions…"></div></div><p class="hint mt">Active Schema <strong>${e(s.name)}</strong> · ${s.tables.length} tables · ${s.tables.reduce((n, t) => n + t.columns.length, 0)} columns${s.migration ? ` · <span class="chip chip-migrated">Migrated from ${e(s.migration.fromFormat)}</span>` : ''}${l.unmappedLabels ? ` · <span class="chip chip-legacy">${l.unmappedLabels} decode label(s) without code</span>` : ''}</p><div class="schema-results" id="tablesReadOnlyList"></div>`;
    const list = () => { const q = schSearch.toLowerCase(); const ts = s.tables.filter((t) => !schModule || t.module === schModule).map((t) => ({ t, cols: t.columns.filter((x) => !q || `${t.name} ${t.description} ${x.name} ${x.description} ${x.alias || ''}`.toLowerCase().includes(q)) })).filter((x) => x.cols.length).slice(0, 120);
      p.querySelector('#tablesReadOnlyList')!.innerHTML = ts.map(({ t, cols }) => `<div class="schema-table-card"><div class="schema-table-head"><h4>${e(t.name)}</h4>${t.objectType === 'VIEW' ? `<span class="chip chip-view">${icon('eye', 11)} VIEW</span>` : ''}<span class="chip">${e(t.module)}</span></div><p class="hint">${e(t.description)}</p><table class="schema-col-table"><thead><tr><th>Column</th><th>Type</th><th>Keys</th><th>Decode</th><th>Description</th></tr></thead><tbody>${cols.map((x) => `<tr><td>${e(x.name)}</td><td>${e(x.type)}${x.length ? `(${x.length})` : ''}</td><td>${x.isPrimaryKey ? '<span class="chip chip-pk">PK</span>' : ''}${x.references ? `<span class="chip chip-fk">FK → ${e(x.references.table)}.${e(x.references.column)}</span>` : ''}${x.unresolvedReference ? `<span class="hint">ref ${e(x.unresolvedReference.table)} (outside schema)</span>` : ''}</td><td>${e((x.decode || []).map((d) => `${d.rawValue}=${d.label}`).join(', '))}${x.unmappedDecodeLabels?.length ? ` <span class="chip chip-legacy">${x.unmappedDecodeLabels.length} without code</span>` : ''}</td><td>${e(x.description)}</td></tr>`).join('')}</tbody></table></div>`).join('') || '<p class="hint">No tables or columns match your search.</p>'; };
    p.querySelector('#schemaModuleSelect')!.addEventListener('change', (ev) => { schModule = (ev.target as HTMLSelectElement).value; list(); });
    p.querySelector('#schemaSearchInput')!.addEventListener('input', (ev) => { schSearch = (ev.target as HTMLInputElement).value; list(); }); list(); }
  function stored(p: HTMLElement): void { const reg = schemas.registry();
    p.innerHTML = `<div class="schema-list">${reg.schemas.map((x) => `<div class="schema-card ${x.id === reg.activeSchemaId ? 'is-active' : ''}" data-schema-row="${e(x.name)}"><div class="schema-card-head"><h3>${e(x.name)}</h3><span class="chip ${x.id === reg.activeSchemaId ? 'chip-active' : 'chip-inactive'}">${x.id === reg.activeSchemaId ? 'Active' : 'Inactive'}</span></div><p class="hint">${x.tables.length} tables · updated ${e(x.updatedAt.slice(0, 10))}${x.migration ? ' · migrated' : ''}</p><div class="row-actions">${x.id !== reg.activeSchemaId ? `<button type="button" class="btn btn-primary btn-sm" data-activate="${e(x.id)}">${icon('check', 14)} Set Active</button>` : ''}<button type="button" class="btn btn-outline btn-sm" data-export="${e(x.id)}">${icon('download', 14)} Export JSON</button></div></div>`).join('')}</div>`;
    p.querySelectorAll<HTMLElement>('[data-activate]').forEach((b) => b.addEventListener('click', () => { schemas.setActive(b.dataset.activate!); store.pushToast('success', `Active Schema: ${schemas.active().name}`); }));
    p.querySelectorAll<HTMLElement>('[data-export]').forEach((b) => b.addEventListener('click', () => { const x = schemas.byId(b.dataset.export!)!; downloadBlob(`${x.name.replace(/\W+/g, '_')}.json`, JSON.stringify(x, null, 2), 'application/json'); })); }
}
// ── Error Rectifier ──
export function renderErrorRectifierPage(c: HTMLElement): void {
  c.innerHTML = `<div class="page"><h1 class="page-title">${icon('bug')} Error Rectifier</h1><p class="page-subtitle">Paste the database error and the SQL that produced it. SQL Assistant explains the error and proposes a corrected query.</p><div class="builder-grid-top" data-tour="error-rectifier-form"><div class="builder-panel"><h2>${icon('alert-triangle', 16)} Database error</h2><textarea id="errInput" rows="4" placeholder="e.g. ORA-00904: &quot;VENDOR_NM&quot;: invalid identifier"></textarea><h2>${icon('code', 16)} SQL that failed</h2><textarea id="errSqlInput" rows="8" spellcheck="false"></textarea><div class="row-actions"><button type="button" class="btn btn-primary" id="errRectifyBtn">${icon('wand', 15)} Rectify</button></div></div><div class="builder-panel"><h2>${icon('check', 16)} Corrected SQL</h2><div id="errResult"><p class="hint">The corrected query and explanation appear here.</p></div></div></div></div>`;
  c.querySelector('#errRectifyBtn')!.addEventListener('click', () => { const sql = (c.querySelector('#errSqlInput') as HTMLTextAreaElement).value; const r = rectify((c.querySelector('#errInput') as HTMLTextAreaElement).value, sql); const m = c.querySelector<HTMLElement>('#errResult')!;
    if (!sql.trim()) { m.innerHTML = '<div class="issue-box mini">Paste the SQL that produced the error.</div>'; return; }
    m.innerHTML = `<pre class="sql-output" id="errRectifiedSql">${e(r.correctedSql)}</pre><div class="explanation-box"><strong>${r.dialect ? `${e(r.dialect)} — ` : ''}What the error means</strong><p>${e(r.explanation)}</p><strong>What changed</strong><ul>${r.whatChanged.map((w) => `<li>${e(w)}</li>`).join('')}</ul></div>`; });
}
// ── About ──
export function renderAboutPage(c: HTMLElement): void {
  const s = active();
  c.innerHTML = `<div class="page" data-tour="about-panel"><h1 class="page-title">${icon('info')} About SQL Assistant</h1><div class="hero-card" style="display:flex;gap:1rem;align-items:center"><span style="width:56px;height:56px;flex:0 0 auto">${logoMarkSvg(56)}</span><div><h1 style="margin:0">SQL Assistant</h1><p class="lead">Version ${e(APP.version)} · Created by Subham Ain</p></div></div>
    <div class="advanced-grid mt"><div class="builder-panel"><h2>${icon('zap', 16)} Engines</h2><ul><li>Offline NLU (${e(NLU_ENGINE_VERSION)}) — primary engine, works without a network</li><li>Optional AI/LLM Model — validated against the Active Schema; the offline result is used if it fails</li><li>No database connection; SQL is never executed</li></ul></div><div class="builder-panel"><h2>${icon('database', 16)} Active Schema</h2><p>${e(s.name)} · ${s.tables.length} tables</p><h2>${icon('history', 16)} Recent versions</h2><ul><li><strong>17.5.1</strong> — a short cross-device administrator message in the navbar (Settings → Synchronization → Admin message): plain text up to 140 characters, published through the existing repository connection, hideable per device, cleared everywhere with one click.</li><li><strong>17.5</strong> — table tick-marks appear immediately; schema-based CASE / DECODE for columns (Manual or From Schema); Schema → Pull Schema with a masked, show/hide passphrase and an encrypted, versioned, transactional cross-device schema synchronization.</li><li><strong>17.4</strong> — Manual Selectors keep their state (no more resets); Admin Query Library; centralized, tiered self-learning from confirmed and successfully executed SQL; admin and learned patterns adapted by the offline NLU; 12-point SQL validation; Explain generated SQL; sub-select filters, RIGHT / FULL JOIN and a description for every option; encrypted vault push with read-back verification; layered AI/LLM architecture with an optional local model.</li><li><strong>17.3.1</strong> — V17.2 UI restored; schema synchronization root-cause fixes (legacy schema migration, storage key, repository path, writer stamp); single-file build that loads from disk, any web server and GitHub Pages.</li><li><strong>17.2</strong> — 3-way merge sync, stale-copy guard, Accept &amp; Learn, table aliases and join paths.</li><li><strong>17.1</strong> — publish gate and per-schema validation.</li><li><strong>17.0</strong> — offline self-training NLU, AI/LLM Model, Push Secret Vault to Repository.</li></ul></div></div></div>`;
}
