import { state, emptyReadOnly } from '../../state/store';
import { services, aiConfig, secrets } from '../context';
import { esc, val, checked, toast, options } from '../dom';
import { generateFromDescription, type OrchestratedResult } from '../../v17/services/queryOrchestrator';
import { buildSelectSQL } from '../../engines/sqlEngine';
import { validateFullReadOnly } from '../../engines/validationEngine';
import { validateSqlAgainstSchema } from '../../engines/sqlSchemaValidator';
import { FILTER_OPERATORS, requiresValue } from '../../engines/filterEngine';
import { advancedOverrides, completeGroupBy, ADVANCED_INPUT_KEYS, type ManualOptionKey } from '../../v17/engines/advancedOptionsResolver';
import { makeId } from '../../utils/id';
import type { Dialect, FilterOperator } from '../../types';
let last: OrchestratedResult | null = null; let baseline = '';
function regen(): void { completeGroupBy(state.readOnly); state.readOnly.generatedSql = buildSelectSQL(state.readOnly, services().schemas.active()); baseline = state.readOnly.generatedSql; }
export function renderReadOnly(root: HTMLElement): void {
  const { schemas, learning } = services(); const s = schemas.active(); const st = state.readOnly;
  st.selectedTables = st.selectedTables.filter((t) => s.tables.some((x) => x.name === t)); // never keep tables from a previous Active Schema
  const cols = st.selectedTables.flatMap((t) => (s.tables.find((x) => x.name === t)?.columns || []).map((c) => ({ t, c }))); const co = cols.map(({ t, c }) => `${t}.${c.name}`);
  const v = st.generatedSql ? validateFullReadOnly(st) : null; const sv = st.generatedSql ? validateSqlAgainstSchema(st.generatedSql, s) : null;
  const man = (k: ManualOptionKey) => (advancedOverrides.isManual(k) ? '<span class="manual-badge">manual</span>' : '');
  root.innerHTML = `<h1>Read Only Query Builder</h1>
  <div class="card"><label for="nlText">Describe What You Need</label><textarea id="nlText" placeholder="e.g. total invoice amount per vendor for approved invoices in the last 30 days, top 10">${esc(st.naturalLanguageText)}</textarea>
  <div class="row"><select id="dialect">${options(['Oracle', 'SQL Server', 'PostgreSQL', 'MySQL', 'Generic'], st.dialect)}</select><button class="primary" id="nlGenerate">Generate SQL</button><button id="resetRo">Reset</button><span class="muted small">Active Schema: <strong>${esc(s.name)}</strong> · Engine: offline NLU${aiConfig.enabled ? ' (AI/LLM Model fallback enabled)' : ''}</span></div>
  ${last ? `<div class="auto-opt" id="autoOptions"><h3>Automatically inferred</h3><ul>${last.requirement.autoOptions.map((o) => `<li class="applied">✓ ${esc(o.description)}</li>`).join('') || '<li class="muted">Nothing inferred.</li>'}</ul>${last.keptManual.length ? `<p class="small">Manual selections kept: ${esc(last.keptManual.join(', '))}</p>` : ''}${last.requirement.schemaGaps.length ? `<div class="issue-box">Not found in the Active Schema: ${esc(last.requirement.schemaGaps.join(', '))}</div>` : ''}${last.requirement.notes.map((n) => `<p class="small muted">${esc(n)}</p>`).join('')}${last.onlineNote ? `<p class="small">${esc(last.onlineNote)}</p>` : ''}</div>` : ''}</div>
  <div class="two"><div class="card"><h2>Manual Selectors</h2><label>Tables</label><select id="tableSelect" multiple size="6" style="width:100%">${s.tables.map((t) => `<option value="${esc(t.name)}"${st.selectedTables.includes(t.name) ? ' selected' : ''}>${esc(t.name)}</option>`).join('')}</select>
  <h3>Columns</h3><div class="scroll" style="max-height:220px"><table class="grid"><tbody>${cols.map(({ t, c }) => { const sel = st.selectedColumns.find((x) => x.table === t && x.column === c.name && !x.manualExpr); const k = `${t}.${c.name}`; return `<tr><td><input type="checkbox" data-col="${esc(k)}"${sel ? ' checked' : ''}></td><td>${esc(k)}</td><td><select data-agg="${esc(k)}">${options(['', 'COUNT', 'SUM', 'AVG', 'MIN', 'MAX'], sel?.aggregate || '')}</select></td></tr>`; }).join('')}</tbody></table></div>
  <h3>Filters</h3>${st.filters.map((f, i) => `<div class="row small"><code>${esc(`${i ? f.combinator + ' ' : ''}${f.table}.${f.column} ${f.operator} ${f.value}`)}</code><button data-rmf="${i}">✕</button></div>`).join('')}
  <div class="row"><select id="fCol">${options(co, null)}</select><select id="fOp">${options(FILTER_OPERATORS, '=')}</select><input id="fVal" placeholder="value" size="10"><select id="fComb">${options(['AND', 'OR'], 'AND')}</select><button id="addFilter">Add</button></div>
  <h3>Sorting</h3>${st.sorts.map((so, i) => `<div class="row small"><code>${esc(`${so.expression || `${so.table}.${so.column}`} ${so.direction}`)}</code><button data-rms="${i}">✕</button></div>`).join('')}
  <div class="row"><select id="sCol">${options(co, null)}</select><select id="sDir">${options(['ASC', 'DESC'], 'ASC')}</select><button id="addSort">Add</button></div></div>
  <div class="card"><h2>Advanced Options</h2><p class="small muted">Inferred automatically; values you change are marked <span class="manual-badge">manual</span> and take precedence.</p>
  <label><input type="checkbox" id="advDistinct"${st.advanced.distinct ? ' checked' : ''}> DISTINCT${man('distinct')}</label><label for="advGroupBy">GROUP BY${man('groupBy')}</label><input id="advGroupBy" style="width:100%" value="${esc(st.advanced.groupByColumns.join(', '))}">
  <label for="advHaving">HAVING${man('having')}</label><input id="advHaving" style="width:100%" value="${esc(st.advanced.havingClause)}">
  <div class="row"><div><label for="advLimit">Limit${man('limit')}</label><input id="advLimit" type="number" min="1" value="${st.advanced.limit ?? ''}" size="6"></div><div><label for="advJoinType">Join type${man('joinType')}</label><select id="advJoinType">${options(['INNER JOIN', 'LEFT JOIN'], st.advanced.joinType || 'INNER JOIN')}</select></div></div>
  <label><input type="checkbox" id="advTableAliases"${st.advanced.tableAliases ? ' checked' : ''}> Table aliases${man('tableAliases')}</label><div class="row" style="margin-top:8px"><button id="applyAdvanced">Apply</button><button id="releaseManual">Return all options to automatic</button></div></div></div>
  <div class="card"><div class="row"><h2 class="grow" style="margin:0">Generated SQL</h2><button id="copySql">Copy</button><button class="primary" id="acceptSql">Accept (teach the model)</button></div><textarea id="sqlOut" style="min-height:140px;font-family:Consolas,monospace">${esc(st.generatedSql)}</textarea>
  ${v ? `<div class="issue-box ${v.valid && sv?.valid ? 'ok' : 'error'}" id="sqlValidation">${v.valid && sv?.valid ? 'SQL is read-only and valid against the Active Schema.' : `<ul>${[...v.issues.map((i) => i.message), ...(sv?.warnings || [])].map((m) => `<li>${esc(m)}</li>`).join('')}</ul>`}</div>` : ''}</div>`;
  const re = () => renderReadOnly(root); const q = (x: string) => root.querySelector(x)!;
  q('#nlGenerate').addEventListener('click', async () => { const text = val('nlText').trim(); if (!text) { toast('warning', 'Describe what you need first.'); return; } st.dialect = val('dialect') as Dialect; try { last = await generateFromDescription(text, st, s, st.dialect, learning, aiConfig.enabled ? { config: aiConfig, apiKey: secrets.aiApiKey } : null); state.readOnly = last.state; baseline = last.state.generatedSql; re(); } catch (e) { toast('error', `Offline model unable to process request: ${(e as Error).message}`); } });
  q('#resetRo').addEventListener('click', () => { state.readOnly = emptyReadOnly(); advancedOverrides.clear(); last = null; re(); });
  q('#dialect').addEventListener('change', () => { st.dialect = val('dialect') as Dialect; if (st.selectedTables.length) regen(); re(); });
  q('#tableSelect').addEventListener('change', (e) => { st.selectedTables = Array.from((e.target as HTMLSelectElement).selectedOptions).map((o) => o.value); st.selectedColumns = st.selectedColumns.filter((c) => st.selectedTables.includes(c.table)); regen(); re(); });
  root.querySelectorAll<HTMLInputElement>('[data-col]').forEach((cb) => cb.addEventListener('change', () => { advancedOverrides.mark('columns'); const [t, c] = cb.dataset.col!.split('.'); if (cb.checked) st.selectedColumns.push({ id: makeId('col'), table: t, column: c, alias: '', useDecode: false, aggregate: null }); else st.selectedColumns = st.selectedColumns.filter((x) => !(x.table === t && x.column === c)); regen(); re(); }));
  root.querySelectorAll<HTMLSelectElement>('[data-agg]').forEach((el) => el.addEventListener('change', () => { const [t, c] = el.dataset.agg!.split('.'); const sp = st.selectedColumns.find((x) => x.table === t && x.column === c); if (!sp) { toast('info', 'Tick the column first.'); return; } sp.aggregate = (el.value || null) as typeof sp.aggregate; regen(); re(); }));
  q('#addFilter').addEventListener('click', () => { const [t, c] = val('fCol').split('.'); const op = val('fOp') as FilterOperator; if (!t) return; if (requiresValue(op) && !val('fVal').trim()) { toast('warning', 'Enter a filter value.'); return; } st.filters.push({ id: makeId('f'), table: t, column: c, operator: op, value: val('fVal').trim(), combinator: val('fComb') as 'AND' }); regen(); re(); });
  root.querySelectorAll<HTMLElement>('[data-rmf]').forEach((b) => b.addEventListener('click', () => { st.filters.splice(+b.dataset.rmf!, 1); regen(); re(); }));
  q('#addSort').addEventListener('click', () => { const [t, c] = val('sCol').split('.'); if (!t) return; advancedOverrides.mark('sorts'); st.sorts.push({ id: makeId('s'), table: t, column: c, direction: val('sDir') as 'ASC' }); regen(); re(); });
  root.querySelectorAll<HTMLElement>('[data-rms]').forEach((b) => b.addEventListener('click', () => { st.sorts.splice(+b.dataset.rms!, 1); regen(); re(); }));
  Object.entries(ADVANCED_INPUT_KEYS).forEach(([id, k]) => root.querySelector(`#${id}`)?.addEventListener('change', () => advancedOverrides.mark(k)));
  q('#applyAdvanced').addEventListener('click', () => { st.advanced.distinct = checked('advDistinct'); st.advanced.groupByColumns = val('advGroupBy').split(',').map((x) => x.trim()).filter(Boolean); st.advanced.havingClause = val('advHaving').trim(); const l = parseInt(val('advLimit'), 10); st.advanced.limit = l > 0 ? l : null; st.advanced.tableAliases = checked('advTableAliases'); st.advanced.joinType = val('advJoinType') as 'INNER JOIN'; regen(); re(); });
  q('#releaseManual').addEventListener('click', () => { advancedOverrides.clear(); re(); });
  q('#sqlOut').addEventListener('change', () => { st.generatedSql = val('sqlOut'); });
  q('#copySql').addEventListener('click', async () => { try { await navigator.clipboard.writeText(val('sqlOut')); toast('success', 'SQL copied.'); } catch { toast('warning', 'Clipboard is not available — copy the SQL manually.'); } });
  q('#acceptSql').addEventListener('click', () => { const sql = val('sqlOut'); const text = st.naturalLanguageText || val('nlText'); const chk = validateSqlAgainstSchema(sql, s); if (!chk.valid) { toast('error', `Not learned — ${chk.warnings.join(' ')}`); return; } if (!text.trim()) { toast('info', 'Accepted.'); return; }
    if (!learning.confirm(text, s, sql, sql !== baseline ? sql : null)) learning.record({ schema: s, accepted: true, requestText: text, generatedSql: baseline, modifiedSql: sql !== baseline ? sql : null, finalSql: sql, tables: st.selectedTables, columns: st.selectedColumns.filter((c) => !c.manualExpr).map((c) => ({ table: c.table, column: c.column })), sorts: [], limit: st.advanced.limit });
    toast('success', 'Accepted — this pattern will help future requests on this schema.'); });
}
