/** Read Only Query Builder (V17.2 layout): Describe What You Need + Generated SQL, then Manual Selectors (Tables & Columns / Advanced Options / Selected / Described Requirements). */
import { icon } from '../components/icons'; import { renderTablePicker } from '../components/tablePicker'; import { renderColumnPicker } from '../components/columnPicker'; import { renderFilterBuilder } from '../components/filterBuilder';
import { renderSqlCodeBlock } from '../components/sqlCodeBlock'; import { renderTabs } from '../components/tabs'; import { openManualCaseBuilder, openManualDecodeBuilder } from '../components/manualExprBuilder'; import { openModal } from '../components/modal';
import { store } from '../state'; import { services, aiConfig, secrets } from '../context'; import { e, copyText } from '../dom';
import { generateFromDescription } from '../../v17/services/queryOrchestrator'; import { buildSelect } from '../../engines/sqlEngine'; import { computeAutoJoinPlan } from '../../engines/joinAutoEngine'; import { withFkRelationships } from '../../v17/engines/joinGraph';
import { validateFullReadOnly } from '../../engines/validationEngine'; import { validateSqlAgainstSchema } from '../../engines/sqlSchemaValidator'; import { optimizeSuggestions } from '../../engines/optimizeEngine';
import { advancedOverrides, completeGroupBy, type ManualOptionKey } from '../../v17/engines/advancedOptionsResolver'; import { makeId } from '../../utils/id';
import type { Dialect, ReadOnlyQueryState, SchemaModel, JoinType } from '../../types';
const DIALECTS: Dialect[] = ['SQL Server', 'Oracle', 'PostgreSQL', 'MySQL', 'Generic'];
export function emptyReadOnly(d: Dialect = 'Oracle'): ReadOnlyQueryState { return { dialect: d, naturalLanguageText: '', selectedTables: [], selectedColumns: [], filters: [], sorts: [], advanced: { distinct: false, groupByColumns: [], havingClause: '', limit: null, viewName: '', tableAliases: false, joinType: 'INNER JOIN', recursive: false, ctes: [] }, generatedSql: '-- Select at least one table (or describe your requirement above) to generate SQL.', joinPathChoices: {} }; }
let st: ReadOnlyQueryState = emptyReadOnly(); let activeTab = 'tables-columns'; let notesHtml = ''; let lastSchemaId = ''; let baseline = ''; let autoInfo: string[] = []; let warnings: string[] = [];
const schema = (): SchemaModel => services().schemas.active();
function regenerate(): void { const s = schema(); const valid = new Set(s.tables.map((t) => t.name)); const has = (t: string, c: string) => s.tables.find((x) => x.name === t)?.columns.some((x) => x.name === c);
  st.selectedTables = st.selectedTables.filter((t) => valid.has(t)); st.selectedColumns = st.selectedColumns.filter((c) => c.manualExpr || has(c.table, c.column)); st.filters = st.filters.filter((f) => has(f.table, f.column)); st.sorts = st.sorts.filter((x) => x.expression || has(x.table, x.column));
  const inScope = (g: string) => { const m = g.match(/^([A-Za-z_][\w$#]*)\./); return !m || st.selectedTables.includes(m[1]); }; st.advanced.groupByColumns = st.advanced.groupByColumns.filter(inScope);
  completeGroupBy(st); const b = buildSelect(st, s); st.generatedSql = b.sql; warnings = b.warnings; baseline = st.generatedSql; }
const mark = (k: ManualOptionKey) => advancedOverrides.mark(k);
export function resetReadOnlyForSchemaChange(): void { const id = schema().id; if (lastSchemaId && lastSchemaId !== id) { st = emptyReadOnly(st.dialect); notesHtml = ''; advancedOverrides.clear(); } lastSchemaId = id; }
export function renderReadOnlyPage(container: HTMLElement): void {
  resetReadOnlyForSchemaChange();
  const issuesHtml = () => { const v = validateFullReadOnly(st); const sv = validateSqlAgainstSchema(st.generatedSql, schema()); const err = [...v.issues.filter((i) => i.severity === 'error').map((i) => i.message), ...sv.warnings]; const warn = [...v.issues.filter((i) => i.severity === 'warning').map((i) => i.message), ...warnings];
    return `${err.length ? `<div class="issue-box">${icon('alert-triangle', 15)}<ul>${err.map((m) => `<li>${e(m)}</li>`).join('')}</ul></div>` : ''}${warn.length ? `<div class="issue-box warn">${icon('alert-triangle', 14)}<ul>${warn.map((m) => `<li>${e(m)}</li>`).join('')}</ul></div>` : ''}`; };
  function draw(): void {
    container.innerHTML = `<div class="page"><h1 class="page-title">${icon('table')} Read Only Query Builder</h1><p class="page-subtitle">Generates validated SELECT / WITH statements only. Natural Language and Manual Selectors merge together — use either one, or both.</p>
    <div class="builder-grid-top"><div class="builder-panel" data-tour="describe-card"><h2>${icon('sparkles', 16)} Describe What You Need (optional)</h2><textarea id="nlDesc" rows="5" placeholder="e.g. Top 5 vendors by total invoice amount for approved invoices this year">${e(st.naturalLanguageText)}</textarea><label class="inline-label">SQL dialect<select id="dialectSelect">${DIALECTS.map((d) => `<option ${d === st.dialect ? 'selected' : ''}>${d}</option>`).join('')}</select></label><div class="row-actions"><button type="button" id="nlBuildBtn" class="btn btn-primary">${icon('zap', 15)} Build from Description</button></div><div id="nlNotes">${notesHtml}</div></div>
    <div class="builder-panel"><h2>${icon('code', 16)} Generated SQL</h2><div id="sqlBlockMount"></div></div></div>
    <div class="builder-panel manual-selectors-panel"><h2>${icon('sliders', 16)} Manual Selectors</h2><div id="tabsMount"></div><div class="row-actions build-query-row"><button type="button" id="buildQueryBtn" class="btn btn-primary">${icon('zap', 15)} Build Query</button><span class="hint">Regenerates the SQL from your current manual selections (this also happens automatically as you make changes).</span></div></div><div id="roIssues">${issuesHtml()}</div></div>`;
    container.querySelector('#nlDesc')!.addEventListener('input', (ev) => { st.naturalLanguageText = (ev.target as HTMLTextAreaElement).value; });
    container.querySelector('#dialectSelect')!.addEventListener('change', (ev) => { st.dialect = (ev.target as HTMLSelectElement).value as Dialect; regenerate(); refresh(); });
    container.querySelector('#nlBuildBtn')!.addEventListener('click', () => { void runNl(); });
    container.querySelector('#buildQueryBtn')!.addEventListener('click', () => { regenerate(); store.pushToast('info', 'Query rebuilt from manual selections.'); refresh(); });
    renderSql(); renderTabsSection();
  }
  function refresh(): void { renderSql(); const m = container.querySelector('#roIssues'); if (m) m.innerHTML = issuesHtml(); }
  async function runNl(): Promise<void> {
    const btn = container.querySelector<HTMLButtonElement>('#nlBuildBtn')!; btn.disabled = true; btn.innerHTML = `${icon('zap', 15)} Processing…`;
    try {
      const s = schema(); const text = st.naturalLanguageText.trim(); if (!text) { regenerate(); draw(); return; }
      const r = await generateFromDescription(text, st, s, st.dialect, services().learning, aiConfig.enabled ? { config: aiConfig, apiKey: secrets.aiApiKey } : null);
      st = { ...r.state, joinPathChoices: r.state.joinPathChoices || {} }; warnings = r.build.warnings; baseline = st.generatedSql; autoInfo = r.requirement.autoOptions.map((o) => o.description);
      const badge = r.engine === 'online' ? `<span class="engine-badge engine-online">${icon('bot', 13)} Offline NLU + AI/LLM Model</span>` : `<span class="engine-badge engine-offline">${icon('wifi-off', 13)} Offline NLU${aiConfig.enabled ? ' — AI/LLM not needed' : ''}</span>`;
      const gaps = r.requirement.unresolvedTerms.length ? `<div class="issue-box mini">${icon('alert-triangle', 14)} Not found in the Active Schema (not added to the SQL): ${e(r.requirement.unresolvedTerms.join(', '))}</div>` : '';
      notesHtml = `<div class="notes-box"><div style="width:100%">${badge}<div class="schema-audit-line">${icon('database', 12)} Active Schema used: ${e(s.name)} (v${e(String(s.version))})</div>${autoInfo.length ? `<strong>Query Plan</strong><ul class="plan-list">${autoInfo.map((p) => `<li>${e(p)}</li>`).join('')}</ul>` : ''}${r.keptManual.length ? `<div class="hint">${icon('sliders', 12)} Kept your manual settings: ${e(r.keptManual.join(', '))}.</div>` : ''}${r.requirement.notes.length ? `<strong>Notes</strong><ul>${r.requirement.notes.map((n) => `<li>${e(n)}</li>`).join('')}</ul>` : ''}${r.onlineNote ? `<div class="hint">${icon('bot', 12)} AI/LLM Model: ${e(r.onlineNote)}</div>` : ''}</div></div>${gaps}`;
    } catch (err) { notesHtml = `<div class="issue-box mini">${icon('alert-triangle', 14)} Offline model unable to process request — ${e((err as Error)?.message || 'internal error')}. Manual Selectors still work.</div>`; }
    draw();
  }
  function renderSql(): void {
    const m = container.querySelector<HTMLElement>('#sqlBlockMount'); if (!m) return;
    renderSqlCodeBlock(m, st.generatedSql, {
      onCopy: () => { void copyText(st.generatedSql); store.pushToast('success', 'SQL copied to clipboard.'); },
      onClear: () => { st = emptyReadOnly(st.dialect); advancedOverrides.clear(); notesHtml = ''; store.pushToast('info', 'Query cleared.'); draw(); },
      onValidate: () => { const r = validateFullReadOnly(st); const sv = validateSqlAgainstSchema(st.generatedSql, schema()); const v = m.querySelector('#validationMount'); if (v) v.innerHTML = r.valid && sv.valid ? `<div class="issue-box ok mini">${icon('check', 14)} SQL passed validation — read-only, structurally sound and valid against the Active Schema.</div>` : `<div class="issue-box mini">${icon('alert-triangle', 14)}<ul>${[...r.issues.map((i) => `[${i.severity}] ${i.message}`), ...sv.warnings].map((x) => `<li>${e(x)}</li>`).join('')}</ul></div>`; },
      onRegenerate: () => { regenerate(); store.pushToast('info', 'SQL regenerated from current selections.'); refresh(); }
    }, [{ id: 'btnAcceptLearn', label: 'Accept & Learn', iconName: 'check', onClick: acceptLearn }, { id: 'btnOptimizeToggle', label: 'Optimize', iconName: 'wand', onClick: () => { const o = m.querySelector<HTMLElement>('#optimizeMount')!; if (o.innerHTML.trim()) { o.innerHTML = ''; return; } o.innerHTML = `<div class="tips-box">${icon('wand', 15)}<ul>${optimizeSuggestions(st).map((t) => `<li>${e(t)}</li>`).join('')}</ul></div>`; } }]);
  }
  function acceptLearn(): void {
    const s = schema(); const md = openModal(`${icon('check', 18)} Accept &amp; Learn`, `<p class="hint">Review or adjust the SQL, then accept it. Accepted queries are validated against the Active Schema <strong>${e(s.name)}</strong> and become confirmed learned knowledge for similar descriptions.</p><label class="block-label">Final SQL<textarea id="v17AcceptSql" rows="12" spellcheck="false" style="font-family:'Cascadia Code',Consolas,monospace;font-size:12.5px">${e(st.generatedSql)}</textarea></label><div id="v17AcceptErrors"></div><div class="modal-actions"><button type="button" class="btn btn-ghost" id="v17AcceptCancel">Cancel</button><button type="button" class="btn btn-primary" id="v17AcceptOk">${icon('check', 14)} Accept &amp; Learn</button></div>`, { wide: true, closeOnBackdrop: false });
    md.element.querySelector('#v17AcceptCancel')!.addEventListener('click', () => md.close());
    md.element.querySelector('#v17AcceptOk')!.addEventListener('click', () => { const sql = (md.element.querySelector('#v17AcceptSql') as HTMLTextAreaElement).value.trim(); const chk = validateSqlAgainstSchema(sql, s); const ro = validateFullReadOnly({ ...st, generatedSql: sql });
      if (!chk.valid || !ro.valid || !/\bSELECT\b/i.test(sql)) { md.element.querySelector('#v17AcceptErrors')!.innerHTML = `<div class="issue-box mini">${icon('alert-triangle', 14)} This SQL cannot be accepted:<ul>${[...chk.warnings, ...ro.issues.filter((i) => i.severity === 'error').map((i) => i.message)].map((x) => `<li>${e(x)}</li>`).join('') || '<li>No SELECT statement found.</li>'}</ul></div>`; return; }
      const text = st.naturalLanguageText.trim(); const { learning } = services(); const modified = sql.replace(/\s+/g, ' ') !== baseline.replace(/\s+/g, ' ');
      const ok = text ? (learning.confirm(text, s, sql, modified ? sql : null) || learning.record({ schema: s, accepted: true, requestText: text, generatedSql: baseline, modifiedSql: modified ? sql : null, finalSql: sql, tables: st.selectedTables, columns: st.selectedColumns.filter((c) => !c.manualExpr).map((c) => ({ table: c.table, column: c.column })), sorts: st.sorts.filter((x) => !x.expression).map((x) => ({ table: x.table, column: x.column, direction: x.direction })), limit: st.advanced.limit })) : false;
      if (modified) st.generatedSql = sql; md.close(); renderSql();
      store.pushToast(ok ? 'success' : 'info', ok ? (modified ? 'Modified SQL accepted and learned as confirmed knowledge.' : 'SQL accepted and learned as confirmed knowledge.') : text ? 'Accepted. (Not learned: the request appears to contain a credential.)' : 'SQL accepted. (Nothing was learned because there is no description to learn it against.)'); });
  }
  function renderTabsSection(): void { const m = container.querySelector<HTMLElement>('#tabsMount'); if (!m) return; const s = schema();
    renderTabs(m, [{ id: 'tables-columns', label: 'Tables & Columns', render: (p) => tablesTab(p, s) }, { id: 'advanced', label: 'Advanced Options', render: (p) => advancedTab(p, s) }, { id: 'summary', label: 'Selected / Described Requirements', render: (p) => summaryTab(p) }], activeTab, { 'tables-columns': 'tab-tables-columns', advanced: 'tab-advanced', summary: 'tab-summary' }, (id) => { activeTab = id; }); }
  function tablesTab(panel: HTMLElement, s: SchemaModel): void {
    panel.innerHTML = `<div class="tc-grid"><div class="tc-col"><h3>${icon('list', 15)} Select Tables</h3><div id="tablePickerMount"></div></div><div class="tc-col"><h3>${icon('columns', 15)} Select Columns (Alias/DECODE appear once selected)</h3><div id="columnPickerMount"></div></div><div class="tc-col"><h3>${icon('filter', 15)} Filters</h3><div id="filterBuilderMount"></div></div></div>`;
    renderTablePicker(panel.querySelector<HTMLElement>('#tablePickerMount')!, s, st.selectedTables, (next) => { st.selectedTables = next; regenerate(); tablesTab(panel, s); refresh(); });
    renderColumnPicker(panel.querySelector<HTMLElement>('#columnPickerMount')!, s, st.selectedTables, st.selectedColumns, { onChange: (next) => { mark('columns'); st.selectedColumns = next; regenerate(); refresh(); }, onRequestManualDecodeForColumn: (t, c, specId) => openManualDecodeBuilder(st.dialect, (spec) => { st.selectedColumns = st.selectedColumns.map((x) => (x.id === specId ? spec : x)); regenerate(); refresh(); tablesTab(panel, s); }, { table: t, column: c.name }, specId) });
    renderFilterBuilder(panel.querySelector<HTMLElement>('#filterBuilderMount')!, s, st.selectedTables, st.filters, (next) => { st.filters = next; regenerate(); refresh(); });
  }
  function advancedTab(panel: HTMLElement, s: SchemaModel): void {
    const a = st.advanced; const badge = (k: ManualOptionKey) => (advancedOverrides.isManual(k) ? ' <span class="chip chip-inactive" style="padding:.05rem .4rem;font-size:10.5px">manual</span>' : '');
    panel.innerHTML = `<div class="notes-box" data-v17-auto-options><div style="width:100%"><div class="hint">${icon('sparkles', 13)} Filtering, conditions, date filtering, joins, aggregation, grouping, sorting, DISTINCT, aliases and result limits are detected automatically from <strong>Describe What You Need</strong>. Changing any option below takes manual control of it — manual settings are never overwritten.</div>${autoInfo.length ? `<div class="tiny-label mt"><strong>Applied automatically</strong></div><div class="chip-row">${autoInfo.map((x) => `<span class="chip">${icon('zap', 11)} ${e(x)}</span>`).join('')}</div>` : ''}${advancedOverrides.list().length ? `<div class="tiny-label mt"><strong>Under manual control</strong></div><div class="chip-row">${advancedOverrides.list().map((k) => `<span class="chip">${icon('sliders', 11)} ${e(k)}</span>`).join('')}</div><button type="button" class="btn-link mt" id="releaseManualBtn">Return all options to automatic</button>` : ''}</div></div>
    <div class="advanced-grid mt"><div><label class="inline-check"><input type="checkbox" id="advDistinct" ${a.distinct ? 'checked' : ''}/> DISTINCT${badge('distinct')}</label><label class="block-label">GROUP BY columns (comma separated)${badge('groupBy')}<input type="text" id="advGroupBy" value="${e(a.groupByColumns.join(', '))}" placeholder="TABLE.COLUMN, …"/></label><label class="block-label">HAVING clause${badge('having')}<input type="text" id="advHaving" value="${e(a.havingClause)}" placeholder="COUNT(TABLE.ID) > 1"/></label><label class="block-label">LIMIT${badge('limit')}<input type="number" id="advLimit" min="1" value="${a.limit ?? ''}"/></label><label class="inline-check"><input type="checkbox" id="advRecursive" ${a.recursive ? 'checked' : ''}/> Recursive (WITH RECURSIVE)</label><label class="inline-check"><input type="checkbox" id="advTableAliases" ${a.tableAliases ? 'checked' : ''}/> Use table aliases (e.g. INVOICE_HEADER ih)${badge('tableAliases')}</label><label class="block-label">Join type for automatic joins${badge('joinType')}<select id="advJoinType"><option value="INNER JOIN" ${a.joinType !== 'LEFT JOIN' ? 'selected' : ''}>INNER JOIN (matching rows only)</option><option value="LEFT JOIN" ${a.joinType === 'LEFT JOIN' ? 'selected' : ''}>LEFT JOIN (keep rows without a match)</option></select></label>
      <h4 class="mt">${icon('route', 14)} Join paths</h4><div id="joinPathList"></div><h4 class="mt">${icon('sort-asc', 14)} ORDER BY${badge('sorts')}</h4><div id="sortList"></div></div>
      <div><h4>CTEs</h4><div id="cteList" class="filter-rows"></div><button type="button" id="addCteBtn" class="btn btn-outline btn-sm">${icon('plus', 14)} Add CTE</button><h4 class="mt">Manual CASE / DECODE Columns</h4><div id="manualColsList"></div><div class="row-actions"><button type="button" id="addManualCaseBtn" class="btn btn-outline btn-sm">${icon('code', 14)} Add Manual CASE</button><button type="button" id="addManualDecodeBtn" class="btn btn-outline btn-sm">${icon('sparkles', 14)} Add Manual DECODE</button></div></div></div>`;
    const q = <T extends HTMLElement>(id: string) => panel.querySelector<T>(`#${id}`)!; const re = () => advancedTab(panel, s);
    q('releaseManualBtn')?.addEventListener('click', () => { advancedOverrides.clear(); re(); });
    q('advDistinct').addEventListener('change', (ev) => { mark('distinct'); st.advanced.distinct = (ev.target as HTMLInputElement).checked; regenerate(); refresh(); re(); });
    q('advGroupBy').addEventListener('input', (ev) => { mark('groupBy'); st.advanced.groupByColumns = (ev.target as HTMLInputElement).value.split(',').map((v) => v.trim()).filter(Boolean); regenerate(); refresh(); });
    q('advHaving').addEventListener('input', (ev) => { mark('having'); st.advanced.havingClause = (ev.target as HTMLInputElement).value; regenerate(); refresh(); });
    q('advLimit').addEventListener('input', (ev) => { mark('limit'); const v = parseInt((ev.target as HTMLInputElement).value, 10); st.advanced.limit = v > 0 ? v : null; regenerate(); refresh(); });
    q('advRecursive').addEventListener('change', (ev) => { st.advanced.recursive = (ev.target as HTMLInputElement).checked; regenerate(); refresh(); });
    q('advTableAliases').addEventListener('change', (ev) => { mark('tableAliases'); st.advanced.tableAliases = (ev.target as HTMLInputElement).checked; regenerate(); refresh(); re(); });
    q('advJoinType').addEventListener('change', (ev) => { mark('joinType'); st.advanced.joinType = (ev.target as HTMLSelectElement).value as JoinType; regenerate(); refresh(); re(); });
    const jl = q('joinPathList');
    if (st.selectedTables.length < 2) jl.innerHTML = '<p class="hint">Select two or more tables to see how they are joined.</p>';
    else { const plan = computeAutoJoinPlan(withFkRelationships(s), st.selectedTables[0], st.selectedTables.slice(1), st.joinPathChoices);
      jl.innerHTML = `${plan.resolutions.map((r) => `<div class="mini-row" data-pair="${e(r.pairKey)}"><span><code>${e(r.tableA)}</code> ↔ <code>${e(r.tableB)}</code></span>${r.options.length > 1 ? `<select class="join-path-select" aria-label="Join path"><option value="">— choose a join path —</option>${r.options.map((o) => `<option value="${e(o.id)}" ${o.id === r.chosenOptionId ? 'selected' : ''}>${e(o.label)}</option>`).join('')}</select>` : `<span class="hint">${e(r.options[0].label)}</span>`}</div>`).join('')}${plan.unresolvedWarnings.map((w) => `<div class="issue-box warn mini">${e(w)}</div>`).join('')}`;
      jl.querySelectorAll<HTMLSelectElement>('.join-path-select').forEach((sel) => sel.addEventListener('change', () => { const key = (sel.closest('[data-pair]') as HTMLElement).dataset.pair!; if (sel.value) st.joinPathChoices[key] = sel.value; else delete st.joinPathChoices[key]; regenerate(); refresh(); re(); })); }
    const cols = st.selectedTables.flatMap((t) => (s.tables.find((x) => x.name === t)?.columns || []).map((c) => `${t}.${c.name}`));
    q('sortList').innerHTML = `${st.sorts.map((so, i) => `<div class="mini-row" data-idx="${i}">${so.expression ? `<code>${e(so.expression)}</code>` : `<select class="sort-col" aria-label="Sort column">${cols.map((c) => `<option ${c === `${so.table}.${so.column}` ? 'selected' : ''}>${e(c)}</option>`).join('')}</select>`}<select class="sort-dir" aria-label="Direction"><option ${so.direction === 'ASC' ? 'selected' : ''}>ASC</option><option ${so.direction === 'DESC' ? 'selected' : ''}>DESC</option></select><button type="button" class="icon-btn remove-sort" aria-label="Remove sort">${icon('trash', 14)}</button></div>`).join('')}<button type="button" id="addSortBtn" class="btn btn-outline btn-sm" ${cols.length ? '' : 'disabled'}>${icon('plus', 14)} Add sort</button>`;
    q('sortList').querySelectorAll<HTMLElement>('.mini-row').forEach((r) => { const i = +r.dataset.idx!; r.querySelector('.sort-col')?.addEventListener('change', (ev) => { const [t, c] = (ev.target as HTMLSelectElement).value.split('.'); st.sorts[i] = { ...st.sorts[i], table: t, column: c }; mark('sorts'); regenerate(); refresh(); }); r.querySelector('.sort-dir')!.addEventListener('change', (ev) => { st.sorts[i].direction = (ev.target as HTMLSelectElement).value as 'ASC' | 'DESC'; mark('sorts'); regenerate(); refresh(); }); r.querySelector('.remove-sort')!.addEventListener('click', () => { st.sorts.splice(i, 1); mark('sorts'); regenerate(); refresh(); re(); }); });
    q('addSortBtn')?.addEventListener('click', () => { const [t, c] = cols[0].split('.'); st.sorts.push({ id: makeId('sort'), table: t, column: c, direction: 'ASC' }); mark('sorts'); regenerate(); refresh(); re(); });
    const cl = q('cteList'); cl.innerHTML = st.advanced.ctes.map((c, i) => `<div class="cte-row" data-idx="${i}"><input type="text" class="cte-name-input" value="${e(c.name)}" aria-label="CTE name"/><textarea class="cte-body-input" rows="3" aria-label="CTE body" placeholder="SELECT …">${e(c.body)}</textarea><button type="button" class="icon-btn remove-cte-btn" aria-label="Remove CTE">${icon('trash', 14)}</button></div>`).join('');
    cl.querySelectorAll<HTMLElement>('.cte-row').forEach((r) => { const i = +r.dataset.idx!; r.querySelector('.cte-name-input')!.addEventListener('change', (ev) => { st.advanced.ctes[i].name = (ev.target as HTMLInputElement).value; regenerate(); refresh(); }); r.querySelector('.cte-body-input')!.addEventListener('change', (ev) => { st.advanced.ctes[i].body = (ev.target as HTMLTextAreaElement).value; regenerate(); refresh(); }); r.querySelector('.remove-cte-btn')!.addEventListener('click', () => { st.advanced.ctes.splice(i, 1); regenerate(); refresh(); re(); }); });
    q('addCteBtn').addEventListener('click', () => { st.advanced.ctes.push({ id: makeId('cte'), name: `cte_${st.advanced.ctes.length + 1}`, body: '' }); re(); });
    const manual = st.selectedColumns.filter((c) => c.manualExpr && (c.displayMode !== 'manual-decode' || !st.selectedTables.includes(c.table)));
    q('manualColsList').innerHTML = manual.length ? manual.map((c) => `<div class="mini-row"><code>${e(c.alias)}</code><button type="button" class="icon-btn remove-manual-col" data-id="${e(c.id)}" aria-label="Remove">${icon('trash', 14)}</button></div>`).join('') : '<p class="hint">No custom CASE/DECODE columns added yet.</p>';
    q('manualColsList').querySelectorAll<HTMLElement>('.remove-manual-col').forEach((b) => b.addEventListener('click', () => { st.selectedColumns = st.selectedColumns.filter((c) => c.id !== b.dataset.id); regenerate(); refresh(); re(); }));
    q('addManualCaseBtn').addEventListener('click', () => openManualCaseBuilder((spec) => { st.selectedColumns.push(spec); regenerate(); refresh(); re(); store.pushToast('success', `Manual CASE column "${spec.alias}" added.`); }));
    q('addManualDecodeBtn').addEventListener('click', () => openManualDecodeBuilder(st.dialect, (spec) => { st.selectedColumns.push(spec); regenerate(); refresh(); re(); store.pushToast('success', `Manual DECODE column "${spec.alias}" added.`); }));
  }
  function summaryTab(panel: HTMLElement): void { const a = st.advanced;
    panel.innerHTML = `<div class="summary-grid"><div><h3>Natural-language requirement</h3><p>${e(st.naturalLanguageText || '(none provided)')}</p><h3>Selected tables</h3><p>${e(st.selectedTables.join(', ') || '(none)')}</p><h3>Selected columns</h3><p>${st.selectedColumns.length ? st.selectedColumns.map((c) => e(c.manualExpr ? `Expression: ${c.alias}` : c.aggregate ? `${c.aggregate}(${c.table}.${c.column})${c.alias ? ` AS ${c.alias}` : ''}` : `${c.table}.${c.column}${c.alias ? ` AS ${c.alias}` : ''}${c.useDecode ? ' (schema decode)' : ''}`)).join('<br/>') : '(none — SELECT * will be used)'}</p><h3>Filters</h3><p>${st.filters.length ? st.filters.map((f, i) => e(`${i ? f.combinator + ' ' : ''}${f.table}.${f.column} ${f.operator} ${f.value}${f.value2 ? ' AND ' + f.value2 : ''}`)).join('<br/>') : '(none)'}</p></div><div><h3>Advanced options</h3><ul><li>DISTINCT: ${a.distinct ? 'Yes' : 'No'}</li><li>Sort: ${e(st.sorts.length ? st.sorts.map((x) => `${x.expression || `${x.table}.${x.column}`} ${x.direction}`).join(', ') : '(none)')}</li><li>Group by: ${e(a.groupByColumns.join(', ') || '(none)')}</li><li>Having: ${e(a.havingClause || '(none)')}</li><li>Limit: ${a.limit ?? '(none)'}</li><li>CTEs: ${a.ctes.length}</li><li>Table aliases: ${a.tableAliases ? 'Yes' : 'No'}</li><li>Join type: ${e(a.joinType)}</li><li>Manual overrides: ${e(advancedOverrides.list().join(', ') || 'none')}</li></ul></div></div>`; }
  if (st.selectedTables.length) regenerate();
  draw();
}
