/**
 * Read Only Query Builder (V17.2 layout, V17.3.1 baseline): Describe What You Need + Generated SQL, then Manual Selectors
 * (Tables & Columns / Advanced Options / Selected / Described Requirements).
 * V17.4: Manual Selector state no longer resets — the section is mounted once, its pickers update in place, search/module/scroll/tab
 * live in a centralized UI state and the whole builder survives tab switches, schema changes (selections are pruned, not wiped) and page reloads (session draft).
 */
import { icon } from '../components/icons'; import { renderTablePicker, type TablePickerCtl } from '../components/tablePicker'; import { renderColumnPicker, type ColumnPickerCtl } from '../components/columnPicker'; import { renderFilterBuilder, type FilterBuilderCtl } from '../components/filterBuilder';
import { renderSqlCodeBlock } from '../components/sqlCodeBlock'; import { renderTabs } from '../components/tabs'; import { openManualCaseBuilder, openManualDecodeBuilder } from '../components/manualExprBuilder'; import { openModal } from '../components/modal';
import { store } from '../state'; import { services, aiConfig, secrets } from '../context'; import { e, copyText } from '../dom';
import { generateFromDescription } from '../../v17/services/queryOrchestrator'; import { buildSelect } from '../../engines/sqlEngine'; import { computeAutoJoinPlan } from '../../engines/joinAutoEngine'; import { withFkRelationships } from '../../v17/engines/joinGraph';
import { optimizeSuggestions } from '../../engines/optimizeEngine'; import { activeSelection } from '../../engines/scope';
import { advancedOverrides, completeGroupBy, type ManualOptionKey } from '../../v17/engines/advancedOptionsResolver'; import { makeId } from '../../utils/id';
import { validateFinalQuery, summarizeValidation, type FullValidation } from '../../v17/engines/queryValidator'; import { explainQuery } from '../../v17/engines/explain'; import type { V17Requirement } from '../../v17/engines/nluEngine';
import { TIER_LABEL, type LearnTier } from '../../v17/services/learningStore';
import { selectorUi, saveDraftSoon, loadDraft, clearDraft } from '../selectorState'; import { OPT_DESC, catalogFor, joinTypesFor, JOIN_TYPE_LABEL } from '../advancedCatalog';
import type { Dialect, ReadOnlyQueryState, SchemaModel, JoinType, SubquerySpec } from '../../types';
const DIALECTS: Dialect[] = ['SQL Server', 'Oracle', 'PostgreSQL', 'MySQL', 'Generic'];
export function emptyReadOnly(d: Dialect = 'Oracle'): ReadOnlyQueryState { return { dialect: d, naturalLanguageText: '', selectedTables: [], selectedColumns: [], filters: [], sorts: [], advanced: { distinct: false, groupByColumns: [], havingClause: '', limit: null, viewName: '', tableAliases: false, joinType: 'INNER JOIN', recursive: false, ctes: [], subqueries: [] }, generatedSql: '-- Select at least one table (or describe your requirement above) to generate SQL.', joinPathChoices: {} }; }
let st: ReadOnlyQueryState = emptyReadOnly(); let notesHtml = ''; let lastSchemaId = ''; let baseline = ''; let autoInfo: string[] = []; let warnings: string[] = []; let lastReq: V17Requirement | null = null; let restored = false; let explainOpen = false; let checksOpen = false;
const schema = (): SchemaModel => services().schemas.active();
const persist = () => saveDraftSoon(() => ({ v: 1, schemaId: schema().id, st, ui: { ...selectorUi }, manual: advancedOverrides.list(), autoInfo }));
/** Rebuilds the SQL from the state. Selections that no longer exist in the Active Schema are pruned; selections on unselected tables are KEPT (not used). */
function regenerate(): void { const s = schema(); const valid = new Set(s.tables.map((t) => t.name)); const has = (t: string, c: string) => s.tables.find((x) => x.name === t)?.columns.some((x) => x.name === c);
  st.advanced.subqueries = st.advanced.subqueries || []; st.selectedTables = st.selectedTables.filter((t) => valid.has(t)); st.selectedColumns = st.selectedColumns.filter((c) => c.manualExpr || has(c.table, c.column)); st.filters = st.filters.filter((f) => has(f.table, f.column)); st.sorts = st.sorts.filter((x) => x.expression || has(x.table, x.column));
  const inScope = (g: string) => { const m = g.match(/^([A-Za-z_][\w$#]*)\./); return !m || st.selectedTables.includes(m[1]); }; st.advanced.groupByColumns = st.advanced.groupByColumns.filter(inScope);
  completeGroupBy(st); const b = buildSelect(st, s); st.generatedSql = b.sql; warnings = b.warnings; baseline = st.generatedSql; persist(); }
const mark = (k: ManualOptionKey) => advancedOverrides.mark(k);
/** Active Schema changed: keep the description, dialect, advanced options and every selection that still exists in the new schema — nothing is wiped. */
export function resetReadOnlyForSchemaChange(): void { const id = schema().id; if (lastSchemaId && lastSchemaId !== id) { st.joinPathChoices = {}; notesHtml = ''; lastReq = null; if (st.selectedTables.length) regenerate(); } lastSchemaId = id; }
function restoreDraftOnce(): void { if (restored) return; restored = true; const d = loadDraft(); if (!d) return; st = d.st; st.advanced.subqueries = st.advanced.subqueries || []; Object.assign(selectorUi, d.ui); d.manual.forEach((k) => advancedOverrides.mark(k as ManualOptionKey)); autoInfo = d.autoInfo || []; if (st.selectedTables.length) regenerate(); }
const failureBox = (what: string, where: string, why: string, next: string) => `<div class="issue-box mini">${icon('alert-triangle', 14)}<div><strong>${e(what)}</strong><br>Where: ${e(where)}<br>Why: ${e(why)}<br>What you can do: ${e(next)}</div></div>`;
export function renderReadOnlyPage(container: HTMLElement): void {
  restoreDraftOnce(); resetReadOnlyForSchemaChange(); let tp: TablePickerCtl | null = null; let cp: ColumnPickerCtl | null = null; let fb: FilterBuilderCtl | null = null;
  const syncSelectors = () => { cp?.update(st.selectedTables, st.selectedColumns); fb?.update(st.selectedTables, st.filters); tp?.update(st.selectedTables); };
  const validationNow = (): FullValidation | null => (st.selectedTables.length || /^\s*(WITH|SELECT)\b/i.test(st.generatedSql) ? validateFinalQuery(st.generatedSql, schema(), st.dialect, { state: st, unresolvedTerms: lastReq?.unresolvedTerms }) : null);
  const checksHtml = (v: FullValidation) => `<ul class="check-list">${v.checks.map((c) => `<li><span class="ck ck-${c.status}">${c.status === 'pass' ? '✔' : c.status === 'warn' ? '!' : '✖'}</span><span>${e(c.label)}${c.details.map((d) => `<span class="why">${e(d)}</span>`).join('')}</span></li>`).join('')}</ul>`;
  const validationHtml = (v: FullValidation | null) => !v ? '' : `<div class="issue-box ${v.valid ? 'ok' : ''} mini">${icon(v.valid ? 'check' : 'alert-triangle', 14)} ${v.valid ? 'SQL passed validation' : 'SQL needs attention'} — ${e(summarizeValidation(v))}</div><details ${checksOpen ? 'open' : ''} data-checks><summary>What was checked</summary>${checksHtml(v)}</details>`;
  const issuesHtml = () => { const v = validationNow(); const err = v ? v.errors : []; const warn = [...(v ? v.warnings : []), ...warnings];
    return `${err.length ? `<div class="issue-box">${icon('alert-triangle', 15)}<ul>${err.map((m) => `<li>${e(m)}</li>`).join('')}</ul></div>` : ''}${warn.length ? `<div class="issue-box warn">${icon('alert-triangle', 14)}<ul>${Array.from(new Set(warn)).map((m) => `<li>${e(m)}</li>`).join('')}</ul></div>` : ''}`; };
  const explainHtml = () => { if (!st.selectedTables.length) return ''; const s = schema(); const x = explainQuery(buildSelect(st, s), st, s, lastReq); const row = (k: string, v: string[] | string) => { const a = Array.isArray(v) ? v : v ? [v] : []; return a.length ? `<dt>${k}</dt><dd>${a.map(e).join('<br>')}</dd>` : ''; };
    return `<details class="explain-box" ${explainOpen ? 'open' : ''} data-explain><summary>${icon('info', 13)} Explain this SQL</summary><dl>${row('Tables', x.tables)}${row('Columns', x.columns)}${row('Joins', x.joins)}${row('Filters', x.filters)}${row('Aggregation', x.aggregations)}${row('Grouping', x.grouping)}${row('Sorting', x.sorting)}${row('Limit', x.limit)}${row('Options', x.options)}${row('Pattern used', x.pattern)}${row('Not resolved', x.unresolved)}</dl></details>`; };
  function draw(): void {
    container.innerHTML = `<div class="page"><h1 class="page-title">${icon('table')} Read Only Query Builder</h1><p class="page-subtitle">Generates validated SELECT / WITH statements only. Natural Language and Manual Selectors merge together — use either one, or both.</p>
    <div class="builder-grid-top"><div class="builder-panel" data-tour="describe-card"><h2>${icon('sparkles', 16)} Describe What You Need (optional)</h2><textarea id="nlDesc" rows="5" placeholder="e.g. Top 5 vendors by total invoice amount for approved invoices this year">${e(st.naturalLanguageText)}</textarea><label class="inline-label">SQL dialect<select id="dialectSelect">${DIALECTS.map((d) => `<option ${d === st.dialect ? 'selected' : ''}>${d}</option>`).join('')}</select></label><div class="row-actions"><button type="button" id="nlBuildBtn" class="btn btn-primary">${icon('zap', 15)} Build from Description</button></div><div id="nlNotes">${notesHtml}</div></div>
    <div class="builder-panel"><h2>${icon('code', 16)} Generated SQL</h2><div id="sqlBlockMount"></div></div></div>
    <div class="builder-panel manual-selectors-panel"><h2>${icon('sliders', 16)} Manual Selectors</h2><div id="tabsMount"></div><div class="row-actions build-query-row"><button type="button" id="buildQueryBtn" class="btn btn-primary">${icon('zap', 15)} Build Query</button><span class="hint">Regenerates the SQL from your current manual selections (this also happens automatically as you make changes).</span></div></div><div id="roIssues">${issuesHtml()}</div></div>`;
    container.querySelector('#nlDesc')!.addEventListener('input', (ev) => { st.naturalLanguageText = (ev.target as HTMLTextAreaElement).value; persist(); });
    container.querySelector('#dialectSelect')!.addEventListener('change', (ev) => { st.dialect = (ev.target as HTMLSelectElement).value as Dialect; if (st.dialect === 'MySQL' && st.advanced.joinType === 'FULL JOIN') { st.advanced.joinType = 'LEFT JOIN'; store.pushToast('info', 'FULL JOIN is not available in MySQL — LEFT JOIN is used instead.'); } regenerate(); cp?.update(st.selectedTables, st.selectedColumns); refresh(); });
    container.querySelector('#nlBuildBtn')!.addEventListener('click', () => { void runNl(); });
    container.querySelector('#buildQueryBtn')!.addEventListener('click', () => { regenerate(); store.pushToast('info', 'Query rebuilt from manual selections.'); refresh(); });
    renderSql(); renderTabsSection();
  }
  function refresh(): void { renderSql(); const m = container.querySelector('#roIssues'); if (m) m.innerHTML = issuesHtml(); persist(); }
  async function runNl(): Promise<void> {
    const btn = container.querySelector<HTMLButtonElement>('#nlBuildBtn')!; btn.disabled = true; btn.innerHTML = `${icon('zap', 15)} Processing…`;
    notesHtml = ''; const nn = container.querySelector('#nlNotes'); if (nn) nn.innerHTML = ''; // a new operation starts clean — no stale result or error from the previous one
    try {
      const s = schema(); const text = st.naturalLanguageText.trim(); if (!text) { regenerate(); draw(); return; }
      const r = await generateFromDescription(text, st, s, st.dialect, services().learning, aiConfig.enabled ? { config: aiConfig, apiKey: secrets.aiApiKey } : null, services().admin);
      st = { ...r.state, joinPathChoices: r.state.joinPathChoices || {} }; warnings = r.build.warnings; baseline = st.generatedSql; autoInfo = r.requirement.autoOptions.map((o) => o.description); lastReq = r.requirement;
      const badge = r.engine === 'online' ? `<span class="engine-badge engine-online">${icon('bot', 13)} Offline NLU + AI/LLM Model</span>` : `<span class="engine-badge engine-offline">${icon('wifi-off', 13)} Offline NLU${aiConfig.enabled ? ' — AI/LLM not needed' : ''}</span>`;
      const gaps = r.requirement.unresolvedTerms.length ? `<div class="issue-box mini">${icon('alert-triangle', 14)} Not found in the Active Schema (not added to the SQL): ${e(r.requirement.unresolvedTerms.join(', '))}</div>` : '';
      const pu = r.requirement.patternUsed; const pat = pu ? `<div class="hint">${icon(pu.source === 'admin' ? 'shield' : 'sparkles', 12)} ${pu.source === 'admin' ? 'Admin Query Library' : `Learned query${pu.tier ? ` (${e(TIER_LABEL[pu.tier as LearnTier] || pu.tier)})` : ''}`}: <strong>${e(pu.label)}</strong> — ${Math.round(pu.similarity * 100)}% similar; ${pu.adopted.length ? `adapted: ${e(pu.adopted.join(', '))}` : 'nothing needed to be adapted'}.</div>` : '';
      notesHtml = `<div class="notes-box"><div style="width:100%">${badge}<div class="schema-audit-line">${icon('database', 12)} Active Schema used: ${e(s.name)} (v${e(String(s.version))})</div>${pat}${autoInfo.length ? `<strong>Query Plan</strong><ul class="plan-list">${autoInfo.map((p) => `<li>${e(p)}</li>`).join('')}</ul>` : ''}${r.keptManual.length ? `<div class="hint">${icon('sliders', 12)} Kept your manual settings: ${e(r.keptManual.join(', '))}.</div>` : ''}${r.requirement.notes.length ? `<strong>Notes</strong><ul>${r.requirement.notes.map((n) => `<li>${e(n)}</li>`).join('')}</ul>` : ''}${r.onlineNote ? `<div class="hint">${icon('bot', 12)} AI/LLM Model: ${e(r.onlineNote)}</div>` : ''}<details class="mt"><summary class="hint">How this was resolved</summary><ol class="trace-list">${r.trace.map((t) => `<li>${e(t)}</li>`).join('')}</ol></details></div></div>${gaps}`;
    } catch (err) { notesHtml = failureBox('The description could not be turned into SQL.', 'Describe What You Need → offline NLU / SQL engine', (err as Error)?.message || 'an unexpected internal error occurred', 'Rephrase the description with table or column names from the Active Schema, or use Manual Selectors — they are not affected.'); }
    draw();
  }
  function renderValidation(): void { const m = container.querySelector<HTMLElement>('#validationMount'); if (m) { m.innerHTML = validationHtml(validationNow()); m.querySelector('[data-checks]')?.addEventListener('toggle', (ev) => { checksOpen = (ev.target as HTMLDetailsElement).open; }); } const x = container.querySelector<HTMLElement>('#explainMount'); if (x) { x.innerHTML = explainHtml(); x.querySelector('[data-explain]')?.addEventListener('toggle', (ev) => { explainOpen = (ev.target as HTMLDetailsElement).open; }); } }
  function renderSql(): void {
    const m = container.querySelector<HTMLElement>('#sqlBlockMount'); if (!m) return;
    renderSqlCodeBlock(m, st.generatedSql, {
      onCopy: () => { void copyText(st.generatedSql); store.pushToast('success', 'SQL copied to clipboard.'); },
      onClear: () => { st = emptyReadOnly(st.dialect); advancedOverrides.clear(); notesHtml = ''; lastReq = null; autoInfo = []; clearDraft(); store.pushToast('info', 'Query cleared.'); draw(); },
      onValidate: () => { checksOpen = true; renderValidation(); },
      onRegenerate: () => { regenerate(); store.pushToast('info', 'SQL regenerated from current selections.'); refresh(); }
    }, [{ id: 'btnAcceptLearn', label: 'Accept & Learn', iconName: 'check', onClick: acceptLearn }, { id: 'btnReportIssue', label: 'Report issue', iconName: 'alert-triangle', onClick: reportIssue }, { id: 'btnOptimizeToggle', label: 'Optimize', iconName: 'wand', onClick: () => { const o = m.querySelector<HTMLElement>('#optimizeMount')!; if (o.innerHTML.trim()) { o.innerHTML = ''; return; } o.innerHTML = `<div class="tips-box">${icon('wand', 15)}<ul>${optimizeSuggestions(st).map((t) => `<li>${e(t)}</li>`).join('')}</ul></div>`; } }]);
    renderValidation();
  }
  const learnArgs = () => ({ tables: st.selectedTables, columns: activeSelection(st).columns.filter((c) => !c.manualExpr).map((c) => ({ table: c.table, column: c.column })), sorts: activeSelection(st).sorts.filter((x) => !x.expression).map((x) => ({ table: x.table, column: x.column, direction: x.direction })), limit: st.advanced.limit });
  function acceptLearn(): void {
    const s = schema(); const md = openModal(`${icon('check', 18)} Accept &amp; Learn`, `<p class="hint">Review or adjust the SQL, then accept it. Accepted queries are validated against the Active Schema <strong>${e(s.name)}</strong>. Unchanged SQL becomes <em>confirmed</em>, edited SQL becomes <em>modified &amp; confirmed</em>, and SQL you report as having run successfully becomes the strongest learned pattern.</p><label class="block-label">Final SQL<textarea id="v17AcceptSql" rows="12" spellcheck="false" style="font-family:'Cascadia Code',Consolas,monospace;font-size:12.5px">${e(st.generatedSql)}</textarea></label><label class="block-label">Result when you ran it<select id="v17AcceptResult"><option value="unknown">Not run yet</option><option value="success">Ran successfully (correct result)</option><option value="failed">Failed or gave a wrong result</option></select></label><label class="block-label">Feedback (optional)<input type="text" id="v17AcceptNote" maxlength="300" placeholder="e.g. exactly what I needed"></label><div id="v17AcceptErrors"></div><div class="modal-actions"><button type="button" class="btn btn-ghost" id="v17AcceptCancel">Cancel</button><button type="button" class="btn btn-primary" id="v17AcceptOk">${icon('check', 14)} Accept &amp; Learn</button></div>`, { wide: true, closeOnBackdrop: false });
    md.element.querySelector('#v17AcceptCancel')!.addEventListener('click', () => md.close());
    md.element.querySelector('#v17AcceptOk')!.addEventListener('click', () => { const sql = (md.element.querySelector('#v17AcceptSql') as HTMLTextAreaElement).value.trim(); const result = (md.element.querySelector('#v17AcceptResult') as HTMLSelectElement).value as 'unknown' | 'success' | 'failed'; const note = (md.element.querySelector('#v17AcceptNote') as HTMLInputElement).value;
      const v = validateFinalQuery(sql, s, st.dialect, { state: { ...st, generatedSql: sql } });
      if (!v.valid || !/\bSELECT\b/i.test(sql)) { md.element.querySelector('#v17AcceptErrors')!.innerHTML = failureBox('This SQL cannot be accepted.', 'Accept & Learn → validation against the Active Schema', (v.errors.slice(0, 4).join(' ') || 'No SELECT statement was found.'), 'Correct the SQL above (or use Report issue if the generated SQL was wrong) and accept again.'); return; }
      const text = st.naturalLanguageText.trim(); const { learning } = services(); const modified = sql.replace(/\s+/g, ' ') !== baseline.replace(/\s+/g, ' ');
      const ok = text ? learning.confirm(text, s, sql, modified ? sql : null, { resultStatus: result, feedback: result === 'success' ? 'positive' : result === 'failed' ? 'negative' : 'none', feedbackNote: note, dialect: st.dialect }) : false;
      if (modified) st.generatedSql = sql; md.close(); renderSql(); persist();
      store.pushToast(ok ? (result === 'failed' ? 'warning' : 'success') : 'info', ok ? (result === 'failed' ? 'Noted as a failed result — it will not be used as a learned pattern.' : result === 'success' ? 'Learned as a successfully executed query (strongest learned pattern).' : modified ? 'Modified SQL accepted and learned as confirmed knowledge.' : 'SQL accepted and learned as confirmed knowledge.') : text ? 'Accepted. (Not learned: the description appears to contain a credential, or browser storage refused the write.)' : 'SQL accepted. (Nothing was learned because there is no description to learn it against.)'); });
  }
  function reportIssue(): void {
    const text = st.naturalLanguageText.trim(); if (!text) { store.pushToast('info', 'Describe the requirement first — feedback is recorded against a description.'); return; }
    const md = openModal(`${icon('alert-triangle', 18)} Report an issue with this SQL`, `<p class="hint">The description and its SQL will no longer be used as a learned pattern.</p><label class="block-label">What was wrong?<select id="v17IssueKind"><option>Wrong table or column</option><option>Wrong filter or date range</option><option>Wrong grouping, total or sorting</option><option>The SQL failed when I ran it</option><option>Other</option></select></label><label class="block-label">Details (optional)<input type="text" id="v17IssueNote" maxlength="300"></label><div class="modal-actions"><button type="button" class="btn btn-ghost" id="v17IssueCancel">Cancel</button><button type="button" class="btn btn-primary" id="v17IssueOk">Report</button></div>`, { closeOnBackdrop: false });
    md.element.querySelector('#v17IssueCancel')!.addEventListener('click', () => md.close());
    md.element.querySelector('#v17IssueOk')!.addEventListener('click', () => { const kind = (md.element.querySelector('#v17IssueKind') as HTMLSelectElement).value; const note = (md.element.querySelector('#v17IssueNote') as HTMLInputElement).value; const ok = services().learning.setFeedback(text, schema(), 'negative', `${kind}${note ? ` — ${note}` : ''}`, /failed/.test(kind)); md.close(); store.pushToast(ok ? 'success' : 'info', ok ? 'Thank you — this result will not be used as a learned pattern.' : 'Nothing to demote: this description has not been learned on this device.'); });
  }
  function renderTabsSection(): void { const m = container.querySelector<HTMLElement>('#tabsMount'); if (!m) return; const s = schema(); tp = cp = fb = null;
    renderTabs(m, [{ id: 'tables-columns', label: 'Tables & Columns', render: (p) => tablesTab(p, s) }, { id: 'advanced', label: 'Advanced Options', render: (p) => advancedTab(p, s) }, { id: 'summary', label: 'Selected / Described Requirements', render: (p) => summaryTab(p) }], selectorUi.activeTab, { 'tables-columns': 'tab-tables-columns', advanced: 'tab-advanced', summary: 'tab-summary' }, (id) => { selectorUi.activeTab = id; if (id === 'tables-columns') setTimeout(syncSelectors, 0); persist(); }, { persist: ['tables-columns'] }); }
  function tablesTab(panel: HTMLElement, s: SchemaModel): void {
    panel.innerHTML = `<div class="tc-grid"><div class="tc-col"><h3>${icon('list', 15)} Select Tables</h3><div id="tablePickerMount"></div></div><div class="tc-col"><h3>${icon('columns', 15)} Select Columns (Alias/DECODE appear once selected)</h3><div id="columnPickerMount"></div></div><div class="tc-col"><h3>${icon('filter', 15)} Filters</h3><div id="filterBuilderMount"></div></div></div>`;
    tp = renderTablePicker(panel.querySelector<HTMLElement>('#tablePickerMount')!, s, st.selectedTables, (next) => { st.selectedTables = next; regenerate(); cp?.update(st.selectedTables, st.selectedColumns); fb?.update(st.selectedTables, st.filters); refresh(); });
    cp = renderColumnPicker(panel.querySelector<HTMLElement>('#columnPickerMount')!, s, st.selectedTables, st.selectedColumns, { getDialect: () => st.dialect, onChange: (next) => { mark('columns'); st.selectedColumns = next; regenerate(); refresh(); }, onRequestManualDecodeForColumn: (t, c, specId) => openManualDecodeBuilder(st.dialect, (spec) => { st.selectedColumns = st.selectedColumns.map((x) => (x.id === specId ? spec : x)); regenerate(); refresh(); cp?.update(st.selectedTables, st.selectedColumns); }, { table: t, column: c.name }, specId) });
    fb = renderFilterBuilder(panel.querySelector<HTMLElement>('#filterBuilderMount')!, s, st.selectedTables, st.filters, (next) => { st.filters = next; regenerate(); refresh(); }, () => st.dialect);
  }
  function advancedTab(panel: HTMLElement, s: SchemaModel): void {
    const a = st.advanced; const d = st.dialect; const subs = a.subqueries || []; const badge = (k: ManualOptionKey) => (advancedOverrides.isManual(k) ? ' <span class="chip chip-inactive" style="padding:.05rem .4rem;font-size:10.5px">manual</span>' : '');
    const cat = catalogFor(d); const groups = ['Query controls', 'Join controls', 'SQL structures'] as const;
    panel.innerHTML = `<div class="notes-box" data-v17-auto-options><div style="width:100%"><div class="hint">${icon('sparkles', 13)} Filtering, conditions, date filtering, joins, aggregation, grouping, sorting, DISTINCT, aliases and result limits are detected automatically from <strong>Describe What You Need</strong>. Changing any option below takes manual control of it — manual settings are never overwritten.</div>${autoInfo.length ? `<div class="tiny-label mt"><strong>Applied automatically</strong></div><div class="chip-row">${autoInfo.map((x) => `<span class="chip">${icon('zap', 11)} ${e(x)}</span>`).join('')}</div>` : ''}${advancedOverrides.list().length ? `<div class="tiny-label mt"><strong>Under manual control</strong></div><div class="chip-row">${advancedOverrides.list().map((k) => `<span class="chip">${icon('sliders', 11)} ${e(k)}</span>`).join('')}</div><button type="button" class="btn-link mt" id="releaseManualBtn">Return all options to automatic</button>` : ''}</div></div>
    <details class="adv-catalog mt" data-catalog><summary>${icon('list', 13)} All SQL options at a glance — ${cat.length} available for ${e(d)}</summary><dl>${groups.map((g) => `<h6>${g}</h6>${cat.filter((o) => o.group === g).map((o) => `<dt>${e(o.label)}</dt><dd>${e(o.description)}<br><span class="hint">${e(o.where)}</span></dd>`).join('')}`).join('')}</dl></details>
    <div class="advanced-grid mt"><div><label class="inline-check"><input type="checkbox" id="advDistinct" ${a.distinct ? 'checked' : ''}/> DISTINCT${badge('distinct')}</label><div class="opt-desc">${e(OPT_DESC.distinct)}</div>
      <label class="block-label">GROUP BY columns (comma separated)${badge('groupBy')}<input type="text" id="advGroupBy" value="${e(a.groupByColumns.join(', '))}" placeholder="TABLE.COLUMN, …"/></label><div class="opt-desc">${e(OPT_DESC.groupBy)}</div>
      <label class="block-label">HAVING clause${badge('having')}<input type="text" id="advHaving" value="${e(a.havingClause)}" placeholder="COUNT(TABLE.ID) > 1"/></label><div class="opt-desc">${e(OPT_DESC.having)}</div>
      <label class="block-label">LIMIT${badge('limit')}<input type="number" id="advLimit" min="1" value="${a.limit ?? ''}"/></label><div class="opt-desc">${e(OPT_DESC.limit(d))}</div>
      <label class="inline-check"><input type="checkbox" id="advRecursive" ${a.recursive ? 'checked' : ''}/> Recursive (WITH RECURSIVE)</label><div class="opt-desc">${e(OPT_DESC.recursive)}</div>
      <label class="inline-check"><input type="checkbox" id="advTableAliases" ${a.tableAliases ? 'checked' : ''}/> Use table aliases (e.g. INVOICE_HEADER ih)${badge('tableAliases')}</label><div class="opt-desc">${e(OPT_DESC.aliases)}</div>
      <label class="block-label">Join type for automatic joins${badge('joinType')}<select id="advJoinType">${joinTypesFor(d).map((j) => `<option value="${j}" ${a.joinType === j ? 'selected' : ''}>${e(JOIN_TYPE_LABEL[j])}</option>`).join('')}</select></label><div class="opt-desc">${e(OPT_DESC.joinType)}</div>
      <h4 class="mt">${icon('route', 14)} Join paths</h4><div class="opt-desc">${e(OPT_DESC.joinPaths)}</div><div id="joinPathList"></div><h4 class="mt">${icon('sort-asc', 14)} ORDER BY${badge('sorts')}</h4><div class="opt-desc">${e(OPT_DESC.orderBy)}</div><div id="sortList"></div></div>
      <div><h4>CTEs</h4><div class="opt-desc">${e(OPT_DESC.cte)}</div><div id="cteList" class="filter-rows"></div><button type="button" id="addCteBtn" class="btn btn-outline btn-sm">${icon('plus', 14)} Add CTE</button>
      <h4 class="mt">Sub-select filters</h4><div class="opt-desc">${e(OPT_DESC.subselect)}</div><div id="subList"></div><button type="button" id="addSubBtn" class="btn btn-outline btn-sm">${icon('plus', 14)} Add sub-select filter</button>
      <h4 class="mt">Manual CASE / DECODE Columns</h4><div class="opt-desc">${e(OPT_DESC.caseDecode)}</div><div id="manualColsList"></div><div class="row-actions"><button type="button" id="addManualCaseBtn" class="btn btn-outline btn-sm">${icon('code', 14)} Add Manual CASE</button><button type="button" id="addManualDecodeBtn" class="btn btn-outline btn-sm">${icon('sparkles', 14)} Add Manual DECODE</button></div></div></div>`;
    const q = <T extends HTMLElement>(id: string) => panel.querySelector<T>(`#${id}`)!; const re = () => advancedTab(panel, s);
    q('releaseManualBtn')?.addEventListener('click', () => { advancedOverrides.clear(); re(); });
    q('advDistinct').addEventListener('change', (ev) => { mark('distinct'); st.advanced.distinct = (ev.target as HTMLInputElement).checked; regenerate(); refresh(); re(); });
    q('advGroupBy').addEventListener('input', (ev) => { mark('groupBy'); st.advanced.groupByColumns = (ev.target as HTMLInputElement).value.split(',').map((v) => v.trim()).filter(Boolean); regenerate(); refresh(); });
    q('advHaving').addEventListener('input', (ev) => { mark('having'); st.advanced.havingClause = (ev.target as HTMLInputElement).value; regenerate(); refresh(); });
    q('advLimit').addEventListener('input', (ev) => { mark('limit'); const v = parseInt((ev.target as HTMLInputElement).value, 10); st.advanced.limit = v > 0 ? v : null; regenerate(); refresh(); });
    q('advRecursive').addEventListener('change', (ev) => { st.advanced.recursive = (ev.target as HTMLInputElement).checked; regenerate(); refresh(); });
    q('advTableAliases').addEventListener('change', (ev) => { mark('tableAliases'); st.advanced.tableAliases = (ev.target as HTMLInputElement).checked; regenerate(); refresh(); re(); });
    q('advJoinType').addEventListener('change', (ev) => { mark('joinType'); st.advanced.joinType = (ev.target as HTMLSelectElement).value as JoinType; regenerate(); refresh(); re(); });
    const jl = q('joinPathList');
    if (st.selectedTables.length < 2) jl.innerHTML = '<p class="hint">Select two or more tables to see how they are joined.</p>';
    else { const plan = computeAutoJoinPlan(withFkRelationships(s), st.selectedTables[0], st.selectedTables.slice(1), st.joinPathChoices);
      jl.innerHTML = `${plan.resolutions.map((r) => `<div class="mini-row" data-pair="${e(r.pairKey)}"><span><code>${e(r.tableA)}</code> ↔ <code>${e(r.tableB)}</code></span>${r.options.length > 1 ? `<select class="join-path-select" aria-label="Join path"><option value="">— choose a join path —</option>${r.options.map((o) => `<option value="${e(o.id)}" ${o.id === r.chosenOptionId ? 'selected' : ''}>${e(o.label)}</option>`).join('')}</select>` : `<span class="hint">${e(r.options[0].label)}</span>`}</div>`).join('')}${plan.unresolvedWarnings.map((w) => `<div class="issue-box warn mini">${e(w)}</div>`).join('')}`;
      jl.querySelectorAll<HTMLSelectElement>('.join-path-select').forEach((sel) => sel.addEventListener('change', () => { const key = (sel.closest('[data-pair]') as HTMLElement).dataset.pair!; if (sel.value) st.joinPathChoices[key] = sel.value; else delete st.joinPathChoices[key]; regenerate(); refresh(); re(); })); }
    const cols = st.selectedTables.flatMap((t) => (s.tables.find((x) => x.name === t)?.columns || []).map((c) => `${t}.${c.name}`)); const sortsHere = st.sorts.map((so, i) => ({ so, i })).filter((x) => x.so.expression || st.selectedTables.includes(x.so.table));
    q('sortList').innerHTML = `${sortsHere.map(({ so, i }) => `<div class="mini-row" data-idx="${i}">${so.expression ? `<code>${e(so.expression)}</code>` : `<select class="sort-col" aria-label="Sort column">${cols.map((c) => `<option ${c === `${so.table}.${so.column}` ? 'selected' : ''}>${e(c)}</option>`).join('')}</select>`}<select class="sort-dir" aria-label="Direction"><option ${so.direction === 'ASC' ? 'selected' : ''}>ASC</option><option ${so.direction === 'DESC' ? 'selected' : ''}>DESC</option></select><button type="button" class="icon-btn remove-sort" aria-label="Remove sort">${icon('trash', 14)}</button></div>`).join('')}<button type="button" id="addSortBtn" class="btn btn-outline btn-sm" ${cols.length ? '' : 'disabled'}>${icon('plus', 14)} Add sort</button>`;
    q('sortList').querySelectorAll<HTMLElement>('.mini-row').forEach((r) => { const i = +r.dataset.idx!; r.querySelector('.sort-col')?.addEventListener('change', (ev) => { const [t, c] = (ev.target as HTMLSelectElement).value.split('.'); st.sorts[i] = { ...st.sorts[i], table: t, column: c }; mark('sorts'); regenerate(); refresh(); }); r.querySelector('.sort-dir')!.addEventListener('change', (ev) => { st.sorts[i].direction = (ev.target as HTMLSelectElement).value as 'ASC' | 'DESC'; mark('sorts'); regenerate(); refresh(); }); r.querySelector('.remove-sort')!.addEventListener('click', () => { st.sorts.splice(i, 1); mark('sorts'); regenerate(); refresh(); re(); }); });
    q('addSortBtn')?.addEventListener('click', () => { const [t, c] = cols[0].split('.'); st.sorts.push({ id: makeId('sort'), table: t, column: c, direction: 'ASC' }); mark('sorts'); regenerate(); refresh(); re(); });
    const cl = q('cteList'); cl.innerHTML = st.advanced.ctes.map((c, i) => `<div class="cte-row" data-idx="${i}"><input type="text" class="cte-name-input" value="${e(c.name)}" aria-label="CTE name"/><textarea class="cte-body-input" rows="3" aria-label="CTE body" placeholder="SELECT …">${e(c.body)}</textarea><button type="button" class="icon-btn remove-cte-btn" aria-label="Remove CTE">${icon('trash', 14)}</button></div>`).join('');
    cl.querySelectorAll<HTMLElement>('.cte-row').forEach((r) => { const i = +r.dataset.idx!; r.querySelector('.cte-name-input')!.addEventListener('change', (ev) => { st.advanced.ctes[i].name = (ev.target as HTMLInputElement).value; regenerate(); refresh(); }); r.querySelector('.cte-body-input')!.addEventListener('change', (ev) => { st.advanced.ctes[i].body = (ev.target as HTMLTextAreaElement).value; regenerate(); refresh(); }); r.querySelector('.remove-cte-btn')!.addEventListener('click', () => { st.advanced.ctes.splice(i, 1); regenerate(); refresh(); re(); }); });
    q('addCteBtn').addEventListener('click', () => { st.advanced.ctes.push({ id: makeId('cte'), name: `cte_${st.advanced.ctes.length + 1}`, body: '' }); re(); });
    const sl = q('subList'); const msg = (x: SubquerySpec) => { if (!x.body.trim()) return ''; const v = validateFinalQuery(x.body, s, st.dialect); return v.valid ? `<span class="hint" style="color:#2f9e5b">✔ valid read-only SELECT</span>` : `<span class="hint" style="color:#d64550">${e(v.errors.slice(0, 2).join(' '))}</span>`; };
    sl.innerHTML = subs.map((x, i) => `<div class="sub-row" data-idx="${i}"><div class="sub-head"><select class="sub-kind" aria-label="Condition type">${(['EXISTS', 'NOT EXISTS', 'IN', 'NOT IN'] as const).map((k) => `<option ${k === x.kind ? 'selected' : ''}>${k}</option>`).join('')}</select>${x.kind === 'IN' || x.kind === 'NOT IN' ? `<select class="sub-col" aria-label="Column">${cols.map((c) => `<option ${c === x.column ? 'selected' : ''}>${e(c)}</option>`).join('')}</select>` : ''}<button type="button" class="icon-btn remove-sub" aria-label="Remove sub-select filter">${icon('trash', 14)}</button></div><textarea class="sub-body" rows="3" aria-label="Sub-select" placeholder="SELECT … FROM … WHERE … (read-only)">${e(x.body)}</textarea><div class="sub-msg">${msg(x)}</div></div>`).join('');
    sl.querySelectorAll<HTMLElement>('.sub-row').forEach((r) => { const i = +r.dataset.idx!; const x = () => st.advanced.subqueries![i];
      r.querySelector('.sub-kind')!.addEventListener('change', (ev) => { x().kind = (ev.target as HTMLSelectElement).value as SubquerySpec['kind']; if ((x().kind === 'IN' || x().kind === 'NOT IN') && !x().column) x().column = cols[0] || ''; regenerate(); refresh(); re(); });
      r.querySelector('.sub-col')?.addEventListener('change', (ev) => { x().column = (ev.target as HTMLSelectElement).value; regenerate(); refresh(); });
      r.querySelector('.sub-body')!.addEventListener('change', (ev) => { x().body = (ev.target as HTMLTextAreaElement).value; regenerate(); refresh(); (r.querySelector('.sub-msg') as HTMLElement).innerHTML = msg(x()); });
      r.querySelector('.remove-sub')!.addEventListener('click', () => { st.advanced.subqueries!.splice(i, 1); regenerate(); refresh(); re(); }); });
    q('addSubBtn').addEventListener('click', () => { st.advanced.subqueries = [...(st.advanced.subqueries || []), { id: makeId('sub'), kind: 'EXISTS', column: cols[0] || '', body: '' }]; re(); });
    const manual = st.selectedColumns.filter((c) => c.manualExpr && (c.displayMode !== 'manual-decode' || !st.selectedTables.includes(c.table)));
    q('manualColsList').innerHTML = manual.length ? manual.map((c) => `<div class="mini-row"><code>${e(c.alias)}</code><button type="button" class="icon-btn remove-manual-col" data-id="${e(c.id)}" aria-label="Remove">${icon('trash', 14)}</button></div>`).join('') : '<p class="hint">No custom CASE/DECODE columns added yet.</p>';
    q('manualColsList').querySelectorAll<HTMLElement>('.remove-manual-col').forEach((b) => b.addEventListener('click', () => { st.selectedColumns = st.selectedColumns.filter((c) => c.id !== b.dataset.id); regenerate(); refresh(); re(); }));
    q('addManualCaseBtn').addEventListener('click', () => openManualCaseBuilder((spec) => { st.selectedColumns.push(spec); regenerate(); refresh(); re(); store.pushToast('success', `Manual CASE column "${spec.alias}" added.`); }));
    q('addManualDecodeBtn').addEventListener('click', () => openManualDecodeBuilder(st.dialect, (spec) => { st.selectedColumns.push(spec); regenerate(); refresh(); re(); store.pushToast('success', `Manual DECODE column "${spec.alias}" added.`); }));
  }
  function summaryTab(panel: HTMLElement): void { const a = st.advanced; const act = activeSelection(st);
    panel.innerHTML = `<div class="summary-grid"><div><h3>Natural-language requirement</h3><p>${e(st.naturalLanguageText || '(none provided)')}</p><h3>Selected tables</h3><p>${e(st.selectedTables.join(', ') || '(none)')}</p><h3>Selected columns</h3><p>${act.columns.length ? act.columns.map((c) => e(c.manualExpr ? `Expression: ${c.alias}` : c.aggregate ? `${c.aggregate}(${c.table}.${c.column})${c.alias ? ` AS ${c.alias}` : ''}` : `${c.table}.${c.column}${c.alias ? ` AS ${c.alias}` : ''}${c.useDecode ? ' (schema decode)' : ''}`)).join('<br/>') : '(none — SELECT * will be used)'}</p><h3>Filters</h3><p>${act.filters.length ? act.filters.map((f, i) => e(`${i ? f.combinator + ' ' : ''}${f.table}.${f.column} ${f.operator} ${f.value}${f.value2 ? ' AND ' + f.value2 : ''}`)).join('<br/>') : '(none)'}</p>${act.hiddenCount ? `<p class="hint">${act.hiddenCount} selection(s) on tables that are not selected are kept and not used.</p>` : ''}</div><div><h3>Advanced options</h3><ul><li>DISTINCT: ${a.distinct ? 'Yes' : 'No'}</li><li>Sort: ${e(act.sorts.length ? act.sorts.map((x) => `${x.expression || `${x.table}.${x.column}`} ${x.direction}`).join(', ') : '(none)')}</li><li>Group by: ${e(a.groupByColumns.join(', ') || '(none)')}</li><li>Having: ${e(a.havingClause || '(none)')}</li><li>Limit: ${a.limit ?? '(none)'}</li><li>CTEs: ${a.ctes.length}</li><li>Sub-select filters: ${(a.subqueries || []).length}</li><li>Table aliases: ${a.tableAliases ? 'Yes' : 'No'}</li><li>Join type: ${e(a.joinType)}</li><li>Manual overrides: ${e(advancedOverrides.list().join(', ') || 'none')}</li></ul></div></div>`; }
  if (st.selectedTables.length) regenerate();
  draw();
}
