import { state } from '../../state/store';
import { services, secrets, reloadSecrets, repository, aiConfig, setAiConfig, vaultProblem } from '../context';
import { esc, val, checked, toast, options, multiline } from '../dom';
import { legacyLeftovers } from '../../v17/sync/schemaFormat';
import { rejectionMessage, migrationMessage, type PullOutcome } from '../../v17/sync/syncService';
import { analyzeDependencies } from '../../v17/engines/schemaRecordEngine';
import { VALID_DATA_TYPES, type SchemaEditorRow, type SchemaModel } from '../../types';
import { maskSecret, type VaultSecrets } from '../../v17/services/secretVault';
import { validateAiConfig, saveAiConfig, PROVIDER_DEFAULTS, type AiProvider, type AiAuth } from '../../v17/services/aiLlmService';
import { redactSecrets } from '../../v17/errors/appErrors';
import { downloadBlob } from '../../utils/dom';
const TABS: [string, string][] = [['schema-management', 'Schema Management'], ['manual-update', 'Manual Schema Update'], ['vault', 'Secret Vault'], ['ai', 'AI/LLM Model']];
let lastPull: PullOutcome | null = null; let lastPush = ''; let edId: string | null = null; let selRow: string | null = null; let filt = ''; let changes: string[] = [];
export function setLastPull(p: PullOutcome | null): void { lastPull = p; }
const chip = (c: string, l: string) => `<span class="chip ${c}">${esc(l)}</span>`;
export function renderSettings(root: HTMLElement): void {
  root.innerHTML = `<h1>Settings</h1>${vaultProblem ? `<div class="issue-box error">The Secret Vault on this device could not be opened (${esc(vaultProblem)}). Re-enter the configuration in Secret Vault.</div>` : ''}<div class="tabs">${TABS.map(([k, l]) => `<button data-tab="${k}" class="${state.settingsTab === k ? 'active' : ''}">${esc(l)}</button>`).join('')}</div><div id="settingsBody"></div>`;
  root.querySelectorAll<HTMLElement>('[data-tab]').forEach((b) => b.addEventListener('click', () => { state.settingsTab = b.dataset.tab!; renderSettings(root); }));
  const body = root.querySelector('#settingsBody') as HTMLElement; const re = () => renderSettings(root);
  ({ 'schema-management': mgmt, 'manual-update': manual, vault: vaultTab, ai: aiTab } as Record<string, (b: HTMLElement, r: () => void) => void>)[state.settingsTab](body, re);
}
function mgmt(body: HTMLElement, re: () => void): void {
  const { schemas, sync, vault } = services(); const reg = schemas.registry(); const d = schemas.loadDiagnostics; const m = sync.meta();
  body.innerHTML = `<div class="card"><h2>Schemas</h2><table class="grid" id="schemaList"><thead><tr><th>Name</th><th>Format</th><th>Tables</th><th>Legacy leftovers</th><th></th></tr></thead><tbody>${reg.schemas.map((s) => { const l = legacyLeftovers(s); return `<tr><td><strong>${esc(s.name)}</strong> ${s.id === reg.activeSchemaId ? chip('active', 'Active') : ''}</td><td>${s.migration ? `${chip('migrated', 'Migrated schema')}<div class="small muted">from ${esc(s.migration.fromFormat)}</div>` : chip('current', 'Current schema')}</td><td>${s.tables.length}</td><td class="small">${l.unmappedLabels ? `${l.unmappedLabels} label(s) without code ` : ''}${l.unresolvedRefs ? `${l.unresolvedRefs} reference(s) outside schema` : ''}${!l.unmappedLabels && !l.unresolvedRefs ? '—' : ''}</td><td>${s.id !== reg.activeSchemaId ? `<button data-activate="${esc(s.id)}">Set active</button>` : ''}${l.unmappedLabels ? `<button data-recover="${esc(s.id)}">Recover decode codes from source file</button>` : ''}<button class="danger" data-del="${esc(s.id)}">Delete</button></td></tr>`; }).join('')}</tbody></table>
  <div class="row" style="margin-top:10px"><input type="file" id="importFile" accept=".json"><input id="importName" placeholder="Name for imported schema"><button id="importBtn">Import schema file</button><button id="exportBtn">Export all schemas</button></div><input type="file" id="recoverFile" accept=".json" style="display:none"></div>
  <div class="card" id="syncDiagnostics"><div class="row"><h2 class="grow" style="margin:0">Repository synchronization</h2><button class="primary" id="syncNow">Synchronize now</button><button id="pullOnly">Download only</button><button id="publishNow">Publish</button></div>
  <p class="small muted">Repository: <strong>${esc(secrets.githubRepo || '(not configured)')}</strong> · branch ${esc(secrets.githubBranch)} · file <code id="syncPath">${esc(secrets.schemaPath)}</code> · last download ${esc(m.lastPullAt || 'never')} · last publish ${esc(m.lastPushAt || 'never')}</p>
  ${lastPull ? pullHtml(lastPull) : '<p class="muted small">No synchronization in this session yet.</p>'}${lastPush ? `<div class="issue-box ${/^Published/.test(lastPush) ? 'ok' : ''}" id="pushResult">${multiline(lastPush)}</div>` : ''}
  ${d.recoveredFrom.length ? `<div class="issue-box ok">Schemas saved by SQL Assistant V17.2.1/V17.2.2 on this device were recovered into the standard storage.</div>` : ''}
  ${d.unreadable ? `<div class="issue-box error">The schemas stored on this device could not be read (${esc(d.unreadable)}). Default schemas were loaded; the original data was kept as a backup. Use Synchronize now to restore from the repository.</div>` : ''}
  ${sync.conflicts().map((c) => `<div class="issue-box">Schema <strong>${esc(c.schemaName)}</strong> changed here and in the repository. <button data-cf="${esc(c.id)}" data-ch="keep-local">Keep this device's version</button> <button data-cf="${esc(c.id)}" data-ch="take-remote">Use repository version</button></div>`).join('')}
  <details><summary class="small">Synchronization log</summary><table class="grid small">${sync.log().slice(0, 20).map((l) => `<tr><td>${esc(l.timestamp.replace('T', ' ').slice(0, 19))}</td><td>${esc(l.kind)}</td><td>${esc(l.message)}</td></tr>`).join('')}</table></details></div>`;
  body.querySelectorAll<HTMLElement>('[data-activate]').forEach((b) => b.addEventListener('click', () => { schemas.setActive(b.dataset.activate!); re(); }));
  body.querySelectorAll<HTMLElement>('[data-del]').forEach((b) => b.addEventListener('click', () => { if (!confirm('Delete this schema from this device?')) return; const r = schemas.deleteSchema(b.dataset.del!); if (!r.ok) toast('error', r.errors.map((e) => e.message).join(' ')); re(); }));
  let rt = ''; body.querySelectorAll<HTMLElement>('[data-recover]').forEach((b) => b.addEventListener('click', () => { rt = b.dataset.recover!; (body.querySelector('#recoverFile') as HTMLInputElement).click(); }));
  body.querySelector('#recoverFile')!.addEventListener('change', async (e) => { const f = (e.target as HTMLInputElement).files?.[0]; if (!f) return; const r = schemas.recoverFromSource(rt, await f.text()); toast(r.ok ? 'success' : 'error', r.ok ? `${r.restored} decode code(s) restored; ${r.stillUnmapped} label(s) still without a code.` : r.errors.map((x) => x.message).join(' ')); re(); });
  body.querySelector('#importBtn')!.addEventListener('click', async () => { const f = (body.querySelector('#importFile') as HTMLInputElement).files?.[0]; if (!f) { toast('warning', 'Choose a schema file first.'); return; } const r = schemas.importSchemaJson(await f.text(), val('importName')); if (!r.ok) toast('error', r.errors.map((e) => `${e.message}${e.details?.length ? `\n• ${e.details.slice(0, 5).join('\n• ')}` : ''}`).join('\n')); else toast('success', `Imported "${r.schema!.name}" (${r.schema!.tables.length} tables).${r.summary.length ? `\n${r.summary.join('\n')}` : ''}`); re(); });
  body.querySelector('#exportBtn')!.addEventListener('click', () => downloadBlob('sql-assistant-schemas.json', schemas.exportRegistryJson(), 'application/json'));
  const run = async (fn: () => Promise<void>) => { body.querySelectorAll('button').forEach((b) => b.setAttribute('disabled', '')); try { await fn(); } catch (e) { toast('error', redactSecrets((e as Error).message, vault.knownSecrets())); } re(); };
  body.querySelector('#syncNow')!.addEventListener('click', () => run(async () => { const r = await sync.synchronize(); lastPull = r.pull; lastPush = r.push ? [...r.push.messages, ...r.push.problems].join('\n') : ''; if (r.pull.fileProblem) toast('error', r.pull.fileProblem); }));
  body.querySelector('#pullOnly')!.addEventListener('click', () => run(async () => { lastPull = await sync.pull(); lastPush = ''; }));
  body.querySelector('#publishNow')!.addEventListener('click', () => run(async () => { let r = await sync.push(); if (!r.ok && r.skipped === 'remote-invalid' && confirm(`${r.problems.join(' ')}\nPublish anyway?`)) r = await sync.push({ allowReplacingInvalidRemote: true }); lastPush = [...r.messages, ...r.problems].join('\n'); }));
  body.querySelectorAll<HTMLElement>('[data-cf]').forEach((b) => b.addEventListener('click', () => { sync.resolveConflict(b.dataset.cf!, b.dataset.ch as 'keep-local'); re(); }));
}
function pullHtml(p: PullOutcome): string {
  if (p.fileProblem) return `<div class="issue-box error" id="pullReport"><strong>${esc(p.stage || 'Synchronization failed')}</strong><br>${multiline(p.fileProblem)}</div>`;
  const rows = [...p.migrated.map((m) => `<tr><td>${esc(m.name)}</td><td>${chip('migrated', 'Migration successful')}</td><td class="small">${multiline(migrationMessage(m))}</td></tr>`), ...p.rejected.map((r) => `<tr><td>${esc(r.name)}</td><td>${r.legacy ? chip('failed', 'Migration failed') : chip('invalid', 'Invalid schema')}</td><td class="small">${multiline(rejectionMessage(r))}<details><summary>All ${r.total} problem(s)</summary><ul>${r.errors.map((e) => `<li>${esc(e)}</li>`).join('')}</ul></details></td></tr>`), ...[...p.added, ...p.updated, ...p.unchanged].filter((n) => !p.migrated.some((m) => m.name === n)).map((n) => `<tr><td>${esc(n)}</td><td>${p.remoteLegacy ? chip('legacy', 'Legacy schema') : chip('current', 'Current schema')}</td><td class="small">${p.added.includes(n) ? 'Added' : p.updated.includes(n) ? 'Updated from repository' : 'Up to date'}</td></tr>`)];
  return `<p class="small">Repository file written by: <strong>${esc(p.remoteWriter || '—')}</strong>${p.remoteLegacy ? ` ${chip('legacy', 'Legacy schema')} ${chip('legacy', 'Migration required')}` : ''}</p><table class="grid" id="pullReport"><tbody>${rows.join('') || '<tr><td class="muted">Repository is empty — publishing creates the file.</td></tr>'}</tbody></table>${p.rejected.length ? `<div class="issue-box error">${p.rejected.length} schema(s) in the repository failed validation and were not loaded — your local copies were kept unchanged.</div>` : ''}`;
}
function rows(s: SchemaModel): SchemaEditorRow[] { return s.tables.flatMap((t) => t.columns.map((c) => ({ rowId: `${t.name}::${c.name}`, module: t.module, tableName: t.name, tableDescription: t.description, columnName: c.name, columnDescription: c.description, dataType: c.type as SchemaEditorRow['dataType'], length: c.length ?? null, precision: c.precision ?? null, nullable: c.nullable, alias: c.alias ?? '', decodeText: (c.decode || []).map((d) => `${d.rawValue}=${d.label}`).join('\n'), isPrimaryKey: !!c.isPrimaryKey, isForeignKey: !!c.isForeignKey, fkTable: c.references?.table ?? '', fkColumn: c.references?.column ?? '' }))); }
function manual(body: HTMLElement, re: () => void): void {
  const { schemas } = services(); const reg = schemas.registry(); if (!edId || !schemas.byId(edId)) edId = reg.activeSchemaId; const s = schemas.byId(edId)!; const all = rows(s);
  const row = all.find((r) => r.rowId === selRow) || null; const vis = all.filter((r) => !filt || r.rowId.toLowerCase().includes(filt.toLowerCase())).slice(0, 400); const deps = row ? analyzeDependencies(s, row.tableName, row.columnName) : [];
  body.innerHTML = `<div class="card"><div class="row"><select id="muSchema">${options(reg.schemas.map((x) => x.id), s.id, Object.fromEntries(reg.schemas.map((x) => [x.id, x.name])))}</select><input id="muFilter" placeholder="Filter rows" value="${esc(filt)}"><span class="small muted">Select one row to edit or delete it.</span></div>
  <div class="scroll" style="margin-top:8px"><table class="grid" id="muGrid"><tbody>${vis.map((r) => `<tr data-row="${esc(r.rowId)}" class="${r.rowId === selRow ? 'sel' : ''}"><td>${esc(r.tableName)}</td><td>${esc(r.columnName)}</td><td>${esc(r.dataType)}</td><td>${r.isPrimaryKey ? 'PK' : ''}</td></tr>`).join('')}</tbody></table></div></div>
  ${row ? `<div class="card" id="muForm"><h2>Edit ${esc(row.tableName)}.${esc(row.columnName)}</h2><div class="two"><div><label for="muColumn">Column Name</label><input id="muColumn" value="${esc(row.columnName)}"><label for="muType">Data Type</label><select id="muType">${options(Array.from(new Set([row.dataType, ...VALID_DATA_TYPES, 'VARCHAR2', 'NVARCHAR2', 'CHAR', 'INTEGER', 'CLOB'])), row.dataType)}</select><label><input type="checkbox" id="muNullable"${row.nullable ? ' checked' : ''}> Nullable</label><label for="muDesc">Description</label><textarea id="muDesc">${esc(row.columnDescription)}</textarea></div>
  <div><label><input type="checkbox" id="muPk"${row.isPrimaryKey ? ' checked' : ''}> Primary Key</label><label><input type="checkbox" id="muFk"${row.isForeignKey ? ' checked' : ''}> Foreign Key</label><div class="row"><input id="muFkTable" placeholder="References table" value="${esc(row.fkTable)}"><input id="muFkColumn" placeholder="References column" value="${esc(row.fkColumn)}"></div><label for="muDecode">Decode (CODE=Label per line)</label><textarea id="muDecode" style="min-height:110px">${esc(row.decodeText)}</textarea></div></div>
  <div class="row"><button class="primary" id="muSave">Save row</button><button class="danger" id="muDelete">Delete row</button><button id="muCancel">Cancel</button></div>${deps.length ? `<p class="small muted">Depends on this row: ${esc(deps.map((x) => x.description).join('; '))}</p>` : ''}<div id="muResult"></div></div>` : ''}
  ${changes.length ? `<div class="issue-box ok" id="muChanges">Saved:<ul>${changes.map((c) => `<li>${esc(c)}</li>`).join('')}</ul></div>` : ''}`;
  body.querySelector('#muSchema')!.addEventListener('change', () => { edId = val('muSchema'); selRow = null; re(); });
  body.querySelector('#muFilter')!.addEventListener('change', () => { filt = val('muFilter'); re(); });
  body.querySelectorAll<HTMLElement>('[data-row]').forEach((tr) => tr.addEventListener('click', () => { selRow = tr.dataset.row!; changes = []; re(); }));
  body.querySelector('#muCancel')?.addEventListener('click', () => { selRow = null; re(); });
  body.querySelector('#muSave')?.addEventListener('click', () => { if (!row) return; const ed: SchemaEditorRow = { ...row, columnName: val('muColumn'), dataType: val('muType') as SchemaEditorRow['dataType'], nullable: checked('muNullable'), columnDescription: val('muDesc'), isPrimaryKey: checked('muPk'), isForeignKey: checked('muFk'), fkTable: val('muFkTable'), fkColumn: val('muFkColumn'), decodeText: val('muDecode') };
    const r = schemas.upsertRow(s.id, ed, row.rowId); if (!r.ok) { (body.querySelector('#muResult') as HTMLElement).innerHTML = `<div class="issue-box error">${r.errors.map((e) => `${esc(e.message)}${e.details ? `<ul>${e.details.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>` : ''}`).join('')}</div>`; return; }
    changes = r.changes; selRow = `${ed.tableName}::${ed.columnName.trim()}`; toast('success', 'Row saved and the Active Schema refreshed.'); re(); });
  body.querySelector('#muDelete')?.addEventListener('click', () => { if (!row) return; if (!confirm(deps.length ? `Delete ${row.rowId} and unlink ${deps.length} dependent record(s)?` : `Delete ${row.rowId}?`)) return; const r = schemas.deleteRow(s.id, row.rowId, deps.length > 0); if (!r.ok) { toast('error', r.errors.map((e) => e.message).join(' ')); return; } changes = r.changes; selRow = null; re(); });
}
function vaultTab(body: HTMLElement, re: () => void): void {
  const { vault } = services(); const s = secrets;
  body.innerHTML = `<div class="card"><h2>Secret Vault</h2><p class="small muted">Stored encrypted on this device (AES-256-GCM). The repository copy is encrypted with your Vault Sync Passphrase, which is never stored or uploaded.</p><div class="two"><div><label for="vRepo">GitHub repository (owner/name)</label><input id="vRepo" value="${esc(s.githubRepo)}" style="width:100%"><label for="vBranch">Branch</label><input id="vBranch" value="${esc(s.githubBranch)}"><label for="vToken">GitHub access token</label><input id="vToken" type="password" autocomplete="off" placeholder="${esc(maskSecret(s.githubToken))}" style="width:100%"></div><div><label for="vSchemaPath">Schema file path</label><input id="vSchemaPath" value="${esc(s.schemaPath)}" style="width:100%"><label for="vVaultPath">Vault file path</label><input id="vVaultPath" value="${esc(s.vaultPath)}" style="width:100%"></div></div><button class="primary" id="vSave">Save configuration</button></div>
  <div class="card"><h2>Push Secret Vault to Repository</h2><label for="vPass">Vault Sync Passphrase (min. 10 characters)</label><input id="vPass" type="password" autocomplete="new-password" style="width:320px"><div class="row" style="margin-top:8px"><button id="vPush">Push Secret Vault to Repository</button><button id="vPull">Retrieve Secret Vault from Repository</button></div><div id="vResult"></div></div>`;
  const out = (k: string, m: string) => { (body.querySelector('#vResult') as HTMLElement).innerHTML = `<div class="issue-box ${k}">${esc(redactSecrets(m, vault.knownSecrets()))}</div>`; };
  body.querySelector('#vSave')!.addEventListener('click', async () => { const n: VaultSecrets = { ...s, githubRepo: val('vRepo').trim(), githubBranch: val('vBranch').trim() || 'main', schemaPath: val('vSchemaPath').trim(), vaultPath: val('vVaultPath').trim(), githubToken: val('vToken').trim() || s.githubToken }; if (n.githubRepo && !/^[\w.-]+\/[\w.-]+$/.test(n.githubRepo)) { toast('error', 'Repository must be in the form owner/name.'); return; } try { await vault.save(n); await reloadSecrets(); toast('success', 'Secret Vault saved (encrypted).'); re(); } catch (e) { toast('error', `Encryption failed: ${(e as Error).message}`); } });
  body.querySelector('#vPush')!.addEventListener('click', async () => { const r = repository(); if (!r) { out('error', 'Configure the repository and token first.'); return; } try { const t = await vault.exportEncrypted(val('vPass')); const c = await r.read(s.vaultPath); await r.write(s.vaultPath, t, c?.sha ?? null, 'SQL Assistant: update encrypted Secret Vault'); out('ok', 'Encrypted Secret Vault pushed to the repository.'); } catch (e) { out('error', `Push failed: ${(e as Error).message}`); } });
  body.querySelector('#vPull')!.addEventListener('click', async () => { const r = repository(); if (!r) { out('error', 'Configure the repository and token first.'); return; } try { const f = await r.read(s.vaultPath); if (!f) { out('error', 'No vault file in the repository yet.'); return; } await vault.importEncrypted(f.text, val('vPass')); await reloadSecrets(); out('ok', 'Secret Vault retrieved, decrypted and validated.'); } catch (e) { out('error', `Retrieve failed: ${(e as Error).message}`); } });
}
function aiTab(body: HTMLElement, re: () => void): void {
  const { vault, store } = services(); const c = aiConfig;
  body.innerHTML = `<div class="card"><h2>AI/LLM Model</h2><p class="small muted">Optional. The offline NLU model remains the primary engine; the app keeps working if the AI/LLM Model is unavailable.</p><label><input type="checkbox" id="aiEnabled"${c.enabled ? ' checked' : ''}> Enable AI/LLM Model</label>
  <div class="two"><div><label for="aiProvider">Provider</label><select id="aiProvider">${options(['openai', 'azure-openai', 'anthropic', 'custom'], c.provider)}</select><label for="aiModel">Model</label><input id="aiModel" value="${esc(c.model)}"><label for="aiEndpoint">Endpoint</label><input id="aiEndpoint" value="${esc(c.endpoint || PROVIDER_DEFAULTS[c.provider].endpoint)}" style="width:100%"><label for="aiAuth">Authentication</label><select id="aiAuth">${options(['bearer', 'api-key-header', 'none'], c.authType)}</select><label for="aiKey">API key (stored encrypted)</label><input id="aiKey" type="password" autocomplete="off" placeholder="${esc(maskSecret(secrets.aiApiKey))}"></div>
  <div><label for="aiApiVersion">API version</label><input id="aiApiVersion" value="${esc(c.apiVersion)}"><label for="aiTimeout">Timeout (ms)</label><input id="aiTimeout" type="number" value="${c.timeoutMs}"><label for="aiExtra">Model-specific configuration (JSON)</label><textarea id="aiExtra">${esc(c.extraJson)}</textarea></div></div><button class="primary" id="aiSave">Save</button><div id="aiResult"></div></div>`;
  body.querySelector('#aiProvider')!.addEventListener('change', () => { const p = val('aiProvider') as AiProvider; (body.querySelector('#aiEndpoint') as HTMLInputElement).value = PROVIDER_DEFAULTS[p].endpoint; (body.querySelector('#aiAuth') as HTMLSelectElement).value = PROVIDER_DEFAULTS[p].authType; });
  body.querySelector('#aiSave')!.addEventListener('click', async () => { const cfg = { ...c, enabled: checked('aiEnabled'), provider: val('aiProvider') as AiProvider, model: val('aiModel').trim(), endpoint: val('aiEndpoint').trim(), authType: val('aiAuth') as AiAuth, apiVersion: val('aiApiVersion').trim(), timeoutMs: Number(val('aiTimeout')) || 20000, extraJson: val('aiExtra') }; const key = val('aiKey').trim() || secrets.aiApiKey; const p = validateAiConfig(cfg, key);
    if (p.length) { (body.querySelector('#aiResult') as HTMLElement).innerHTML = `<div class="issue-box error">AI/LLM configuration invalid:<ul>${p.map((x) => `<li>${esc(x)}</li>`).join('')}</ul></div>`; return; }
    try { if (key !== secrets.aiApiKey) { await vault.save({ ...secrets, aiApiKey: key }); await reloadSecrets(); } saveAiConfig(cfg, store); setAiConfig(cfg); toast('success', 'AI/LLM Model configuration saved.'); re(); } catch (e) { toast('error', (e as Error).message); } });
}
