/**
 * Settings (V17.2 UI): password-protected. Lock screen → tabs
 *   Security · Manual Schema Update · Schema Management · Secret Vault · Synchronization · AI/LLM Model · Danger Zone
 * Unlocking requires the Admin Password (default "admin" until changed). Settings re-lock after 5 minutes of inactivity.
 */
import { icon } from '../components/icons'; import { adminLibraryTab } from './adminLibrary'; import { adminPassphraseHtml, wireAdminPassphrase } from './schemaPassphraseAdmin'; import { adminMessagePanelHtml, wireAdminMessage } from './adminMessagePanel'; import { MIGRATION_DESCRIPTIONS } from '../../v17/services/migrations'; import { TIER_LABEL } from '../../v17/services/learningStore'; import { pingModel } from '../../v17/services/aiLlmService'; import { knowledgePathFor } from '../../v17/services/knowledgeSync'; import { renderTabs } from '../components/tabs'; import { openModal } from '../components/modal'; import { renderDataTable } from '../components/dataTable';
import { store } from '../state'; import { services, secrets, reloadSecrets, repository, aiConfig, setAiConfig, vaultProblem } from '../context'; import { e, options } from '../dom';
import { verifyPassword, changePassword, isUsingDefaultPassword, resetPasswordToDefault } from '../../services/passwordService';
import { legacyLeftovers, checkRegistry, serializeRegistry, describeIssue, validateSchemaModel } from '../../v17/sync/schemaFormat';
import { rejectionMessage, migrationMessage, type PullOutcome } from '../../v17/sync/syncService';
import { analyzeDependencies, rowsOf, diffRows } from '../../v17/engines/schemaRecordEngine';
import { maskSecret, CANONICAL_SCHEMA_PATH, type VaultSecrets } from '../../v17/services/secretVault';
import { validateAiConfig, saveAiConfig, PROVIDER_DEFAULTS, type AiProvider, type AiAuth } from '../../v17/services/aiLlmService';
import { redactSecrets } from '../../v17/errors/appErrors';
import { downloadBlob } from '../../utils/dom';
import { getSyncPrefs, setSyncSource, setSyncTime, SRC, TIME, type SyncSource, type SyncTimeOption } from '../syncPrefs';
import type { SchemaEditorRow, SchemaModel } from '../../types';
type Tab = 'security' | 'manual-update' | 'schema-management' | 'vault' | 'synchronization' | 'admin-library' | 'ai' | 'danger';
const TABS: [Tab, string][] = [['security', 'Security'], ['manual-update', 'Manual Schema Update'], ['schema-management', 'Schema Management'], ['vault', 'Secret Vault'], ['synchronization', 'Synchronization'], ['admin-library', 'Admin Query Library'], ['ai', 'AI/LLM Model'], ['danger', 'Danger Zone']];
export const SETTINGS_TAB_IDS = TABS.map(([t]) => t);
let knowledgeResult = ''; let lastPull: PullOutcome | null = null; let lastAdvanced = ''; let edSchemaId: string | null = null; let edModule = ''; let edTable = ''; let selectedRowId: string | null = null; let lastChanges: string[] = [];
let sharedDir: any = null; let sharedResult = '';
const msgBox = (kind: 'ok' | 'warn' | 'err', html: string, id = '') => `<div class="issue-box ${kind === 'ok' ? 'ok' : kind === 'warn' ? 'warn' : ''} mini"${id ? ` id="${id}"` : ''}>${icon(kind === 'ok' ? 'check' : 'alert-triangle', 14)}<div class="pre-line">${html}</div></div>`;
const knownSecrets = () => services().vault.knownSecrets();
export function renderSettingsPage(c: HTMLElement): void { if (!store.settingsUnlocked) lockScreen(c); else unlocked(c); }
function lockScreen(c: HTMLElement): void {
  c.innerHTML = `<div class="page page-settings-lock"><div class="settings-lock-card" data-tour="settings-lock-screen"><div class="settings-lock-icon">${icon('lock', 26)}</div><h1 class="page-title" style="justify-content:center">Settings</h1><p class="hint">Settings are password protected. Enter the Admin Password to unlock Security, Manual Schema Update, Schema Management, Secret Vault, Synchronization, Admin Query Library, AI/LLM Model and Danger Zone.</p><label class="block-label" style="text-align:left">Admin Password<input type="password" id="settingsPwInput" autocomplete="current-password"></label><div id="settingsPwError"></div><div class="row-actions"><button type="button" class="btn btn-primary" id="settingsUnlockBtn">${icon('unlock', 15)} Unlock Settings</button></div>${isUsingDefaultPassword() ? '<p class="hint mt">First use: the default password is <code>admin</code>. Change it under Security after unlocking.</p>' : ''}</div></div>`;
  const input = c.querySelector<HTMLInputElement>('#settingsPwInput')!; const err = c.querySelector<HTMLElement>('#settingsPwError')!; const btn = c.querySelector<HTMLButtonElement>('#settingsUnlockBtn')!;
  const go = async () => { btn.disabled = true; err.innerHTML = '';
    try { if (!(await verifyPassword(input.value))) { err.innerHTML = msgBox('err', 'Incorrect password. Settings remain locked.'); input.select(); return; }
      const pw = input.value; store.settingsTab = store.settingsTab || 'security'; store.unlockSettings();
      try { if (await services().vault.migrateFromV172(pw)) { await reloadSecrets(); store.pushToast('success', 'Secret Vault settings from SQL Assistant V17.2 were found on this device and imported.'); } } catch { /* nothing to migrate */ }
      if (isUsingDefaultPassword()) store.pushToast('warning', 'The default Admin Password "admin" is still in use — change it under Settings → Security.');
    } finally { btn.disabled = false; } };
  btn.addEventListener('click', () => { void go(); }); input.addEventListener('keydown', (ev) => { if (ev.key === 'Enter') void go(); }); setTimeout(() => input.focus(), 0);
}
function unlocked(c: HTMLElement): void {
  c.innerHTML = `<div class="page"><div class="settings-header-row"><h1 class="page-title">${icon('settings')} Settings</h1><button type="button" class="btn btn-outline btn-sm" id="lockSettingsBtn">${icon('lock', 14)} Lock Settings</button></div><p class="page-subtitle">Unlocked. Settings lock automatically after 5 minutes of inactivity.</p>${vaultProblem ? msgBox('err', `${e(vaultProblem)}`) : ''}${isUsingDefaultPassword() ? msgBox('warn', 'The default Admin Password <code>admin</code> is still in use. Change it under Security.') : ''}<div class="settings-tabs-scroll" id="settingsTabsMount"></div></div>`;
  c.querySelector('#lockSettingsBtn')!.addEventListener('click', () => { store.lockSettings(); store.pushToast('info', 'Settings locked.'); });
  const renderers: Record<Tab, (p: HTMLElement) => void> = { security, 'manual-update': manualUpdate, 'schema-management': schemaManagement, vault: vaultTab, synchronization: syncTab, 'admin-library': adminLibraryTab, ai: aiTab, danger: dangerZone };
  renderTabs(c.querySelector<HTMLElement>('#settingsTabsMount')!, TABS.map(([id, label]) => ({ id, label, render: renderers[id] })), store.settingsTab, {}, (id) => { store.settingsTab = id; lastAdvanced = ''; lastPull = null; sharedResult = ''; knowledgeResult = ''; });
}
async function requirePassword(p: HTMLElement, inputSel: string, errSel: string): Promise<boolean> { const ok = await verifyPassword(p.querySelector<HTMLInputElement>(inputSel)?.value || ''); const err = p.querySelector<HTMLElement>(errSel); if (err) err.innerHTML = ok ? '' : msgBox('err', 'Incorrect Admin Password — nothing was changed.'); return ok; }
// ───────── Security ─────────
function security(p: HTMLElement): void {
  p.innerHTML = `<div class="advanced-grid"><div class="builder-panel"><h2>${icon('key', 16)} Change Admin Password</h2><p class="hint">The Admin Password protects Settings. It is never stored — only an encrypted verification marker (PBKDF2-SHA-256 + AES-256-GCM).</p><label class="block-label">Current password<input type="password" id="pwCurrent" autocomplete="current-password"></label><label class="block-label">New password (min. 4 characters)<input type="password" id="pwNew" autocomplete="new-password"></label><label class="block-label">Confirm new password<input type="password" id="pwConfirm" autocomplete="new-password"></label><div class="row-actions"><button type="button" class="btn btn-primary" id="changePwBtn">${icon('save', 14)} Change Password</button></div><div id="pwResult"></div></div>
    <div class="builder-panel"><h2>${icon('shield', 16)} Session</h2><ul><li>Password status: <strong>${isUsingDefaultPassword() ? 'default password in use (change it)' : 'custom password set'}</strong></li><li>Automatic lock: after 5 minutes of inactivity</li><li>Secret Vault on this device: AES-256-GCM, non-extractable device key</li><li>Repository copy of the vault: AES-256-GCM, key from your Vault Sync Passphrase (never stored)</li></ul><div class="row-actions"><button type="button" class="btn btn-outline" id="lockNowBtn">${icon('lock', 14)} Lock now</button></div></div></div>`;
  p.querySelector('#lockNowBtn')!.addEventListener('click', () => { store.lockSettings(); store.pushToast('info', 'Settings locked.'); });
  p.querySelector('#changePwBtn')!.addEventListener('click', async () => { const v = (id: string) => p.querySelector<HTMLInputElement>(id)!.value; const out = p.querySelector<HTMLElement>('#pwResult')!;
    if (v('#pwNew') !== v('#pwConfirm')) { out.innerHTML = msgBox('err', 'The new passwords do not match.'); return; }
    const r = await changePassword(v('#pwCurrent'), v('#pwNew')); out.innerHTML = r.ok ? msgBox('ok', 'Admin Password changed.') : msgBox('err', e(r.error || 'The password could not be changed.'));
    if (r.ok) { ['#pwCurrent', '#pwNew', '#pwConfirm'].forEach((s) => { p.querySelector<HTMLInputElement>(s)!.value = ''; }); store.pushToast('success', 'Admin Password changed.'); } });
}
// ───────── Manual Schema Update (row-wise) ─────────
function manualUpdate(p: HTMLElement): void {
  const { schemas } = services(); const reg = schemas.registry(); if (!edSchemaId || !schemas.byId(edSchemaId)) edSchemaId = reg.activeSchemaId; const s = schemas.byId(edSchemaId)!;
  const modules = Array.from(new Set(s.tables.map((t) => t.module))).sort(); if (edModule && !modules.includes(edModule)) edModule = '';
  const tables = s.tables.filter((t) => !edModule || t.module === edModule).map((t) => t.name); if (edTable && !tables.includes(edTable)) edTable = '';
  const rows = rowsOf(s).filter((r) => (!edModule || r.module === edModule) && (!edTable || r.tableName === edTable)); if (selectedRowId && !rows.some((r) => r.rowId === selectedRowId)) selectedRowId = null;
  const sel = rows.find((r) => r.rowId === selectedRowId) || null;
  p.innerHTML = `<div class="editing-schema-banner">${icon('edit', 14)} Editing schema <strong>${e(s.name)}</strong>${s.id === reg.activeSchemaId ? ' <span class="chip chip-active">Active</span>' : ''} — every saved change is validated, stored centrally and refreshes the Active Schema immediately.</div>
    <div class="form-row-3"><label class="block-label">Schema<select id="editorSchemaSelect">${options(reg.schemas.map((x) => x.id), s.id, Object.fromEntries(reg.schemas.map((x) => [x.id, x.name])))}</select></label><label class="block-label">Module<select id="editorModuleSelect"><option value="">All Modules</option>${options(modules, edModule)}</select></label><label class="block-label">Table<select id="editorTableSelect"><option value="">All Tables</option>${options(tables, edTable)}</select></label></div>
    <div class="row-actions mu-table-bar"><span id="selectedRowLabel" class="hint">${sel ? `Selected row: <strong>${e(sel.tableName)}.${e(sel.columnName)}</strong>` : 'No row selected — select one row to edit or delete it.'}</span><span style="flex:1"></span><button type="button" class="btn btn-outline btn-sm" id="addRowBtn">${icon('plus', 14)} Add Row</button><button type="button" class="btn btn-primary btn-sm" id="editRowBtn" ${sel ? '' : 'disabled'}>${icon('edit', 14)} Edit Selected Row</button><button type="button" class="btn btn-danger btn-sm" id="deleteRowBtn" ${sel ? '' : 'disabled'}>${icon('trash', 14)} Delete Selected Row</button></div>
    <div id="editorTableMount" class="mt"></div>${lastChanges.length ? `<div class="issue-box ok mini" id="muChanges">${icon('check', 14)}<div>Saved to the centralized schema. The Active Schema, SQL generation and the offline NLU knowledge were refreshed:<ul>${lastChanges.map((x) => `<li>${e(x)}</li>`).join('')}</ul></div></div>` : ''}`;
  const re = () => manualUpdate(p);
  p.querySelector('#editorSchemaSelect')!.addEventListener('change', (ev) => { edSchemaId = (ev.target as HTMLSelectElement).value; edModule = ''; edTable = ''; selectedRowId = null; lastChanges = []; re(); });
  p.querySelector('#editorModuleSelect')!.addEventListener('change', (ev) => { edModule = (ev.target as HTMLSelectElement).value; edTable = ''; re(); });
  p.querySelector('#editorTableSelect')!.addEventListener('change', (ev) => { edTable = (ev.target as HTMLSelectElement).value; re(); });
  renderDataTable<SchemaEditorRow>(p.querySelector<HTMLElement>('#editorTableMount')!, { rows, getRowId: (r) => r.rowId.replace('::', ''), selectedRowId: selectedRowId ? selectedRowId.replace('::', '') : null, pageSize: 50, emptyMessage: 'No rows in this selection.',
    searchPredicate: (r, t) => `${r.tableName} ${r.columnName} ${r.columnDescription} ${r.module}`.toLowerCase().includes(t),
    columns: [{ key: 'module', label: 'Module', sortValue: (r) => r.module }, { key: 'tableName', label: 'Table', sortValue: (r) => r.tableName }, { key: 'columnName', label: 'Column', sortValue: (r) => r.columnName, render: (r) => `<strong>${e(r.columnName)}</strong>` }, { key: 'dataType', label: 'Type' }, { key: 'nullable', label: 'Null', render: (r) => (r.nullable ? 'Y' : 'N') }, { key: 'keys', label: 'Keys', render: (r) => `${r.isPrimaryKey ? 'PK ' : ''}${r.isForeignKey ? `FK→${e(r.fkTable)}` : ''}` }, { key: 'decodeText', label: 'Decode', render: (r) => e(r.decodeText.split('\n').slice(0, 2).join('; ') + (r.decodeText.split('\n').length > 2 ? '…' : '')) }, { key: 'columnDescription', label: 'Description' }],
    onRowClick: (r) => { selectedRowId = r.rowId; lastChanges = []; const lbl = p.querySelector('#selectedRowLabel'); if (lbl) lbl.innerHTML = `Selected row: <strong>${e(r.tableName)}.${e(r.columnName)}</strong>`; (p.querySelector('#editRowBtn') as HTMLButtonElement).disabled = false; (p.querySelector('#deleteRowBtn') as HTMLButtonElement).disabled = false; } });
  p.querySelector('#editRowBtn')!.addEventListener('click', () => { const r = rowsOf(s).find((x) => x.rowId === selectedRowId); if (r) rowEditor(s, r, re); });
  p.querySelector('#addRowBtn')!.addEventListener('click', () => rowEditor(s, { rowId: '', module: edModule || modules[0] || 'General', tableName: edTable || '', tableDescription: '', columnName: '', columnDescription: '', dataType: 'VARCHAR2', length: null, precision: null, nullable: true, alias: '', decodeText: '', isPrimaryKey: false, isForeignKey: false, fkTable: '', fkColumn: '' }, re, true));
  p.querySelector('#deleteRowBtn')!.addEventListener('click', () => { const r = rowsOf(s).find((x) => x.rowId === selectedRowId); if (r) rowDelete(s, r, re); });
}
function rowEditor(s: SchemaModel, row: SchemaEditorRow, done: () => void, isNew = false): void {
  const types = Array.from(new Set([row.dataType, 'VARCHAR2', 'NVARCHAR2', 'VARCHAR', 'CHAR', 'NUMBER', 'INTEGER', 'DATE', 'TIMESTAMP', 'CLOB', 'BLOB', 'FLAG'].filter(Boolean)));
  const f = (id: string, label: string, v: string, extra = '') => `<label class="block-label">${label}<input type="text" id="f_${id}" value="${e(v)}" ${extra}></label>`;
  const m = openModal(`${icon('edit', 18)} ${isNew ? 'Add Row' : 'Edit Selected Row'}`, `${isNew ? '' : `<div class="editing-schema-banner" data-v172-selected-row>${icon('table', 14)} Table <strong>${e(row.tableName)}</strong> · Column <strong>${e(row.columnName)}</strong> · Schema <strong>${e(s.name)}</strong></div>`}
    <div class="form-row-2">${f('tableName', 'Table Name *', row.tableName, isNew ? '' : 'readonly')}${f('columnName', 'Column Name *', row.columnName)}</div><div class="form-row-3"><label class="block-label">Data Type *<select id="f_dataType">${options(types, row.dataType)}</select></label>${f('length', 'Length', row.length === null ? '' : String(row.length), 'inputmode="numeric"')}${f('precision', 'Precision', row.precision === null ? '' : String(row.precision), 'inputmode="numeric"')}</div>
    <div class="form-row-3"><label class="inline-check"><input type="checkbox" id="f_nullable" ${row.nullable ? 'checked' : ''}> Nullable</label><label class="inline-check"><input type="checkbox" id="f_isPrimaryKey" ${row.isPrimaryKey ? 'checked' : ''}> Primary Key</label><label class="inline-check"><input type="checkbox" id="f_isForeignKey" ${row.isForeignKey ? 'checked' : ''}> Foreign Key</label></div>
    <div class="form-row-3">${f('fkTable', 'References Table', row.fkTable)}${f('fkColumn', 'References Column', row.fkColumn)}${f('alias', 'Alias', row.alias)}</div>
    <label class="block-label">Column Description<textarea id="f_columnDescription" rows="2">${e(row.columnDescription)}</textarea></label><label class="block-label">Decode (one per line: CODE=Label)<textarea id="f_decodeText" rows="4" style="font-family:Consolas,monospace">${e(row.decodeText)}</textarea></label>
    <div class="form-row-2">${f('module', 'Module <span class="chip chip-inactive" style="font-size:10px">applies to the whole table</span>', row.module)}${f('tableDescription', 'Table Description <span class="chip chip-inactive" style="font-size:10px">applies to the whole table</span>', row.tableDescription)}</div>
    <h5 class="mt">Current → modified</h5><div data-v172-row-changes class="hint">No changes.</div><div id="rowFormIssues"></div>
    <div class="modal-actions"><button type="button" class="btn btn-ghost" id="rowFormCancel">Cancel</button><button type="button" class="btn btn-outline" id="rowFormReset">${icon('refresh', 14)} Reset</button><button type="button" class="btn btn-primary" id="rowFormSave" disabled>${icon('save', 14)} Save</button></div>`, { wide: true, closeOnBackdrop: false });
  const el = m.element; const g = (id: string) => el.querySelector<HTMLInputElement>(`#f_${id}`)!;
  const read = (): SchemaEditorRow => { const n = (id: string) => { const v = g(id).value.trim(); return v === '' ? null : Number(v); }; return { ...row, tableName: g('tableName').value.trim(), columnName: g('columnName').value.trim(), dataType: (el.querySelector('#f_dataType') as HTMLSelectElement).value, length: n('length'), precision: n('precision'), nullable: g('nullable').checked, isPrimaryKey: g('isPrimaryKey').checked, isForeignKey: g('isForeignKey').checked, fkTable: g('fkTable').value.trim(), fkColumn: g('fkColumn').value.trim(), alias: g('alias').value.trim(), columnDescription: (el.querySelector('#f_columnDescription') as HTMLTextAreaElement).value, decodeText: (el.querySelector('#f_decodeText') as HTMLTextAreaElement).value, module: g('module').value.trim(), tableDescription: g('tableDescription').value }; };
  const LABEL: Record<string, string> = { columnName: 'Column Name', dataType: 'Data Type', length: 'Length', precision: 'Precision', nullable: 'Nullable', alias: 'Alias', decodeText: 'Decode', isPrimaryKey: 'Primary Key', isForeignKey: 'Foreign Key', fkTable: 'References Table', fkColumn: 'References Column', columnDescription: 'Column Description', module: 'Module', tableDescription: 'Table Description', tableName: 'Table Name' };
  const refresh = () => { const d = diffRows(row, read()); el.querySelector('[data-v172-row-changes]')!.innerHTML = d.length ? `<ul>${d.map((x) => `<li><strong>${e(LABEL[x.field] || x.field)}</strong>${x.tableLevel ? ' (all columns of the table)' : ''}: <span>${e(x.from || '(empty)')}</span> → <span>${e(x.to || '(empty)')}</span></li>`).join('')}</ul>` : 'No changes.'; (el.querySelector('#rowFormSave') as HTMLButtonElement).disabled = !d.length; };
  el.querySelectorAll('input, select, textarea').forEach((x) => { x.addEventListener('input', refresh); x.addEventListener('change', refresh); });
  el.querySelector('#rowFormCancel')!.addEventListener('click', () => m.close());
  el.querySelector('#rowFormReset')!.addEventListener('click', () => { m.close(); rowEditor(s, row, done, isNew); });
  el.querySelector('#rowFormSave')!.addEventListener('click', () => { const next = read(); const r = services().schemas.upsertRow(s.id, next, isNew ? null : row.rowId);
    if (!r.ok) { el.querySelector('#rowFormIssues')!.innerHTML = msgBox('err', r.errors.map((x) => `${e(x.message)}${x.details?.length ? `\n• ${x.details.map(e).join('\n• ')}` : ''}`).join('\n')); return; }
    lastChanges = r.changes; selectedRowId = `${next.tableName}::${next.columnName}`; m.close(); store.pushToast('success', 'Row saved, validated, and the Active Schema was refreshed.'); done(); });
}
function rowDelete(s: SchemaModel, row: SchemaEditorRow, done: () => void): void {
  const deps = analyzeDependencies(s, row.tableName, row.columnName);
  const m = openModal(`${icon('trash', 18)} Delete Selected Row`, `<div id="delStep"></div>`, { closeOnBackdrop: false }); const step = m.element.querySelector<HTMLElement>('#delStep')!;
  const s1 = () => { step.innerHTML = `<p>Delete <strong>${e(row.tableName)}.${e(row.columnName)}</strong> from schema <strong>${e(s.name)}</strong>? Only this row is removed.</p><div class="modal-actions"><button type="button" class="btn btn-ghost" id="c1Cancel">Cancel</button><button type="button" class="btn btn-danger" id="c1Continue">Continue</button></div>`; step.querySelector('#c1Cancel')!.addEventListener('click', () => m.close()); step.querySelector('#c1Continue')!.addEventListener('click', s2); };
  const s2 = () => { step.innerHTML = `${deps.length ? `<div class="issue-box warn mini">${icon('alert-triangle', 14)}<div>These dependent records will also be removed or unlinked:<ul>${deps.map((d) => `<li>${e(d.description)}</li>`).join('')}</ul></div></div>` : '<p class="hint">No other schema records depend on this row.</p>'}<div class="modal-actions"><button type="button" class="btn btn-ghost" id="c2Back">Back</button><button type="button" class="btn btn-danger" id="c2Continue">Continue</button></div>`; step.querySelector('#c2Back')!.addEventListener('click', s1); step.querySelector('#c2Continue')!.addEventListener('click', s3); };
  const s3 = () => { step.innerHTML = `<label class="block-label">Confirm with the Admin Password<input type="password" id="c3Password" autocomplete="current-password"></label><div id="c3Error"></div><div class="modal-actions"><button type="button" class="btn btn-ghost" id="c3Cancel">Cancel</button><button type="button" class="btn btn-danger" id="c3Delete">${icon('trash', 14)} Delete Row</button></div>`; step.querySelector('#c3Cancel')!.addEventListener('click', () => m.close());
    step.querySelector('#c3Delete')!.addEventListener('click', async () => { if (!(await requirePassword(step, '#c3Password', '#c3Error'))) return; const r = services().schemas.deleteRow(s.id, row.rowId, deps.length > 0); if (!r.ok) { step.querySelector('#c3Error')!.innerHTML = msgBox('err', e(r.errors.map((x) => `${x.message} ${(x.details || []).join(' ')}`).join(' '))); return; } lastChanges = r.changes; selectedRowId = null; m.close(); store.pushToast('success', 'Row deleted and the Active Schema was refreshed.'); done(); }); };
  s1();
}
// ───────── Schema Management ─────────
function pullHtml(o: PullOutcome): string {
  if (o.fileProblem) return msgBox('err', `<strong>Synchronization failed at stage: ${e(o.stage || 'unknown')}</strong>\n${e(o.fileProblem)}\nYour local schemas and the Active Schema were not changed. Fix the cause and press Sync with GitHub Now to retry.`);
  const lines: string[] = [];
  o.migrated.forEach((x) => lines.push(`<div class="conflict-card"><div class="conflict-card-head">${icon('refresh', 14)} <strong>${e(x.name)}</strong> <span class="chip chip-migrated">Migration successful</span></div><div class="pre-line hint">${e(migrationMessage(x))}</div></div>`));
  o.rejected.forEach((x) => lines.push(`<div class="conflict-card"><div class="conflict-card-head">${icon('alert-triangle', 14)} <strong>${e(x.name)}</strong> <span class="chip chip-invalid">${x.legacy ? 'Migration failed' : 'Invalid schema'}</span></div><div class="pre-line hint">${e(rejectionMessage(x))}</div><details><summary class="hint">All ${x.total} problem(s)</summary><ul>${x.errors.map((m) => `<li>${e(m)}</li>`).join('')}${x.total > x.errors.length ? `<li>…and ${x.total - x.errors.length} more</li>` : ''}</ul></details></div>`));
  const plain = [...o.added.map((n) => [n, 'Added']), ...o.updated.map((n) => [n, 'Updated from repository']), ...o.unchanged.map((n) => [n, 'Up to date']), ...o.localAhead.map((n) => [n, 'Newer on this device — published'])].filter(([n]) => !o.migrated.some((x) => x.name === n));
  return `<div id="pullReport"><p class="hint">Repository file: <code>${e(o.path)}</code> · written by <strong>${e(o.remoteWriter || '—')}</strong>${o.remoteLegacy ? ' <span class="chip chip-legacy">Legacy schema</span> <span class="chip chip-legacy">Migration required</span>' : ''}${o.activeChanged ? ' <span class="chip chip-active">Active Schema refreshed</span>' : ''}</p>${plain.length ? `<ul>${plain.map(([n, t]) => `<li><strong>${e(n)}</strong> — ${e(t)}${o.remoteLegacy && t === 'Up to date' ? '' : ''}</li>`).join('')}</ul>` : ''}${o.remoteMissing ? '<p class="hint">The repository has no schema file yet — publishing creates it.</p>' : ''}<div class="conflict-banner-wrap">${lines.join('')}</div>${o.rejected.length ? msgBox('err', `${o.rejected.length} schema(s) in the repository failed validation and were not loaded — your local copies were kept unchanged.`) : msgBox('ok', 'Synchronization finished.')}</div>`;
}
function schemaManagement(p: HTMLElement): void {
  const { schemas, sync } = services(); const reg = schemas.registry(); const d = schemas.loadDiagnostics; const meta = sync.meta(); const health = reg.schemas.map((s) => ({ s, v: validateSchemaModel(s) })).filter((x) => !x.v.valid);
  p.innerHTML = `<div class="builder-panel"><h2>${icon('folder-sync', 16)} Repository synchronization</h2><p class="hint">Download → detect format → migrate legacy schemas → validate → save → refresh Active Schema → publish in the current format. Invalid repository data never replaces a valid local schema.</p>
    <div class="editing-schema-banner">${icon('github', 14)} ${e(secrets.githubOwner && secrets.githubRepo ? `${secrets.githubOwner}/${secrets.githubRepo}` : 'Repository not configured')} · ${e(secrets.githubBranch)} · <code>${e(secrets.schemaPath)}</code> · last download ${e(meta.lastPullAt?.replace('T', ' ').slice(0, 16) || 'never')}<button type="button" class="btn btn-primary btn-sm sync-now-inline-btn" id="simpleSyncBtn">${icon('refresh', 14)} Sync with GitHub Now</button></div>
    <div id="simpleSyncResult">${lastPull ? pullHtml(lastPull) : ''}</div><div id="syncErrorMount"></div>
    ${sync.conflicts().length ? `<div class="conflict-banner-wrap"><div class="conflict-banner-head">${icon('shield-alert', 16)} ${sync.conflicts().length} unresolved synchronization conflict(s)</div>${sync.conflicts().map((x) => `<div class="conflict-card"><div class="conflict-card-head">${icon('shield-alert', 15)} <strong>${e(x.schemaName)}</strong></div><p class="hint">Changed on this device and in the repository · detected ${e(new Date(x.detectedAt).toLocaleString())}</p><div class="row-actions"><button type="button" class="btn btn-outline btn-sm" data-cf="${e(x.id)}" data-ch="keep-local">Use Local (keep my changes)</button><button type="button" class="btn btn-outline btn-sm" data-cf="${e(x.id)}" data-ch="take-remote">Use Remote (apply theirs)</button></div></div>`).join('')}</div>` : ''}
    <div id="schemaHealthMount">${health.length ? `<div class="issue-box">${icon('alert-triangle', 15)}<div><strong>${health.length} local schema(s) do not pass validation and will not be published:</strong><ul>${health.map((h) => `<li>${e(h.s.name)}: ${e(h.v.errors.slice(0, 3).map(describeIssue).join(' '))}</li>`).join('')}</ul></div></div>` : ''}</div>
    ${d.recoveredFrom.length ? msgBox('ok', 'Schemas saved by SQL Assistant V17.2.1 / V17.2.2 / V17.3 on this device were recovered into the standard storage.') : ''}${d.unreadable ? msgBox('err', `The schemas stored on this device could not be read (${e(d.unreadable)}). Default schemas were loaded; the original data was kept as <code>${e(d.backupKey || '')}</code>. Use Sync with GitHub Now to recover from the repository.`) : ''}</div>
  ${adminPassphraseHtml()}
  <h2 class="section-title">${icon('database')} Stored Schemas</h2><div class="schema-list">${reg.schemas.map((s) => { const l = legacyLeftovers(s); return `<div class="schema-card ${s.id === reg.activeSchemaId ? 'is-active' : ''}" data-schema-row="${e(s.name)}"><div class="schema-card-head"><h3>${e(s.name)}</h3><span class="chip ${s.id === reg.activeSchemaId ? 'chip-active' : 'chip-inactive'}">${s.id === reg.activeSchemaId ? 'Active' : 'Inactive'}</span></div><p class="hint">${s.tables.length} tables · last synced ${e(s.lastSyncedAt?.replace('T', ' ').slice(0, 16) || 'never')}</p><div class="chip-row">${s.migration ? `<span class="chip chip-migrated" title="Migrated from ${e(s.migration.fromFormat)}">Migrated schema</span>` : '<span class="chip">Current schema</span>'}${l.unmappedLabels ? `<span class="chip chip-legacy">${l.unmappedLabels} decode label(s) without code</span>` : ''}${l.unresolvedRefs ? `<span class="chip chip-inactive">${l.unresolvedRefs} reference(s) outside schema</span>` : ''}</div>
      <div class="row-actions">${s.id !== reg.activeSchemaId ? `<button type="button" class="btn btn-primary btn-sm" data-activate="${e(s.id)}">${icon('check', 14)} Set Active</button>` : ''}<button type="button" class="btn btn-outline btn-sm" data-rename="${e(s.id)}">${icon('edit', 14)} Rename</button><button type="button" class="btn btn-outline btn-sm" data-export="${e(s.id)}">${icon('download', 14)} Export</button>${l.unmappedLabels ? `<button type="button" class="btn btn-outline btn-sm" data-recover="${e(s.id)}">${icon('wand', 14)} Recover decode codes</button>` : ''}<button type="button" class="icon-btn" data-del="${e(s.id)}" aria-label="Delete schema">${icon('trash', 15)}</button></div></div>`; }).join('')}</div><input type="file" id="recoverFile" accept=".json" hidden>
  <h2 class="section-title">${icon('file-plus')} Add or Import a Schema</h2><div class="advanced-grid"><div class="builder-panel"><h2>${icon('plus', 16)} New empty schema</h2><label class="block-label">Schema name<input type="text" id="newSchemaName"></label><div class="row-actions"><button type="button" class="btn btn-outline" id="addSchemaBtn">${icon('plus', 14)} Add Schema</button></div></div><div class="builder-panel"><h2>${icon('upload', 16)} Import schema file (JSON, any SQL Assistant version)</h2><label class="block-label">File<input type="file" id="importFile" accept=".json,application/json"></label><label class="block-label">Schema name<input type="text" id="importName" placeholder="Name shown in SQL Assistant"></label><div class="row-actions"><button type="button" class="btn btn-primary" id="importBtn">${icon('upload', 14)} Import</button></div><div id="importResult"></div></div></div>
  <details class="advanced-sync-details mt"><summary>${icon('sliders', 14)} Advanced synchronization &amp; recovery</summary><div class="row-actions"><button type="button" class="btn btn-outline btn-sm" id="pullRegistryBtn">${icon('download', 14)} Restore from repository (pull only)</button><button type="button" class="btn btn-outline btn-sm" id="pushRegistryBtn">${icon('upload', 14)} Push All Schemas</button><button type="button" class="btn btn-outline btn-sm" id="validateRepoBtn">${icon('clipboard-check', 14)} Validate repository file</button><button type="button" class="btn btn-outline btn-sm" id="downloadRepoBtn">${icon('download', 14)} Download repository file</button><button type="button" class="btn btn-outline btn-sm" id="publishLocalBtn">${icon('upload', 14)} Publish my local copies</button><button type="button" class="btn btn-outline btn-sm" id="exportAllBtn">${icon('download', 14)} Export all schemas</button></div><div id="registrySyncResult">${lastAdvanced}</div></details>`;
  const re = () => schemaManagement(p); wireAdminPassphrase(p, re);
  const run = async (fn: () => Promise<void>) => { p.querySelectorAll('button').forEach((b) => b.setAttribute('disabled', '')); try { await fn(); } catch (err) { lastAdvanced = msgBox('err', `Unexpected error: ${e(redactSecrets((err as Error).message, knownSecrets()))}`); } re(); };
  p.querySelector('#simpleSyncBtn')!.addEventListener('click', () => run(async () => { void services().adminMessage.synchronize().catch(() => undefined); const r = await sync.synchronize(); lastPull = r.pull; lastAdvanced = r.push ? msgBox(r.push.ok ? 'ok' : 'warn', e([...r.push.messages, ...r.push.problems].join('\n'))) : '';
    if (r.pull.fileProblem) store.pushToast('error', `Synchronization failed — ${r.pull.stage}.`); else if (r.pull.migrated.length) store.pushToast('success', 'Legacy schema migrated, validated and synchronized.'); else if (r.pull.rejected.length) store.pushToast('warning', `${r.pull.rejected.length} repository schema(s) failed validation; your local copies were kept.`); else store.pushToast('success', 'Schemas synchronized.'); }));
  p.querySelector('#pullRegistryBtn')!.addEventListener('click', () => run(async () => { lastPull = await sync.pull(); lastAdvanced = ''; }));
  p.querySelector('#pushRegistryBtn')!.addEventListener('click', () => run(async () => { const r = await sync.push(); lastAdvanced = msgBox(r.ok ? 'ok' : 'err', e([...r.messages, ...r.problems.map((x) => `${r.stage ? `${r.stage}: ` : ''}${x}`)].join('\n'))); }));
  p.querySelector('#publishLocalBtn')!.addEventListener('click', () => run(async () => { if (!confirm('Replace the repository schema file with the schemas on this device? Every schema is validated first.')) return; const r = await sync.push({ allowReplacingInvalidRemote: true }); lastAdvanced = msgBox(r.ok ? 'ok' : 'err', e([...r.messages, ...r.problems].join('\n'))); }));
  p.querySelector('#validateRepoBtn')!.addEventListener('click', () => run(async () => { const v = await sync.validateRemote(); lastAdvanced = msgBox(v.ok ? 'ok' : 'err', e(`${v.ok ? 'Repository file is valid. ' : `${v.stage}: `}${v.message}${v.report ? `\n${v.report.invalidSchemas.map((x) => `✗ ${x.name}: ${x.errors.slice(0, 3).map(describeIssue).join('; ')}${x.errors.length > 3 ? ` …and ${x.errors.length - 3} more` : ''}`).join('\n')}` : ''}`)); }));
  p.querySelector('#downloadRepoBtn')!.addEventListener('click', () => run(async () => { const t = await sync.downloadRemoteText(); if (t === null) { lastAdvanced = msgBox('warn', 'No repository file to download (not configured or not found).'); return; } downloadBlob('repository-registry.json', t, 'application/json'); lastAdvanced = msgBox('ok', 'Repository file downloaded.'); }));
  p.querySelector('#exportAllBtn')!.addEventListener('click', () => downloadBlob('sql-assistant-schemas.json', schemas.exportRegistryJson(), 'application/json'));
  p.querySelectorAll<HTMLElement>('[data-cf]').forEach((b) => b.addEventListener('click', () => { sync.resolveConflict(b.dataset.cf!, b.dataset.ch as 'keep-local'); re(); }));
  p.querySelectorAll<HTMLElement>('[data-activate]').forEach((b) => b.addEventListener('click', () => { schemas.setActive(b.dataset.activate!); store.pushToast('success', `Active Schema: ${schemas.active().name}`); re(); }));
  p.querySelectorAll<HTMLElement>('[data-export]').forEach((b) => b.addEventListener('click', () => { const s = schemas.byId(b.dataset.export!)!; downloadBlob(`${s.name.replace(/\W+/g, '_')}.json`, JSON.stringify(s, null, 2), 'application/json'); }));
  p.querySelectorAll<HTMLElement>('[data-rename]').forEach((b) => b.addEventListener('click', () => { const s = schemas.byId(b.dataset.rename!)!; const m = openModal(`${icon('edit', 18)} Rename Schema`, `<label class="block-label">Schema Name *<input type="text" id="schemaNameInput" value="${e(s.name)}"></label><div id="schemaNameError"></div><div class="modal-actions"><button type="button" class="btn btn-ghost" id="schemaNameCancel">Cancel</button><button type="button" class="btn btn-primary" id="schemaNameConfirm">${icon('check', 14)} Confirm Name</button></div>`);
    m.element.querySelector('#schemaNameCancel')!.addEventListener('click', () => m.close()); m.element.querySelector('#schemaNameConfirm')!.addEventListener('click', () => { const name = (m.element.querySelector('#schemaNameInput') as HTMLInputElement).value.trim(); const ok = /^[A-Za-z0-9][A-Za-z0-9 _\-./]*$/.test(name) && !schemas.schemas().some((x) => x.id !== s.id && x.name.toLowerCase() === name.toLowerCase());
      if (!ok) { m.element.querySelector('#schemaNameError')!.innerHTML = msgBox('err', 'Use a unique name that starts with a letter or digit (letters, digits, spaces, _ - . /).'); return; } const r = schemas.saveSchema({ ...s, name }); if (!r.ok) { m.element.querySelector('#schemaNameError')!.innerHTML = msgBox('err', e(r.errors.map((x) => x.message).join(' '))); return; } m.close(); re(); }); }));
  p.querySelectorAll<HTMLElement>('[data-del]').forEach((b) => b.addEventListener('click', () => { const s = schemas.byId(b.dataset.del!)!; const m = openModal(`${icon('trash', 18)} Delete Schema`, `<p>Delete <strong>${e(s.name)}</strong> from this device? A backup file is downloaded first.</p><label class="block-label">Admin Password<input type="password" id="delSchemaPw"></label><div id="delSchemaErr"></div><div class="modal-actions"><button type="button" class="btn btn-ghost" id="delSchemaCancel">Cancel</button><button type="button" class="btn btn-danger" id="delSchemaOk">${icon('trash', 14)} Delete</button></div>`);
    m.element.querySelector('#delSchemaCancel')!.addEventListener('click', () => m.close()); m.element.querySelector('#delSchemaOk')!.addEventListener('click', async () => { if (!(await requirePassword(m.element, '#delSchemaPw', '#delSchemaErr'))) return; downloadBlob(`backup-${s.name.replace(/\W+/g, '_')}.json`, JSON.stringify(s, null, 2), 'application/json'); const r = schemas.deleteSchema(s.id); if (!r.ok) { m.element.querySelector('#delSchemaErr')!.innerHTML = msgBox('err', e(r.errors.map((x) => x.message).join(' '))); return; } m.close(); store.pushToast('success', `Schema "${s.name}" deleted from this device.`); re(); }); }));
  let recoverTarget = ''; p.querySelectorAll<HTMLElement>('[data-recover]').forEach((b) => b.addEventListener('click', () => { recoverTarget = b.dataset.recover!; p.querySelector<HTMLInputElement>('#recoverFile')!.click(); }));
  p.querySelector('#recoverFile')!.addEventListener('change', async (ev) => { const f = (ev.target as HTMLInputElement).files?.[0]; if (!f) return; const r = schemas.recoverFromSource(recoverTarget, await f.text()); store.pushToast(r.ok ? 'success' : 'error', r.ok ? `${r.restored} decode code(s) restored from the source file; ${r.stillUnmapped} label(s) still without a code.` : r.errors.map((x) => x.message).join(' ')); re(); });
  p.querySelector('#addSchemaBtn')!.addEventListener('click', () => { const name = (p.querySelector('#newSchemaName') as HTMLInputElement).value.trim(); if (!name) { store.pushToast('warning', 'Enter a schema name.'); return; } const r = schemas.importSchemaJson(JSON.stringify({ name, tables: [{ name: 'NEW_TABLE', module: 'General', description: '', columns: [{ name: 'ID', type: 'NUMBER', nullable: false, isPrimaryKey: true, description: 'Primary key.' }] }] }), name); store.pushToast(r.ok ? 'success' : 'error', r.ok ? `Schema "${name}" added. Edit it in Manual Schema Update.` : r.errors.map((x) => x.message).join(' ')); re(); });
  p.querySelector('#importBtn')!.addEventListener('click', async () => { const f = (p.querySelector('#importFile') as HTMLInputElement).files?.[0]; const out = p.querySelector<HTMLElement>('#importResult')!; if (!f) { out.innerHTML = msgBox('warn', 'Choose a schema file first.'); return; }
    const r = schemas.importSchemaJson(await f.text(), (p.querySelector('#importName') as HTMLInputElement).value || f.name.replace(/\.json$/i, ''));
    out.innerHTML = r.ok ? msgBox('ok', `Imported "${e(r.schema!.name)}" (${r.schema!.tables.length} tables).${r.summary.length ? `\n${r.summary.map(e).join('\n')}` : ''}`) : msgBox('err', r.errors.map((x) => `${e(x.message)}${x.details?.length ? `\n• ${x.details.slice(0, 10).map(e).join('\n• ')}` : ''}`).join('\n'));
    if (r.ok) setTimeout(re, 1200); });
}
// ───────── Secret Vault ─────────
function vaultTab(p: HTMLElement): void {
  const s = secrets; const { vault } = services();
  p.innerHTML = `<div class="builder-panel"><h2>${icon('github', 16)} GitHub repository (schema synchronization)</h2><p class="hint">Stored on this device encrypted with AES-256-GCM (non-extractable device key). The token is sent only to <code>api.github.com</code> over HTTPS. Use a fine-grained token limited to this repository with <strong>Contents: Read and write</strong>.</p>
    <div class="form-row-3"><label class="block-label">Repository (owner/repo)<input type="text" id="vaultRepo" value="${e(s.githubOwner && s.githubRepo ? `${s.githubOwner}/${s.githubRepo}` : '')}" placeholder="e.g. acme-corp/sql-assistant-data"></label><label class="block-label">Branch<input type="text" id="vaultBranch" value="${e(s.githubBranch)}"></label><label class="block-label">Schema file path<input type="text" id="vaultPath" value="${e(s.schemaPath)}" placeholder="${e(CANONICAL_SCHEMA_PATH)}"></label></div>
    <label class="block-label">GitHub Access Token</label><div class="masked-token-row"><span class="masked-token-display" id="maskedToken">${icon('key', 14)} ${e(maskSecret(s.githubToken))}</span><button type="button" class="btn btn-outline btn-sm" id="changeTokenBtn">${icon('edit', 14)} ${s.githubToken ? 'Change Token' : 'Set Token'}</button></div><div id="tokenEditor" hidden><div class="row-actions"><input type="password" id="newTokenInput" autocomplete="off" placeholder="ghp_… or github_pat_…" style="max-width:420px"><button type="button" class="btn btn-primary btn-sm" id="saveTokenBtn">${icon('save', 14)} Save Token</button></div></div>
    <div class="row-actions"><button type="button" class="btn btn-primary" id="saveVaultCfgBtn">${icon('save', 14)} Save Configuration</button></div><div id="vaultCfgResult"></div></div>
  <div class="builder-panel mt" data-v17-vault-sync><h2>${icon('cloud', 16)} Push Secret Vault to Repository</h2><p class="hint">Shares this configuration (repository, branch, path, token, AI/LLM API key) with your other devices. It is written to the repository <strong>only as AES-256-GCM ciphertext</strong>; the key is derived (PBKDF2-SHA-256) from a separate <strong>Vault Sync Passphrase</strong> that is never stored or uploaded. Storing an encrypted secret in a repository is not equivalent to a server-side secret vault — use a strong passphrase (min. 10 characters) and rotate the token if the passphrase may have been disclosed. Files pushed by V17.2 can also be retrieved here.</p>
    <div class="form-row-3"><label class="block-label">Vault Sync Passphrase<input type="password" id="v17VaultPass" autocomplete="new-password"></label><label class="block-label">Confirm passphrase (for push)<input type="password" id="v17VaultPass2" autocomplete="new-password"></label><label class="block-label">Vault file path<input type="text" id="vaultFilePath" value="${e(s.vaultPath)}"></label></div>
    <div class="row-actions"><button type="button" class="btn btn-primary" id="pushVaultBtn">${icon('upload', 14)} Push Secret Vault to Repository</button><button type="button" class="btn btn-outline" id="pullVaultBtn">${icon('download', 14)} Retrieve from Repository</button><label class="btn btn-outline file-input-label">${icon('file-plus', 14)} Import encrypted file<input type="file" id="importVaultFile" accept=".json" hidden></label></div><div id="v17VaultResult"></div></div>`;
  const out = (sel: string, ok: boolean, m: string) => { p.querySelector(sel)!.innerHTML = msgBox(ok ? 'ok' : 'err', e(redactSecrets(m, vault.knownSecrets()))); };
  const showRetrieved = (m: string) => { vaultTab(p); const el = p.querySelector<HTMLElement>('#v17VaultResult'); if (el) el.innerHTML = msgBox('ok', e(m)); }; // re-render so the masked token / repository fields show the retrieved configuration
  const readCfg = (): VaultSecrets | string => { const repo = (p.querySelector('#vaultRepo') as HTMLInputElement).value.trim(); if (repo && !/^[\w.-]+\/[\w.-]+$/.test(repo)) return 'Repository must be in the form owner/repo.'; const [o, r] = repo ? repo.split('/') : ['', '']; return { ...secrets, githubOwner: o, githubRepo: r, githubBranch: (p.querySelector('#vaultBranch') as HTMLInputElement).value.trim() || 'main', schemaPath: (p.querySelector('#vaultPath') as HTMLInputElement).value.trim() || CANONICAL_SCHEMA_PATH, vaultPath: (p.querySelector('#vaultFilePath') as HTMLInputElement).value.trim() || secrets.vaultPath }; };
  const persist = async (next: VaultSecrets, sel: string, okMsg: string) => { try { await vault.save(next); await reloadSecrets(); out(sel, true, okMsg); store.pushToast('success', okMsg); setTimeout(() => vaultTab(p), 900); } catch (err) { out(sel, false, `Encryption failed: ${(err as Error).message}`); } };
  p.querySelector('#changeTokenBtn')!.addEventListener('click', () => { p.querySelector<HTMLElement>('#tokenEditor')!.hidden = false; p.querySelector<HTMLInputElement>('#newTokenInput')!.focus(); });
  p.querySelector('#saveTokenBtn')!.addEventListener('click', () => { const t = (p.querySelector('#newTokenInput') as HTMLInputElement).value.trim(); if (!t) { out('#vaultCfgResult', false, 'Enter a token.'); return; } const c = readCfg(); if (typeof c === 'string') { out('#vaultCfgResult', false, c); return; } void persist({ ...c, githubToken: t }, '#vaultCfgResult', 'GitHub access token saved (encrypted).'); });
  p.querySelector('#saveVaultCfgBtn')!.addEventListener('click', () => { const c = readCfg(); if (typeof c === 'string') { out('#vaultCfgResult', false, c); return; } void persist(c, '#vaultCfgResult', 'Secret Vault configuration saved (encrypted).'); });
  const pass = () => (p.querySelector('#v17VaultPass') as HTMLInputElement).value;
  p.querySelector('#pushVaultBtn')!.addEventListener('click', async () => {
    const res = p.querySelector<HTMLElement>('#v17VaultResult')!; const steps: string[] = []; const show = (kind: 'ok' | 'err', head: string) => { res.innerHTML = msgBox(kind, `${e(head)}<ul class="step-list">${steps.map((x) => `<li>${e(x)}</li>`).join('')}</ul>`); }; res.innerHTML = '';
    const pw = pass(); const pw2 = (p.querySelector('#v17VaultPass2') as HTMLInputElement).value; const btn = p.querySelector<HTMLButtonElement>('#pushVaultBtn')!; btn.disabled = true;
    try {
      const problems = await vault.validateForPush(pw, pw2); if (problems.length) { steps.push(...problems.map((x) => `✖ ${x}`)); show('err', 'Step 1 of 6 — the secret configuration is not ready to push. Nothing was written.'); return; } steps.push('✔ 1 Secret configuration validated');
      const repo = repository(); if (!repo) { steps.push('✖ Repository access is not configured (owner/repo and a token with Contents: Read and write).'); show('err', 'Push stopped before encryption. Nothing was written.'); return; }
      const text = await vault.exportEncrypted(pw); steps.push('✔ 2 Sensitive values encrypted (AES-256-GCM, key from PBKDF2-SHA-256 · 310 000 iterations)'); steps.push('✔ 3 Repository-safe representation prepared — no plaintext or Base64 copy of any secret');
      const cur = await repo.read(secrets.vaultPath); await repo.write(secrets.vaultPath, text, cur?.sha ?? null, 'SQL Assistant: update encrypted Secret Vault'); steps.push(`✔ 4 Encrypted configuration pushed to ${secrets.vaultPath}`);
      const back = await repo.read(secrets.vaultPath); const verified = !!back && back.text === text && (await vault.verifyEncrypted(back.text, pw)); steps.push(verified ? '✔ 5 Synchronization confirmed — read back, decrypted and matches this device' : '✖ 5 The file written to the repository could not be verified'); steps.push('✔ 6 The token was never shown or logged');
      show(verified ? 'ok' : 'err', verified ? 'Encrypted Secret Vault pushed to the repository (ciphertext only).' : 'The push finished but could not be verified — retrieve it on another device to confirm.');
    } catch (err) { steps.push(`✖ ${redactSecrets((err as Error).message, vault.knownSecrets())}`); show('err', 'Push failed — the repository was not changed unless step 4 is shown above.'); } finally { btn.disabled = false; } });
  p.querySelector('#pullVaultBtn')!.addEventListener('click', async () => { const repo = repository(); if (!repo) { out('#v17VaultResult', false, 'Configure the repository and a token with read access first, or use "Import encrypted file".'); return; }
    try { let f = await repo.read(secrets.vaultPath); if (!f && secrets.vaultPath !== 'sql-assistant-data/vault/secret-vault.v17.enc.json') f = await repo.read('sql-assistant-data/vault/secret-vault.v17.enc.json'); if (!f) { out('#v17VaultResult', false, 'No encrypted Secret Vault found in the repository yet.'); return; } await vault.importEncrypted(f.text, pass()); await reloadSecrets(); showRetrieved('Secret Vault retrieved, decrypted and validated.'); } catch (err) { out('#v17VaultResult', false, `Retrieve failed: ${(err as Error).message}`); } });
  p.querySelector('#importVaultFile')!.addEventListener('change', async (ev) => { const f = (ev.target as HTMLInputElement).files?.[0]; if (!f) return; try { await vault.importEncrypted(await f.text(), pass()); await reloadSecrets(); showRetrieved('Encrypted vault file imported.'); } catch (err) { out('#v17VaultResult', false, `Import failed: ${(err as Error).message}`); } });
}
// ───────── Synchronization ─────────
function syncTab(p: HTMLElement): void {
  const { sync, schemas, knowledge, migrations } = services(); const cfg = getSyncPrefs(); const fsa = typeof (window as any).showDirectoryPicker === 'function';
  p.innerHTML = `<div class="advanced-grid"><div class="builder-panel"><h2>${icon('folder-sync', 16)} Sync Source &amp; Sync Time</h2><label class="block-label">Sync Source<select id="syncSourceSelect">${(Object.keys(SRC) as SyncSource[]).map((s) => `<option value="${s}" ${cfg.source === s ? 'selected' : ''}>${SRC[s]}</option>`).join('')}</select></label><label class="block-label">Sync Time<select id="syncTimeSelect">${(Object.keys(TIME) as SyncTimeOption[]).map((t) => `<option value="${t}" ${cfg.time === t ? 'selected' : ''}>${TIME[t]}</option>`).join('')}</select></label><p class="hint">Background synchronization runs only when the repository is configured in the Secret Vault. It never blocks the application.</p></div>
    <div class="builder-panel"><h2>${icon('folder', 16)} Shared Location</h2><p class="hint">Exchange the schema registry through a shared folder (File System Access API${fsa ? '' : ' — not supported in this browser; use Export/Import instead'}). Data is validated before it is read or written.</p><div class="row-actions"><button type="button" class="btn btn-outline btn-sm" id="connectSharedBtn" ${fsa ? '' : 'disabled'}>${icon('folder', 14)} ${sharedDir ? `Connected: ${e(sharedDir.name)}` : 'Connect folder'}</button><button type="button" class="btn btn-outline btn-sm" id="pullSharedBtn" ${sharedDir ? '' : 'disabled'}>${icon('download', 14)} Pull from folder</button><button type="button" class="btn btn-outline btn-sm" id="pushSharedBtn" ${sharedDir ? '' : 'disabled'}>${icon('upload', 14)} Push to folder</button></div><div id="sharedResult">${sharedResult}</div></div></div>
  <div class="builder-panel mt"><h2>${icon('sparkles', 16)} Central knowledge (learned queries + Admin Query Library)</h2><p class="hint">Learned queries and the Admin Query Library are stored as one versioned data structure and synchronized through the same repository connection as the schemas: <code>${e(knowledgePathFor(secrets.schemaPath))}</code>. Records are merged per item (last change wins; the higher trust tier is kept; deletions propagate). Incoming records are validated — credentials and non-read-only SQL are rejected. Last pull: ${e(knowledge.meta().lastPullAt?.replace('T', ' ').slice(0, 16) || 'never')} · last publish: ${e(knowledge.meta().lastPushAt?.replace('T', ' ').slice(0, 16) || 'never')}.</p><div class="row-actions"><button type="button" class="btn btn-primary btn-sm" id="syncKnowledgeBtn">${icon('refresh', 14)} Sync knowledge now</button><button type="button" class="btn btn-outline btn-sm" id="pullKnowledgeBtn">${icon('download', 14)} Pull only</button><button type="button" class="btn btn-outline btn-sm" id="pushKnowledgeBtn">${icon('upload', 14)} Publish only</button></div><div id="knowledgeResult">${knowledgeResult}</div></div>
  ${adminMessagePanelHtml()}
  <div class="builder-panel mt"><h2>${icon('history', 16)} Data migrations (V17.4)</h2><p class="hint">Versioned, idempotent and non-destructive — older data is kept in place.</p>${migrations.applied.length ? `<ul class="plan-list">${migrations.applied.map((m) => `<li><strong>${e(MIGRATION_DESCRIPTIONS[m.id] || m.id)}</strong> — ${e(m.result)} · ${e(m.detail)} <span class="hint">${e(m.at.slice(0, 16).replace('T', ' '))}</span></li>`).join('')}</ul>` : '<p class="hint">No migration has run on this device.</p>'}</div>
  <h2 class="section-title">${icon('shield-alert')} Conflict Management</h2>${sync.conflicts().length ? sync.conflicts().map((x) => `<div class="conflict-card"><div class="conflict-card-head"><strong>${e(x.schemaName)}</strong></div><div class="row-actions"><button type="button" class="btn btn-outline btn-sm" data-cf="${e(x.id)}" data-ch="keep-local">Use Local</button><button type="button" class="btn btn-outline btn-sm" data-cf="${e(x.id)}" data-ch="take-remote">Use Remote</button></div></div>`).join('') : '<p class="hint">No unresolved conflicts.</p>'}
  <h2 class="section-title">${icon('history')} Synchronization Log</h2><div class="sync-log-list">${sync.log().slice(0, 50).map((l) => `<div class="sync-log-row ${l.kind === 'error' ? 'sync-log-error' : ''}">${icon(l.kind === 'error' ? 'alert-triangle' : l.kind === 'push' ? 'upload' : 'download', 13)}<span class="sync-log-time">${e(new Date(l.timestamp).toLocaleString())}</span><span class="sync-log-msg">${e(l.message)}</span></div>`).join('') || '<p class="hint">No synchronization activity yet.</p>'}</div>`;
  const re = () => syncTab(p); wireAdminMessage(p, re);
  const kn = async (mode: 'sync' | 'pull' | 'push') => { const out = p.querySelector<HTMLElement>('#knowledgeResult')!; out.innerHTML = msgBox('warn', 'Working…'); const r = await (mode === 'sync' ? knowledge.synchronize() : mode === 'pull' ? knowledge.pull() : knowledge.push()); knowledgeResult = msgBox(r.ok ? 'ok' : 'err', e(r.ok ? r.message : `Knowledge synchronization failed at stage "${r.stage}". ${r.message}`) + (r.rejected.length ? `<br>${e(`${r.rejected.length} record(s) rejected: ${r.rejected.slice(0, 3).join(' · ')}`)}` : '')); re(); };
  p.querySelector('#syncKnowledgeBtn')!.addEventListener('click', () => { void kn('sync'); }); p.querySelector('#pullKnowledgeBtn')!.addEventListener('click', () => { void kn('pull'); }); p.querySelector('#pushKnowledgeBtn')!.addEventListener('click', () => { void kn('push'); });
  p.querySelector('#syncSourceSelect')!.addEventListener('change', (ev) => { setSyncSource((ev.target as HTMLSelectElement).value as SyncSource); store.pushToast('info', 'Sync source updated.'); });
  p.querySelector('#syncTimeSelect')!.addEventListener('change', (ev) => { setSyncTime((ev.target as HTMLSelectElement).value as SyncTimeOption); store.pushToast('info', 'Sync time updated.'); });
  p.querySelectorAll<HTMLElement>('[data-cf]').forEach((b) => b.addEventListener('click', () => { sync.resolveConflict(b.dataset.cf!, b.dataset.ch as 'keep-local'); re(); }));
  p.querySelector('#connectSharedBtn')!.addEventListener('click', async () => { try { sharedDir = await (window as any).showDirectoryPicker({ mode: 'readwrite' }); sharedResult = msgBox('ok', `Connected to folder "${e(sharedDir.name)}".`); } catch { sharedResult = msgBox('warn', 'Folder selection was cancelled or denied.'); } re(); });
  p.querySelector('#pullSharedBtn')!.addEventListener('click', async () => { try { const fh = await sharedDir.getFileHandle('registry.json'); const r = checkRegistry({ text: await (await fh.getFile()).text() }); if (r.fileProblem) { sharedResult = msgBox('err', e(r.fileProblem.message)); re(); return; } let n = 0; r.validSchemas.forEach((s) => { const ex = schemas.schemas().find((x) => x.name.toLowerCase() === s.name.toLowerCase()); if (schemas.saveSchema(ex ? { ...s, id: ex.id, status: ex.status } : { ...s, status: 'inactive' }).ok) n += 1; }); sharedResult = msgBox(r.invalidSchemas.length ? 'warn' : 'ok', e(`${n} schema(s) loaded from the shared folder.${r.invalidSchemas.length ? ` ${r.invalidSchemas.length} schema(s) failed validation and were not loaded: ${r.invalidSchemas.map((x) => x.name).join(', ')}.` : ''}`)); } catch (err) { sharedResult = msgBox('err', `Could not read registry.json from the connected folder: ${e((err as Error).message)}`); } re(); });
  p.querySelector('#pushSharedBtn')!.addEventListener('click', async () => { const ser = serializeRegistry(schemas.registry(), 'shared-location'); if (!ser.ok) { sharedResult = msgBox('err', 'Not written: a local schema does not pass validation (see Schema Management).'); re(); return; } try { const fh = await sharedDir.getFileHandle('registry.json', { create: true }); const w = await fh.createWritable(); await w.write(ser.text); await w.close(); sharedResult = msgBox('ok', 'Schema registry written to the shared folder (validated, current format).'); } catch (err) { sharedResult = msgBox('err', `Could not write to the connected folder: ${e((err as Error).message)}`); } re(); });
}
// ───────── AI/LLM Model ─────────
function layersHtml(): string {
  const { schemas, learning, admin } = services(); const s = schemas.active(); const cols = s.tables.reduce((n, t) => n + t.columns.length, 0); const ls = learning.stats(); const ac = admin.counts(); const c = aiConfig;
  const l4 = !c.enabled ? 'Disabled — everything runs offline.' : !c.model ? 'Enabled but no model is configured — the offline result is used.' : `Configured: ${c.provider} / ${c.model}. Consulted only when the offline result is uncertain; if unavailable the offline result is used.`;
  return `<div class="layer-grid"><div class="layer-card"><h4>${icon('database', 14)} Layer 1 · Schema-aware engine</h4><p>Active Schema <strong>${e(s.name)}</strong>: ${s.tables.length} tables, ${cols} columns, ${s.relationships.length} relationships. Schema matching, relationship detection, query construction and 12-point SQL validation. Cached per schema version.</p></div><div class="layer-card"><h4>${icon('sparkles', 14)} Layer 2 · Offline NLU</h4><p>Intent, entity and requirement extraction, query-pattern recognition. Always active, no network needed.</p></div><div class="layer-card"><h4>${icon('history', 14)} Layer 3 · Local learning</h4><p>${ac.trusted} trusted Admin Query Library entr${ac.trusted === 1 ? 'y' : 'ies'}; learned: ${ls.executed} ${TIER_LABEL.executed.toLowerCase()}, ${ls.confirmed + ls.modified} confirmed, ${ls.repeated} repeated, ${ls.generated} unconfirmed (not used). Order of trust: Admin &gt; executed &gt; confirmed &gt; repeated.</p></div><div class="layer-card"><h4>${icon('bot', 14)} Layer 4 · Optional local LLM</h4><p>${e(l4)}</p></div></div>`;
}
function aiTab(p: HTMLElement): void {
  const c = aiConfig; const { vault, store: kv } = services();
  p.innerHTML = `<div class="builder-panel"><h2>${icon('bot', 16)} AI/LLM Model <span class="chip chip-inactive">optional</span></h2><div class="note-box">${icon('wifi-off', 16)}<div><strong>Offline NLU: always active (primary/default engine).</strong> The AI/LLM Model is consulted only when it is enabled and the offline result is uncertain. Its SQL must pass the read-only and Active Schema checks. If it is unavailable (offline browser, missing key, provider error) the offline result is used.</div></div>
    ${layersHtml()}
    <label class="inline-check mt"><input type="checkbox" id="v17LlmEnabled" ${c.enabled ? 'checked' : ''}> Enable AI/LLM Model</label>
    <div class="form-row-3"><label class="block-label">Provider<select id="v17LlmProvider">${options(Object.keys(PROVIDER_DEFAULTS), c.provider, Object.fromEntries(Object.entries(PROVIDER_DEFAULTS).map(([k, v]) => [k, v.label])))}</select></label><label class="block-label">Model<input type="text" id="v17LlmModel" value="${e(c.model)}" placeholder="e.g. gpt-4o-mini"></label><label class="block-label">Authentication<select id="v17LlmAuth">${options(['bearer', 'api-key-header', 'none'], c.authType, { bearer: 'Bearer token', 'api-key-header': 'API key header', none: 'None (local model)' })}</select></label></div>
    <label class="block-label">Endpoint<input type="text" id="v17LlmEndpoint" value="${e(c.endpoint || PROVIDER_DEFAULTS[c.provider].endpoint)}"></label>
    <div class="form-row-3"><label class="block-label">API key (stored encrypted in the Secret Vault)<input type="password" id="v17LlmKey" autocomplete="off" placeholder="${e(maskSecret(secrets.aiApiKey))} — leave empty to keep"></label><label class="block-label">API version<input type="text" id="v17LlmApiVersion" value="${e(c.apiVersion)}"></label><label class="block-label">Timeout (ms)<input type="number" id="v17LlmTimeout" value="${c.timeoutMs}"></label></div>
    <label class="block-label">Model-specific configuration (JSON)<textarea id="v17LlmExtra" rows="2" style="font-family:Consolas,monospace">${e(c.extraJson)}</textarea></label><div class="row-actions"><button type="button" class="btn btn-primary" id="v17LlmSave">${icon('save', 14)} Save</button><button type="button" class="btn btn-outline" id="v17LlmTest">${icon('wifi', 14)} Test connection</button></div><div id="v17LlmResult"></div></div>`;
  p.querySelector('#v17LlmProvider')!.addEventListener('change', (ev) => { const pv = (ev.target as HTMLSelectElement).value as AiProvider; (p.querySelector('#v17LlmEndpoint') as HTMLInputElement).value = PROVIDER_DEFAULTS[pv].endpoint; (p.querySelector('#v17LlmAuth') as HTMLSelectElement).value = PROVIDER_DEFAULTS[pv].authType; });
  p.querySelector('#v17LlmTest')!.addEventListener('click', async () => { const g = (id: string) => (p.querySelector(id) as HTMLInputElement).value; const out = p.querySelector<HTMLElement>('#v17LlmResult')!; out.innerHTML = msgBox('warn', 'Contacting the model…'); const r = await pingModel({ ...c, provider: g('#v17LlmProvider') as AiProvider, model: g('#v17LlmModel').trim(), endpoint: g('#v17LlmEndpoint').trim(), authType: g('#v17LlmAuth') as AiAuth, apiVersion: g('#v17LlmApiVersion').trim(), timeoutMs: Number(g('#v17LlmTimeout')) || 8000, extraJson: g('#v17LlmExtra') }, g('#v17LlmKey').trim() || secrets.aiApiKey); out.innerHTML = msgBox(r.ok ? 'ok' : 'err', e(redactSecrets(r.message, vault.knownSecrets()))); });
  p.querySelector('#v17LlmSave')!.addEventListener('click', async () => { const g = (id: string) => (p.querySelector(id) as HTMLInputElement).value; const cfg = { ...c, enabled: (p.querySelector('#v17LlmEnabled') as HTMLInputElement).checked, provider: g('#v17LlmProvider') as AiProvider, model: g('#v17LlmModel').trim(), endpoint: g('#v17LlmEndpoint').trim(), authType: g('#v17LlmAuth') as AiAuth, apiVersion: g('#v17LlmApiVersion').trim(), timeoutMs: Number(g('#v17LlmTimeout')) || 20000, extraJson: g('#v17LlmExtra') };
    const key = g('#v17LlmKey').trim() || secrets.aiApiKey; const probs = validateAiConfig(cfg, key); const out = p.querySelector<HTMLElement>('#v17LlmResult')!;
    if (probs.length) { out.innerHTML = msgBox('err', `AI/LLM configuration invalid:\n• ${probs.map(e).join('\n• ')}`); return; }
    try { if (key !== secrets.aiApiKey) { await vault.save({ ...secrets, aiApiKey: key }); await reloadSecrets(); } saveAiConfig(cfg, kv); setAiConfig(cfg); out.innerHTML = msgBox('ok', 'AI/LLM Model configuration saved.'); store.pushToast('success', 'AI/LLM Model configuration saved.'); } catch (err) { out.innerHTML = msgBox('err', e((err as Error).message)); } });
}
// ───────── Danger Zone ─────────
function dangerZone(p: HTMLElement): void {
  const { schemas, learning, store: kv } = services(); const reg = schemas.registry();
  p.innerHTML = `<div class="issue-box">${icon('alert-triangle', 16)}<div><strong>Danger Zone.</strong> These actions cannot be undone. Each one asks for the Admin Password.</div></div><label class="block-label mt" style="max-width:340px">Admin Password<input type="password" id="dangerPw" autocomplete="current-password"></label><div id="dangerErr"></div>
    <div class="advanced-grid mt"><div class="builder-panel"><h2>${icon('trash', 16)} Delete all contents of a schema</h2><select id="dangerSchema">${options(reg.schemas.map((s) => s.id), reg.activeSchemaId, Object.fromEntries(reg.schemas.map((s) => [s.id, s.name])))}</select><p class="hint">A backup is downloaded first. The schema keeps its name; all tables are removed.</p><button type="button" class="btn btn-danger btn-sm" id="dangerClearSchema">${icon('trash', 14)} Delete contents</button></div>
      <div class="builder-panel"><h2>${icon('broom', 16)} Clean up browser storage</h2><p class="hint">Removes backups of corrupted registries, quarantined schemas and the synchronization log.</p><button type="button" class="btn btn-danger btn-sm" id="dangerCleanup">${icon('broom', 14)} Clean up</button></div>
      <div class="builder-panel"><h2>${icon('sparkles', 16)} Clear learned query knowledge</h2><p class="hint">${learning.all().length} learned pattern(s). Clears them on this device and, after the next knowledge sync, on your other devices. The schema and the Admin Query Library are not affected.</p><button type="button" class="btn btn-danger btn-sm" id="dangerLearning">${icon('trash', 14)} Clear</button></div>
      <div class="builder-panel"><h2>${icon('key', 16)} Reset Secret Vault on this device</h2><p class="hint">Removes the stored repository configuration, token and AI/LLM API key from this device.</p><button type="button" class="btn btn-danger btn-sm" id="dangerVault">${icon('trash', 14)} Reset vault</button></div>
      <div class="builder-panel"><h2>${icon('lock', 16)} Reset Admin Password to default</h2><p class="hint">Sets the Admin Password back to <code>admin</code> and locks Settings.</p><button type="button" class="btn btn-danger btn-sm" id="dangerPwReset">${icon('refresh', 14)} Reset password</button></div></div>`;
  const guard = (fn: () => void | Promise<void>) => async () => { if (!(await requirePassword(p, '#dangerPw', '#dangerErr'))) return; await fn(); };
  p.querySelector('#dangerClearSchema')!.addEventListener('click', guard(() => { const s = schemas.byId((p.querySelector('#dangerSchema') as HTMLSelectElement).value)!; downloadBlob(`backup-${s.name.replace(/\W+/g, '_')}.json`, JSON.stringify(s, null, 2), 'application/json'); const r = schemas.replaceRegistry({ ...reg, schemas: reg.schemas.map((x) => (x.id === s.id ? { ...x, tables: [{ name: 'EMPTY_TABLE', module: 'General', description: 'Placeholder — add tables in Manual Schema Update.', columns: [{ name: 'ID', label: 'ID', type: 'NUMBER', nullable: false, isPrimaryKey: true, description: '' }] }], relationships: [], updatedAt: new Date().toISOString() } : x)) }); store.pushToast(r.ok ? 'success' : 'error', r.ok ? `Contents of "${s.name}" deleted (backup downloaded).` : r.errors.map((x) => x.message).join(' ')); dangerZone(p); }));
  p.querySelector('#dangerCleanup')!.addEventListener('click', guard(() => { let n = 0; kv.keys().filter((k) => /\.corrupt-|quarantine|sqla\.syncLog|sqla\.synclog/.test(k)).forEach((k) => { kv.remove(k); n += 1; }); store.pushToast('success', `${n} storage entr${n === 1 ? 'y' : 'ies'} removed.`); }));
  p.querySelector('#dangerLearning')!.addEventListener('click', guard(() => { learning.clear(); store.pushToast('success', 'Learned query knowledge cleared.'); dangerZone(p); }));
  p.querySelector('#dangerVault')!.addEventListener('click', guard(async () => { kv.remove('sqla.vault.local.v17'); try { localStorage.removeItem('sqla.secretvault.v15'); } catch { /* */ } (services().vault as unknown as { cache: unknown }).cache = null; await reloadSecrets(); store.pushToast('success', 'Secret Vault reset on this device.'); }));
  p.querySelector('#dangerPwReset')!.addEventListener('click', guard(() => { resetPasswordToDefault(); store.lockSettings(); store.pushToast('warning', 'Admin Password reset to the default "admin". Settings locked.'); }));
}
