import { icon } from '../components/icons';
import { aiService } from '../services/aiService';
export function renderAboutPage(container: HTMLElement): void {
  container.innerHTML = `<div class="page" data-tour="about-panel"><h1 class="page-title">${icon('info')} About AP-SQL Assistant</h1><div class="builder-panel"><p>AP-SQL Assistant is a self-contained tool that helps support teams construct accurate SQL without needing deep, memorized knowledge of the underlying database schema. It is packaged as a single self-contained HTML file and works identically when opened by double-click (file://) or served over http/https.</p>
  <h3>V17.1 — Schema synchronization stability release</h3><ul><li>Fixes <em>"Schema synchronization failed: the remote schema file failed validation"</em>: invalid schema data can no longer be published (the same validation now runs before every push), and remote data is normalised before it is validated.</li><li>One rule set for import, Manual Schema Update, push and pull. Older schema formats (V15 – V17.0) are converted losslessly; every conversion is reported.</li><li>Each schema in the repository is checked on its own. Invalid ones are rejected with the exact table/column and JSON path, and your local copy is never overwritten.</li><li>Recovery options in Settings → Schema Management: validate the repository file, repair referential leftovers (explicit, listed), restore from the repository, or review a repaired remote copy.</li><li>Large schema files (&gt; 1 MB) now download correctly from GitHub.</li></ul>
  <h3>V17.0 — Offline self-training NLU, AI / LLM Model, safe schema records, encrypted vault sync</h3><ul><li><strong>Describe What You Need</strong> runs a fully offline NLU engine grounded in the Active Schema: joins (including foreign-key paths), conditions, date filtering (dialect-aware), aggregation, GROUP BY / HAVING, sorting, DISTINCT and limits.</li><li><strong>Controlled learning:</strong> requests and accepted SQL become learned knowledge only when repeated or confirmed with <em>Accept &amp; Learn</em>.</li><li><strong>Advanced Options</strong> shows what was applied automatically; anything set manually is never overwritten.</li><li><strong>Manual Schema Update</strong> edits/deletes exactly one record and blocks changes that would break relationships.</li><li><strong>Secret Vault</strong> is pushed to the repository only on request, encrypted with AES-256-GCM using a separate Vault Sync Passphrase.</li><li><strong>AI / LLM Model</strong> (optional) replaces the Online AI/NLP Endpoint; its SQL is used only after validation.</li></ul>
  <h3>V16.x</h3><p>GitHub timeouts, Active Schema synchronization across devices, optional M365 Copilot Enterprise integration, error boxes only rendered when an error exists, real-world data types, storage-quota hardening, and offline file:// support.</p>
  <p class="hint">Current engine: ${aiService.providerName}.</p><p class="hint">Strictly a SQL-text generator — never opens a database connection, never executes a query.</p><p class="hint">Crafted by Subham Ain · Senior Support Consultant</p></div></div>`;
}
