import { icon } from '../components/icons';
import { aiService } from '../services/aiService';
export function renderAboutPage(container: HTMLElement): void {
  container.innerHTML = `<div class="page" data-tour="about-panel"><h1 class="page-title">${icon('info')} About AP-SQL Assistant</h1><div class="builder-panel"><p>AP-SQL Assistant is a self-contained tool that helps support teams construct accurate SQL without needing deep, memorized knowledge of the underlying database schema. It is packaged as a single self-contained HTML file and works identically when opened by double-click (file://) or served over http/https.</p>
  <h3>V17.0 — Offline self-training NLU, AI / LLM Model, safe schema records, encrypted vault sync</h3><ul><li><strong>Describe What You Need</strong> runs a fully offline NLU engine grounded in the Active Schema: joins (including foreign-key paths), conditions, date filtering (dialect-aware), aggregation, GROUP BY / HAVING, sorting, DISTINCT and limits.</li><li><strong>Controlled learning:</strong> requests and accepted SQL become learned knowledge only when repeated or confirmed with <em>Accept &amp; Learn</em>; patterns are re-validated against the Active Schema every time and can be synchronized across devices.</li><li><strong>Advanced Options</strong> shows what was applied automatically; anything set manually is never overwritten.</li><li><strong>Manual Schema Update</strong> edits/deletes exactly one record, blocks changes that would break relationships, and persists to the centralized registry.</li><li><strong>Secret Vault</strong> is pushed to the repository only on request, encrypted with AES-256-GCM using a separate Vault Sync Passphrase that is never stored in the repository.</li><li><strong>AI / LLM Model</strong> (optional) replaces the Online AI/NLP Endpoint; its SQL is used only after read-only and Active Schema validation, and the offline engine always remains available.</li></ul>
  <h3>V16.3 – V16.5</h3><p>GitHub requests time out after 8 seconds instead of hanging; the Active Schema selection synchronizes across devices (last selection wins) through the same automatic discovery used for schema content.</p>
  <h3>V16.x</h3><p>M365 Copilot Enterprise integration (optional), error boxes only rendered when an error exists, card sizing, real-world data types accepted during import and sync, storage-quota hardening, and offline file:// support.</p>
  <p class="hint">Current engine: ${aiService.providerName}.</p><p class="hint">Strictly a SQL-text generator — never opens a database connection, never executes a query.</p><p class="hint">Crafted by Subham Ain · Senior Support Consultant</p></div></div>`;
}
