import { icon } from '../components/icons';
import { aiService } from '../services/aiService';
import { APP_VERSION } from '../v17/sync/schemaFormat';
import { getDeviceTag } from '../engines/schemaVersionEngine';
export function renderAboutPage(container: HTMLElement): void {
  container.innerHTML = `<div class="page" data-tour="about-panel"><h1 class="page-title">${icon('info')} About SQL Assistant</h1><div class="builder-panel"><p>SQL Assistant is a self-contained tool that helps support teams construct accurate SQL without needing deep, memorized knowledge of the underlying database schema. It is packaged as a single self-contained HTML file and works identically when opened by double-click (file://) or served over http/https.</p>
  <h3>V17.2 — Reliable schema synchronization, row-wise schema editing, richer offline NLU</h3><ul><li>Fixes the schema synchronization error that could reappear after a repair: repository files are never read from the browser cache, an already-replaced copy is never applied again, and discovery reads the same repository location that pushes write.</li><li>Normal synchronization merges automatically (3-way merge against the last synchronized copy); a push that races another device recovers on its own. Errors name the failing stage and which device/version wrote invalid data.</li><li>Manual Schema Update shows the selected row, its current values and every modified value before saving, with Reset and Cancel.</li><li>Advanced Options add table aliases, INNER/LEFT join type and a join-path chooser; the offline NLU detects them, maps country names to ISO codes and understands current/previous periods.</li><li>Learned query knowledge records the full example (filters, joins, sorting, grouping, aggregates, date logic, schema and engine version) and never learns credentials.</li></ul>
  <h3>V17.1</h3><p>One validation rule set for import, Manual Schema Update, push and pull; invalid schema data can no longer be published; each repository schema is checked on its own; explicit recovery options; large (&gt; 1 MB) schema files.</p>
  <h3>V17.0</h3><p>Offline self-training NLU for <strong>Describe What You Need</strong>, controlled learning (Accept &amp; Learn), automatic/manual Advanced Options, single-record Manual Schema Update, encrypted Secret Vault push, and the optional AI/LLM Model (replacing the Online AI/NLP Endpoint).</p>
  <h3>V16.x</h3><p>GitHub timeouts, Active Schema synchronization across devices, optional M365 Copilot Enterprise integration, error boxes only rendered when an error exists, real-world data types, storage-quota hardening, and offline file:// support.</p>
  <p class="hint">Version ${APP_VERSION} · This device: ${getDeviceTag()} · Engine: ${aiService.providerName}.</p><p class="hint">Strictly a SQL-text generator — never opens a database connection, never executes a query.</p><p class="hint">Crafted by Subham Ain · Senior Support Consultant</p></div></div>`;
}
