import { icon } from '../components/icons';
import { store } from '../state/store';
import { schemaService } from '../services/schemaService';
import { syncService } from '../services/syncService';
import { secretVaultService } from '../services/secretVaultService';
import { performBackgroundPull, performPublicDiscovery } from '../services/autoSyncService';
import { renderConflictBanner } from '../components/conflictBanner';
import { openSchemaNameModal } from '../components/schemaNameModal';
import { decodeLegend } from '../engines/decodeEngine';
import { downloadBlob, escapeHtml as e } from '../utils/dom';
import { safeTrim } from '../utils/validation';
import type { SchemaModel, TableDef } from '../types';
const ok = (m: string) => `<div class="issue-box ok mini">${icon('check', 14)} ${e(m)}</div>`;
const bad = (m: string) => `<div class="issue-box mini">${icon('alert-triangle', 14)} ${e(m)}</div>`;
/** Rendered only when syncService has an active error (V16.1/V16.2 pattern). */
function renderSyncErrorIndicator(container: HTMLElement): void {
  const draw = () => { const m = syncService.getLastError(); container.innerHTML = m ? `<div class="issue-box mini">${icon('alert-triangle', 14)} ${e(m)} <button type="button" class="btn-link sync-error-dismiss">Dismiss</button></div>` : ''; container.querySelector('.sync-error-dismiss')?.addEventListener('click', () => syncService.clearLastError()); };
  const un = syncService.subscribe(draw); draw(); (container as any)._cleanup = un;
}
function pullSummary(r: { newSchemasAdded: string[]; updatedSchemas: string[]; unchanged: number; conflicts: unknown[]; activeSchemaChanged?: boolean }): string { const p: string[] = []; if (r.newSchemasAdded.length) p.push(`Added ${r.newSchemasAdded.length} new schema(s): ${r.newSchemasAdded.join(', ')}.`); if (r.updatedSchemas.length) p.push(`Updated ${r.updatedSchemas.length} schema(s).`); if (r.unchanged) p.push(`${r.unchanged} schema(s) already up to date.`); if (r.conflicts.length) p.push(`${r.conflicts.length} schema(s) have conflicting changes — resolve them above.`); if (r.activeSchemaChanged) p.push('Active schema updated to the latest selection from another device.'); return p.join(' ') || 'Everything is already in sync.'; }
export function renderSchemaManagementSection(container: HTMLElement, opts: { allowAddImport: boolean }, onAfterAction?: () => void): void {
  function draw(): void {
    const schemas = schemaService.getAllSchemas();
    container.innerHTML = `${opts.allowAddImport ? `<div class="note-box">${icon('cloud', 15)}<span>Automatic sync: creating, importing, updating, or renaming a schema automatically synchronizes it to the repository once the Secret Vault is unlocked. The Active Schema selection also synchronizes across devices automatically.</span></div><div class="row-actions"><button type="button" id="simpleSyncBtn" class="btn btn-outline btn-sm">${icon('github', 15)} Sync with GitHub Now</button></div><div id="simpleSyncResult"></div><div id="conflictBannerMount"></div><div id="syncErrorMount"></div>` : ''}
    <div class="schema-list">${schemas.map((s) => `<div class="schema-card ${s.status === 'active' ? 'is-active' : ''}"><div class="schema-card-head"><h3>${e(s.name)}</h3><span class="chip ${s.status === 'active' ? 'chip-active' : 'chip-inactive'}">${s.status === 'active' ? 'Active' : s.status === 'default' ? 'Default' : 'Inactive'}</span></div><p class="hint">v${e(String(s.versionMeta?.version ?? s.version))} · ${s.tables.length} tables · updated ${new Date(s.updatedAt).toLocaleString()}</p><p class="hint">Last synced: ${s.lastSyncedAt ? new Date(s.lastSyncedAt).toLocaleString() : 'never'}${s.versionMeta ? ` · source: ${e(s.versionMeta.source)}` : ''}${s.originalFileName ? ` · imported from: ${e(s.originalFileName)}` : ''}</p><div class="row-actions wrap">${s.status !== 'active' ? `<button type="button" class="btn btn-primary btn-sm" data-action="activate" data-id="${s.id}">${icon('check', 14)} Set Active</button>` : `<button type="button" class="btn btn-outline btn-sm" disabled>${icon('check', 14)} Currently active</button>`}${opts.allowAddImport ? `<button type="button" class="btn btn-outline btn-sm" data-action="rename" data-id="${s.id}">${icon('edit', 14)} Rename</button>` : ''}<button type="button" class="btn btn-outline btn-sm" data-action="export-json" data-id="${s.id}">${icon('download', 14)} Export JSON</button><button type="button" class="btn btn-outline btn-sm" data-action="export-csv" data-id="${s.id}">${icon('download', 14)} Export CSV</button>${opts.allowAddImport && schemas.length > 1 ? `<button type="button" class="btn btn-ghost btn-sm" data-action="delete-schema" data-id="${s.id}">${icon('trash', 14)} Remove</button>` : ''}</div></div>`).join('')}</div>
    ${opts.allowAddImport ? `<div class="row-actions mt"><button type="button" id="addSchemaBtn" class="btn btn-primary btn-sm">${icon('file-plus', 14)} Add Schema</button><label class="btn btn-outline btn-sm file-input-label">${icon('upload', 14)} Import Schema<input type="file" id="importSchemaFile" accept=".json,application/json" hidden/></label></div><div id="importSchemaPreview"></div><details class="advanced-sync-details mt"><summary>${icon('github', 14)} Advanced: manual push/pull</summary><div class="row-actions"><button type="button" id="pushRegistryBtn" class="btn btn-outline btn-sm">${icon('github', 14)} Push All Schemas to GitHub</button><button type="button" id="pullRegistryBtn" class="btn btn-outline btn-sm">${icon('folder-sync', 14)} Pull Schemas from GitHub</button></div><div id="registrySyncResult"></div></details>` : ''}`;
    if (opts.allowAddImport) { const cb = container.querySelector<HTMLElement>('#conflictBannerMount'); if (cb) renderConflictBanner(cb, onAfterAction); const em = container.querySelector<HTMLElement>('#syncErrorMount'); if (em) renderSyncErrorIndicator(em); }
    container.querySelectorAll<HTMLElement>('[data-action="activate"]').forEach((b) => b.addEventListener('click', () => { schemaService.switchActiveSchema(b.dataset.id!); store.regenerateReadOnlySql(); store.pushToast('success', 'Active schema switched.'); onAfterAction?.(); }));
    container.querySelectorAll<HTMLElement>('[data-action="rename"]').forEach((b) => b.addEventListener('click', () => { const s = schemaService.getSchemaById(b.dataset.id!); if (!s) return; openSchemaNameModal({ title: `Rename "${s.name}"`, suggestedName: s.name, onConfirm: (n) => { const r = schemaService.renameSchema(s.id, n); if (r.ok) store.pushToast('success', `Renamed to "${n}".`); else store.pushToast('error', r.error || 'Schema update failed.'); } }); }));
    container.querySelectorAll<HTMLElement>('[data-action="export-json"]').forEach((b) => b.addEventListener('click', () => downloadBlob(`schema-${b.dataset.id}.json`, schemaService.exportSchemaJson(b.dataset.id!), 'application/json')));
    container.querySelectorAll<HTMLElement>('[data-action="export-csv"]').forEach((b) => b.addEventListener('click', () => downloadBlob(`schema-${b.dataset.id}.csv`, schemaService.exportSchemaCsv(b.dataset.id!), 'text/csv')));
    container.querySelectorAll<HTMLElement>('[data-action="delete-schema"]').forEach((b) => b.addEventListener('click', () => { if (!confirm('Remove this schema from this device (and from the repository on the next sync)?')) return; const r = schemaService.deleteSchema(b.dataset.id!); if (r.ok) { store.regenerateReadOnlySql(); store.pushToast('success', 'Schema removed.'); } else store.pushToast('error', r.error || 'Could not remove schema.'); }));
    container.querySelector('#addSchemaBtn')?.addEventListener('click', () => openSchemaNameModal({ title: 'Name the New Schema', onConfirm: (n) => { const r = schemaService.addNewSchema(n); if (r.ok) store.pushToast('success', `Schema "${n}" created.`); else store.pushToast('error', r.error || 'Could not create schema.'); } }));
    container.querySelector('#importSchemaFile')?.addEventListener('change', async (ev) => {
      const input = ev.target as HTMLInputElement; const file = input.files?.[0]; input.value = ''; if (!file) return; const fileName = safeTrim(file.name);
      const preview = () => container.querySelector<HTMLElement>('#importSchemaPreview');
      let parsed: SchemaModel; try { parsed = JSON.parse(await file.text()); } catch (err) { const p = preview(); if (p) p.innerHTML = bad(`Could not parse file: ${(err as Error).message}`); return; }
      const suggested = safeTrim(parsed?.name) || fileName.replace(/\.[^.]+$/, '').replace(/[^A-Za-z0-9 _\-.]/g, '_');
      openSchemaNameModal({ title: 'Name the Imported Schema', suggestedName: suggested, originalFileName: fileName, onConfirm: (n) => { const r = schemaService.importSchema(parsed, n, fileName); const p = preview(); if (!p) return; p.innerHTML = r.ok ? ok(`${r.replacedExisting ? `Updated existing schema "${n}" in place` : `Imported as "${n}"`} — it will sync automatically once the Secret Vault is unlocked.`) : bad(r.error || 'Schema import failed.'); if (r.ok) store.pushToast('success', 'Schema imported.'); } });
    });
    const busy = async (id: string, label: string, fn: () => Promise<void>) => { const b = container.querySelector<HTMLButtonElement>(id)!; const o = b.innerHTML; b.disabled = true; b.innerHTML = label; try { await fn(); } finally { if (b.isConnected) { b.disabled = false; b.innerHTML = o; } } };
    container.querySelector('#simpleSyncBtn')?.addEventListener('click', () => busy('#simpleSyncBtn', 'Syncing…', async () => { const r = await syncService.syncWithGitHubSimple(); const m = container.querySelector<HTMLElement>('#simpleSyncResult'); if (m) m.innerHTML = r.ok ? ok(pullSummary(r)) : bad(r.error || 'Repository synchronization failed.'); if (r.ok) store.pushToast('success', 'Synchronized with GitHub.'); }));
    container.querySelector('#pushRegistryBtn')?.addEventListener('click', () => busy('#pushRegistryBtn', 'Pushing…', async () => { const r = await syncService.pushRegistryToGitHub(); const m = container.querySelector<HTMLElement>('#registrySyncResult'); if (m) m.innerHTML = r.ok ? ok('All schemas pushed to GitHub successfully.') : bad(`${r.error}${r.requiresPullFirst ? ' Pull the latest version first.' : ''}`); }));
    container.querySelector('#pullRegistryBtn')?.addEventListener('click', () => busy('#pullRegistryBtn', 'Pulling…', async () => { const r = await syncService.pullRegistryFromGitHub(); const m = container.querySelector<HTMLElement>('#registrySyncResult'); if (m) m.innerHTML = r.ok ? ok(pullSummary(r)) : bad(r.error || 'Repository synchronization failed.'); }));
  }
  const u1 = schemaService.subscribe(() => { if (container.isConnected) draw(); }); draw(); (container as any)._cleanup = () => u1();
}
function tableCard(t: TableDef): string { const v = t.objectType === 'VIEW'; return `<div class="schema-table-card"><div class="schema-table-head">${icon(v ? 'eye' : 'table', 16)}<div><h4>${e(t.name)}${v ? ' <span class="chip chip-view">VIEW</span>' : ''}</h4><span class="hint">${e(t.module)} · ${e(t.description)}</span></div></div><div style="overflow-x:auto"><table class="schema-col-table"><thead><tr><th>Column</th><th>Type</th><th>Nullable</th><th>Keys</th><th>Decode</th></tr></thead><tbody>${t.columns.map((c) => `<tr><td>${e(c.name)}</td><td>${e(c.type)}${c.length ? `(${c.length})` : ''}</td><td>${c.nullable ? 'Yes' : 'No'}</td><td>${c.isPrimaryKey ? '<span class="chip chip-pk">PK</span>' : ''}${c.isForeignKey ? `<span class="chip chip-fk">FK→${e(c.references?.table || '')}.${e(c.references?.column || '')}</span>` : ''}</td><td>${e(decodeLegend(c))}</td></tr>`).join('')}</tbody></table></div></div>`; }
export function renderSchemaPage(container: HTMLElement): void {
  let mod = ''; let term = '';
  performPublicDiscovery('schema-page-mount').catch(() => {}); if (secretVaultService.isUnlocked()) performBackgroundPull('schema-page-mount').catch(() => {});
  const scoped = () => schemaService.getActiveSchema().tables.filter((t) => (!mod || t.module === mod) && (!term || t.name.toLowerCase().includes(term.toLowerCase()) || t.description.toLowerCase().includes(term.toLowerCase())));
  const listHtml = () => { const s = scoped(); return s.length ? s.map(tableCard).join('') : '<p class="hint">No tables match the current Module/Search filter.</p>'; };
  function draw(): void {
    const a = schemaService.getActiveSchema(); const modules = schemaService.getModulesForSchema(a.id); if (mod && !modules.includes(mod)) mod = '';
    container.innerHTML = `<div class="page"><h1 class="page-title">${icon('database')} Schema</h1><p class="page-subtitle">The active schema is the single source of truth for all SQL generation.</p><h2 class="section-title">${icon('list', 15)} Stored Schemas</h2><div id="schemaMgmtMount"></div><h2 class="section-title">${icon('table', 15)} Tables &amp; Views in Active Schema (${e(a.name)})</h2><div class="row-actions" data-tour="schema-module-selector"><select id="schemaModuleSelect" style="max-width:260px" aria-label="Module"><option value="">All Modules</option>${modules.map((m) => `<option ${m === mod ? 'selected' : ''}>${e(m)}</option>`).join('')}</select><div class="picker-search" style="flex:1">${icon('search', 14)}<input type="text" id="schemaTableSearch" class="picker-search-input" placeholder="Search tables…" value="${e(term)}" aria-label="Search tables"/></div></div><div class="schema-results" id="tablesReadOnlyList">${listHtml()}</div><div class="note-box">${icon('lock', 14)}<span>Need to add, edit, or delete tables/columns, or add/import/sync a whole schema? That's inside password-protected Settings (Manual Schema Update and Schema Management tabs).</span></div></div>`;
    container.querySelector('#schemaModuleSelect')!.addEventListener('change', (ev) => { mod = (ev.target as HTMLSelectElement).value; container.querySelector('#tablesReadOnlyList')!.innerHTML = listHtml(); });
    container.querySelector('#schemaTableSearch')!.addEventListener('input', (ev) => { term = (ev.target as HTMLInputElement).value; container.querySelector('#tablesReadOnlyList')!.innerHTML = listHtml(); });
    renderSchemaManagementSection(container.querySelector<HTMLElement>('#schemaMgmtMount')!, { allowAddImport: false }, draw);
  }
  draw();
}
