import { icon } from '../components/icons';
import { store } from '../state/store';
import { schemaService } from '../services/schemaService';
import { changePassword, resetPasswordToDefault, verifyPassword, isUsingDefaultPassword } from '../services/passwordService';
import { secretVaultService, maskToken, DEFAULT_BOOTSTRAP_CONFIG } from '../services/secretVaultService';
import { syncService } from '../services/syncService';
import { handleVaultUnlocked } from '../services/autoSyncService';
import { clearCachedCopilotToken } from '../services/msalAuthService';
import { renderSchemaManagementSection } from './schemaPage';
import { renderSchemaEditorSection } from './schemaEditorSection';
import { renderConflictBanner } from '../components/conflictBanner';
import { renderSyncLogPanel } from '../components/syncLogPanel';
import { renderTabs } from '../components/tabs';
import { renderV17AiLlmTab, mountV17VaultSync } from '../v17/integration';
import { downloadBlob, formatBytes, escapeHtml as e } from '../utils/dom';
import { estimateStringBytes } from '../utils/validation';
import type { SyncTimeOption } from '../types';
const ok = (m: string) => `<div class="issue-box ok mini">${icon('check', 14)} ${e(m)}</div>`;
const bad = (m: string) => `<div class="issue-box mini">${icon('alert-triangle', 14)} ${e(m)}</div>`;
export function renderSettingsPage(container: HTMLElement): void {
  let activeTab = 'security';
  function draw(): void { if (!store.settingsUnlocked) lockScreen(); else unlocked(); }
  function lockScreen(): void {
    // V16.2: #settingsPwError is a completely empty container until a real incorrect-password attempt.
    container.innerHTML = `<div class="page-settings-lock"><div class="settings-lock-card" data-tour="settings-lock-screen"><div class="settings-lock-icon">${icon('lock', 32)}</div><h2>Settings</h2><p class="hint">Settings — including Schema Management, the Secret Vault, AI / LLM Model and cross-device synchronization — are protected.</p><label class="block-label">Enter Admin Password<input id="settingsPwInput" type="password" autocomplete="current-password"/></label><div id="settingsPwError"></div><div class="row-actions"><button id="settingsCancelBtn" class="btn btn-ghost" type="button">Cancel</button><button id="settingsUnlockBtn" class="btn btn-primary" type="button">${icon('unlock', 15)} Unlock</button></div></div></div>`;
    const input = container.querySelector<HTMLInputElement>('#settingsPwInput')!; const err = container.querySelector<HTMLElement>('#settingsPwError')!;
    async function tryUnlock(): Promise<void> {
      const pw = input.value; if (!(await verifyPassword(pw))) { err.innerHTML = `<div class="issue-box mini">${icon('alert-triangle', 14)} Incorrect password.</div>`; return; }
      const r = await secretVaultService.tryAutoUnlock(pw); store.unlockSettings();
      if (r.ok) { store.pushToast(r.error ? 'warning' : 'success', r.error || (r.source === 'repository' ? 'Secret Vault configuration retrieved from the repository.' : r.source === 'created-fresh' ? 'Secret Vault created with default configuration.' : 'Secret Vault unlocked.')); handleVaultUnlocked().catch(() => {}); }
      else store.pushToast('warning', r.error || 'The Secret Vault could not be unlocked automatically.');
      if (isUsingDefaultPassword()) store.pushToast('warning', 'You are using the default Admin Password — change it in Settings → Security.');
    }
    container.querySelector('#settingsUnlockBtn')!.addEventListener('click', tryUnlock);
    input.addEventListener('keydown', (ev) => { if (ev.key === 'Enter') tryUnlock(); }); input.addEventListener('input', () => { err.innerHTML = ''; });
    container.querySelector('#settingsCancelBtn')!.addEventListener('click', () => { window.location.hash = 'quickstart'; });
  }
  function unlocked(): void {
    container.innerHTML = `<div class="page"><div class="settings-header-row"><h1 class="page-title">${icon('settings')} Settings Unlocked</h1><button id="lockSettingsBtn" class="btn btn-outline btn-sm" type="button">${icon('lock', 14)} Lock Settings</button></div><p class="page-subtitle">Same Admin Password, encrypted at rest. Settings lock automatically after 5 minutes of inactivity.</p><div class="settings-tabs-scroll"><div id="settingsTabsMount"></div></div></div>`;
    container.querySelector('#lockSettingsBtn')!.addEventListener('click', () => { store.lockSettings(); secretVaultService.lock(); store.pushToast('info', 'Settings locked.'); });
    renderTabs(container.querySelector<HTMLElement>('#settingsTabsMount')!, [
      { id: 'security', label: 'Security', render: securityTab },
      { id: 'schema-editor', label: 'Manual Schema Update', render: (p) => { p.setAttribute('data-tour', 'schema-editor-panel'); renderSchemaEditorSection(p); } },
      { id: 'schema-mgmt', label: 'Schema Management', render: (p) => renderSchemaManagementSection(p, { allowAddImport: true }) },
      { id: 'secret-vault', label: 'Secret Vault', render: vaultTab },
      { id: 'sync', label: 'Synchronization', render: syncTab },
      { id: 'nlp', label: 'AI / LLM Model', render: (p) => renderV17AiLlmTab(p) },
      { id: 'danger', label: 'Danger Zone', render: dangerTab }
    ], activeTab, { security: 'settings-security', danger: 'settings-danger' }, (id) => { activeTab = id; });
  }
  function securityTab(p: HTMLElement): void {
    p.innerHTML = `<h5>Change Admin Password</h5><p class="hint">This password also protects the local Secret Vault — changing it re-encrypts the vault automatically on this device.</p><div class="form-row-2"><label class="block-label">Current password<input id="oldPwInput" type="password" autocomplete="current-password"/></label><label class="block-label">New password<input id="newPwInput" type="password" autocomplete="new-password"/></label></div><button id="changePwBtn" class="btn btn-primary btn-sm mt" type="button">${icon('key', 14)} Change Password</button><div id="changePwResult"></div>
    <h5 class="mt">Forgot Password</h5><p class="hint">Resets the Admin Password back to its internal default. This does NOT re-encrypt an existing Secret Vault — reset the Secret Vault too (or Pull/Import the V17 encrypted copy).</p><button id="resetPwBtn" class="btn btn-outline btn-sm" type="button">${icon('refresh', 14)} Reset to Default</button><div id="resetPwResult"></div><h5 class="mt">Session Security</h5><p class="hint">Settings automatically locks after 5 minutes of inactivity, or immediately via "Lock Settings" (this also re-locks the Secret Vault).</p>`;
    p.querySelectorAll('input').forEach((i) => i.addEventListener('input', () => { p.querySelector('#changePwResult')!.innerHTML = ''; }));
    p.querySelector('#changePwBtn')!.addEventListener('click', async () => { const o = p.querySelector<HTMLInputElement>('#oldPwInput')!.value; const n = p.querySelector<HTMLInputElement>('#newPwInput')!.value; const m = p.querySelector<HTMLElement>('#changePwResult')!; const r = await changePassword(o, n); if (!r.ok) { m.innerHTML = bad(r.error || 'Password change failed.'); return; } const re = await secretVaultService.reencryptForNewPassword(o, n); m.innerHTML = ok(`Password changed successfully.${re.ok ? ' The local Secret Vault was re-encrypted automatically.' : ` (Note: ${re.error})`}`); store.pushToast('success', 'Admin password changed.'); p.querySelector<HTMLInputElement>('#oldPwInput')!.value = ''; p.querySelector<HTMLInputElement>('#newPwInput')!.value = ''; });
    p.querySelector('#resetPwBtn')!.addEventListener('click', () => { if (!confirm('Reset the Admin Password to the internal default?')) return; resetPasswordToDefault(); p.querySelector('#resetPwResult')!.innerHTML = ok('Password reset to the internal default.'); });
  }
  function vaultTab(p: HTMLElement): void {
    const u = secretVaultService.isUnlocked(); const c = secretVaultService.getConfig(); const cp = c?.m365Copilot;
    p.innerHTML = `<div class="issue-box ${u ? 'ok' : ''} mini">${icon(u ? 'unlock' : 'lock', 14)} Secret Vault ${u ? 'Unlocked' : 'Locked'}</div><p class="hint">The local Secret Vault stores the GitHub configuration, the AI / LLM API key and the optional M365 Copilot configuration, encrypted with the Admin Password on this device.</p>${u ? `
    <h5 class="mt">${icon('key', 15)} GitHub Access Token *</h5><p class="hint">A personal credential — never shown or stored in plain text.</p><div class="masked-token-row"><span class="masked-token-display" id="maskedToken">${icon('lock', 13)} ${e(maskToken(c?.githubToken))}</span><button type="button" id="changeTokenBtn" class="btn btn-outline btn-sm">${c?.githubToken ? 'Change Token' : 'Set Token'}</button></div><div id="tokenEditRow" hidden><label class="block-label">New GitHub Access Token<input type="password" id="newTokenInput" autocomplete="off"/></label><div class="row-actions"><button type="button" id="saveTokenBtn" class="btn btn-primary btn-sm">${icon('save', 14)} Save Token</button><button type="button" id="cancelTokenBtn" class="btn btn-ghost btn-sm">Cancel</button></div></div>
    <h5 class="mt">${icon('github', 15)} Repository</h5><div class="form-row-3"><label class="block-label">Repository (owner/repo)<input type="text" id="ghRepo" value="${e(c?.githubRepo || DEFAULT_BOOTSTRAP_CONFIG.githubRepo)}"/></label><label class="block-label">Branch<input type="text" id="ghBranch" value="${e(c?.githubBranch || 'main')}"/></label><label class="block-label">Schema file path<input type="text" id="ghPath" value="${e(c?.githubSchemaPath || DEFAULT_BOOTSTRAP_CONFIG.githubSchemaPath)}"/></label></div><button type="button" id="saveRepoConfigBtn" class="btn btn-primary btn-sm mt">${icon('save', 14)} Save Repository Settings</button>
    <h5 class="mt">${icon('bot', 15)} M365 Copilot Enterprise Integration <span class="chip chip-inactive">Optional</span></h5><p class="hint">Optional — assists natural-language interpretation only. The offline engine and your Active Schema always determine the final SQL. Sign-in uses the Microsoft identity platform (no password is stored).</p><label class="inline-check"><input type="checkbox" id="copilotEnabled" ${cp?.enabled ? 'checked' : ''}/> Enable M365 Copilot Enterprise for Describe What You Need</label><div class="form-row-2"><label class="block-label">Tenant ID (Entra ID)<input type="text" id="copilotTenantId" value="${e(cp?.tenantId || '')}"/></label><label class="block-label">Client ID (App Registration)<input type="text" id="copilotClientId" value="${e(cp?.clientId || '')}"/></label></div><label class="block-label">Agent / Endpoint URL<input type="text" id="copilotEndpoint" value="${e(cp?.agentEndpoint || '')}"/></label><label class="block-label">Scope<input type="text" id="copilotScope" value="${e(cp?.scope || '')}"/></label><div class="row-actions"><button type="button" id="saveCopilotBtn" class="btn btn-primary btn-sm">${icon('save', 14)} Save M365 Copilot Settings</button><button type="button" id="clearCopilotSessionBtn" class="btn btn-ghost btn-sm">${icon('refresh', 14)} Clear cached sign-in</button></div><div id="copilotConfigResult"></div>
    <h5 class="mt">${icon('upload', 15)} Push Secret Vault to Repository</h5><div id="pushVaultSection"><button type="button" id="pushVaultBtn" class="btn btn-outline btn-sm">${icon('github', 14)} Push Secret Vault Now</button></div>
    <h5 class="mt">${icon('trash', 15)} Reset Secret Vault</h5><p class="hint">Permanently discards the LOCAL stored GitHub, AI / LLM and M365 Copilot configuration on this device.</p><button type="button" id="resetVaultBtn" class="btn btn-outline btn-sm">${icon('trash', 14)} Reset Secret Vault</button>` : `<div class="issue-box mini">${icon('alert-triangle', 14)} The Secret Vault should already be unlocked automatically — try locking and re-unlocking Settings.</div>`}<div id="secretVaultResult"></div>`;
    if (!u) return;
    const res = p.querySelector<HTMLElement>('#secretVaultResult')!; p.querySelectorAll('input').forEach((i) => i.addEventListener('input', () => { res.innerHTML = ''; }));
    p.querySelector('#changeTokenBtn')!.addEventListener('click', () => { const r = p.querySelector<HTMLElement>('#tokenEditRow')!; r.hidden = !r.hidden; });
    p.querySelector('#cancelTokenBtn')!.addEventListener('click', () => { p.querySelector<HTMLElement>('#tokenEditRow')!.hidden = true; p.querySelector<HTMLInputElement>('#newTokenInput')!.value = ''; });
    p.querySelector('#saveTokenBtn')!.addEventListener('click', async () => { const t = p.querySelector<HTMLInputElement>('#newTokenInput')!.value.trim(); if (!t) { res.innerHTML = bad('Enter the GitHub access token.'); return; } const r = await secretVaultService.saveConfig({ githubToken: t }); if (r.ok) { store.pushToast('success', 'GitHub token saved securely in the local Secret Vault.'); vaultTab(p); } else res.innerHTML = bad(r.error || 'The token could not be saved.'); });
    p.querySelector('#saveRepoConfigBtn')!.addEventListener('click', async () => { const repo = p.querySelector<HTMLInputElement>('#ghRepo')!.value.trim(); if (!/^[^/\s]+\/[^/\s]+$/.test(repo)) { res.innerHTML = bad('Repository must be in the form "owner/repo".'); return; } const r = await secretVaultService.saveConfig({ githubRepo: repo, githubBranch: p.querySelector<HTMLInputElement>('#ghBranch')!.value.trim() || 'main', githubSchemaPath: p.querySelector<HTMLInputElement>('#ghPath')!.value.trim() || DEFAULT_BOOTSTRAP_CONFIG.githubSchemaPath }); res.innerHTML = r.ok ? ok('Repository settings saved.') : bad(r.error || 'Save failed.'); });
    p.querySelector('#saveCopilotBtn')!.addEventListener('click', async () => { const v = (id: string) => p.querySelector<HTMLInputElement>(`#${id}`)!.value.trim(); const enabled = p.querySelector<HTMLInputElement>('#copilotEnabled')!.checked; const m = p.querySelector<HTMLElement>('#copilotConfigResult')!; const cfg = { enabled, tenantId: v('copilotTenantId'), clientId: v('copilotClientId'), agentEndpoint: v('copilotEndpoint'), scope: v('copilotScope') }; if (enabled && (!cfg.tenantId || !cfg.clientId || !cfg.agentEndpoint || !cfg.scope)) { m.innerHTML = bad('To enable M365 Copilot Enterprise, Tenant ID, Client ID, Endpoint URL, and Scope are all required.'); return; } const r = await secretVaultService.saveM365CopilotConfig(cfg); m.innerHTML = r.ok ? ok('Saved. This only affects natural-language interpretation — nothing else changes.') : bad(r.error || 'Save failed.'); });
    p.querySelector('#clearCopilotSessionBtn')!.addEventListener('click', () => { clearCachedCopilotToken(); store.pushToast('info', 'Cached M365 Copilot sign-in cleared.'); });
    p.querySelector('#resetVaultBtn')!.addEventListener('click', () => { if (confirm('This permanently discards the LOCAL stored GitHub, AI / LLM and M365 Copilot configuration. Continue?')) { secretVaultService.resetVault(); store.pushToast('info', 'Secret Vault reset — lock and unlock Settings to create a new one.'); vaultTab(p); } });
    mountV17VaultSync(p.querySelector<HTMLElement>('#pushVaultSection')!);
  }
  function syncTab(p: HTMLElement): void {
    const cfg = syncService.getConfig();
    p.innerHTML = `<h5>${icon('folder', 15)} Shared Location</h5><p class="hint">Status: ${syncService.hasConnectedLocation() ? 'Connected' : 'Not connected'}${syncService.isFileSystemAccessSupported() ? '' : ' — this browser does not support the File System Access API; use Import/Export instead.'}</p><button id="connectLocationBtn" class="btn btn-outline btn-sm" type="button">${icon('folder', 14)} Connect Folder</button><div id="locationResult"></div>
    <h5 class="mt">${icon('github', 15)} GitHub Sync</h5><p class="hint">Repository configuration and access token live in Settings → Secret Vault. Schema changes and the Active Schema selection synchronize automatically.</p><button id="simpleSyncBtn2" class="btn btn-outline btn-sm" type="button">${icon('github', 14)} Sync with GitHub Now</button><div id="syncResult2"></div>
    <h5 class="mt">${icon('clock', 15)} Sync Time (periodic background pull)</h5><p class="hint">Current: ${e(cfg.time)}. Change it from the navbar "Sync Time" dropdown.</p>${cfg.time === 'custom' ? `<div class="row-actions"><label class="inline-label">Time of day<input type="time" id="customTimeInput" value="${e(cfg.customTime || '20:30')}"/></label><button type="button" id="saveCustomTimeBtn" class="btn btn-primary btn-sm">${icon('save', 14)} Save</button></div>` : ''}
    <h5 class="mt">${icon('shield-alert', 15)} Conflict Management</h5><div id="conflictBannerMountSync"></div><h5 class="mt">${icon('history', 15)} Synchronization Activity Log</h5><div id="syncLogMount"></div>`;
    p.querySelector('#connectLocationBtn')!.addEventListener('click', async () => { const r = await syncService.connectSharedLocation(); p.querySelector('#locationResult')!.innerHTML = r.ok ? ok(`Connected: ${r.label}`) : bad(r.error || 'Could not connect the folder.'); });
    p.querySelector('#simpleSyncBtn2')!.addEventListener('click', async () => { const b = p.querySelector<HTMLButtonElement>('#simpleSyncBtn2')!; const o = b.innerHTML; b.disabled = true; b.innerHTML = 'Syncing…'; const r = await syncService.syncWithGitHubSimple(); b.disabled = false; b.innerHTML = o; p.querySelector('#syncResult2')!.innerHTML = r.ok ? `${r.warning ? `<div class="issue-box warn mini">${icon('alert-triangle', 14)} ${e(r.warning)}</div>` : ''}${ok(`Synchronized — ${r.newSchemasAdded.length} new, ${r.updatedSchemas.length} updated, ${r.unchanged} unchanged, ${r.conflicts.length} conflict(s)${r.rejected?.length ? `, ${r.rejected.length} rejected` : ''}.`)}` : bad(r.error || 'Repository synchronization failed.'); });
    p.querySelector('#saveCustomTimeBtn')?.addEventListener('click', () => { const t = p.querySelector<HTMLInputElement>('#customTimeInput')!.value || '20:30'; syncService.setTime('custom' as SyncTimeOption, t); store.pushToast('success', `Custom sync time saved: ${t}.`); });
    renderConflictBanner(p.querySelector<HTMLElement>('#conflictBannerMountSync')!); renderSyncLogPanel(p.querySelector<HTMLElement>('#syncLogMount')!);
  }
  function dangerTab(p: HTMLElement): void {
    const a = schemaService.getActiveSchema(); const h = schemaService.getStorageHealth(); const size = estimateStringBytes(JSON.stringify(schemaService.getRegistry()));
    p.innerHTML = `<h5>${icon('hard-drive', 15)} Local Storage Health</h5><p class="hint">Schemas are cached in this browser's local storage for offline use and fast loading.</p><div class="issue-box ${h.lastPersistOk ? 'ok' : ''} mini">${icon(h.lastPersistOk ? 'check' : 'alert-triangle', 14)} Last save: ${h.lastPersistOk ? 'OK' : 'FAILED'}${h.lastRecovered ? ' (recovered after cleanup)' : ''}</div>${!h.lastPersistOk && h.lastError ? bad(h.lastError) : ''}<p class="hint">Schema catalogue size: ${formatBytes(size)} · <span id="quotaEstimateMount">Checking available browser storage…</span></p><button type="button" id="cleanupStorageBtn" class="btn btn-outline btn-sm">${icon('broom', 14)} Clean up duplicate/stale schemas</button><div id="cleanupResult"></div>
    <h5 class="mt">${icon('trash', 15)} Delete Schema Contents</h5><p class="hint">Deletes all tables and relationships of the active schema "<strong>${e(a.name)}</strong>". A full backup is downloaded automatically before anything is deleted.</p><button type="button" id="wipeSchemaBtn" class="btn btn-danger btn-sm">${icon('trash', 14)} Delete Schema Contents</button><div id="wipeResult"></div>`;
    const qm = p.querySelector<HTMLElement>('#quotaEstimateMount')!;
    if ((navigator as any).storage?.estimate) (navigator as any).storage.estimate().then((x: any) => { qm.textContent = x.quota ? `Browser storage in use: ${formatBytes(x.usage || 0)} of ${formatBytes(x.quota)} (${Math.round(((x.usage || 0) / x.quota) * 100)}%).` : 'Browser storage estimate unavailable.'; }).catch(() => { qm.textContent = 'Browser storage estimate unavailable.'; }); else qm.textContent = 'Browser storage estimate not supported in this browser.';
    p.querySelector('#cleanupStorageBtn')!.addEventListener('click', () => { const r = schemaService.pruneForSpace(); store.pushToast('success', `Storage cleanup complete — removed ${r.removedCount} schema(s), about ${formatBytes(r.freedApproxBytes)}.`); dangerTab(p); });
    p.querySelector('#wipeSchemaBtn')!.addEventListener('click', () => { const w = p.querySelector<HTMLElement>('#wipeResult')!; w.innerHTML = `<div class="issue-box warn mini" style="flex-direction:column">Enter the Admin Password to confirm.<input type="password" id="wipePwInput"/><div id="wipePwError"></div><div class="row-actions"><button type="button" id="wipeCancelBtn" class="btn btn-ghost btn-sm">Cancel</button><button type="button" id="wipeConfirmBtn" class="btn btn-danger btn-sm">${icon('trash', 14)} Confirm Delete</button></div></div>`;
      w.querySelector('#wipeCancelBtn')!.addEventListener('click', () => { w.innerHTML = ''; });
      w.querySelector('#wipeConfirmBtn')!.addEventListener('click', async () => { if (!(await verifyPassword(w.querySelector<HTMLInputElement>('#wipePwInput')!.value))) { w.querySelector('#wipePwError')!.innerHTML = bad('Incorrect password.'); return; } const backup = schemaService.deleteAllSchemaContents(schemaService.getActiveSchema().id); downloadBlob(`schema-backup-${Date.now()}.json`, backup, 'application/json'); store.pushToast('success', 'Schema contents deleted. A backup was downloaded automatically.'); dangerTab(p); }); });
  }
  draw();
}
